### ISSUE TITLE
Creation of a new cluster with a separate volume for WAL files (`pg_wal`)

### ISSUE THREAD

**Issue by gbartolini** [cloudnative-pg/cloudnative-pg#10]
For vertical scalability, introduce a separate and dedicated volume for storing the WAL archive (`pg_wal`) to parallelize I/O operations between transaction logs and database pages.

This also improves business continuity as we can limit the amount of space used by the archive and dedicate the PGDATA volume for Postgres pages.

In this initial implementation, we only enable this feature at cluster creation time and disable changing this setting on existing clusters.

The second implementation (which will be in a separate ticket) should implement adding the separate volume to an existing cluster that's without it. We should also enable resizing, as well as removing the separate volume from an existing cluster.

**Comment by JanKarremans** [comment]
I think you would be welcome to contribute, Anthony.

**Comment by anthonator** [comment]
For sure but would still like to know if anything has been started on this yet and how far along before deciding to help.
