### ISSUE TITLE
Add E2E tests for restore + backup safety

### ISSUE THREAD

**Issue by jsilvela** [cloudnative-pg/cloudnative-pg#104]
We are adding logic to the operator to:
- avoid having a cluster back up into the same location it restored from
- avoid having a cluster back up into a location already used by another

See issues #61  and #62 
Our existing E2E suite covers backup and recovery separately, but not "restored cluster has a backup spec".

Scenarios:
- We have cluster A. We create a cluster B to restore from A, but the YAML for B specifies the same barman object as A. --> FAIL
- We have cluster A. Create cluster B which recovers from A and uses a new location for Backup. Create cluster C which recovers from B and uses A's bucket as a Backup location --> FAIL
- We have cluster A. Create cluster B which recovers from A and back-up's into X. Get B to come up properly and perhaps force some WAL writing. Create cluster C from A, and back up into X too. --> FAIL
- We have cluster A. Create cluster B which backs up to new location X --> AOK

**Comment by danishedb** [comment]
Added one more scenario where we are verifying cluster creation with same destination path in two different namespace. 
We have cluster A. Create cluster B which backs up to new location X --> AOK Didnot added this test cause it is covered already within tests.
