### ISSUE TITLE
Problem running pgbench from CNPG plugin (namespace parameter placement in the command)

### ISSUE THREAD

**Issue by MichaluxPL** [cloudnative-pg/cloudnative-pg#1078]
There is a slight problem with cnpg plugin pgbench command.
According to the documentation (both web and plugin help) it should be run like this:
kubectl cnpg pgbench cluster-example --db-name pgbench --pgbench-job-name pgbench-job -- --time 30 --client 1 --jobs 1 -n NAMESPACE
Unfortuanely this produces "cluster not found" error.
The problem is with "-n NAMESPACE" placement. Running the command like this:
kubectl cnpg pgbench cluster-example --db-name pgbench --pgbench-job-name pgbench-job -n NAMESPACE -- --time 30 --client 1 --jobs 1
creates the pbbench job correctly.
So either docs should be corrected or pgbench command namespace parameter placement fixed.

**Comment by danishedb** [comment]
@MichaluxPL You can test the fix.

**Comment by MichaluxPL** [comment]
> @MichaluxPL You can test the fix.

Where can I get this fix to download ?

**Comment by danishedb** [comment]
HI @MichaluxPL you can build it from Branch dev/1078 to test it.

**Comment by MichaluxPL** [comment]
> HI @MichaluxPL you can build it from Branch dev/1078 to test it.

Unfortunately don't have dev environment to do it, so I'll have to wait for a new release.
