### ISSUE TITLE
Allow set service type to NodePort

### ISSUE THREAD

**Issue by amincheloh** [cloudnative-pg/cloudnative-pg#1139]
there are no options to change the service type (-rw, -ro, -r, -any) from default ClusterIP to NodePort.

**Comment by armru** [comment]
Hello @amincheloh,

At the moment it is not possible to customize the type of service generated by CNPG, but we intend to support it in the future. 

Currently, as a workaround, you can create a service of type NodePort with the selectors of one of the CNPG services (-rw, -ro, -r, -any) to obtain the same behavior.
