### ISSUE TITLE
Override default `backup.target` policy in `ScheduledBackup` and `Backup` resources

### ISSUE THREAD

**Issue by gbartolini** [cloudnative-pg/cloudnative-pg#1141]
Change the logic of the ScheduledBackup and Backup resources to manage the `backup.target` option in #1140 and select the most aligned standby. Please also consider synchronous replication.

**Comment by phisco** [comment]
Should this override the cluster configuration, if present? I mean: #1140 introduces a target parameter in the backup section of the Cluster resource, so any Backup/ScheduledBackup targeting that Cluster will adopt the chosen policy (primary/prefer-standby), so we want to have a target field in the BackupSpec that can override the policy set in the Cluster, if any?

**Comment by sxd** [comment]
I think this can be closed, if it's a mistake we may reopen it again

**Comment by phisco** [comment]
Nope, @sxd, this is about backups and scheduled backups being able to overwrite the backup target policy. Or at least that's how I intended it, is that correct, @gbartolini?
