### ISSUE TITLE
Client-side encryption for backups

### ISSUE THREAD

**Issue by ArjonBu** [cloudnative-pg/cloudnative-pg#1146]
Hello, 

Currently cloudnative-pg supports applying an encryption policy to the s3 objects which itself is encryption at rest. 
I don't see any option to have client-side encryption. Basically I want my databases to be encrypted in my cluster and then uploaded to the s3 endpoint. I do not want the cloud provider to be able to read my backups. 

Is this currently possible? [Rclone crypt remote](https://rclone.org/crypt/) is a good example on what I am looking for. 

Thanks in advamce

**Comment by gbartolini** [comment]
AFAIK Barman Cloud (which we rely on) does not support this. @theadamwright can you please confirm?

**Comment by sxd** [comment]
Turning this into a discussion since it's not an issue yet.
