### ISSUE TITLE
Allow .spec.postgresqlVersion in Cluster definition

### ISSUE THREAD

**Issue by aran** [cloudnative-pg/cloudnative-pg#1207]
Currently cloudnative-pg uses a clever convention to retrieve the postgres major version from its own image tag.

As a feature request, allow overriding this convention with an explicit configuration setting, for example, "postgresqlVersion". If specified, this setting would be used by validation code and other logic in place of the tag.

The motivation is a tool called [Skaffold](https://skaffold.dev/). For rapid iteration in dev mode, skaffold generates an image digest to use as a tag and pushes it directly to docker daemon. The image digest ensures that there is never an inconsistency where the kubernetes has the wrong version of an image. The cnpg webhook validation rejects these images.

**Comment by sxd** [comment]
Hi @aran 

Yes, this is used to avoid using images 15 in a cluster that was created with version 14, that will produce a lots of issues, and it's not a minor problem that can be solved easily, major upgrades in PostgreSQL can come with lots of problems to solve, imagine if someone just put a different version (greater or lower) in the storage, that will be a big mess.

Do you have an idea on how to solve that issue? someone putting a version greater or lower than the one in the storage?

Turning this into a discussion

Best Regards!
