### ISSUE TITLE
Cleanup old testing images from container registry

### ISSUE THREAD

**Issue by mnencia** [cloudnative-pg/cloudnative-pg#121]
The testing images are generated for every pull request and commit, and they never expire.

We need to implement something like 

https://github.com/snok/container-retention-policy

And let the old containers in `-testing` repositories disappear in one week.

**Comment by litaocdl** [comment]
Due to issue [.github/workflows/registry-clean.yml ](https://github.com/snok/container-retention-policy/issues/33) exists, I split the images remove into two actions, for `cloudnative-pg-testing`, keep 5 days images until issue is fixed, for the other two testing image, keep 7 days images.

**Comment by hh24k** [comment]
> Due to issue [Action should evaluate all pages of Get all package versions API response](https://github.com/snok/container-retention-policy/issues/33) exists, I split the images removing into 2 actions, for package `cloudnative-pg-testing`, keep 5 days images until issue is fixed. for `pgbouncer-testing` and `postgresql-testing`, keep 7 days images.

Just add it for the convenience of understanding: the different retention periods are set based on the packages' different update frequency.
