### ISSUE TITLE
E2E: investigate failure of configuration update test

### ISSUE THREAD

**Issue by jsilvela** [cloudnative-pg/cloudnative-pg#126]
The configuration update test is failing often in the cloudnative-pg repository.
See https://github.com/cloudnative-pg/cloudnative-pg/runs/6338341491?check_suite_focus=true

**Comment by litaocdl** [comment]
Add some trace in branch to investigating

**Comment by litaocdl** [comment]
A failure https://github.com/cloudnative-pg/cloudnative-pg/runs/6384630653?check_suite_focus=true#step:8:1814
the pg sever kept in pending restart status for 300 seconds, then case failed. investigating...

**Comment by litaocdl** [comment]
The failure happens waiting for all pods in a status without pending restart,  during that time, from the log I find `he primary needs to be restarted, we'll trigger a switchover to do that`, this means the instance is going to have a swtich over. probally this is the required switch over in prevous test case, so we need give privous test case a well good ending.

**Comment by litaocdl** [comment]
The failure is caused by a bug. while do the configuration change by decreasing the sensitive param. expected process is 
1. primary decrease by a restart. 
2. standby decrease.  there is no switchover.  but switchover happens after apply the decreasing configuration. opened another tiket to solve the issue, and use this one to refact the e2e

**Comment by litaocdl** [comment]
The fix for failure is covered by issue https://github.com/cloudnative-pg/cloudnative-pg/issues/168

for this issue, refactor the configuration test suite, move each configuration change into a seperate spec, make it well orginazed and easy to diagnose and expand in future.

**Comment by wadlejitendra** [comment]
LGTM.
