### ISSUE TITLE
Enabling Monitoring for running cluster does not restart pods

### ISSUE THREAD

**Issue by maaft** [cloudnative-pg/cloudnative-pg#1324]
For a running cluster, the pods are not restarted, when enabling monitoring afterwards.

```yaml
monitoring:
    enablePodMonitor: true
```

I had to restart the pods manually to enable metrics.

I'd expect `cnpg` to pick-up these changes and roll-out new pods (with exposed metrics).

**Comment by phisco** [comment]
Hi @maaft, could you better explain why you "had to restart the pods manually to enable metrics"? What were you expecting and what was not working before you restarted the pods?
