### ISSUE TITLE
Update status if pvc resize is pending

### ISSUE THREAD

**Issue by jlong49** [cloudnative-pg/cloudnative-pg#134]
Currently we update the status of the cluster if a resize is happening but there are scenarios where a resize could be pending for a non trivial amount of time. In these instances we should update the Cluster status to reflect that a resize is scheduled to happen but has yet to happen.

**Comment by gbartolini** [comment]
While writing the release notes, I could not figure out why we are doing this. Are we sure we want to ship this in the next patch release? This is our last chance to revert it.

**Comment by sxd** [comment]
I'm closing this issue, since it's not needed anymore
