### ISSUE TITLE
Suppress "Backup not configured, skip WAL archiving" if no backup is configured

### ISSUE THREAD

**Issue by edgarkz** [cloudnative-pg/cloudnative-pg#1371]
Hello,
Running PG 14.5 using the latest 1.18 operator and I do see the following info level msg in the logs
`"logger":"wal-archive","msg":"Backup not configured, skip WAL archiving","logging_pod":"audit-1","walName":"pg_wal/000000010000001F00000018"`

I don’t have any backups configured, is there any way to suppress those msgs? can it be turned off by default? or maybe you can add a flag to suppress it
https://github.com/cloudnative-pg/cloudnative-pg/blob/main/internal/cmd/manager/walarchive/cmd.go#L111

thank you

**Comment by gbartolini** [comment]
I have already responded in the chat about this issue, but I will briefly reply here.

There is actually a reason for that message to be there. Our point of view at CloudNativePG, given also our story in the Postgres community with Barman, is that there are no production databases without continuous backup in place, and we remind users of that. WAL archiving is required by continuous backup, which is required for point in time recovery.

WAL files are also important for self-healing purposes, as they prevent replicas from falling out of sync and enable former primaries to resync in case WAL files are not present on the other location.

Those log entries are like sentinels that protect users, especially new users of Postgres, from data loss.

**Comment by sxd** [comment]
Closing since this it's not considered an issue and it was already answered in Slack
