### ISSUE TITLE
Operator does not deploy on OpenShift

### ISSUE THREAD

**Issue by wkulhanek** [cloudnative-pg/cloudnative-pg#143]
The operator won't start on OpenShift because of security constraints.

From the events after the `kubectl apply` step:

9s          Warning   FailedCreate        replicaset/cnpg-controller-manager-74d87d659   Error creating: pods "cnpg-controller-manager-74d87d659-" is forbidden: unable to validate against any security context constraint: [provider "anyuid": Forbidden: not usable by user or serviceaccount, provider "pipelines-scc": Forbidden: not usable by user or serviceaccount, provider "containerized-data-importer": Forbidden: not usable by user or serviceaccount, spec.containers[0].securityContext.runAsUser: Invalid value: 1001: must be in the ranges: [1000770000, 1000779999], provider "nonroot": Forbidden: not usable by user or serviceaccount, provider "hostmount-anyuid": Forbidden: not usable by user or serviceaccount, provider "kubevirt-controller": Forbidden: not usable by user or serviceaccount, provider "bridge-marker": Forbidden: not usable by user or serviceaccount, provider "machine-api-termination-handler": Forbidden: not usable by user or serviceaccount, provider "hostnetwork": Forbidden: not usable by user or serviceaccount, provider "hostaccess": Forbidden: not usable by user or serviceaccount, provider "linux-bridge": Forbidden: not usable by user or serviceaccount, provider "nmstate": Forbidden: not usable by user or serviceaccount, provider "kubevirt-handler": Forbidden: not usable by user or serviceaccount, provider "node-exporter": Forbidden: not usable by user or serviceaccount, provider "privileged": Forbidden: not usable by user or serviceaccount]

**Comment by gbartolini** [comment]
Hi @wkulhanek, thanks for your question.

We currently have no plans to support OpenShift at community level, at least in this phase - we are now concentrated in testing vanilla Kubernetes. Things might change when the community grows together with the contributors' base.

Having said this, we always welcome those organisations that are willing to offer that kind of support as part of their professional services. We will list all of them in the ["Support" page of the website](https://cloudnative-pg.io/support/).

**Comment by sxd** [comment]
Closing, it can be reopened if needed or create new one.

**Comment by jngrb** [comment]
For the record: this can be overcome to get it running with the privileged role for the service account:
```
oc project cnpg-system
oc adm policy add-scc-to-user privileged -z cnpg-cloudnative-pg
```
This assumes that the target namespace is cnpg-system and the serviceaccount is named cnpg-cloudnative-pg.

Please note that this is not a proper reconciliation because now the service account has too many rights. The privileged scc is the most permissive one.

**Comment by edib** [comment]
@jngrb  I have overcome the problem like this but when I am creating cluster,   initdb container says. "logger":"initdb","msg":"The files belonging to this database system will be owned by user \"1000730000\".\ and then real pg leader container fails with this. "standard_init_linux.go:219: exec user process caused: permission denied" 
I cannot find anywhere to set this id in cluster definition.  any idea?

**Comment by 0x4d6165** [comment]
Having this issue too. Anyone have an idea for how to fix this?
