### ISSUE TITLE
Replace distroless image in the Dockerfile

### ISSUE THREAD

**Issue by sxd** [cloudnative-pg/cloudnative-pg#1508]
We're currently using gcr.io/distroless/static:nonroot and we should use gcr.io/distroless/static-debian11:nonroot according to the documentation here https://github.com/GoogleContainerTools/distroless#what-images-are-available

**Comment by ismailbaskin** [comment]
What do you think about using [ko](https://github.com/ko-build/ko#ko-easy-go-containers)? In this way, CI configuration can also be simplified.
