### ISSUE TITLE
Refactoring of the backup command code

### ISSUE THREAD

**Issue by armru** [cloudnative-pg/cloudnative-pg#1523]
The current implementation of the backup code is quite complex and the result of regular addition of code over time. With backup from a standby, for example, we have introduced a few bugs that were only noticed when BigAnimal went in production.

It is also difficult for new developers to start working on this part of the code. It is a general opinion in the team that a refactoring exercise is needed to reduce the cognitive load required to improve and maintain it in the future.

We should start by removing the duplicated code regarding the conditions and the defer of LastFailedBackup

Issue made by @armru @mnencia @gbartolini

**Comment by leonardoce** [comment]
The merged PR partially close this issue, so I'm reopening it.
