### ISSUE TITLE
barman-cloud-backup fails with "Part number must be an integer between 1 and 1000"

### ISSUE THREAD

**Issue by jgillich** [cloudnative-pg/cloudnative-pg#1673]
My base backups are failing, and I've tracked it down to this:
```
{"level":"info","ts":1677975525.336761,"logger":"barman-cloud-backup","msg":"2023-03-05 00:18:45,335 [2472973] ERROR: Upload error: An error occurred (InvalidArgument) when calling the UploadPart operation: Part number must be an integer between 1 and 1000, inclusive (worker 0)","pipe":"stderr","logging_pod":"pool1-cnpg-1"}
{"level":"info","ts":1677975525.64154,"logger":"barman-cloud-backup","msg":"2023-03-05 00:18:45,639 [2472161] ERROR: Error received from upload worker: An error occurred (InvalidArgument) when calling the UploadPart operation: Part number must be an integer between 1 and 1000, inclusive","pipe":"stderr","logging_pod":"pool1-cnpg-1"}
```

Related to https://github.com/EnterpriseDB/barman/issues/284

I'm using Scaleway object storage, which apparently only supports up to 1000 parts. Therefore, this error appears after exceeding 20GB.

A solution could be to add a configuration option for the barman `--max-archive-size` flag (as far as I can tell it's not available in CNPG at the moment).

**Comment by sxd** [comment]
I'm closing this since it's a bug in Barman and not in CloudNativePG, when it's fixed there it will be fixed in the new operand image
