### ISSUE TITLE
Add Issue templates

### ISSUE THREAD

**Issue by phisco** [cloudnative-pg/cloudnative-pg#1679]
We should define some issue templates so that we can ask for details and point to the discussion section for Q&A.
See https://github.com/crossplane/crossplane/issues/new/choose as an example.

**Comment by phisco** [comment]
another really good example: https://github.com/golangci/golangci-lint/tree/master/.github/ISSUE_TEMPLATE

**Comment by phisco** [comment]
and another one: https://github.com/renovatebot/renovate/tree/main/.github/ISSUE_TEMPLATE, see also how they have templates for discussions at https://github.com/renovatebot/renovate/tree/main/.github/DISCUSSION_TEMPLATE

**Comment by sxd** [comment]
This was already done
