### ISSUE TITLE
PG Certificates - configurable values for threshold \ certificateDuration

### ISSUE THREAD

**Issue by edgarkz** [cloudnative-pg/cloudnative-pg#1691]
Hello,
Currently those are hardcoded values for certificate renewal threshold and also certificate duration.
Can you please make those value adjustable via helm chart?

expiringCheckThreshold:
https://github.com/cloudnative-pg/cloudnative-pg/blob/main/pkg/certs/certs.go#L49
[certs.go](https://github.com/cloudnative-pg/cloudnative-pg/blob/main/pkg/certs/certs.go)
    expiringCheckThreshold = 7 * 24 * time.Hour

certificateDuration: 
https://github.com/cloudnative-pg/cloudnative-pg/blob/main/pkg/certs/certs.go#L40
[certs.go](https://github.com/cloudnative-pg/cloudnative-pg/blob/main/pkg/certs/certs.go)
    certificateDuration = 90 * 24 * time.Hour

`        Issuer: OU=postgresql, CN=archive
        Validity
            Not Before: Jan 25 12:40:34 2023 GMT
            Not After : Apr 25 12:40:34 2023 GMT
        Subject: OU=postgresql, CN=archive
`

**Comment by gbartolini** [comment]
Any volunteers in the community to try and tackle this and submit a pull request?

**Comment by Otterpohl** [comment]
I will take a look at this over the next couple of weeks!
