### ISSUE TITLE
Argocd: error calculating structured merge diff after upgrading helm-chart from 0.16.1 to 0.17.0

### ISSUE THREAD

**Issue by maaft** [cloudnative-pg/cloudnative-pg#1698]
I've deployed cnpg via helm and argocd. After upgrading the helm-chart from 0.16.1 to 0.17.0 an thus the operator to 1.19, argocd fails to calculate the diff with this error:

```
error calculating structured merge diff: error building typed value from live resource: errors: .spec.backup.target: field not declared in schema .spec.failoverDelay: field not declared in schema
```

Is there any guideline for users how to handle this?

Sorry, if this a question is more related to argocd. Happy to close, if this is the case.

**Comment by maaft** [comment]
apparently, this is on ArgoCD's side: [CRDs are not updated](https://github.com/argoproj/argo-cd/issues/9303)

I solved it by applying all CRDs manually, then upgrading cnpg.

**Comment by itay-grudev** [comment]
@maaft It's actually from Helm. You need to manually upgrade CRDs. Always check the charts upgrade guides, as rhey will tell you, usually, if a manual step is required.
