### ISSUE TITLE
failed to wait for cluster caches to sync: timed out waiting for cache to be synced

### ISSUE THREAD

**Issue by Evolt0** [cloudnative-pg/cloudnative-pg#1739]
it always restart ,when apply this operator 
occured by failed to wait for cluster caches to sync
![image](https://user-images.githubusercontent.com/38104576/225801440-907e56d7-a18e-4a24-895e-3658604160de.png)

**Comment by sxd** [comment]
@Evolt0 the errors above show something like the operator wasn't installed properly, how was the operator installed?
Also, can you please share the error in plain text? it's a bit annoying to read an image.

I'm turning this into a discussion since it's not an issue yet
