### ISSUE TITLE
pulling ghcr.io/cloudnative-pg/postgresql:15.2 error

### ISSUE THREAD

**Issue by cloveropen** [cloudnative-pg/cloudnative-pg#1781]
how can i pull the ghcr.io/cloudnative-pg/postgresql:15.2 manually?
use docker or ctr？

**Comment by phisco** [comment]
`docker pull ghcr.io/cloudnative-pg/postgresql:15.2` is working for me

**Comment by cloveropen** [comment]
thank @phisco
