### ISSUE TITLE
Avoid executing DDLs against PostgreSQL when not needed

### ISSUE THREAD

**Issue by leonardoce** [cloudnative-pg/cloudnative-pg#179]
In this moment the reconciliation loop of the instance manager will execute a `CREATE EXTENSION IF NOT EXISTS` or `DROP EXTENSION IF EXISTS` every time PostgreSQL is started, and this is needed to keep the list of extensions we managed aligned with the database.

It's better to avoid executing a DDL when this is possible, as this results in spurious logging when every DDL is logged

**Comment by gbartolini** [comment]
I agree, it makes sense to first peek in the catalog with a `SELECT`.
