### ISSUE TITLE
The `pg_replication_slots` metric fails on a replica

### ISSUE THREAD

**Issue by gbartolini** [cloudnative-pg/cloudnative-pg#1794]
The file `config/manager/default-monitoring.yaml` contains a metric called `pg_replication_slots` that at the moment can only be run if executed on the primary due to the execution of functions that cannot be executed on replicas. This is similar to the problem resolved by the patch contained in #1666 (issue #1604).

When running this query on a standby it returns `WAL control functions cannot be executed during recovery`:

```
        SELECT slot_name,
          slot_type,
          database,
          active,
          pg_catalog.pg_wal_lsn_diff(pg_catalog.pg_current_wal_lsn(), restart_lsn)
        FROM pg_catalog.pg_replication_slots
        WHERE NOT temporary
```

This is also still present in the prometheus exporter: https://github.com/prometheus-community/postgres_exporter/issues/547

**Comment by sajdakabir** [comment]
@gbartolini  can I work on this issue?

**Comment by gbartolini** [comment]
Of course, please propose a patch if interested

**Comment by mblp** [comment]
https://github.com/prometheus-community/postgres_exporter/pull/914

**Comment by B1ue-W01f** [comment]
@gbartolini Im somewhat confused, i cant find the fixes referenced here actually present in the 1.22.2, or 1.21.0 releases?
