### ISSUE TITLE
Docs could not build local

### ISSUE THREAD

**Issue by schnes4** [cloudnative-pg/cloudnative-pg#184]
Hi,

I've discussed your project with your team on KubeCon in Valencia and tried to give it a try.
But if I try to build the documentation local it fails because I'm not authorized to pull the docker image used in the README.

```
docker pull quay.io/enterprisedb/cloud-native-docutils:mkdocs
Error response from daemon: unauthorized: access to the requested resource is not authorized
```

Is there a deployed version of the documentation I missed?

**Comment by sxd** [comment]
Hi @schnes4 

Yes, you're totally right, that's was clearly something we missed when open sourcing the project, we will work on fix it that!

You can see the same copy of the last documentation here https://cloudnative-pg.io/documentation/1.15.0/ while we work on fixing this

Regards!

**Comment by gbartolini** [comment]
We will remove the PDF build most likely. For now you can just run the local docs with:

```
mkdocs serve
```

**Comment by gbartolini** [comment]
What about changing the instructions to use a widely available image of mkdocs such as https://hub.docker.com/r/minidocks/mkdocs ?

**Comment by gbartolini** [comment]
I have pushed a patch for this, please someone test it.

**Comment by schnes4** [comment]
👍 
I like the generic Image!

Maybe you could add a link to the current deployed documentation in the main readme
