### ISSUE TITLE
Reporting a vulnerability

### ISSUE THREAD

**Issue by igibek** [cloudnative-pg/cloudnative-pg#1894]
Hello! 

I hope you are doing well! 

We are a security research team. Our tool automatically detected a vulnerability in this repository. We want to disclose it responsibly.  GitHub has a feature called **Private vulnerability reporting**, which enables security research to privately disclose a vulnerability. Unfortunately, it is not enabled for this repository. 

Can you enable it, so that we can report it? 

Thanks in advance! 

PS: you can read about how to enable private vulnerability reporting here: https://docs.github.com/en/code-security/security-advisories/repository-security-advisories/configuring-private-vulnerability-reporting-for-a-repository

**Comment by sxd** [comment]
Hi @igibek ! 

It was enabled, so now you can report =) 

Thank sin advance!

Regards!

**Comment by sxd** [comment]
Hi @igibek 

We haven't hear or get anything in the last week, it's this vulnerability still an issue ?
For the moment I'm closing this so we can keep a track if it's reopened and don't forget in the future

Best Regards!
