### ISSUE TITLE
Feature request: label inheritance from custom resource

### ISSUE THREAD

**Issue by fernandr** [cloudnative-pg/cloudnative-pg#1923]
Current: can inherit labels as defined in operator configmap.

Want: to inherit labels from custom resource too (kind: Cluster)

Motivation: 

- As platform team, we are running one operator in a multi-tenant K8s cluster, 
- various tenants (customers) are spinning-up custom resources, 
- each customer wanting to use their own labels (to be propagated to e.g. the database instance pods)

**Comment by phisco** [comment]
If you mean that you would like users to be able to specify labels/annotations on a Cluster and get them propagated to other resources created for that Cluster, you can use the `spec.inheritedMetadata` field already: https://github.com/cloudnative-pg/cloudnative-pg/blob/main/config/crd/bases/postgresql.cnpg.io_clusters.yaml#L2148

**Comment by fernandr** [comment]
Works like a charm :-)

**Comment by sxd** [comment]
Looks solved, closing this issue, you can reopen it if that's not the case
