### ISSUE TITLE
kubectl-cnpg completion bash fails when there is no APIserver

### ISSUE THREAD

**Issue by sathieu** [cloudnative-pg/cloudnative-pg#1932]
When `KUBECONFIG` is not set, I get:

```console
$ kubectl cnpg completion bash
Error: Get http://localhost:8080/api?timeout=32s: dial tcp 127.0.0.1:8080: connect: connection refused
$ # While it works for `kubectl`:
$ kubectl completion bash
# Copyright 2016 The Kubernetes Authors.
# [...]
```

This prevents usage of `source <(kubectl cnpg completion bash)` in `~/.bashrc`

**Comment by sathieu** [comment]
The cause is probably:

https://github.com/cloudnative-pg/cloudnative-pg/blob/943c514361e1b947340504b4234990f775cf0a0c/cmd/kubectl-cnpg/main.go#L58-L61

This part should not be run with the `completion` command.

**Comment by sxd** [comment]
Hi @sathieu 

Yes, following your analysis makes a lot of sense it fails because of that, I'm assigning this ticket to me to work on a fix during the day! will let you know and update the ticket!

Thanks for this report!

Regards!

**Comment by sxd** [comment]
Hi @sathieu 

There's a PR in place, can you test it and provide us your input on this fix?

Regards!
