### ISSUE TITLE
[ Medium Prio] Pods stuck in taint toleration after node restart

### ISSUE THREAD

**Issue by Ornias1993** [cloudnative-pg/cloudnative-pg#1946]
In some obscure custom cases, such as single-node TrueNAS SCALE clusters, the cluster adds a taint to the node on reboot, which gets removed after all bootup procedure are finished.

This, obviously means the pods cannot be scheduled till after the taints are removed.
However the pods don't automatically get recreated after the taints are removed from the node. Leading to the cnpg pods never restarting.

Dirty solution:
- Recreate after 5 minutes if pods get stuck in taint-toleration state

Clean solution:
- Check when there is a schedulable node available, then recreate pods

---
Medium prio, due to completely bricking cnpg in some cases on singlenode clusters.

**Comment by Ornias1993** [comment]
Thanks for putting some time into this @armru !

**Comment by mnencia** [comment]
Can you please test #2056 and see if it solves the issue?
