### ISSUE TITLE
Important changes to default values in 1.20

### ISSUE THREAD

**Issue by litaocdl** [cloudnative-pg/cloudnative-pg#1950]
Version 1.20 will change the default behaviour of the operator for a few settings, as described in #1707.

Specifically:

- replication slots for HA will be enabled by default, unless explicitly disabled in `.spec.replicationSlots.highAvailability.enabled`
- following a rolling update, the primary will be restarted, unless `switchover` is explicitly defined for `.spec.primaryUpdateMethod`
- base backups will be taken from a standby, if available, unless `.spec.backup.target` is explicitly set to `primary`
- the `-any` service will not be created anymore, unless the `CREATE_ANY_SERVICE` variable in the operator's configuration is set to `true` (already implemented as part of 3798c23aa10baaf677a2aff2731fd3162e409a81).

Make the above changes and add a section in the docs that explains the upgrade path.

**Comment by gbartolini** [comment]
We decided to postpone changing the default for replication slots to 1.21 and prepare for that in this release.
