### ISSUE TITLE
Support HA for logical replication slots

### ISSUE THREAD

**Issue by sjuls** [cloudnative-pg/cloudnative-pg#1962]
Currently CloudNativePG supports HA replication slots for physical replication slots, but ignores _logical_ replication slots. To better support connectors such as debezium which require the replication slot to be available upon connection, it would make sense to extend the current behaviour to also synchronize logical replication slot from the primary to the standby's and advance the LSN in the configured interval.

This would also protect against excessive WAL piling up on a standby risking running out of disk, since the consumer will likely consumer from the primary instance.

Similar comments have been made to [issue 13](https://github.com/cloudnative-pg/cloudnative-pg/issues/13), though the issue seems to have an overall different goal, hence the separate issue I am creating here.

**Comment by nmargaritis** [comment]
Hello, what's the status of this?

**Comment by ntx-ben** [comment]
Also looking forward to this for Debezium support

**Comment by justinwyer** [comment]
Is any community contribution needed to move this forward?

**Comment by ironytr** [comment]
any update?

**Comment by ozen** [comment]
Looks like this is not an issue anymore sine the pg_failover_slots extension is the solution:

https://github.com/cloudnative-pg/cloudnative-pg/pull/1997#issuecomment-1722519914

**Comment by sjuls** [comment]
@ozen I agree, closing.
