### ISSUE TITLE
[Feature] begin using `startupProbe`

### ISSUE THREAD

**Issue by jcpunk** [cloudnative-pg/cloudnative-pg#1964]
With `startupProbe` introduced in Kubernetes 1.17, and the current version being 1.27, can CNPG begin using this feature?

Folks running Kubernetes older than 1.17 are unlikely to be updating CNPG at this point.

**Comment by armru** [comment]
I explored the possibility of adding a startupProbe implementation and it resulted more complex than needed without adding enough benefits.

I think we can revisit the opportunity to add the startupProbe once we simplify the operator <> instance interactions.

cc @mnencia @gbartolini

**Comment by sxd** [comment]
closing since it was the wontfix label
