### ISSUE TITLE
[DOC] example using Subject Alternative Name

### ISSUE THREAD

**Issue by jcpunk** [cloudnative-pg/cloudnative-pg#1965]
It would be helpful if https://cloudnative-pg.io/documentation/1.19/certificates/#server-alternative-dns-names had an example of how to set the SAN for the server certificate.

**Comment by sxd** [comment]
Hi @jcpunk 

You can find that documentation here https://cloudnative-pg.io/documentation/1.19/api_reference/#CertificatesConfiguration

Regards!
