### ISSUE TITLE
[DOC] example alert when recovery point older than XYZ

### ISSUE THREAD

**Issue by jcpunk** [cloudnative-pg/cloudnative-pg#1975]
The example dashboard provides a timeseries for `cnpg_collector_first_recoverability_point{namespace=~"$namespace",pod=~"$instances"}*1000 > 0`.

It would be nice if the example PrometheusRules were extended to have a alert at severity warning if there is no recoverability_point within the last 24 hours and an alert at severity critical if no point within the last week.

These examples should help folks figure out what is right for them with minimal effort while also acting as a reminder that these data points should be part of a production alerting path.

**Comment by sxd** [comment]
hello @jcpunk 

That will be a great idea, can you suggest a change with a PR? Thanks in advance!

Regards!

**Comment by sxd** [comment]
The dashboard is not handled on this project anymore closing https://github.com/cloudnative-pg/grafana-dashboards
