### ISSUE TITLE
1.20 "kubectl-cnpg install generate" is using the 1.19 operator image

### ISSUE THREAD

**Issue by smiyc** [cloudnative-pg/cloudnative-pg#1988]
@gbartolini 

The 1.20 kubectl-plugin is usting the 1.19 (test) image.

╰─➤  kubectl-cnpg version                                                       
Build: {Version:1.20.0 Commit:008bb80b Date:2023-04-27}

╰─➤  kubectl-cnpg install generate --namespace cnpg-test > cnpg-test_1.20.0.yaml
{"level":"info","ts":"2023-04-28T12:02:01+02:00","msg":"fetching installation manifests","branch":"release-1.19","url":"https://raw.githubusercontent.com/cloudnative-pg/artifacts/release-1.19/manifests/operator-manifest.yaml"}

╰─➤  grep 1.20 cnpg-test_1.20.0.yaml 

╰─➤  grep 1.19 cnpg-test_1.20.0.yaml                                                                                                                        
          value: ghcr.io/cloudnative-pg/cloudnative-pg-testing:release-1.19
        image: ghcr.io/cloudnative-pg/cloudnative-pg-testing:release-1.19

**Comment by NiccoloFei** [comment]
This has been fixed with #2130. Now the plugin will use its internal release YAMLs to generate the output release manifest. By default it will generate a manifest using the same version of the `cnpg plugin`, and it will use stable release images.
