### ISSUE TITLE
Can recent releases be added in main branch "releases" folder?

### ISSUE THREAD

**Issue by quercus-carsten** [cloudnative-pg/cloudnative-pg#1995]
Hi folks,

first of all - thank you for providing this awesome operator. It's really reliable so far and
made it so much easier to accomplish my tasks.

I have a question about the releases. I use RenovateBot to pull updates from here:
https://github.com/cloudnative-pg/cloudnative-pg/tree/main/releases

What I now stumbled upon is that there is only 1.XX.0 and 1.XX.1 Versions shown in main branch /releases.
Is there any chance you could push your recent versions of the operator to main?

( I know that I could for instance pull from here:
  https://github.com/cloudnative-pg/cloudnative-pg/releases/download/v1.19.2/cnpg-1.19.2.yaml
  but the version [1.19.2] is mentioned twice in the URL, which is problematic for RenoveateBot ) ...

If you have an alternative URL with just one version number in it, then I would gladly take that too.
Thanks again for this great operator :)

**Comment by sxd** [comment]
Hi @quercus-carsten 

The YAML file are in the release page in GitHub, so probably that isn't an issue for RenovateBot? We use RenovateBot for the project too, but I don't know if that could be useful, probably @phisco can help us a bit here.

Can you let us know if this still being an issue?

Regards!

**Comment by phisco** [comment]
🤔 can you describe what you are trying to achieve and share the relevant parts of your renovate config?

**Comment by quercus-carsten** [comment]
Hi @sxd and hi @phisco , thanks for your replies, let me share some more detail about my config.

renovate.json:
```
  "regexManagers": [

    {
      "fileMatch": [
        "^kustomization.yaml$"
      ],
      "matchStrings": [
        ".*cnpg-(?<currentValue>.*).yaml"
      ],
      "datasourceTemplate": "github-tags",
      "depNameTemplate": "cloudnative-pg/cloudnative-pg",
      "extractVersionTemplate": "(?<version>\\d+.\\d+.\\d+)"
    }
  ]
```

kustomization.yaml :
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://raw.githubusercontent.com/cloudnative-pg/cloudnative-pg/main/releases/cnpg-1.19.1.yaml
- controller-config-map.yaml
patchesStrategicMerge:
  - patch-delete.yaml
```

I use kustomize to pull cnpg yaml. It allows me to make adjustments I need for different clusters using overlays.

Now where I am stumbling upon is the resources part. As you can see, I need to reference the URL leading to the cnpg yaml. The URL is parsed by renovate for a version. The regexManager defined in renovate.json does the follwing for me:
1. It finds my kustomize.yaml
2. It searches for a version in the URL. [ which in this example is "cnpg-1.19.1.yaml" so it grabs  "1.19.1" ]
3. It searches for new git tags in cloudnative-pg repository ( "removes the leading "v" character)
4. It compares the version numbers
5. If there is one or more new tags, then renovate will open separate MR/PR for my gitlab repository
6. The MR/PR contains an automatically generated URL based on the regex match. For instance:
    "-   https://raw.githubusercontent.com/cloudnative-pg/cloudnative-pg/main/releases/cnpg-1.19.1.yaml"
    "+   https://raw.githubusercontent.com/cloudnative-pg/cloudnative-pg/main/releases/cnpg-1.19.2.yaml"

And there is where the update will fail: there is no "cnpg-1.19.2.yaml" in main branch.


I also had a look at the downloads in "releases" section. There you find another path structure in the URL:
  https://github.com/cloudnative-pg/cloudnative-pg/releases/download/v1.19.2/cnpg-1.19.2.yaml

Renovate can only find and replace a version in one place with "currentValue". But this URL has the version twice: ".../v1.19.1/cnpg-1.19.1.yaml" which results in
".../v1.19.1/cnpg-1.19.2.yaml"


So another idea would be to simply use a filename like "cnpg.yaml", whatever the version - then you still would have separate folders for different versions.
But my guess is it's maybe easier to push new versions of cnpg yaml also into main branch /releases folder ...

**Comment by phisco** [comment]
Makes sense! Maybe you could work around that using https://docs.renovatebot.com/configuration-options/#autoreplacestringtemplate? 🤔

**Comment by quercus-carsten** [comment]
Cool :sunglasses:. This actually allowed me to replace the version more than once in the URL. You are free to place it multiple times in a newly generated string. The resulting string replaces the line with regexMatch completely. This is what I added to my regexManagers config:
```
"autoReplaceStringTemplate": "- https://raw.githubusercontent.com/cloudnative-pg/cloudnative-pg/v{{{newValue}}}/releases/cnpg-{{{newValue}}}.yaml"
```
Thank you @phisco for this idea!
