### ISSUE TITLE
Krew release failing due to wrong URL

### ISSUE THREAD

**Issue by sxd** [cloudnative-pg/cloudnative-pg#200]
The krew release failed for version v1.15.1 due to some issues with the home page, that didn't match the one that was already there.

The proper homepage needs to be the GitHub URL of the project just like it is in the krew project.

**Comment by sxd** [comment]
It's being updated with this PR https://github.com/kubernetes-sigs/krew-index/pull/2292

**Comment by ahmetb** [comment]
Homepage doesn't need to be a github url. The release probably failed to merge automatically because it changed, requiring manual review.

**Comment by sxd** [comment]
@ahmetb yep, that's why we created the new PR, since our CI has the github url which is the one we actually want, thanks for caring about this!

**Comment by sxd** [comment]
The issue should not happen again since the homepage URL is now the same in the release at Krew index and our CI
