### ISSUE TITLE
Cluster Bootstrapping fails with Meta-Commands in postInitSQL Section

### ISSUE THREAD

**Issue by realulim** [cloudnative-pg/cloudnative-pg#2023]
When trying to create a database with schemas via postInitSql we have no choice (due to PostgreSQL not having a use command like MySQL) but to use meta commands like so:

```
postInitSQL:
  - CREATE DATABASE mydb;
  - \connect mydb
  - CREATE SCHEMA IF NOT EXISTS myschema;

```
The backslash in the connect meta command is then apparently escaped in the conversion to JSON and bootstrapping the cluster then fails with an error message like this:

`"message":"syntax error at or near \"\\\"","query":"\\connect mydb","query_pos":"1"`

**Comment by realulim** [comment]
The problem with escaping the backslash exists for postInitApplicationSQL as well. I agree that you should not try to interpret these commands at all, but can't you just send them to the database?

That being said, I have meanwhile found a workaround for my concrete problem, so that I don't have to use any Backslash-Commands anymore.

**Comment by matanshk** [comment]
Same issue here..
@realulim , can you please share your solution?

**Comment by realulim** [comment]
My workaround was to switch to Kubegres.

**Comment by andonovj** [comment]
Hello guys
I have the following problem with pgcloudnative.
I am trying to execute several commands on a database, but it doesn't execute at all and nothing in the logs:


`      postInitSQL:
        - "CREATE DATABASE portal_db OWNER experience_db;"
        - "CREATE DATABASE referral_db OWNER experience_db;"
        - "CREATE USER pghero WITH LOGIN PASSWORD 'password';"
      postInitApplicationSQL:
        - "CREATE SCHEMA pghero;"
      postInitApplicationSQLRefs:
        configMapRefs:
        - name: postinitapp-cm
          key: pghero.sql
`

The postInitSQL executed, but not the other two: postInitApplicationSQL or postInitApplicationSQLRefs
Nothing in the postgresql log file, also I cannot set it as it is "fixed" parameter nor the kubectl logs.

Any advice ?

Best regards
