### ISSUE TITLE
Handle volumes remounted as read-only

### ISSUE THREAD

**Issue by mkroman** [cloudnative-pg/cloudnative-pg#2024]
Hi,

I have found a scenario where mounted volume blocks used for postgres data and WAL end up as read-only, and the postgres instance continues to look "healthy".

### Background

I run a Kubernetes cluster in my home lab with a random assortment of resource-limited nodes, which means I run into all kinds of fun edge cases.

For my data plane I run [Longhorn](https://longhorn.io/), and because my resource-limited nodes also run as control-plane and etcd nodes, all on the same disk, I run into a scenario where Longhorn can't reach a volume replica on a node (possibly because its apiserver isn't responding as the disk is thrashing, or the manager is.)

This sometimes creates a negative feedback loop where Longhorn will then re-provision the volume (and possibly other volumes) on another node - only for that node to start thrashing and timing out as well, due to the massive increase in disk operations.

Eventually the volume ends up in a state where the kernel (or longhorn instance manager?) remounts the block volume as read-only, due to errors, which is accepted and provisioned to the postgres instance pod.

### Issue

I don't think the actual issue is limited to my setup - I believe it is just exacerbated by it.

Longhorn relies on `iscsid`. If this issue is limited to volume managers running a similar setup, I think it is still worth looking into, as such a setup doesn't seem uncommon.

When a postgres instance is running with a read-only mounted volume there doesn't seem to be any health checks or sanity checks - and the instance appears healthy, which prevents the controller from recreating the instance.

It could be that the filesystem errors aren't propagated properly, but I can't exclude that it may just be that my app always attempts a read before a write.

### Proposal

Filesystem writability could perhaps be a periodic health check? Not sure if there's a use-case for read-only instances with read-only volumes that makes this more difficult.

Otherwise it's worth looking into how fs errors are propagated.. At some points it may be better for the whole thing to crash, so a failover can happen.

### Details

Some details about my home lab setup:

Kubernetes: v1.24.12 (as of writing)
Longhorn version: [v1.4.1](https://github.com/mkroman/k8s/blob/main/longhorn/Chart.yaml#L22) (as of writing)
cloudnative-pg version: [v1.19.1](https://github.com/mkroman/k8s-cluster-infra-apps/tree/main/cloudnative-pg) (as of writing)

**Comment by sxd** [comment]
Hi @mkroman 

What you're describing it's a scenario on which not only the PostgreSQL database may be affected, but all the volumes that are provided in this way, this it's external to the operator since the operator it's storage-agnostic, meaning that we don't set any test proof that may prevent things to happen, this it's something that need to be handled at kubernetes cluster level.

I'm closing this for now since there's nothing we can do and it's not an operator issue.

Regards,
