### ISSUE TITLE
API reference documentation is missing details

### ISSUE THREAD

**Issue by fcanovai** [cloudnative-pg/cloudnative-pg#2085]
The parts of the API that are defined inline are not picked up by our documentation generator.

The [BarmanObjectStoreConfiguration](https://cloudnative-pg.io/documentation/1.20/api_reference/#BarmanObjectStoreConfiguration) section is missing details about `BarmanCredentials`. The correct way is explained in the [Backup and Recovery](https://cloudnative-pg.io/documentation/1.20/backup_recovery/) section of the documentation.

 Similarly, the same happens for `CertificatesConfiguration` inside `CertificatesStatus`.

**Comment by gabriele-wolfox** [comment]
Open the PR https://github.com/EnterpriseDB/k8s-api-docgen/pull/13
I tested it locally and it works.
