### ISSUE TITLE
Add ability to modify operator manifests with kubectl cnpg plugin

### ISSUE THREAD

**Issue by sxd** [cloudnative-pg/cloudnative-pg#2168]
The kubectl cnpg has the `install` command that it's used to generate a manifest that can be applied to deploy the 
operator, nonetheless, we have all the values by default like:

* Namespace
* Environment Variables
* Operator configuration parameters
* nodeSelector for deployment
* etc...

The idea behind this tickets it's to give the `install` the ability to deliver a proper manifest with these fields modified.
As a plus, will be great to give the ability to the plugin to work with an already existing file.

**Comment by phisco** [comment]
We are already exposing all these things in the helm chart, maybe could be worth switching to use that in order to avoid duplicating the whole logic?

**Comment by phisco** [comment]
I mean using that inside the kubectl plug-in just as a rendering engine (helm template ...) so people could provide the values as configuration parameter and get the templates plain yaml as output

**Comment by sxd** [comment]
@phisco it's not a bad idea at all, can we talk about it ?

**Comment by phisco** [comment]
My feeling is that we should avoid overengineering the cnpg kubectl plugin, it should be a handy mean to download and install the latest manifests, but then I'd redirect people to modify those manifests or use the available helm chart if they need more changes.

**Comment by sxd** [comment]
not required anymore
