### ISSUE TITLE
Instructions for latest snapshot installation are wrong

### ISSUE THREAD

**Issue by gbartolini** [cloudnative-pg/cloudnative-pg#2169]
Instructions about installing the latest snapshot are wrong, as they actually point to the latest stable release, and not the main branch.

See: https://cloudnative-pg.io/documentation/current/installation_upgrade/#testing-the-latest-development-snapshot

**Comment by jsilvela** [comment]
An issue with rollout forced us to revert the fix. Reopening, will add a fix soon.
