### ISSUE TITLE
Support topologySpreadConstraints

### ISSUE THREAD

**Issue by ColonelBundy** [cloudnative-pg/cloudnative-pg#2192]
Currently we only have affinity rules to play with to control scheduling. In order to guarantee that a replica and primary don't get scheduled in the same zone we need to be able to specify topologySpreadConstraints.

You currently can limit the zone using affinity rules, but it's not enough, with topologySpreadConstraints you can control this a lot better.

Reference: https://kubernetes.io/docs/concepts/scheduling-eviction/topology-spread-constraints/

**Comment by itay-grudev** [comment]
You can already set a `topologyKey` that will ensure that doesn't happen. See https://cloudnative-pg.io/documentation/current/api_reference/#AffinityConfiguration

**Comment by ColonelBundy** [comment]
> You can already set a `topologyKey` that will ensure that two pods are not scheduled in the same zone. See https://cloudnative-pg.io/documentation/current/api_reference/#AffinityConfiguration
> 
> This is what I use:
> 
> ```yaml
>   affinity:
>     topologyKey: topology.kubernetes.io/zone
> ```

Yes this will in theory work but in a smaller cluster lets say 4 nodes? there's a good chance two replicas will be scheduled on the same node since the hostname is no longer the topologyKey for the pod affinity.

**Comment by itay-grudev** [comment]
How can two replicas be scheduled on the same node, when they wouldn't be allowed in the same zone?

**Comment by ColonelBundy** [comment]
> @ColonelBundy How can two replicas be scheduled on the same node, when they wouldn't be allowed in the same zone?

Right, I misspoke. What I meant was if I have two zones I would be limited to two replicas. With topologySpreadConstraints I can fulfill that requirement and once it's fulfilled I can scheduler more replicas in the same zone. This cannot be done with pod affinity I'm afraid. 
On top of that I can combine constraints such as that I shouldn't be allowed to put more replicas on the same node until all other nodes have replicas of which cannot be done with affinity either.

**Comment by ColonelBundy** [comment]
@armru @sxd  Thanks for the quick implementation! Greatly appreciated!

**Comment by sxd** [comment]
@ColonelBundy all the credit to @armru :)
