### ISSUE TITLE
E2E to verify that recovery works with custom `serverName` on the source yaml

### ISSUE THREAD

**Issue by jsilvela** [cloudnative-pg/cloudnative-pg#220]
Issue https://github.com/cloudnative-pg/cloudnative-pg/issues/209 fixes a bug that could prevent recovery when a source cluster used a custom `serverName` in the backup spec.
We should add an E2E test to cover this case.

**Comment by hh24k** [comment]
Removed the defer func since "dumping failure report" has been done in the JustAfterEach setup node.

**Comment by jsilvela** [comment]
@hh24k the `defer` was not redundant. There is a new cluster created with this E2E on top of the "normal" cluster used in the remainder of the test. Without this defer, a failure of the test will not trigger saving the cluster environment.
OTOH perhaps I should not have used a shadowed name for the cluster
