### ISSUE TITLE
Improve condition message inside cluster status to have relevant info.

### ISSUE THREAD

**Issue by danishedb** [cloudnative-pg/cloudnative-pg#223]
* Right now the condition message for the types backup and archiving is picking very generic error and failure message. We should pick the right error message from log and put it in cluster status message.

Like this 
This is actual failure reason.
ERROR: WAL archive check failed for server pg-backup-minio: Expected empty archive","pipe":"stderr","logging_pod":"pg-backup-minio-1"}

This is whatc ondition  message is reflecting.
conditions:
  - message: 'unexpected failure invoking barman-cloud-wal-archive: exit status
Which is very generic.

**Comment by jlong49** [comment]
I think that what we have is sufficient. Conditions typically just tell you the state of something and a generic error. The explicit error that you linked is in the logs of the pod. For instance, if you have a pod that cannot start the condition is simply Ready: false. I do not think that we should change the current behavior. @leonardoce, what do you think?

**Comment by leonardoce** [comment]
Yes, I have the same opinion on this
