### ISSUE TITLE
Krew plugin version on the krew index is outdated

### ISSUE THREAD

**Issue by xoxys** [cloudnative-pg/cloudnative-pg#2248]
On the [krew plugin index](https://github.com/kubernetes-sigs/krew-index/blob/master/plugins/cnpg.yaml#L6), the latest version is still v1.19.0. Any chance to get it updated to latest v1.20?

**Comment by sxd** [comment]
Hi @xoxys 

This will be fixed in the next release which is scheduled for the next week.

Regards!
