### ISSUE TITLE
E2E most tests don't dump the affected clusters on error

### ISSUE THREAD

**Issue by jsilvela** [cloudnative-pg/cloudnative-pg#227]
In the ginkgo tests in our E2E suite we are relying on a JustAfterEach node to dump the cluster environment.
Like so:

``` go
	JustAfterEach(func() {
		if CurrentSpecReport().Failed() {
			env.DumpClusterEnv(namespace, clusterName,
				"out/"+CurrentSpecReport().LeafNodeText+".log")
		}
	})
```

But in many cases, for example on replication tests, a particular spec may create new clusters. On error, the DumpClusterEnv will not be applied to those clusters, and we will lose valuable context.

We should ensure that the affected clusters in a failed spec have their environment dumped.
This ticket should be for the development of a strategy.
The application of said strategy throughout the code base could be done on extra tickets, since it will involve a scan of the whole suite.

**Comment by hh24k** [comment]
Hi @sxd, I've done the second review, but it would need an admin approval to get the PR merged. 

Can you use your power for me? :)
