### ISSUE TITLE
Postgres connection metrics

### ISSUE THREAD

**Issue by jgillich** [cloudnative-pg/cloudnative-pg#2292]
It's important to keep an eye on the maximum number of connections, but as far as I can tell, CNPG currently does not export connection metrics comparable to `pg_stat_activity_count`, `pg_settings_max_connections` and `pg_settings_superuser_reserved_connections` in [postgres_exporter](https://github.com/prometheus-community/postgres_exporter) 

The first two alerts [here](https://github.com/prometheus-community/postgres_exporter/blob/master/postgres_mixin/alerts/postgres.libsonnet) would be quite useful.

I'm open to writing a patch for this if I can get a go-ahead

**Comment by phisco** [comment]
Looks like these could be definitely added to the default metrics: https://github.com/cloudnative-pg/cloudnative-pg/blob/main/config/manager/default-monitoring.yaml

I'll let the pg experts check we are not already exposing these info in some other form 😉 CC @gbartolini @sxd

**Comment by phisco** [comment]
Edit: I think we already expose `pg_settings_*`. My only doubt is on the `pg_stat_activity_count`

**Comment by gbartolini** [comment]
I am looking at the `backends` metric which already provides the number of connections grouped by database, user name, application name and state. I wonder if these can be easily aggregated on the client side, and then compared with the max and reserved number of connections (I'm not an expert on the Prometheus side).

**Comment by gbartolini** [comment]
@jgillich any comments?

**Comment by gbartolini** [comment]
I am closing this due to lack of responses.
