### ISSUE TITLE
Deleting cnpg cluster does not delete serviceaccount in openshift 4.11.29 with cnpg operator 1.19.1

### ISSUE THREAD

**Issue by boers001** [cloudnative-pg/cloudnative-pg#2295]
When we create a simple cluster with the cnpg-operator (1.19.1) and afterwards when the database is created we delete the created cluster ojbect. We see that the created serviceaccount that has the same name as the cluster is not deleted. We tested this on kind and on plain kubernetes 1.24 and then the service is correctly deleted. 
So the question is why is the serviceAccount not deleted. Should this serviceAccount be deleted by the cnpg operator or should the service account be deleted by kubernetes as a cascaded delete as the ownerreference mentioned in the definition of the serviceaccount points to the cluster which has been deleted. In the latter case we should create an issue with Redhat.

**Comment by gbartolini** [comment]
Hi, FYI the CloudNativePG community does not currently support OpenShift. See: https://cloudnative-pg.io/documentation/current/supported_releases/#support-status-of-cloudnativepg-releases
