### ISSUE TITLE
Cannot create Cluster auxiliary objects: while patching service account: serviceaccounts on openshift 4.11.29

### ISSUE THREAD

**Issue by boers001** [cloudnative-pg/cloudnative-pg#2296]
We have an existing simple database cluster named example that has been created with the cnpg operator 1.19.1. Then we decide to upgrade the cnpg-operator to 1.20.0. When the new version of the cnpg-operator is running we see the following error in the cnpg-operator log:
`
{"level":"error","ts":"2023-05-08T14:46:55Z","msg":"Reconciler error","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"example","namespace":"sp-devdemo-tst"},"namespace":"sp-devdemo-tst","name":"example","reconcileID":"da57c868-aeac-4cf7-a6a0-426e0389f355","error":"cannot create Cluster auxiliary objects: while patching service account: serviceaccounts \"example\" is forbidden: cannot set an ownerRef on a resource you can't delete: , <nil>","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:329\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:274\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:235"}
`
What does the cngp-operator try to patch on the serviceaccount? and could this be related to #2295. We see the database instances getting restarted but they do not reach healthy state.

**Comment by gbartolini** [comment]
Hi, FYI the CloudNativePG community does not currently support OpenShift. See: https://cloudnative-pg.io/documentation/current/supported_releases/#support-status-of-cloudnativepg-releases
