### ISSUE TITLE
Docs: API reference embedded structs rendering issue

### ISSUE THREAD

**Issue by phisco** [cloudnative-pg/cloudnative-pg#2350]
The generated API reference documentation is not properly rendering embedded structs with `json:",inline"` annotations.
See [docs](https://cloudnative-pg.io/documentation/current/api_reference/#SecretKeySelector) (code [here](https://github.com/cloudnative-pg/cloudnative-pg/blob/74b460ec02e152253e51d2090bebfde405ede629/docs/src/api_reference.md?plain=1#L1022)), which is shown to only have a `key` field, while it should also have a `name` inherited from the embedded `LocalObjectReference`, see https://github.com/cloudnative-pg/cloudnative-pg/blob/74b460ec02e152253e51d2090bebfde405ede629/api/v1/base_types.go#L34

**Comment by gabriele-wolfox** [comment]
Together with @fcanovai , we are starting to check if replace the doc generation tool https://github.com/EnterpriseDB/k8s-api-docgen/ with https://github.com/ahmetb/gen-crd-api-reference-docs, that looks like a more standard way.

**Comment by fcanovai** [comment]
[gen-crd-api-reference-docs](https://github.com/ahmetb/gen-crd-api-reference-docs) would add a `(Members of LocalObjectReference are embedded into this type.)` text in the description of the key. The same applies to  `BarmanCredentials` and `CertificatesConfiguration`.
