### ISSUE TITLE
Error collecting user query

### ISSUE THREAD

**Issue by ColonelBundy** [cloudnative-pg/cloudnative-pg#2377]
We are experiencing lots of error messages in our replicas in a new 3 node cluster, we have enabled pod monitor and running a pooler of the same size as the cluster.

Errors:
![image](https://github.com/cloudnative-pg/cloudnative-pg/assets/1438014/d08c4323-aafd-41b6-9243-24cb5b02b0c9)

We have not added our own user queries.
**Version** 1.20.1

**Comment by phisco** [comment]
And can you share the custom queries being run? Because from the logs it looks like a query is running on standbys when it should be marked as `primary: true` instead

**Comment by phisco** [comment]
```

    pg_replication_slots:
      query: |
        SELECT slot_name,
          slot_type,
          database,
          active,
          pg_catalog.pg_wal_lsn_diff(pg_catalog.pg_current_wal_lsn(), restart_lsn)
        FROM pg_catalog.pg_replication_slots
        WHERE NOT temporary
      metrics:
        - slot_name:
            usage: "LABEL"
            description: "Name of the replication slot"
        - slot_type:
            usage: "LABEL"
            description: "Type of the replication slot"
        - database:
            usage: "LABEL"
            description: "Name of the database"
        - active:
            usage: "GAUGE"
            description: "Flag indicating whether the slot is active"
        - pg_wal_lsn_diff:
            usage: "GAUGE"
            description: "Replication lag in bytes"
```
Looks like it's complaining about this one 🤔

**Comment by ColonelBundy** [comment]
> Hi @ColonelBundy
> 
> Can you provide us with a text log? because I can't barely read the lines in the image with my screen =(
> 
> Regards!

Sure! [logs.txt](https://github.com/cloudnative-pg/cloudnative-pg/files/11906337/logs.txt)



> And can you share the custom queries being run? Because from the logs it looks like a query is running on standbys when it should be marked as `primary: true` instead

We don't have any custom queries, these are the built in ones.
