### ISSUE TITLE
Enhance externalClusters management of password to use `.pgpass` files

### ISSUE THREAD

**Issue by gbartolini** [cloudnative-pg/cloudnative-pg#2386]
At the moment, whenever we use the `password` field contained in the declared `externalCluster.password` secret to build the connection information to the PostgreSQL server we insert the password in the `DSN`.

The proposal here is to actually leverage the [PostgreSQL `.pgpass` file](https://www.postgresql.org/docs/current/libpq-pgpass.html) for this purpose by omitting the `password` field in the DSN, therefore triggering the password file capability.

The idea is to generate for each `externalCluster` that contains a `password` field an entry in the `~/.pgpass` file, with the following content:

```
hostname:port:*:username:password
```

Note that the `dbname` is fixed to `*` as we do not want to discriminate based on the target database, just the pair host:port.

As part of this feature, please make sure that the code is refactored to use this technique everytime we use the `password` field in a way that is potentially and unnecessarily exposed.

**Comment by dspeck1** [comment]
Was this part of 1.20.2 release?

**Comment by jarom-pdk** [comment]
> Was this part of 1.20.2 release?

Unfortunately no, it hasn't been included in any release as of yet. I am still eagerly awaiting the inclusion of this feature.

**Comment by gbartolini** [comment]
It works like a charm, amazing job! I was able to replicate the example in this [blog article](https://www.enterprisedb.com/blog/current-state-major-postgresql-upgrades-cloudnativepg-kubernetes), by changing the `SUBSCRIPTION` line as follows:

```
CREATE SUBSCRIPTION migrate CONNECTION 'host=pg1-rw user=angus dbname=app sslmode=require passfile=/controller/external/pg1/pgpass' PUBLICATION migrate
```

As you can see, the password is not in the configuration of the `Cluster`, and we only reference the `/controller/external/pg1/pgpass` password file.
