### ISSUE TITLE
By default, recovery_target_inclusive should be false per document

### ISSUE THREAD

**Issue by litaocdl** [cloudnative-pg/cloudnative-pg#2459]
if exclusive not specific or exclusive is true, ecovery_target_inclusive should be false.

**Comment by gbartolini** [comment]
The default behaviour in PostgreSQL is to have the inclusive target enabled by default. See https://www.postgresql.org/docs/current/runtime-config-wal.html#GUC-RECOVERY-TARGET-INCLUSIVE

I think we just need to fix the documentation as the code, IMHO, is coherent with Postgres' behaviour:

```
        switch {
        case target.Exclusive == nil:
                result += "recovery_target_inclusive = true\n"
        case *target.Exclusive:
                result += "recovery_target_inclusive = true\n"
        default:
                result += "recovery_target_inclusive = false\n"
        }
```

**Comment by jsilvela** [comment]
Agree with matching the default in Postgres.
As I read the code, I think the code is wrong though:

``` go
    case *target.Exclusive:
        result += "recovery_target_inclusive = true\n"
    default:
        result += "recovery_target_inclusive = false\n"
```

if `target.Exclusive` is FALSE, we append `recovery_target_inclusive = true`.
Does not look right...
