### ISSUE TITLE
Outdated primary becomes the cluster primary

### ISSUE THREAD

**Issue by deved99** [cloudnative-pg/cloudnative-pg#2513]
Hello!

Testing the high availability capabilities of the operator, I found out that after the recovery of a 
network disruption, an outdated instance becomes the primary, losing data and putting the cluster in an
inconsistent state.

## The test
On a 3 node cluster, I spun up a cluster with 3 instances, like the following
```yaml
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: example
spec:
  instances: 3
  primaryUpdateStrategy: unsupervised
  storage:
    size: 1Gi
```
This creates the following pods:
```
$ kubectl get pods -o wide -L role
NAME                                 READY   STATUS    RESTARTS      AGE   IP            NODE      NOMINATED NODE   READINESS GATES   ROLE
example-1                            1/1     Running   0             53s   10.42.2.103   node-03   <none>           <none>            primary
example-2                            1/1     Running   0             29s   10.42.0.204   node-01   <none>           <none>            replica
example-3                            1/1     Running   0             16s   10.42.1.192   node-02   <none>           <none>            replica
```
I then create a table, insert a row and verify:
```
$ kubectl exec -it example-1 -- psql --quiet app
Defaulted container "postgres" out of: postgres, bootstrap-controller (init)
app=# CREATE TABLE uuids ( id uuid NOT NULL );
app=# INSERT INTO uuids VALUES ('9a75ca44-2a9a-4aa8-9eb5-01126d7992a8');
app=# SELECT * FROM uuids;
                  id
--------------------------------------
 9a75ca44-2a9a-4aa8-9eb5-01126d7992a8
(1 row)
```
Then I verify the values on the other pods:
```
$ kubectl exec -it example-2 -- psql --quiet app -c 'select * from uuids;'
Defaulted container "postgres" out of: postgres, bootstrap-controller (init)
                  id
--------------------------------------
 9a75ca44-2a9a-4aa8-9eb5-01126d7992a8
(1 row)

$ kubectl exec -it example-3 -- psql --quiet app -c 'select * from uuids;'
Defaulted container "postgres" out of: postgres, bootstrap-controller (init)
                  id
--------------------------------------
 9a75ca44-2a9a-4aa8-9eb5-01126d7992a8
(1 row)
```
On the console of the node with the primary server, I disable the network card to simulate a network failure:
```
$ ip link set eno1 down
```
Then I wait until a new primary gets elected:
```
$ kubectl get pods -o wide -L role
NAME                                 READY   STATUS    RESTARTS       AGE    IP            NODE      NOMINATED NODE   READINESS GATES   ROLE
example-1                            1/1     Running   0              47m    10.42.2.103   node-03   <none>           <none>            replica
example-2                            1/1     Running   0              47m    10.42.0.204   node-01   <none>           <none>            primary
example-3                            1/1     Running   0              46m    10.42.1.192   node-02   <none>           <none>            replica
```
I insert a new row on the current primary:
```
$ kubectl exec -it example-2 -- psql --quiet app
Defaulted container "postgres" out of: postgres, bootstrap-controller (init)
app=# INSERT INTO uuids VALUES ('e2480173-741c-4667-8aa7-a64d38fc566a');
app=# select * from uuids;
                  id
--------------------------------------
 9a75ca44-2a9a-4aa8-9eb5-01126d7992a8
 e2480173-741c-4667-8aa7-a64d38fc566a
(2 rows)
```
I verify the row is replicated on the third pod:
```
$ kubectl exec -it example-3 -- psql --quiet app -c 'select * from uuids;'
Defaulted container "postgres" out of: postgres, bootstrap-controller (init)
                  id
--------------------------------------
 9a75ca44-2a9a-4aa8-9eb5-01126d7992a8
 e2480173-741c-4667-8aa7-a64d38fc566a
(2 rows)
```
I then enable the network card on the server which had the first primary:
```
ip link set eno1 up
```
The now outdated primary becomes primary:
```
$ kubectl get pods -o wide -L role
NAME        READY   STATUS    RESTARTS      AGE   IP            NODE      NOMINATED NODE   READINESS GATES   ROLE
example-1   1/1     Running   0             50m   10.42.2.103   node-03   <none>           <none>            primary
example-2   1/1     Running   2 (54s ago)   50m   10.42.0.204   node-01   <none>           <none>            replica
example-3   1/1     Running   0             50m   10.42.1.192   node-02   <none>           <none>            replica
```
Notice that the previous primary has crashed. If I check the `uuids` table now on the primary:
```
$ kubectl exec -it example-1 -- psql --quiet app -c 'select * from uuids;'
Defaulted container "postgres" out of: postgres, bootstrap-controller (init)
                  id
--------------------------------------
 9a75ca44-2a9a-4aa8-9eb5-01126d7992a8
(1 row)
```
On the second pod:
```
$ kubectl exec -it example-2 -- psql --quiet app -c 'select * from uuids;'
Defaulted container "postgres" out of: postgres, bootstrap-controller (init)
                  id
--------------------------------------
 9a75ca44-2a9a-4aa8-9eb5-01126d7992a8
(1 row)
```
If I check it on the third pod:
```
$ kubectl exec -it example-3 -- psql --quiet app -c 'select * from uuids;'
Defaulted container "postgres" out of: postgres, bootstrap-controller (init)
                  id
--------------------------------------
 9a75ca44-2a9a-4aa8-9eb5-01126d7992a8
 e2480173-741c-4667-8aa7-a64d38fc566a
(2 rows)
```

## Expected behavior
I expected the now outdated primary to become a replica, recovering from the now primary, without further
service disruptions.

## Found behavior
The outdated primary becomes the cluster primary, the old primary crashes and the cluster gets into a 
inconsistent state since the third pod has more rows than the other two.

# Software used
Software | Version
---------|---------
CNPG     | 1.20.2
K8s      | 1.27.3

**Comment by armru** [comment]
Hello, @deved99, thanks for the report.
We will look into this as soon as possible.

**Comment by armru** [comment]
Hello @deved99,  is it possible to have the:
- full logs of the operators and the instances
- the cluster resource including the status

Thanks,

**Comment by deved99** [comment]
Hello @armru, sorry for the late reply.

I've had to reproduce again the behavior above. I've run the following commands:
```
$ kubectl logs -n cnpg-system cnpg-controller-manager-b78df5556-txfwz > controller.log
$ kubectl get cluster example -o yaml > cluter-get.yaml.txt
$ kubectl describe cluster example > cluster-describe.txt
```
and attached the resulting files. Tell me if you need more/different logs.

Also, the operator deployed the controller pod on the node I was about to kill. Before reproducing the issue (but after creating the cluster) I killed it a bunch of times to move it to a node I wasn't about to break. 

On a side note, I noticed that by default the number of replicas of the operator is just one:
```
$ sudo kubectl get deploy -n cnpg-system
NAME                      READY   UP-TO-DATE   AVAILABLE   AGE
cnpg-controller-manager   1/1     1            1           43m
```
If the server where the pod of this deployment dies, there's no way a failover can happen. Can I safely raise the number of replicas to 3?

[cluster-describe.txt](https://github.com/cloudnative-pg/cloudnative-pg/files/12525122/cluster-describe.txt)
[cluster-get.yaml.txt](https://github.com/cloudnative-pg/cloudnative-pg/files/12525123/cluster-get.yaml.txt)
[controller.log](https://github.com/cloudnative-pg/cloudnative-pg/files/12525124/controller.log)

**Comment by deved99** [comment]
@armru are there any updates on this? I've seen that in the last update of the CNPG operator there has been some changes regarding WAL during the switchover. Would those changes patch/solve the issue I've found?

**Comment by armru** [comment]
Hello @deved99 we have made a lot of changes to improve stability, could you please retry and let us know if the issue still persist?

**Comment by h0jeZvgoxFepBQ2C** [comment]
Would be great to get an update here, if this issue is fixed.
