### ISSUE TITLE
Import Db job with the  Istio service mesh

### ISSUE THREAD

**Issue by j-zimnowoda** [cloudnative-pg/cloudnative-pg#2525]
In our environment all Pods are getting `istio-proxy` sidecar by default.

When the import-db job starts, the `import` container cannot immediately connects with the `kube-api`, because the `istio-proxy` has not configured the network routing yet. The `init` container immediately exits with error (see below).

Would it be possible that whenever `10.0.0.1:443: connect: connection refused` occurs the `import` container retries the request? 
OR
Would it be possible to define annotations just for the `import-db` job?

In the log below the `10.0.0.1:443`  belongs to the kube-api
```
"level":"error","ts":"2023-07-31T10:59:10Z","msg":"error while waiting for the API server to be reachable","logging_pod":"harbor-otomi-db-1-import","error":"Get \"[https://10.0.0.1:443/apis/postgresql.cnpg.io/v1/namespaces/harbor/clusters/harbor-otomi-db](https://10.0.0.1/apis/postgresql.cnpg.io/v1/namespaces/harbor/clusters/harbor-otomi-db)\": dial tcp 10.0.0.1:443: connect: connection refused","stacktrace":"github.com/cloudnative-pg/cloudnative-pg/pkg/management/log.(*logger).Error\n\tpkg/management/log/log.go:128\ngithub.com/cloudnative-pg/cloudnative-pg/pkg/management.WaitKubernetesAPIServer\n\tpkg/management/client.go:147\ngithub.com/cloudnative-pg/cloudnative-pg/internal/cmd/manager/instance/initdb.NewCmd.func1\n\tinternal/cmd/manager/instance/initdb/cmd.go:54\ngithub.com/spf13/cobra.(*Command).execute\n\tpkg/mod/github.com/spf13/cobra@v1.7.0/command.go:925\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\tpkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068\ngithub.com/spf13/cobra.(*Command).Execute\n\tpkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992\nmain.main\n\tcmd/manager/main.go:64\nruntime.main\n\t/opt/hostedtoolcache/go/1.20.3/x64/src/runtime/proc.go:250"}
Error: error while waiting for the API server to be reachable: Get "[https://10.0.0.1:443/apis/postgresql.cnpg.io/v1/namespaces/harbor/clusters/harbor-otomi-db](https://10.0.0.1/apis/postgresql.cnpg.io/v1/namespaces/harbor/clusters/harbor-otomi-db)": dial tcp 10.0.0.1:443: connect: connection refused
```

**Comment by sxd** [comment]
@j-zimnowoda hi

Which version of the operator are you testing? this should be fixed in the latest version already

Regards!

**Comment by IsaackRasmussen** [comment]
I'm also seeing this with operator 1.20.2 and Istio

**Comment by j-zimnowoda** [comment]
> @j-zimnowoda hi
> 
> 
> 
> Which version of the operator are you testing? this should be fixed in the latest version already
> 
> 
> 
> Regards!

1.20

**Comment by sxd** [comment]
This could be related to some other issues that we're getting we will keep everyone posted but we're right now working on issues similar to this one

**Comment by j-zimnowoda** [comment]
We also observe the same issue while extending the database cluster.
The job is failing and it seems like there is a race condition between istio-proxy sidecar and cnpg container.

**Comment by j-zimnowoda** [comment]
Heey, we have solved that issue by setting the `holdApplicationUntilProxyStarts` for istio meshConfig. In a nutshell it delays application startup until the pod proxy is ready to accept traffic.

**Comment by simardeep1792** [comment]
Yes, we did use a similar approach and re-solved this issue.

**Comment by sxd** [comment]
this issue looks fixed and is already outdated, if you find something similar please open another issue

**Comment by bhanotjyoti** [comment]
@kndoni  @simardeep1792 : Did you guys solve, facing similar issue
