### ISSUE TITLE
Skip configuration of the app database and user in replica mode

### ISSUE THREAD

**Issue by mnencia** [cloudnative-pg/cloudnative-pg#253]
When the replica mode is active, the database is read-only, 
so the operator cannot perform any change, so the code introduced in
#76 may fail.

Also, while in most cases when replica mode is enabled we don't want
to have app database and user in the cluster spec, in some cases,
this could be desired (see when you import a database from outside
Kubernetes in CloudNativePG). 

A way to solve the issue could be

* skip the changes when in replica mode
* document that application database configuration is disabled in replica mode
* add an E2E test for this case
* (optional) manage the reconciliation of the app database and user when the instance is promoted

**Comment by gbartolini** [comment]
I have read the documentation and I think that the way it is written now - or even the patch - is misleading.

The concept is that a replica cluster is in read-only mode, so any change - if any - must be performed once the cluster is promoted.

The general idea here is to enable users to define different values of owner, database, and secret of the app from **THE DEFAULT**, making sure that they are **IDENTICAL** to the source (either a backup or a live system).

What's your opinion on this?

**Comment by mnencia** [comment]
Yes, you are right. The instance manager must not try to reconcile the app and owner settings in a replica cluster. However, it must take these settings into account when it needs to know what the app database is, so the user should specify it in case it is different from the default on the source cluster.

**Comment by litaocdl** [comment]
so we should not stop user to configure it in webhook, just skip the configuration and once the replica mode is disabled, take those into consideration if they are different than default.

**Comment by gbartolini** [comment]
Yes, indeed. As Marco pointed out, the reconciliation could even be considered optional (but in that case we must document it properly).

**Comment by litaocdl** [comment]
do it now.
