### ISSUE TITLE
Does cloudnative-pg/EDB support openstack SWIFT S3 storage ?

### ISSUE THREAD

**Issue by oberai07** [cloudnative-pg/cloudnative-pg#2531]
If it supports then anyone has integrated and tested it successfully along with the replica cluster on another K8s cluster?

**Comment by sxd** [comment]
hi @oberai07 

Swift s3 storage is AWS compatible so it should be supported, but it's not tested

Regards!

**Comment by oberai07** [comment]
> hi @oberai07
> 
> Swift s3 storage is AWS compatible so it should be supported, but it's not tested
> 
> Regards!

@sxd  thanks for the reply. Actually, we are testing it and we are having some issues. I have already discussed the problems as part of the below support ticket. It would be more helpful if you can provide suuport.
https://github.com/cloudnative-pg/cloudnative-pg/issues/2524

**Comment by wvengen** [comment]
Just in case this is useful to someone: we've been using OpenStack SWIFT S3 with cloudnative-pg, for more than a year, across various releases, without any problem.
