### ISSUE TITLE
cert-manager cannot be used for replication certs

### ISSUE THREAD

**Issue by jclangst** [cloudnative-pg/cloudnative-pg#2542]
The [documentation](https://cloudnative-pg.io/documentation/1.20/certificates/) states the you can use cert-manager to provision `clientCASecret` and `replicationTLSSecret`. Example manifests are provided in the docs.

The manifests do not work as the cert-manager generated secret does not contain a `ca.key` entry as it is of type `kubernetes.io/tls`. As a result, cert-manager cannot be used to manage this secret, and I believe the docs are incorrect or a bug exists here.

Version: `1.20.2`

<details>
  <summary>Logs</summary>
  
```json
  
  {
     "level":"error",
     "ts":"2023-08-08T01:56:08Z",
     "msg":"Reconciler error",
     "controller":"cluster",
     "controllerGroup":"postgresql.cnpg.io",
     "controllerKind":"Cluster",
     "Cluster":{
        "name":"api-server-pg",
        "namespace":"api-server"
     },
     "namespace":"api-server",
     "name":"api-server-pg",
     "reconcileID":"5d3d9c1b-d5da-40e7-b2a1-3d352ae0dd19",
     "error":"cannot create Cluster auxiliary objects: generating streaming replication client certificate: missing ca.key secret data",
     "stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:324\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:265\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:226"
  }
```
</details>

**Comment by phisco** [comment]
Hi, can you share your manifests?

**Comment by jclangst** [comment]
Hi I am just utilizing the [manifests](https://cloudnative-pg.io/documentation/1.20/samples/cluster-example-cert-manager.yaml) as linked from the docs with some name changes.

**Comment by jclangst** [comment]
As a reference, here is a summary of the secret that the operator is failing on reading. As you can see, cert-manager does not generate secrets with the key `ca.key` which is what the operator is expecting.

![image](https://github.com/cloudnative-pg/cloudnative-pg/assets/13301098/ab3b4954-eec4-4793-9039-7c0279e9d50f)

**Comment by wasd171** [comment]
I have a similar issue with the same error message (using cert-manager for certificates) and I am generally confused why this is happening. If we provide `serverTLSSecret` + `replicationTLSSecret` + `serverCASecret` + `clientCASecret` then I would expect that CNPG would not need `ca.key` at all since it does not need to generate certificates. We have encountered it yesterday when our secrets marked with `cnpg.io/reload: "true"` were updated by cert-manager, but CNPG failed to reload them. I had to delete certificates and recreate them for the changes to apply

**Comment by wasd171** [comment]
Actually the certs themselves do work, replicas can successfully connect to master, clients can also connect using client certificates. The biggest problem is that the secrets marked with `cnpg.io/reload: "true"` label are not watched for updates

**Comment by phisco** [comment]
yep, definitely a bug, let me have a look at it.
