### ISSUE TITLE
[Feature request] Increase or make the expiringCheckThreshold for certificate expiration check configurable 

### ISSUE THREAD

**Issue by rdegez** [cloudnative-pg/cloudnative-pg#2560]
Hi,

Currently the cnpg generated x509 certificates will renew only 7 days before expiration (constant defined in [source].
https://github.com/cloudnative-pg/cloudnative-pg/blob/70912a9a20959d5ed53d2e3a44ed77ceb92f54b3/pkg/certs/certs.go#L49

Let's encrypt recommand to regen 90 days validity certificates after [60 days](https://letsencrypt.org/docs/faq/#what-is-the-lifetime-for-let-s-encrypt-certificates-for-how-long-are-they-valid). 
A 7 days seems a bit short and doesn't give a lot of time to fix an expiring certificate if something fishy and unnoticed is happening on a cluster.

It would be great to either increase this expiringCheckThreshold to 30 days or to make this constant a tunable since this low value would trigger a ceritificate expiration warning with some generic k8s cluster certificate expiration check mecanism (like https://github.com/enix/x509-certificate-exporter for instance) before this 7 day period.

Cheers!

**Comment by sxd** [comment]
This was already handled on #3686 closing
