### ISSUE TITLE
Misleading documentation regarding PGBouncer debug

### ISSUE THREAD

**Issue by jurim76** [cloudnative-pg/cloudnative-pg#2578]
According to documentation, you could use `curl` inside the pod, to verify metrics status.
https://cloudnative-pg.io/documentation/1.20/connection_pooling/  "Monitoring" section

`You can debug the exporter on a pod running PgBouncer through the following command:`
`kubectl exec -ti <PGBOUNCER_POD> -- curl 127.0.0.1:9127/metrics`

But curl utility is not included in pooler image and this command will produce an error

`Defaulted container "pgbouncer" out of: pgbouncer, bootstrap-controller (init)
error: Internal error occurred: error executing command in container: failed to exec in container: failed to start exec "cb6504590d3487120dffe1b98209651c0ab6bccfd2db02ba396eb453ed4a19d9": OCI runtime exec failed: exec failed: container_linux.go:380: starting container process caused: exec: "curl": executable file not found in $PATH: unknown`

**Comment by gbartolini** [comment]
That's because we started to use the minimal image and we missed this spot. I think we should do something similar to what we've done here: https://cloudnative-pg.io/documentation/current/monitoring/#how-to-inspect-the-exported-metrics
