### ISSUE TITLE
Restore from a particular backup

### ISSUE THREAD

**Issue by vanyasvl** [cloudnative-pg/cloudnative-pg#2603]
Hello.
I have ScheduledBackups configured and several on demand backups.
How I can specify a particular backup when restoring (bootstraping) a cluster? (other namespace or k8s cluster, so I don't have Backup objects)

**Comment by gbartolini** [comment]
You just need to point to the recovery object store, as explained here: https://cloudnative-pg.io/documentation/current/bootstrap/#recovery-from-an-object-store

Then, you can use any of the recovery targets that the API provides. If you want to start from a given backup, you just need to provide the `backupID` (see https://cloudnative-pg.io/documentation/current/api_reference/#recoverytarget).

Feel free to reopen this ticket if the answer doesn't satisfy you.

**Comment by gbartolini** [comment]
Let me reopen this as I just noticed a possible issue in the code, as we are not allowing a recovery target with a `backupID` unless we use a `Backup` resource. While in most cases users want to achieve either full recovery (no target) or time stamped point in time recovery - neither of which requires a `backupID` - there exist cases in which you want to specify a label (restore point) or a XID as a target. In such cases you need to specify a backup from which to start.

I see that the patch related to #2387 might address this with VolumeSnapshots.

**Comment by gbartolini** [comment]
I am closing this as `backupID` is now managed by Volume Snapshots too.
