### ISSUE TITLE
When creating secrets for a cluster's users, add a label indicating what kind of user it's for

### ISSUE THREAD

**Issue by nogweii** [cloudnative-pg/cloudnative-pg#2631]
I am hoping to be able to rely on label searches alone to identify the superuser vs owner secret for a given cluster. So I'm imagining a label similar to `cnpg.io/user-role` where the value would be one of `superuser` or `owner`.

That way, I could find the secret using the pair of `cnpg.io/cluster` and this new label without relying on the assumption that the secret's name will always be the cluster name appended with "-app".

What do you think?

**Comment by pchovelon** [comment]
Working on it.
A Pull Request will be there soon.
