### ISSUE TITLE
Boostrap cluster from wal-g backup

### ISSUE THREAD

**Issue by rochecompaan** [cloudnative-pg/cloudnative-pg#2638]
We currently use [wal-g](https://github.com/wal-g/wal-g) to make backups to an AWS S3 bucket for a Postgres cluster running outside Kubernetes. Due to security restrictions, we cannot access the cluster directly, and we need to bootstrap the CNPG cluster from the wal-g backup. The documentation suggests I can restore from an object store or a Backup object. Whatever is in the object store assumes it was created by Barman, which it wasn't in this case. The Backup object seems to be something CNPG created in the first place.

I'm trying to figure out the most optimal route to bootstrap the new CNPG cluster. Does the following make sense:
1. Create a temporary Postgres cluster and restore from wal-g.
2. Backup temporary Postgres cluster to S3 with Barman
3. Bootstrap the CNPG cluster from the S3 backup made by Barman

Does the above sound reasonable? Is there a better way to do this? If one can reconstruct a Backup object, it would save setting up the temporary cluster, for instance.

**Comment by MichaluxPL** [comment]
You can also bootstrap directly from the temporary PGSQL cluster (restored from wal-g) - of course if there is a network connection between this cluster and CNPG cluster.
