### ISSUE TITLE
Remove the deprecated parameter of `az monitor diagnostic-settings` 

### ISSUE THREAD

**Issue by YanniHu1996** [cloudnative-pg/cloudnative-pg#2641]
Seems Microsoft is over-eager with some API deprecations. https://github.com/Azure/ResourceModules/issues/3572 
We should remove `retentionPolicy` and configure it following https://learn.microsoft.com/en-us/azure/azure-monitor/essentials/migrate-to-azure-storage-lifecycle-policy

**Comment by AlexanderSehr** [comment]
@YanniHu1996 over eager is relative - the community behind the [Azure/ResourceModules](aka.ms/carml) repository are not members of the product groups. So yeah - caught me by surprise too, though it seemed to have been anounced in the `azure-monitor`  docs for some time.
