### ISSUE TITLE
Superuser password rotation does not respond to in-place Kubernetes Secret updates

### ISSUE THREAD

**Issue by fullykubed** [cloudnative-pg/cloudnative-pg#2658]
Operation Version: `1.20.2`

We have a cluster configured with the external superuser secret config

```yaml
superuserSecret:
  name: primary-api-pg-superuser
```

Here is an example of a random version of our secret (still b64 encoded):

```yaml
apiVersion: v1
data:
  password: TU5nYnU2UEljOFJHVGxZMnIwajI5Wk5HNFppRXdlVEwyUTZvbUNxaTVnN3NhdTI2SDFqZHVrRVE1djdtWnczWg==
  pgpass: cHJpbWFyeS1hcGktcGctcnc6NTQzMjoqOnBvc3RncmVzOk1OZ2J1NlBJYzhSR1RsWTJyMGoyOVpORzRaaUV3ZVRMMlE2b21DcWk1ZzdzYXUyNkgxamR1a0VRNXY3bVp3M1o=
  username: cG9zdGdyZXM=
kind: Secret
metadata:
  creationTimestamp: "2023-08-31T16:26:11Z"
  name: primary-api-pg-superuser
  namespace: primary-api
  resourceVersion: "22198398"
  uid: 49c909d7-3de3-4520-a281-3454158bbaaf
type: kubernetes.io/basic-auth
```

The secret works for cluster initialization, but subsequent in-place updates of the `password` or `pgpass` field are not applied without taking further action on our end (note: we only waited about 5 minutes or so).

We have found that doing any of the following triggers the password rotation:

- restarting the operators
- restarting the cluster nodes
- creating a new `Secret` object and changing the `Cluster` resource to point to the new object

However, I believe that the operator should be watching this secret and applying in-place updates. Not sure if this is a bug or new feature request.

**Comment by Th3Lourde** [comment]
Hi @fullykubed!

I found this issue a couple days ago when I was looking for a similar solution. I think I have a solution for you! My use-case is a little different so you should check it yourself.

Also I'm putting this here b/c this issue was at the top of my search engine instead of the place in the docs.


According to the docs:

```
If you want ConfigMaps and Secrets to be automatically reloaded by instances,
you can add a label with key cnpg.io/reload to it,
```

There an [example](https://cloudnative-pg.io/documentation/1.16/certificates/#:~:text=If%20you%20want%20ConfigMaps%20and,the%20kubectl%20cnpg%20reload%20subcommand) in the docs and below is my test .yaml:

```yaml
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: secret-rotation-cluster
spec:
  instances: 3
  bootstrap:
    initdb:
      database: app
      owner: app
      secret:
        name: secret1
  storage:
    size: 1Gi
  walStorage:
    size: 1Gi

---

apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
  name: secret1
  labels:
    cnpg.io/reload: ""
stringData:
  username: "app"
  password: "world"
```

By adding the
```yaml
  labels:
    cnpg.io/reload: ""
```
I was able to change the password, then update the secret in my k8s cluster, and then the new password was magically set.

This didn't restart any pods which I thought was very cool.

Hope this helps you/whomever from the future is reading this!

**Comment by fullykubed** [comment]
I do have this label set and it was not working previously, but I can revisit to see if this is resolved in a later version.

**Comment by fullykubed** [comment]
This appears to be working now!

**Comment by vldo766hi** [comment]
hello guys, but I am still facing the super password not updated on initial. here my manifest. anyone can help?

`cluster.yaml`:
```yaml
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: my-db-cluster
  namespace: database
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:17.7

  enableSuperuserAccess: true
  superuserSecret:
    name: database-admin-password

  bootstrap:
    initdb:
      database: my-db
      owner: postgres

  storage:
    size: 20Gi
    storageClass: storage-mgmt

  replicationSlots:
    highAvailability:
      enabled: true

  resources:
    requests:
      memory: "1Gi"
      cpu: "500m"
    limits:
      memory: "2Gi"
      cpu: "2"

  affinity:
    enablePodAntiAffinity: true
    topologyKey: kubernetes.io/hostname
    podAntiAffinityType: required
```

`kubectl get secret -n database database-admin-password`
```yaml
apiVersion: v1
data:
  password: ******
kind: Secret
metadata:
  annotations:
    reconcile.external-secrets.io/data-hash: 659a95001767945a8163f279120be289b6a05567081bb828bc438291
  creationTimestamp: "2025-12-15T09:48:49Z"
  labels:
    cnpg.io/reload: ""
    reconcile.external-secrets.io/created-by: c1beceb38e3451c02184ec0dfc8f2043e6eb9e2110ddcdca0cb8c7bf
    reconcile.external-secrets.io/managed: "true"
  name: database-admin-password
  namespace: database
  ownerReferences:
  - apiVersion: external-secrets.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: ExternalSecret
    name: database-admin-password
    uid: c88d6df2-77fe-481e-8606-4a38918363f7
  resourceVersion: "7776530"
  uid: 59af887a-6c17-4785-bb1c-030f003f866b
type: opaque
```
