### ISSUE TITLE
Add a flag preventing deletion in the cluster spec

### ISSUE THREAD

**Issue by achanda** [cloudnative-pg/cloudnative-pg#2659]
It will be useful to have a flag in the cluster spec that will prevent deletion of the cluster using kubectl unless that flag is switched off. Databases are generally more stable than other workloads like load balancers etc. so an operator should have an option to block deleting a database cluster by mistake.

**Comment by phisco** [comment]
Hi, that would be nice indeed. As a workaround this could be easily done with something like opa or Kyverno blocking deletions for a specific resource or resources matching some labels/annotations.

**Comment by sxd** [comment]
Hi @achanda 

You mean an option in the spec that will reject something like `kubectl delete cluster cluster-example` ? or something to avoid a `DROP DATABASE app` ?

What do you think @phisco  ?

Regards,

**Comment by achanda** [comment]
hi @sxd I was thinking the first one: an option in the spec that will prevent `kubectl delete cluster cluster-example`
