### ISSUE TITLE
If ENV TIMEZONE is not UTC, restore-pitr does not work.

### ISSUE THREAD

**Issue by markpapa7** [cloudnative-pg/cloudnative-pg#2701]
env:
- name: TZ
   value: Asia/Seoul

Set up as above to deploy/backup the cluster and run restore-pitr as shown below.
recoveryTarget:
    targetTime: "2023-09-08 08:31:14"
restore failed.
However, if the env timezone is not set and deployed with the default UTC, restore operates normally with the same settings.

cngp version : 1.20.1
cluster version: ghcr.io/cloudnative-pg/postgresql:15
cloud env : aks 1.26.6(k8s)

thanks~

**Comment by MichaluxPL** [comment]
AFAIK backups are stored only in UTC (regardles what timezone You set for the cluster), so You have to define targetTime with timezone shift like this:
recoveryTarget:
        targetTime: "${TimeStamp}.0000${TIMEZONESHIFT}"

where TIMEZONESHIFT=$( date +%z | cut -c1-3 )

Of course this is just some kind of a workaround. Ideally barman-cloud shoud take cluster timezone setting into account somehow.

**Comment by markpapa7** [comment]
Hi. MichaluxPL

Unfortunately, I already tried the method you suggested several times, but it did not work properly. Fortunately, it was just before operational service, so I decided to change the cluster’s time zone to UTC and redistribute it.
Thank you for your help.

**Comment by MichaluxPL** [comment]
That's strange - I'm using this approach all the time and it works as expected.

**Comment by sxd** [comment]
Hi @markpapa7 

If this still happening to you, please provide a full example and configurations on how to reproduce this

Thanks!
