### ISSUE TITLE
Allow users to disable `ALTER SYSTEM`

### ISSUE THREAD

**Issue by gbartolini** [cloudnative-pg/cloudnative-pg#2725]
**Background information:** I have submitted a patch for PostgreSQL to disable `ALTER SYSTEM` at startup time. For more information and also the reason behind it, please refer to the thread in the pgsql-hackers mailing list below:

https://www.postgresql.org/message-id/CA%2BVUV5rEKt2%2BCdC_KUaPoihMu%2Bi5ChT4WVNTr4CD5-xXZUfuQw%40mail.gmail.com

If ever, this patch will not land in PostgreSQL before version 17. There are chances though that it will never land.

In the meantime, it would be good to introduce a workaround for all currently available Postgres versions, including the upcoming 16. Add a new option in the cluster's spec called `enableAlterSystem` with a current default value of `true` for back-compatibility (in 1.22 we should make the default change to `false`).

The idea is that the `postgresql.auto.conf` file is made read-only. Add proper documentation too.

**Comment by leonardoce** [comment]
I'd disable `ALTER SYSTEM` in CNPG. I can't imagine a case where this should be used when the cluster is working.

I understand this would be useful to fix a broken cluster, but in this case, the user could:

1. Fence the instances
2. Update the `postgres.conf` file as needed

By doing this the user will have total control over the GUCs, and over where/which configuration file we include.
