### ISSUE TITLE
after some time pg_crash is leaving the cluster out of sync

### ISSUE THREAD

**Issue by smiyc** [cloudnative-pg/cloudnative-pg#2766]
I built an image with pg_crash to test the replication slots.

This is the part I added to the Dockerfile:
####################################################################################
# install pg_crash
RUN	apt-get update && \
	apt-get install -y postgresql-server-dev-15 build-essential git && \
	cd /tmp && \
	git clone https://github.com/cybertec-postgresql/pg_crash && \
	cd /tmp/pg_crash && \
	PG_CONFIG=/usr/lib/postgresql/15/bin/pg_config make && \
	PG_CONFIG=/usr/lib/postgresql/15/bin/pg_config make install && \
	rm -rf /tmp/pg_crash && \
	apt-get remove -y postgresql-server-dev-15 build-essential git

And after some time running pg_crash this ist the status

Primary:
postgres@keycloak-test-1:/$ pg_controldata 
pg_control version number:            1300
Catalog version number:               202209061
Database system identifier:           7277494897175216152
Database cluster state:               in production
pg_control last modified:             Wed 13 Sep 2023 02:14:00 PM UTC
Latest checkpoint location:           0/200015D0
Latest checkpoint's REDO location:    0/20001598
Latest checkpoint's REDO WAL file:    0000002E0000000000000020
Latest checkpoint's TimeLineID:       46
Latest checkpoint's PrevTimeLineID:   46
Latest checkpoint's full_page_writes: on
Latest checkpoint's NextXID:          0:859
Latest checkpoint's NextOID:          16488
Latest checkpoint's NextMultiXactId:  1
Latest checkpoint's NextMultiOffset:  0
Latest checkpoint's oldestXID:        716
Latest checkpoint's oldestXID's DB:   1
Latest checkpoint's oldestActiveXID:  859
Latest checkpoint's oldestMultiXid:   1
Latest checkpoint's oldestMulti's DB: 1
Latest checkpoint's oldestCommitTsXid:0
Latest checkpoint's newestCommitTsXid:0
Time of latest checkpoint:            Wed 13 Sep 2023 02:14:00 PM UTC
Fake LSN counter for unlogged rels:   0/3E8
Minimum recovery ending location:     0/0
Min recovery ending loc's timeline:   0
Backup start location:                0/0
Backup end location:                  0/0
End-of-backup record required:        no
wal_level setting:                    logical
wal_log_hints setting:                on
max_connections setting:              200
max_worker_processes setting:         32
max_wal_senders setting:              10
max_prepared_xacts setting:           0
max_locks_per_xact setting:           64
track_commit_timestamp setting:       off
Maximum data alignment:               8
Database block size:                  8192
Blocks per segment of large relation: 131072
WAL block size:                       8192
Bytes per WAL segment:                16777216
Maximum length of identifiers:        64
Maximum columns in an index:          32
Maximum size of a TOAST chunk:        1996
Size of a large-object chunk:         2048
Date/time type storage:               64-bit integers
Float8 argument passing:              by value
Data page checksum version:           1
Mock authentication nonce:            77fd6f44309c4cf2219111e3622748e2a70219c312d19efea256351f93cf677e

Standby 1:
postgres@keycloak-test-3:/$ pg_controldata 
pg_control version number:            1300
Catalog version number:               202209061
Database system identifier:           7277494897175216152
Database cluster state:               in archive recovery
pg_control last modified:             Wed 13 Sep 2023 02:14:16 PM UTC
Latest checkpoint location:           0/1F000060
Latest checkpoint's REDO location:    0/1E001550
Latest checkpoint's REDO WAL file:    0000002D000000000000001E
Latest checkpoint's TimeLineID:       45
Latest checkpoint's PrevTimeLineID:   45
Latest checkpoint's full_page_writes: on
Latest checkpoint's NextXID:          0:859
Latest checkpoint's NextOID:          16488
Latest checkpoint's NextMultiXactId:  1
Latest checkpoint's NextMultiOffset:  0
Latest checkpoint's oldestXID:        716
Latest checkpoint's oldestXID's DB:   1
Latest checkpoint's oldestActiveXID:  859
Latest checkpoint's oldestMultiXid:   1
Latest checkpoint's oldestMulti's DB: 1
Latest checkpoint's oldestCommitTsXid:0
Latest checkpoint's newestCommitTsXid:0
Time of latest checkpoint:            Wed 13 Sep 2023 12:56:37 PM UTC
Fake LSN counter for unlogged rels:   0/3E8
Minimum recovery ending location:     0/20002A30
Min recovery ending loc's timeline:   46
Backup start location:                0/0
Backup end location:                  0/0
End-of-backup record required:        no
wal_level setting:                    logical
wal_log_hints setting:                on
max_connections setting:              200
max_worker_processes setting:         32
max_wal_senders setting:              10
max_prepared_xacts setting:           0
max_locks_per_xact setting:           64
track_commit_timestamp setting:       off
Maximum data alignment:               8
Database block size:                  8192
Blocks per segment of large relation: 131072
WAL block size:                       8192
Bytes per WAL segment:                16777216
Maximum length of identifiers:        64
Maximum columns in an index:          32
Maximum size of a TOAST chunk:        1996
Size of a large-object chunk:         2048
Date/time type storage:               64-bit integers
Float8 argument passing:              by value
Data page checksum version:           1
Mock authentication nonce:            77fd6f44309c4cf2219111e3622748e2a70219c312d19efea256351f93cf677e

standby 2:
postgres@keycloak-test-4:/$ pg_controldata 
pg_control version number:            1300
Catalog version number:               202209061
Database system identifier:           7277494897175216152
Database cluster state:               in archive recovery
pg_control last modified:             Wed 13 Sep 2023 02:18:13 PM UTC
Latest checkpoint location:           0/200014F0
Latest checkpoint's REDO location:    0/200014B8
Latest checkpoint's REDO WAL file:    0000002D0000000000000020
Latest checkpoint's TimeLineID:       45
Latest checkpoint's PrevTimeLineID:   45
Latest checkpoint's full_page_writes: on
Latest checkpoint's NextXID:          0:859
Latest checkpoint's NextOID:          16488
Latest checkpoint's NextMultiXactId:  1
Latest checkpoint's NextMultiOffset:  0
Latest checkpoint's oldestXID:        716
Latest checkpoint's oldestXID's DB:   1
Latest checkpoint's oldestActiveXID:  859
Latest checkpoint's oldestMultiXid:   1
Latest checkpoint's oldestMulti's DB: 1
Latest checkpoint's oldestCommitTsXid:0
Latest checkpoint's newestCommitTsXid:0
Time of latest checkpoint:            Wed 13 Sep 2023 02:13:56 PM UTC
Fake LSN counter for unlogged rels:   0/3E8
Minimum recovery ending location:     0/20001568
Min recovery ending loc's timeline:   45
Backup start location:                0/0
Backup end location:                  0/0
End-of-backup record required:        no
wal_level setting:                    logical
wal_log_hints setting:                on
max_connections setting:              200
max_worker_processes setting:         32
max_wal_senders setting:              10
max_prepared_xacts setting:           0
max_locks_per_xact setting:           64
track_commit_timestamp setting:       off
Maximum data alignment:               8
Database block size:                  8192
Blocks per segment of large relation: 131072
WAL block size:                       8192
Bytes per WAL segment:                16777216
Maximum length of identifiers:        64
Maximum columns in an index:          32
Maximum size of a TOAST chunk:        1996
Size of a large-object chunk:         2048
Date/time type storage:               64-bit integers
Float8 argument passing:              by value
Data page checksum version:           1
Mock authentication nonce:            77fd6f44309c4cf2219111e3622748e2a70219c312d19efea256351f93cf677e

**Comment by smiyc** [comment]
[report_cluster_keycloak-test_2023-09-13T142302Z.zip](https://github.com/cloudnative-pg/cloudnative-pg/files/12598837/report_cluster_keycloak-test_2023-09-13T14.23.02Z.zip)

**Comment by smiyc** [comment]
[report_cluster_keycloak-test_2023-09-13T144236Z.zip](https://github.com/cloudnative-pg/cloudnative-pg/files/12598862/report_cluster_keycloak-test_2023-09-13T14.42.36Z.zip)

**Comment by smiyc** [comment]
this where the parameter used in the test
```
  postgresql:
    shared_preload_libraries:
     - "pg_crash"
    parameters:
      crash.signals: "1 2 3"
      crash.delay: "30"
```

**Comment by smiyc** [comment]
I managed to reproduce the error on a kind cluster running on my laptop

Operator Version: 1.20.2
PostgreSQL Version: 15.4

parameters used
```
  postgresql:
    shared_preload_libraries:
     - "pg_crash"
    parameters:
      crash.signals: "1 2 3"
      crash.delay: "60"
```

```
╭─daniel@ThinkPad-L13 ~ 
╰─$ kubectl-cnpg status keycloak-test            
Cluster Summary
Name:               keycloak-test
Namespace:          cnpg-system
System ID:          7278937663502848033
PostgreSQL Image:   repo/cnpg:15.4_pg_crash
Primary instance:   keycloak-test-4
Status:             Failing over Failing over from keycloak-test-3 to keycloak-test-4
Instances:          3
Ready instances:    2
Current Write LSN:  0/2D009A08 (Timeline: 85 - WAL File: 00000055000000000000002D)

Certificates Status
Certificate Name           Expiration Date                Days Left Until Expiration
----------------           ---------------                --------------------------
keycloak-test-ca           2023-12-14 06:30:33 +0000 UTC  88.67
keycloak-test-replication  2023-12-14 06:30:33 +0000 UTC  88.67
keycloak-test-server       2023-12-14 06:30:33 +0000 UTC  88.67

Continuous Backup status
Not configured

Streaming Replication status
Replication Slots Enabled
Name             Sent LSN    Write LSN   Flush LSN   Replay LSN  Write Lag  Flush Lag  Replay Lag  State      Sync State  Sync Priority  Replication Slot
----             --------    ---------   ---------   ----------  ---------  ---------  ----------  -----      ----------  -------------  ----------------
keycloak-test-3  0/2D009A08  0/2D009A08  0/2D009A08  0/2D009A08  00:00:00   00:00:00   00:00:00    streaming  quorum      1              active

Unmanaged Replication Slot Status
No unmanaged replication slots found

Instances status
Name             Database Size  Current LSN  Replication role  Status             QoS         Manager Version  Node
----             -------------  -----------  ----------------  ------             ---         ---------------  ----
keycloak-test-4  29 MB          0/2D009A08   Primary           OK                 Guaranteed  1.20.2           kind-worker3
keycloak-test-3  29 MB          0/2D009A08   Standby (sync)    OK                 Guaranteed  1.20.2           kind-worker
keycloak-test-1  -    
```

primary instance
```
╭─daniel@ThinkPad-L13 ~/git/kind/keycloak-test 
╰─$ k exec -it keycloak-test-4 -- pg_controldata
Defaulted container "postgres" out of: postgres, bootstrap-controller (init)
pg_control version number:            1300
Catalog version number:               202209061
Database system identifier:           7278937663502848033
Database cluster state:               in production
pg_control last modified:             Sat 16 Sep 2023 02:13:06 PM UTC
Latest checkpoint location:           0/2D000060
Latest checkpoint's REDO location:    0/2C0090B8
Latest checkpoint's REDO WAL file:    00000053000000000000002C
Latest checkpoint's TimeLineID:       83
Latest checkpoint's PrevTimeLineID:   83
Latest checkpoint's full_page_writes: on
Latest checkpoint's NextXID:          0:997
Latest checkpoint's NextOID:          16488
Latest checkpoint's NextMultiXactId:  1
Latest checkpoint's NextMultiOffset:  0
Latest checkpoint's oldestXID:        716
Latest checkpoint's oldestXID's DB:   1
Latest checkpoint's oldestActiveXID:  997
Latest checkpoint's oldestMultiXid:   1
Latest checkpoint's oldestMulti's DB: 1
Latest checkpoint's oldestCommitTsXid:0
Latest checkpoint's newestCommitTsXid:0
Time of latest checkpoint:            Sat 16 Sep 2023 02:13:06 PM UTC
Fake LSN counter for unlogged rels:   0/3E8
Minimum recovery ending location:     0/0
Min recovery ending loc's timeline:   0
Backup start location:                0/0
Backup end location:                  0/0
End-of-backup record required:        no
wal_level setting:                    logical
wal_log_hints setting:                on
max_connections setting:              200
max_worker_processes setting:         32
max_wal_senders setting:              10
max_prepared_xacts setting:           0
max_locks_per_xact setting:           64
track_commit_timestamp setting:       off
Maximum data alignment:               8
Database block size:                  8192
Blocks per segment of large relation: 131072
WAL block size:                       8192
Bytes per WAL segment:                16777216
Maximum length of identifiers:        64
Maximum columns in an index:          32
Maximum size of a TOAST chunk:        1996
Size of a large-object chunk:         2048
Date/time type storage:               64-bit integers
Float8 argument passing:              by value
Data page checksum version:           1
Mock authentication nonce:            798336ef922f30d8c4504fd9ebe678f14ab1cdc4015f4ddcdecf221d6ff9946a
```

standby instance (OK)
```
╭─daniel@ThinkPad-L13 ~/git/kind/keycloak-test 
╰─$ k exec -it keycloak-test-3 -- pg_controldata                                                                                          1 ↵
Defaulted container "postgres" out of: postgres, bootstrap-controller (init)
pg_control version number:            1300
Catalog version number:               202209061
Database system identifier:           7278937663502848033
Database cluster state:               in archive recovery
pg_control last modified:             Sat 16 Sep 2023 02:13:33 PM UTC
Latest checkpoint location:           0/2D000060
Latest checkpoint's REDO location:    0/2C0090B8
Latest checkpoint's REDO WAL file:    00000053000000000000002C
Latest checkpoint's TimeLineID:       83
Latest checkpoint's PrevTimeLineID:   83
Latest checkpoint's full_page_writes: on
Latest checkpoint's NextXID:          0:997
Latest checkpoint's NextOID:          16488
Latest checkpoint's NextMultiXactId:  1
Latest checkpoint's NextMultiOffset:  0
Latest checkpoint's oldestXID:        716
Latest checkpoint's oldestXID's DB:   1
Latest checkpoint's oldestActiveXID:  997
Latest checkpoint's oldestMultiXid:   1
Latest checkpoint's oldestMulti's DB: 1
Latest checkpoint's oldestCommitTsXid:0
Latest checkpoint's newestCommitTsXid:0
Time of latest checkpoint:            Sat 16 Sep 2023 02:13:06 PM UTC
Fake LSN counter for unlogged rels:   0/3E8
Minimum recovery ending location:     0/2D0000D8
Min recovery ending loc's timeline:   83
Backup start location:                0/0
Backup end location:                  0/0
End-of-backup record required:        no
wal_level setting:                    logical
wal_log_hints setting:                on
max_connections setting:              200
max_worker_processes setting:         32
max_wal_senders setting:              10
max_prepared_xacts setting:           0
max_locks_per_xact setting:           64
track_commit_timestamp setting:       off
Maximum data alignment:               8
Database block size:                  8192
Blocks per segment of large relation: 131072
WAL block size:                       8192
Bytes per WAL segment:                16777216
Maximum length of identifiers:        64
Maximum columns in an index:          32
Maximum size of a TOAST chunk:        1996
Size of a large-object chunk:         2048
Date/time type storage:               64-bit integers
Float8 argument passing:              by value
Data page checksum version:           1
Mock authentication nonce:            798336ef922f30d8c4504fd9ebe678f14ab1cdc4015f4ddcdecf221d6ff9946a
```

standby instance (NOK)
```
╭─daniel@ThinkPad-L13 ~/git/kind/keycloak-test 
╰─$ k exec -it keycloak-test-1 -- pg_controldata
Defaulted container "postgres" out of: postgres, bootstrap-controller (init)
pg_control version number:            1300
Catalog version number:               202209061
Database system identifier:           7278937663502848033
Database cluster state:               shut down
pg_control last modified:             Sat 16 Sep 2023 02:17:51 PM UTC
Latest checkpoint location:           1/A2000028
Latest checkpoint's REDO location:    1/A2000028
Latest checkpoint's REDO WAL file:    0000004700000001000000A2
Latest checkpoint's TimeLineID:       71
Latest checkpoint's PrevTimeLineID:   71
Latest checkpoint's full_page_writes: on
Latest checkpoint's NextXID:          0:961
Latest checkpoint's NextOID:          16488
Latest checkpoint's NextMultiXactId:  1
Latest checkpoint's NextMultiOffset:  0
Latest checkpoint's oldestXID:        716
Latest checkpoint's oldestXID's DB:   1
Latest checkpoint's oldestActiveXID:  0
Latest checkpoint's oldestMultiXid:   1
Latest checkpoint's oldestMulti's DB: 1
Latest checkpoint's oldestCommitTsXid:0
Latest checkpoint's newestCommitTsXid:0
Time of latest checkpoint:            Sat 16 Sep 2023 02:17:51 PM UTC
Fake LSN counter for unlogged rels:   0/3E8
Minimum recovery ending location:     0/0
Min recovery ending loc's timeline:   0
Backup start location:                0/0
Backup end location:                  0/0
End-of-backup record required:        no
wal_level setting:                    logical
wal_log_hints setting:                on
max_connections setting:              200
max_worker_processes setting:         32
max_wal_senders setting:              10
max_prepared_xacts setting:           0
max_locks_per_xact setting:           64
track_commit_timestamp setting:       off
Maximum data alignment:               8
Database block size:                  8192
Blocks per segment of large relation: 131072
WAL block size:                       8192
Bytes per WAL segment:                16777216
Maximum length of identifiers:        64
Maximum columns in an index:          32
Maximum size of a TOAST chunk:        1996
Size of a large-object chunk:         2048
Date/time type storage:               64-bit integers
Float8 argument passing:              by value
Data page checksum version:           1
Mock authentication nonce:            798336ef922f30d8c4504fd9ebe678f14ab1cdc4015f4ddcdecf221d6ff9946a
```

events
```
╭─daniel@ThinkPad-L13 ~/git/kind/keycloak-test 
╰─$ kubectl get events --sort-by='.lastTimestamp'
LAST SEEN   TYPE      REASON                   OBJECT                       MESSAGE
13m         Normal    Scheduled                pod/keycloak-test-1          Successfully assigned cnpg-system/keycloak-test-1 to kind-worker3
53m         Warning   Unhealthy                pod/keycloak-test-3          Readiness probe failed: HTTP probe failed with statuscode: 500
49m         Warning   Unhealthy                pod/keycloak-test-4          Readiness probe failed: HTTP probe failed with statuscode: 500
32m         Normal    Started                  pod/keycloak-test-4          Started container postgres
29m         Normal    Started                  pod/keycloak-test-3          Started container postgres
29m         Warning   Unhealthy                pod/keycloak-test-3          Liveness probe failed: Get "http://10.244.3.6:8000/healthz": dial tcp 10.244.3.6:8000: connect: connection refused
26m         Warning   BackOff                  pod/keycloak-test-3          Back-off restarting failed container
26m         Normal    FailoverTarget           cluster/keycloak-test        Failing over from keycloak-test-3 to keycloak-test-4
25m         Warning   Unhealthy                pod/keycloak-test-1          Readiness probe failed: HTTP probe failed with statuscode: 500
21m         Warning   Unhealthy                pod/keycloak-test-3          Readiness probe failed: Get "http://10.244.3.6:8000/readyz": dial tcp 10.244.3.6:8000: connect: connection refused
15m         Warning   BackOff                  pod/keycloak-test-1          Back-off restarting failed container
13m         Warning   FailedToUpdateEndpoint   endpoints/keycloak-test-r    Failed to update endpoint cnpg-system/keycloak-test-r: Operation cannot be fulfilled on endpoints "keycloak-test-r": the object has been modified; please apply your changes to the latest version and try again
13m         Warning   FailedToUpdateEndpoint   endpoints/keycloak-test-ro   Failed to update endpoint cnpg-system/keycloak-test-ro: Operation cannot be fulfilled on endpoints "keycloak-test-ro": the object has been modified; please apply your changes to the latest version and try again
13m         Normal    Started                  pod/keycloak-test-1          Started container bootstrap-controller
13m         Normal    Created                  pod/keycloak-test-1          Created container bootstrap-controller
13m         Normal    Pulled                   pod/keycloak-test-1          Container image "ghcr.io/cloudnative-pg/cloudnative-pg:1.20.2" already present on machine
13m         Normal    Started                  pod/keycloak-test-1          Started container postgres
13m         Normal    Created                  pod/keycloak-test-1          Created container postgres
12m         Normal    Pulled                   pod/keycloak-test-4          Container image "repo/cnpg:15.4_pg_crash" already present on machine
12m         Normal    Created                  pod/keycloak-test-4          Created container postgres
12m         Warning   Unhealthy                pod/keycloak-test-1          Liveness probe failed: HTTP probe failed with statuscode: 500
12m         Normal    Killing                  pod/keycloak-test-1          Container postgres failed liveness probe, will be restarted
12m         Normal    Pulled                   pod/keycloak-test-1          Container image "repo/cnpg:15.4_pg_crash" already present on machine
10m         Normal    FailoverTarget           cluster/keycloak-test        Failing over from keycloak-test-4 to keycloak-test-3
9m26s       Normal    Created                  pod/keycloak-test-3          Created container postgres
9m26s       Normal    Pulled                   pod/keycloak-test-3          Container image "repo/cnpg:15.4_pg_crash" already present on machine
8m21s       Normal    FailingOver              cluster/keycloak-test        Current primary isn't healthy, initiating a failover from keycloak-test-3
8m20s       Warning   Unhealthy                pod/keycloak-test-1          Readiness probe failed: HTTP probe failed with statuscode: 500
3m30s       Warning   BackOff                  pod/keycloak-test-1          Back-off restarting failed container
2m20s       Warning   BackOff                  pod/keycloak-test-4          Back-off restarting failed container
2m18s       Normal    FailingOver              cluster/keycloak-test        Current primary isn't healthy, initiating a failover from keycloak-test-4
2m10s       Normal    nodeAssigned             service/keycloak-test-lb     announcing from node "kind-worker3" with protocol "layer2"
```
[report_cluster_keycloak-test_2023-09-16T14:31:05Z.zip](https://github.com/cloudnative-pg/cloudnative-pg/files/12640905/report_cluster_keycloak-test_2023-09-16T14.31.05Z.zip)

[report_operator_2023-09-16T14:31:27Z.zip](https://github.com/cloudnative-pg/cloudnative-pg/files/12640904/report_operator_2023-09-16T14.31.27Z.zip)
[dockerfile.txt](https://github.com/cloudnative-pg/cloudnative-pg/files/12640925/dockerfile.txt)

**Comment by smiyc** [comment]
the same behavior with 1.21.0

**Comment by jsilvela** [comment]
Going to try to repro. I had to modify the Dockerfile a bit for my machine. This worked:

```
FROM ghcr.io/cloudnative-pg/postgresql:15.4-3

 # To install any package we need to be root
 USER root

# We update the package list, install our package
# and clean up any cache from the package manager
RUN set -xe; \
	apt-get update; \
	apt-get install -y postgresql-server-dev-15 build-essential git; \
	cd /tmp; \
	git clone https://github.com/cybertec-postgresql/pg_crash; \
	cd /tmp/pg_crash; \
	PG_CONFIG=/usr/lib/postgresql/15/bin/pg_config make; \
	PG_CONFIG=/usr/lib/postgresql/15/bin/pg_config make install; \
	rm -rf /tmp/pg_crash; \
	apt-get remove -y postgresql-server-dev-15 build-essential git


 # Change to the uid of postgres (26)
 USER 26
 ```

**Comment by jsilvela** [comment]
oh, I had not seen you had a file `dockerfile.txt` attached. 🤦

**Comment by sxd** [comment]
Hi @smiyc 

I've been running pg_crash with the latest version in main and I wasn't able to reproduce this issue, at least not after a day and so with your parameters.

Are you able to reproduce this with the latest version in main? or the latest release version of 1.21.x ? can you test? will be great to have your feedback here

Regards!

**Comment by smiyc** [comment]
my cluster stopped working

![grafik](https://github.com/cloudnative-pg/cloudnative-pg/assets/36233521/f36bb504-0782-4af4-8dc6-08d3331c3e57)


[report_operator_2023-11-24T180828Z.zip](https://github.com/cloudnative-pg/cloudnative-pg/files/13461598/report_operator_2023-11-24T18.08.28Z.zip)
[report_cluster_keycloak_2023-11-24T180812Z.zip](https://github.com/cloudnative-pg/cloudnative-pg/files/13461599/report_cluster_keycloak_2023-11-24T18.08.12Z.zip)

**Comment by sxd** [comment]
Hi @smiyc 

This test was on version 1.21.1 right, not main? if that the case I'm going to start testing with that specific tag

Regards!

**Comment by smiyc** [comment]
@sxd  correct

**Comment by sxd** [comment]
@smiyc I was able to partially reproduce this by running a cluster for 20m but I'm setting up a new environment to make it run for a day or two will update soon! BTW yes, version 1.21.1 has the issue but main doesn't, we will find out soon!

**Comment by sxd** [comment]
@smiyc good news! I may have found the bug, will work in a PR now =) cc @leonardoce @jsilvela

**Comment by smiyc** [comment]
@sxd very nice, looking forward to test it

**Comment by gbartolini** [comment]
I have created this repository: https://github.com/cloudnative-pg/pgcrash-containers

The idea is to use the postgres-containers images as a base, and then install the related pg_crash extension.

Provie the possibility to schedule regular tests or execute on demand one for a specific image.

**Comment by smiyc** [comment]
I think this issue can be closed

in the mean time a set up an e2e testing environment with an local minio as a backup location on my laptop.
There Itested with 1.22.2 and an 15.6 PG Cluster with pg_crash andthe the following settings

```
  instances: 3
  minSyncReplicas: 1
  maxSyncReplicas: 1    
  startDelay: 300
  stopDelay: 300

  postgresql:
    shared_preload_libraries:
     - "pg_crash"      
    parameters:
      crash.signals: "1 2 3"
      crash.delay: "20"    
```

I let it crash for a while now.
Even the worst case, where all 3 cluster instances where in CrashLoopBackOff status was resolved by the operator.
