### ISSUE TITLE
Convert E2E tests for PITR on volume snapshots to declarative mode

### ISSUE THREAD

**Issue by gbartolini** [cloudnative-pg/cloudnative-pg#2806]
Currently, E2E tests for PITR on volume snapshots use the plugin. Before we release 1.21 we are planning to deprecate the `cnpg snapshot` command in favor of the `cnpg backup -v volumeSnapshot` command, which builds the `Backup` resource.

As a results, such E2E tests need to be converted to use declarative mode.

**Comment by NiccoloFei** [comment]
Closing. It will be merged as part of https://github.com/cloudnative-pg/cloudnative-pg/issues/2797
