### ISSUE TITLE
cnpg plugin  reports wrong certificates

### ISSUE THREAD

**Issue by plesoun-stein** [cloudnative-pg/cloudnative-pg#2834]
### cluster
* cluster is ok, new certs a deployed with SIGHUP immediately. 
* New certs are ok.  On filesystem `/controller/certificates/server.crt` verified with `openssl x509`
* runnig test `openssl s_client -starttls postgres -connect 127.0.0.1:5432` in pod shows new certificate is OK

### what happened?
* command ` kubectl cnpg status cluster-advanced-initdb  -n test-pg`  </br> reports expired certificate 
```
Cluster Summary
Name:               cluster-advanced-initdb
Namespace:          test-pg
System ID:          7280481494915178515
PostgreSQL Image:   ghcr.io/cloudnative-pg/postgresql:15.3
Primary instance:   cluster-advanced-initdb-1
Status:             Cluster in healthy state 
Instances:          3
Ready instances:    3
Current Write LSN:  1B/64000060 (Timeline: 1 - WAL File: 000000010000001B00000064)

Certificates Status
Certificate Name  Expiration Date                Days Left Until Expiration
----------------  ---------------                --------------------------
pg-client-cert    2023-09-26 11:26:18 +0000 UTC  5.10 - Expires Soon
pg-server-cert    2023-09-19 12:21:18 +0000 UTC  Expired

```

### environment:
**kubernetes:** `v1.27.4`

**cert-manager:** 
```
Client Version: util.Version{GitVersion:"v1.13.0", GitCommit:"d34bd7aa15055b428bf865851bc420412f3710e6", GitTreeState:"", GoVersion:"go1.20.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: &versionchecker.Version{Detected:"v1.12.4", Sources:map[string]string{"crdLabelVersion":"v1.12.4"}}
```
**cloudnative-pg:** `Build: {Version:1.20.2 Commit:6f7f10b7 Date:2023-07-27} `

certificate created with 
```
  secretTemplate:
    labels:
      cnpg.io/reload: ""
```

**Comment by sxd** [comment]
Hi @plesoun-stein 

Can you confirm if this still happening in the version 1.22.2 ? 
For now I'm closing, if you find this issue again please reopen this same issue

Regards,
