### ISSUE TITLE
Grafana Dashboard: WAL PVC size missing

### ISSUE THREAD

**Issue by smiyc** [cloudnative-pg/cloudnative-pg#2836]
In the "Volume Space Usage" section, only the DATA PVC is displayed.

![PVC1](https://github.com/cloudnative-pg/cloudnative-pg/assets/36233521/9d19e670-12c4-405a-93c1-a95d9dc3b593)

It would be nice to see the WAL PVC too.
![PVC2](https://github.com/cloudnative-pg/cloudnative-pg/assets/36233521/7c0b3aa4-8a28-40b4-9509-d779e14b5de8)

**Comment by gbartolini** [comment]
Do you think you can come up with a patch? :)
