### ISSUE TITLE
Refactor: make idiomatic types for Sorting - Catalog, PostgresqlStatusList

### ISSUE THREAD

**Issue by jsilvela** [cloudnative-pg/cloudnative-pg#284]
In a couple of instances in our codebase, we need a custom Sort on a collection.
And we create a custom type as a struct containing a slice inside. Like so:

```
type PostgresqlStatusList struct {
	Items []PostgresqlStatus `json:"items"`
}
```

This is not necessary and somewhat clunky, as any named `type` in go can have methods.
To refactor:  `Catalog`, `PostgresqlStatusList`

**Comment by jlong49** [comment]
We have decided not to implement this change because having a struct containing a list `Items` is the way that this is accomplished in the core v1 API.
