### ISSUE TITLE
Standby pod hanging while taking an online backup

### ISSUE THREAD

**Issue by gbartolini** [cloudnative-pg/cloudnative-pg#2862]
While the cluster was taking an online backup on the object store, I tried to delete the pod with grace period 1. However, it was hanging. See the pod output and the error log containing issues like `Error while getting cluster CA Client secret`.

[error.log](https://github.com/cloudnative-pg/cloudnative-pg/files/12713695/error.log)
[pod.log](https://github.com/cloudnative-pg/cloudnative-pg/files/12713704/pod.log)

**Comment by jsilvela** [comment]
The postgres process never seems to successfully shut down.

We see messages at 09:31:19

``` json
{"level":"info","ts":"2023-09-25T09:31:19Z","logger":"postgres","msg":"record","logging_pod":"kubecon-na-23-eu-central-1-3","record":{"log_time":"2023-09-25 09:31:19.574 UTC","user_name":"postgres","database_name":"postgres","process_id":"19921","connection_from":"[local]","session_id":"65115367.4dd1","session_line_num":"1","session_start_time":"2023-09-25 09:31:19 UTC","transaction_id":"0","error_severity":"FATAL","sql_state_code":"57P03","message":"the database system is shutting down","backend_type":"client backend","query_id":"0"}}
```

and at 09:43:12, more than 12 minutes later. 

``` json
{"level":"info","ts":"2023-09-25T09:43:12Z","logger":"postgres","msg":"record","logging_pod":"kubecon-na-23-eu-central-1-3","record":{"log_time":"2023-09-25 09:43:12.305 UTC","user_name":"postgres","database_name":"postgres","process_id":"22135","connection_from":"[local]","session_id":"65115630.5677","session_line_num":"1","session_start_time":"2023-09-25 09:43:12 UTC","transaction_id":"0","error_severity":"FATAL","sql_state_code":"57P03","message":"the database system is shutting down","backend_type":"client backend","query_id":"0"}}
```

All of the messages have the same error code, 
>  "error_severity":"FATAL","sql_state_code":"57P03"

This is **cannot_connect_now** from https://www.postgresql.org/docs/current/errcodes-appendix.html

**Comment by jsilvela** [comment]
Tried this a bunch more times. With gigabyte-size databases. Can't get standby to hang.
What I see in the logs provided is Postgres was trying to shut down for more than 10 minutes.
Marco points that taking a long time to shut down can be due to having WALs to archive.

**Comment by jsilvela** [comment]
I'm noticing the error log provided starts with:

``` json
{"level":"info","ts":"2023-09-25T09:31:19Z","msg":"Received termination signal","logging_pod":"kubecon-na-23-eu-central-1-3","signal":"interrupt"}
```

in my machine I get

``` json
{"level":"info","ts":"2023-10-06T17:01:57Z","msg":"Received termination signal","logging_pod":"cluster-example-with-backup-2","signal":"interrupt","smartShutdownTimeout":1620}
```

which has the `smartShutdownTimeout` argument.
Realizing Gabriele's test was run before https://github.com/cloudnative-pg/cloudnative-pg/pull/2848
was merged.

Will retry before that was introduced.

**Comment by gbartolini** [comment]
Let's close this for now. I agree that we have made several improvements in the area, that are related to this symptom.
