### ISSUE TITLE
Volume snapshots should be labeled with a historically unique backup ID

### ISSUE THREAD

**Issue by jsilvela** [cloudnative-pg/cloudnative-pg#2876]
In the function to get the volume snapshots taken for a given backup, we are looking for those matching the backup name.

``` go
func GetBackupVolumeSnapshots(
<SNIPPED>

	if err := cli.List(
		ctx,
		&list,
		client.InNamespace(namespace),
		client.MatchingLabels{utils.BackupNameLabelName: backupLabelName},
```

The problem is that the backup name may not be historically unique, for example if the backup manifest was created manually instead of via the plugin.
In such case, we could delete the backup object, create one with the same name, and right away, we would have matching volume snapshots.

**Comment by gbartolini** [comment]
Given that we need to implement #2883 and #2881, do you still think we need this?

**Comment by jsilvela** [comment]
The issue is not just changing the BackupID, but changing how we look for associated volume snapshots, based in an ID field rather than the name, as is done now.
That said, that correction could be done in those other issues...

**Comment by gbartolini** [comment]
I think that with volume snapshots the name is more than enough.

**Comment by jsilvela** [comment]
The problem:

1. I create a backup object named "foo"
2. Snapshots are created, their name would be "foo" from #2883, if I understand correctly.
3. I delete the backup object.
4. Sometime later, I create a new backup object named "foo".

**Comment by gbartolini** [comment]
We are not sure volume snapshots are there, because that depends on `snapshotOwnerReference`. They could have gone. In my opinion we should encourage users to create backups using the scheduled approach or via the plugin. Then, as part of #2881, properly explain the above behaviour. I would not introduce further logic here.

**Comment by jsilvela** [comment]
I mean, fair point, but `we should encourage users to create backups using the scheduled approach or via the plugin`
so users that create a backup via manifest are unsupported?

**Comment by gbartolini** [comment]
I am not saying we don't support them, but I don't see a reason to use them beyond emergency cases in which you don't even have the plugin (as I would use the plugin to generate the backup).

**Comment by mnencia** [comment]
This patch has been superseded by implementing #2881, #2882, #2883, and #2794.
