### ISSUE TITLE
Grafana Dashboard: effective_cache_size is wrong displayed

### ISSUE THREAD

**Issue by smiyc** [cloudnative-pg/cloudnative-pg#2914]
an effective_cache_size=3GB is shown as 

![grafik](https://github.com/cloudnative-pg/cloudnative-pg/assets/36233521/bc9137f4-fa49-49fe-8c34-7b7cdabea76a)

because the metric value is not multiplied by block_size

`"expr": "cnpg_pg_settings_setting{name=\"effective_cache_size\",namespace=~\"$namespace\",pod=~\"$instances\"}",`

please assign the issue to me

**Comment by gbartolini** [comment]
can you submit a pull request please?

**Comment by smiyc** [comment]
I added it to the open one
https://github.com/cloudnative-pg/cloudnative-pg/pull/2839
