### ISSUE TITLE
Point of recoverability should also consider volume snapshots

### ISSUE THREAD

**Issue by gbartolini** [cloudnative-pg/cloudnative-pg#2924]
At the moment, point of recoverability (`firstRecoverabilityPoint`) in the Cluster's status only considers backups in the object store.

We should ensure that volume snapshots are now taken in the equation. It would be great to add this to 1.21.0 if we can.

**Comment by jsilvela** [comment]
As I'm coding this, I see an issue. If we have a cluster that has both object store backups and volume snapshots,
having only one FirstRecoverabilityPoint could be confusing, and also lossy.
Would it make sense to keep a FRP per backup mechanism?
