### ISSUE TITLE
Volume snapshot backup not working on a single instance cluster

### ISSUE THREAD

**Issue by gbartolini** [cloudnative-pg/cloudnative-pg#2948]
In case of a single instance cluster (e.g. development cluster), the volume snapshot backup procedure hangs indefinitely leaving the generated backup resource in `pending` state and the Postgres pod in an unrecoverable state, with this message:

```
{"level":"info","ts":"2023-09-30T10:20:25Z","msg":"Instance could be down, will not proceed with the reconciliation loop","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"small","namespace":"default"},"namespace":"default","name":"small","reconcileID":"f03537c8-bbe0-461e-93ef-0c8aa0db1eb8","uuid":"f83036d5-5f7a-11ee-87a3-6650243b3350","logging_pod":"small-1"}
```

The issue is easily reproducible by testing the feature on a cluster with a single instance.

**Comment by jsilvela** [comment]
Can reproduce, and fix in progress is not difficult.
HOWEVER.
I worry about the following edge case:
- we pick Pod 2 as the target backup, we patch the backup object with it.
- cluster fails over or switches over to Pod 2.
- backup reconciler fences Pod 2

**Comment by jsilvela** [comment]
Also, and more troubling: What if we choose `target: primary` ?

```
  backup:
    volumeSnapshot:
       className: csi-hostpath-snapclass
    target: primary
```

This is legal right now.
Are we going to use the same backup method for hot snapshots?
If we are going to use a different method, and the current `volumeSnapshot` means cold,
we should have the validation webhook reject the primary target.
WDYT @gbartolini ?

**Comment by jsilvela** [comment]
Candidate code dynamically checks the target pod is primary, either current or target.
Marks the backup as failed.

```
NAME                          AGE     CLUSTER                                PHASE    ERROR
backup-with-volume-snapshot   7m28s   cluster-example-with-volume-snapshot   failed   cannot take a volume snapshot of the primary
```

The cluster is unharmed, and we have some logs in the controller

``` json
{"level":"info","ts":"2023-10-03T11:56:11Z",
  "msg":"Snapshot Backup has the primary as a target and cannot proceed",
  "controller":"backup","controllerGroup":"postgresql.cnpg.io",
  <- snipped ->
  "targetPod":"cluster-example-with-volume-snapshot-1"}

{"level":"error","ts":"2023-10-03T11:56:11Z",
  "msg":"Reconciler error","controller":"backup","controllerGroup":"postgresql.cnpg.io",
  "controllerKind":"Backup","Backup":<- snipped ->
  "name":"backup-with-volume-snapshot",
"error":"cannot take a volume snapshot of the primary"
}
```

**Comment by gbartolini** [comment]
There are actually legit cases where there's one instance and needs to be backed up (think of a development environment or a reporting database).  Don't we actually stop any failover/switchover if an instance is fenced?

**Comment by jsilvela** [comment]
After discussion about the functionality, it's clear my initial approach is not valid.
Investigated the root cause of the failure to take the backup:

We can see periodic info logs:
"Not ready backup target, will retry in 30 seconds"

Which is accurate because the pod has been fenced, but this should not stop the volume snapshots.
It is  a valid stopper only for barman backups, which run from the pod.

**Comment by jsilvela** [comment]
Adding a warning log in the controller, as fencing the primary may come
as a surprise to some users:

``` json
{"level":"info","ts":"2023-10-06T09:12:59Z",
"msg":"Cold Snapshot Backup targets the primary. Primary will be fenced",
"controller":"backup",
<- snipped ->
"targetBackup":"backup-with-volume-snapshot-3",
"targetPod":"cluster-example-with-volume-snapshot-1"}
```
