### ISSUE TITLE
local setup not working on m1 mac

### ISSUE THREAD

**Issue by Lennart01** [cloudnative-pg/cloudnative-pg#2955]
The local setup appears to be broken on m1 series macs.
Had to make changes to the `setup-cluster.sh` script.
The following changes had to be made to get it running:
- remove `kubeProxyMode: "ipvs"` from the kind config
- disable the sysctl customization as this did not work
- added `export GORELEASER_CURRENT_TAG=v0.0.0` to the `load()` function bec otherwise goreleaser wouldn't work.

**Comment by armru** [comment]
Hello, @Lennart01 
Can we close this issue?

**Comment by Lennart01** [comment]
looks good to me.
