### ISSUE TITLE
monitoring grafana dashboard: inclusion of kubernetes cluster variable

### ISSUE THREAD

**Issue by dmpe** [cloudnative-pg/cloudnative-pg#3028]
Hi, 

would it be possible to include a new variable called e.g. `kubernetes-cluster` into grafana dashboard so that we can switch between multiple clusters?

In my case, I am using `Thanos` and store metrics on S3. I am not deploying grafana to each individual cluster because of additional overhead it would bring. Thus, if I import your dashboard and have 5 clusters, each having CNPG being deployed .... it creates some challenges of using CNPG metrics. 

The `cluster` variable itself is helpful, but my CNPG clusters are all called same, across all envs, e.g. `sonarqube-v15`. So I need to have some additional variable whereby I can differentiate based on the k8s cluster :)

Would be great addition if it is possible somehow to implement. :)

Many thanks.

**Comment by phisco** [comment]
Related to https://github.com/cloudnative-pg/cloudnative-pg/pull/2954

**Comment by sxd** [comment]
The dashboard is not handled on this repo anymore please refer to https://github.com/cloudnative-pg/grafana-dashboards
