### ISSUE TITLE
Internal error occurred: failed calling webhook "mcluster.kb.io"

### ISSUE THREAD

**Issue by MichaluxPL** [cloudnative-pg/cloudnative-pg#3088]
I get following error trying to create a new PGSQL cluster:
Error from server (InternalError): error when creating "test.yaml": Internal error occurred: failed calling webhook "mcluster.kb.io": failed to call webhook: Post "https://cnpg-webhook-service.cnpg-system.svc:443/mutate-postgresql-cnpg-io-v1-cluster?timeout=10s": x50
9: certificate signed by unknown authority

Yesterday I've upgraded CNPG to 1.21. Upgrade went smoothly but we stared to have problem connectiong all new clusters via network (we could still connect to ones created with previous CNPG version: 1.20.2). I tried different user account.
So I've decided to revert to CNPG 1.20.02.
After downgrade I've started to get errors like above and cannot provision any new cluster.
Going again back to 1.21 also didn't help.
I discussed the issue with @leonardoce  on slack and He noticed that there is no caBundle in operator's mutating webhook.
I've tried to remove both operator, all it's webhooks and even cnpg-operator namespace and recreate it but with no luck.

**Comment by MichaluxPL** [comment]
[crd.txt](https://github.com/cloudnative-pg/cloudnative-pg/files/12893616/crd.txt)

**Comment by MichaluxPL** [comment]
[mutatingwbh.txt](https://github.com/cloudnative-pg/cloudnative-pg/files/12893621/mutatingwbh.txt)

**Comment by MichaluxPL** [comment]
Just a follow-up. I've made some additional tests.
There is also lack of caBundle for validating webhook.
It appears, that after some time (about an hour) both webhook get thier caBudles. It happens just after there is an information in operator's log about TLS certificates update.
So I've made another test: I've upgraded again to CNPG 1.21 (from 1.20.2). The problem occured again, so I've deleted operator's pod (didn't touch both webhooks). After it was recreated, both webhook got their certifacates.
So it looks to me like there is a problem during the initial webhooks creation.

**Comment by cloudymax** [comment]
We are seeing this as well in our CI tests:

```bash
Error: INSTALLATION FAILED: Internal error occurred: failed calling webhook "mcluster.cnpg.io": failed to call webhook: Post "[https://cnpg-webhook-service.cnpg-system.svc:443/mutate-postgresql-cnpg-io-v1-cluster?timeout=10s](https://cnpg-webhook-service.cnpg-system.svc/mutate-postgresql-cnpg-io-v1-cluster?timeout=10s)": dial tcp 10.96.126.130:443: connect: connection refused
```

This doesn't seem happen when we install locally or on any of our VPS machines, just in the kind cluster created by github actions. 🤷

**Comment by cloudymax** [comment]
> @cloudymax Your error doesn't seem to mention anything about TLS handshake error, so I don't believe it's the same case. What You get is connection refused.

my mistake, thanks for the heads up 😅

**Comment by wolframm** [comment]
I'm experiencing the same issue. 

I have a simple `init.sh` script to set up my local dev environment:
```
#!/bin/bash
kind delete cluster --name pb
kind create cluster --name pb --config kind.yaml
kubectl apply -f https://raw.githubusercontent.com/cloudnative-pg/cloudnative-pg/release-1.21/releases/cnpg-1.21.1.yaml
kubectl apply -f cnpg-cluster.yaml
```
The script produces following error when it tries to run the last line:
```
Error from server (InternalError): error when creating "cnpg-cluster.yaml": Internal error occurred: failed calling webhook "mcluster.cnpg.io": failed to call webhook: Post "https://cnpg-webhook-service.cnpg-system.svc:443/mutate-postgresql-cnpg-io-v1-cluster?timeout=10s": context deadline exceeded
```
If I run each line of this script on after the other manually in my terminal (MacOS), there is no error. 

Of course, I can go into `cnpg-1.21.1.yaml` and set the relevant webhook failure policies to `Ignore`, but not sure if this breaks anything down the line.

**Comment by MichaluxPL** [comment]
I've managed to solve this one. The problem was connected to the fact we are using ArgoCD to deploy all objects on our K8s cluster. It appeared that probably both webhooks were created a little bit too late so the operator couldn't inject certificates correctly. I've configured ArgoCD to implement both webhooks before controller's deployment and voila problem solved :)
To do this there is an annotation for controller's deployment object. It looks like this:
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"

**Comment by mfmessaoudi** [comment]
Hello I'm facing the same error trying to deploy a pgsql cluster with cnpg

# k get po -A
NAMESPACE           NAME                                        READY   STATUS      RESTARTS       AGE
cnpg-system         cnpg-controller-manager-8bf6c4b9b-r2dt4     1/1     Running     0              10m

# k get ep -A
NAMESPACE           NAME                                 ENDPOINTS                                                              AGE
cnpg-system         cnpg-webhook-service                 10.100.242.168:9443          

trying to apply a yaml file to create a cluster:
Internal error occurred: failed calling webhook "mcluster.cnpg.io": failed to call webhook: Post "https://cnpg-webhook-service.cnpg-system.svc:443/mutate-postgresql-cnpg-io-v1-cluster?timeout=10s": Service Unavailable

Best regards

**Comment by MichaluxPL** [comment]
CRDs and webhooks are part of the CNPG operator manifest, so they are deployed together with the operator.
ArgoCD creates all objects contained in CPNG manifes, but due to deploy timeline If webhooks are created too late, starting operator deployment is unable to correctly inject certificates to both mentioned webhooks. So no action on the cluster level will help. Just use the workaround I've presented - this will solve the issue. Another solution is to restart (kill) operator's pod, to start it again.

**Comment by bhanotjyoti** [comment]
@flypenguin : How did you resolve? I am facing the same issue

**Comment by MichaluxPL** [comment]
Check if You have certificates in both mutating and validating webhooks. If
not - kill CNPG pod to restart it. It should inject certificates and solve
the problem.

Michał

pon., 16 gru 2024, 22:34 użytkownik bhanotjyoti ***@***.***>
napisał:

**Comment by flypenguin** [comment]
> @flypenguin : How did you resolve? I am facing the same issue

@bhanotjyoti oh ... i don't really rememer, i remember it was super easy though. sorry for that annoying response ... . it might have been @MichaluxPL's solution – kill CNPG, and retry.

**Comment by lavanyaj3** [comment]
@MichaluxPL can you provide the steps you performed with ArgoCD. Iam trying to install postgresql cluster in local kubernetes cluster. But receiving the same error 
"kubectl apply -f cluster-example.yaml
Error from server (InternalError): error when creating "cluster-example.yaml": Internal error occurred: failed calling webhook "mcluster.cnpg.io": failed to call webhook: Post "https://cnpg-webhook-service.cnpg-system.svc:443/mutate-postgresql-cnpg-io-v1-cluster?timeout=10s": dial tcp 10.103.191.246:443: connect: no route to host"

**Comment by ashokks80** [comment]
> [@MichaluxPL](https://github.com/MichaluxPL) can you provide the steps you performed with ArgoCD. Iam trying to install postgresql cluster in local kubernetes cluster. But receiving the same error "kubectl apply -f cluster-example.yaml Error from server (InternalError): error when creating "cluster-example.yaml": Internal error occurred: failed calling webhook "mcluster.cnpg.io": failed to call webhook: Post "https://cnpg-webhook-service.cnpg-system.svc:443/mutate-postgresql-cnpg-io-v1-cluster?timeout=10s": dial tcp 10.103.191.246:443: connect: no route to host"

You have to check hostnetwork true and DNS policy clusterfirstwithhostnetwork I think that will solve issue

**Comment by puneet800123** [comment]
> Hello I'm facing the same error trying to deploy a pgsql cluster with cnpg
> 
> k get po -A NAMESPACE NAME READY STATUS RESTARTS AGE cnpg-system cnpg-controller-manager-8bf6c4b9b-r2dt4 1/1 Running 0 10m
> 
> k get ep -A NAMESPACE NAME ENDPOINTS AGE cnpg-system cnpg-webhook-service 10.100.242.168:9443
> 
> trying to apply a yaml file to create a cluster: Internal error occurred: failed calling webhook "mcluster.cnpg.io": failed to call webhook: Post "https://cnpg-webhook-service.cnpg-system.svc:443/mutate-postgresql-cnpg-io-v1-cluster?timeout=10s": Service Unavailable
> 
> Events: Type Reason Age From Message
> 
> Normal Scheduled 30m default-scheduler Successfully assigned cnpg-system/cnpg-controller-manager-8bf6c4b9b-r2dt4 to k8snode1h01 Normal Pulling 30m kubelet Pulling image "ghcr.io/cloudnative-pg/cloudnative-pg:1.21.0" Normal Pulled 30m kubelet Successfully pulled image "ghcr.io/cloudnative-pg/cloudnative-pg:1.21.0" in 5.701943675s (5.701956741s including waiting) Normal Created 30m kubelet Created container manager Normal Started 30m kubelet Started container manager Warning Unhealthy 30m kubelet Readiness probe failed: Get "https://10.100.242.168:9443/readyz": dial tcp 10.240.242.168:9443: connect: connection refused
> 
> kubectl logs cnpg-controller-manager-8bf6c4b9b-r2dt4 -c manager -n cnpg-system ... {"level":"info","ts":"2024-01-05T10:10:30Z","msg":"Starting workers","controller":"backup","controllerGroup":"postgresql.cnpg.io","controllerKind":"Backup","worker count":5} {"level":"info","ts":"2024-01-05T10:10:30Z","msg":"Starting workers","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","worker count":1} {"level":"info","ts":"2024-01-05T10:10:30Z","msg":"Starting workers","controller":"pooler","controllerGroup":"postgresql.cnpg.io","controllerKind":"Pooler","worker count":1} {"level":"info","ts":"2024-01-05T10:46:00Z","msg":"http: TLS handshake error from 10.100.243.12:46964: local error: tls: bad record MAC\n"} {"level":"info","ts":"2024-01-05T10:46:38Z","msg":"http: TLS handshake error from 10.100.243.12:51082: local error: tls: bad record MAC\n"} {"level":"info","ts":"2024-01-05T10:59:35Z","msg":"http: TLS handshake error from 10.100.243.12:59266: local error: tls: bad record MAC\n"} {"level":"info","ts":"2024-01-05T10:59:38Z","msg":"http: TLS handshake error from 10.100.243.12:47618: local error: tls: bad record MAC\n"} {"level":"info","ts":"2024-01-05T11:10:14Z","logger":"pki","msg":"Periodic TLS certificates maintenance"}
> 
> Best regards

Hi, were you able to solve this one? getting the same error- 

trying to apply a yaml file to create a cluster: Internal error occurred: failed calling webhook "mcluster.cnpg.io": failed to call webhook: Post "https://cnpg-webhook-service.cnpg-system.svc:443/mutate-postgresql-cnpg-io-v1-cluster?timeout=10s": **Service Unavailable**

**Comment by AKhozya** [comment]
Yup, me as well

**Comment by ashokobserve** [comment]
You have to check the hostnetwork true and the DNS policy clusterfirstwithhostnetwork. I think that will solve the issue

try this

**Comment by suse-coder** [comment]
I also have this error:

<img width="1163" height="126" alt="Image" src="https://github.com/user-attachments/assets/6d1f1bf9-0f40-44c2-98b9-1161b5efd24d" />

**Comment by JanBenisek** [comment]
What worked for me was to delete the tls certs in secrets, restart pod and all turned green.

**Comment by chrede88** [comment]
Had the same error as OP, although not during creation of a new cluster. It seemed to be related to the cert rotation which happened just before the error started to show up.
I too solved the issue by deleting the secret holding the bad cert and then deleting the operator pod. Once the operator came back up, it recreated the secret with a new cert. This time the cert was fine and everything went back to normal.
