### ISSUE TITLE
Proposal: Remove docker image tag requirements

### ISSUE THREAD

**Issue by itay-grudev** [cloudnative-pg/cloudnative-pg#3110]
I propose that we forgo the [image tag requirements](https://cloudnative-pg.io/documentation/current/container_images/#image-tag-requirements) from Docker images in favor of OCI annotations, to communicate the version of the packaged PostgreSQL.

Currently the image tag requirement creates a problem for adopting certain externally managed Docker images as their tags may be incompatible.

I propose the following change. The operator:

1. First checks if there is an: `org.opencontainers.image.version` [annotation](https://github.com/opencontainers/image-spec/blob/main/annotations.md#annotations) and uses that.
2. If one is not found only then can it try to infer the version from the image tag as a fallback and for backwards compatibility.

This should also ensure a smooth transition, as the image tag would remain as a fallback when an annotation isn't found.

**Comment by phisco** [comment]
Relying on an annotation would mean cnpg would have to interact with the registry directly?

**Comment by itay-grudev** [comment]
During the CloudNativePG meeting on January 3d, the following ideas for a solution were discussed under `Compatibility with other PostgreSQL “distributions”`:

* Add an annotation to not check the version from the image tag
* Add a field that contain with a regex that extracts the version from an image tag
* Add a field that just overwrites the major version

Each of these solutions is feasible within the operator. Can we discuss the pros-and cons of each of the approaches and choose one?

**Comment by itay-grudev** [comment]
#3711 Would resolve this indeed. Any idea on a release timeline?

**Comment by sxd** [comment]
Closing this since it's being handled with the image catalog project
