### ISSUE TITLE
Samples aren't working as expected because of missing enableSuperuserAccess values

### ISSUE THREAD

**Issue by vstariradev** [cloudnative-pg/cloudnative-pg#3113]
Setting up any cluster that needs to have a superuser account is documented here https://github.com/cloudnative-pg/cloudnative-pg/blob/main/docs/src/security.md#postgresql but the samples are lacking enableSuperuserAccess value altogether. 

Maybe add a commented enableSuperuserAccess value to show that since 1.21 it's required if a superuser is created?

Here's is the supposed cluster-example-full.yaml for which the superuser won't work for 1.21. 
https://github.com/cloudnative-pg/cloudnative-pg/blob/main/docs/src/samples/cluster-example-full.yaml
Also, here the superuser won't be taken into account at all for 1.21:
https://github.com/cloudnative-pg/cloudnative-pg/blob/main/docs/src/samples/cluster-example-secret.yaml

Also documentation here could be misleading if not noted that enableSuperuserAccess must be enabled for it to be completely true: https://github.com/cloudnative-pg/cloudnative-pg/blob/main/docs/src/applications.md#secrets

**Comment by gbartolini** [comment]
Nice catch!

**Comment by gbartolini** [comment]
@vstariradev do you mind reviewing the patch in #3139 ? thanks.

**Comment by vstariradev** [comment]
Done, thanks!
