### ISSUE TITLE
optimize: reduce the run time of `GetStatus`

### ISSUE THREAD

**Issue by YanniHu1996** [cloudnative-pg/cloudnative-pg#3121]
we have a method [GetStatus](https://github.com/cloudnative-pg/cloudnative-pg/blob/main/pkg/management/postgres/probes.go#L66) to get different aspects for a Postgres instance statuses,  but not 
 all callers use all this information, such as   `replicationInfo` is used by `status` command of the plugin only. So we can so we can optimize performance by retrieving data on demand

https://github.com/cloudnative-pg/cloudnative-pg/blob/main/pkg/management/postgres/probes.go#L249-L274

this depends on the pull request #3101

**Comment by sxd** [comment]
closing, fixed on #3101
