### ISSUE TITLE
Backup temp dir in scratch data fills the host disk

### ISSUE THREAD

**Issue by francoispqt** [cloudnative-pg/cloudnative-pg#317]
When we do base backups barman writes its data into `/controller/backup` but this directory is on an EmptyDir volume and in our case the .part buffer file created by barman fills up the host disk and leads to Kubernetes terminating the database pod because it uses ephemeral storage it didn't request. The problem is our host disk isn't big enough to accommodate the .part file and it grows quite big because there is high latency between our object storage location and the database location (and we can't do anything about it).

As a solution we could specify a different path for backups and have a volume for that or maybe there is some barman configuration that could help?

**Comment by sxd** [comment]
I think this issue was fixed in the newer version, please reopen if that's not the case
