### ISSUE TITLE
[Feature]: How to change/control INSTANCE_ID?

### ISSUE THREAD

**Issue by kfkawalec** [cloudnative-pg/cloudnative-pg#3222]
### Is there an existing issue already for this feature request/idea?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new feature request to be evaluated.

### What problem is this feature going to solve? Why should it be added?

Right now my cluster has a "random" ID:
pgsql15-2
pgsql15-4
pgsql15-6

The reason for the current number is that nodes have fallen down and the only way is to destroy them permanently and add another node.
There is an open issue for this.

### Describe the solution you'd like

Is there a way to get back to 1,2,3?
Or reset counter for the new node id?

### Describe alternatives you've considered

Do nothing..., but is ugly and provides for situation when node 6 is really node 3 :(

### Backport?

Yes

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gbartolini** [comment]
Why is that important?

**Comment by gbartolini** [comment]
Any comments?

**Comment by kfkawalec** [comment]
Its important becouse of few reason:
1. Its easier to find some logs in ELK by correct node name.
2. I want to have correct node names :)
Also our project rules says that this node should be numbered from 0 without gaps.

**Comment by gbartolini** [comment]
Got it. Thanks. I guess this is not the right operator for you then. We are using [labels](https://cloudnative-pg.io/documentation/current/labels_annotations/) to control this, rather than a sequence. Closing this ticket.
