### ISSUE TITLE
[Bug]: New server cert is not generated when serverAltDNSNames is updated

### ISSUE THREAD

**Issue by bdun1013** [cloudnative-pg/cloudnative-pg#3269]
### Is there an existing issue already for this bug?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [X] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [X] I have read the troubleshooting guide and I think this is a new bug.

### Version

1.20.3

### What version of Kubernetes are you using?

1.28

### What is your Kubernetes environment?

Self-managed: kind (evaluation)

### How did you install the operator?

Helm

### What happened?

I added additional entries to `cluster.spec.certificates.serverAltDNSNames` and noticed that the server `kubernetes.io/tls` Secret was not updated to reflect the additional SANs.

Deleting the server `kubernetes.io/tls` Secret to force a reconciliation does force the operator to make a new Secret with correct SANs, but the operator should always ensure that the SANs in the actual cert reflect `cluster.spec.certificates.serverAltDNSNames` when using operator managed certs.

I believe the [RenewLeafCertificate](https://github.com/cloudnative-pg/cloudnative-pg/blob/main/pkg/certs/k8s.go#L94) only updates the server tls secret if it is close to expiring. This func should probably be updated to also renew if the SANs in the cert do not match what is declared in the Cluster.

### Cluster resource

```shell
First create a cluster with one entry in serverAltDNSNames:


cluster:
  certificates:
    serverAltDNSNames:
    - postgres-r.domain
```

Then add an additional entry the Cluster's serverAltDNSNames:

```
cluster:
  certificates:
    serverAltDNSNames:
    - postgres-r.domain
    - postgres-rw.domain
```

Inspect the cert in the Secret and noticed that the additional SAN will not be added.
```


### Relevant log output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by phisco** [comment]
I'd say you are right, would you be interested in opening a PR with a fix @bdun1013?

**Comment by bdun1013** [comment]
> I'd say you are right, would you be interested in opening a PR with a fix @bdun1013?

Sure, I'll get started on the changes.
