### ISSUE TITLE
[Feature]: Comply to Semantic Versioning

### ISSUE THREAD

**Issue by Ornias1993** [cloudnative-pg/cloudnative-pg#3311]
### Is there an existing issue already for this feature request/idea?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new feature request to be evaluated.

### What problem is this feature going to solve? Why should it be added?

Currently container updates are often tagged as minor (something.x.something, where X is the increase), even though there are changes that technically break compatibility with the helm chart.

This is also way more compatible with automatic processes  for downstreams and gitops users.

### Describe the solution you'd like

It would be nice if the containers/software starts to comply to semver, to correctly tag breaking changes as a major version increase. This correctly gets detected by nearly all versioning software as (potentially) breaking.

### Describe alternatives you've considered

Continuing the status quo

### Backport?

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sxd** [comment]
Hi @Ornias1993 

This is related to the operand images right? Please open this issue on the related container with some clear examples of which image are you talking about, for now, for us is hard to understand which image you mean since the operator image is semver compliant 

Closing for now

**Comment by Ornias1993** [comment]
@sxd Honestly, when you ask almost half a year later, even I don't know what my original issue was about...
