### ISSUE TITLE
[Feature]: Sign Container Images and provide SBOM

### ISSUE THREAD

**Issue by Ornias1993** [cloudnative-pg/cloudnative-pg#3313]
### Is there an existing issue already for this feature request/idea?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new feature request to be evaluated.

### What problem is this feature going to solve? Why should it be added?

Currently the provided images are completely unsigned.
This increases the risk of supply chain attacks.

### Describe the solution you'd like

In light with good security practices, the images should be signed and, preferably, a Software Bill of Materials, provided as well.

A good example to do this is using cosign and takes just a few rows of CI to get an initial version going:
https://github.com/truecharts/containers/blob/b117c431d48194942333788de082e9726b4bffd5/.github/workflows/containers.build.yaml#L272

### Describe alternatives you've considered

Keeping things insecure, not a realistic nor professional option

### Backport?

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sxd** [comment]
Closing, this is being handled in different steps starting with #4199 and other issues will be opened on each operand project
