### ISSUE TITLE
[Bug]: Stuck in "Creating a new replica" phase after node crash

### ISSUE THREAD

**Issue by theuggla** [cloudnative-pg/cloudnative-pg#3365]
### Is there an existing issue already for this bug?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [X] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [X] I have read the troubleshooting guide and I think this is a new bug.

### Version

older in 1.20.x

### What version of Kubernetes are you using?

1.25

### What is your Kubernetes environment?

Cloud: Amazon EKS

### How did you install the operator?

Helm

### What happened?

**Description:**

When creating a cluster from a backup with three replicas in the cloudnative-pg project, we encountered an issue where the cluster gets stuck in the "Creating a new replica" phase after a node crash during the join-phase of the third replica. The cluster fails to recover and continuously retries creating the new replica, finally getting stuck in the "Creating a new replica" phase preventing further progress.

**Steps to Reproduce:**

1. Create a cluster from a backup with three replicas.
2. Wait for the full-recovery node to finish and join the cluster as the primary instance.
3. Allow the second join-instance to start up and join the cluster as a secondary replica.
4. While the third replica is in the join-phase, intentionally crash the node it is running on.
5. Observe that the new replica creation fails with the "PGData already exists" error.
6. Notice that despite multiple failed attempts, the cluster remains stuck in the "Creating a new replica" phase.

**Expected Behavior:**

- The cluster should be able to retry starting a new replica if the node goes down, possibly by handling the "PGData already exists" error.
- Alternatively, the cluster should exit the "Creating a new replica" phase to allow other phases to initiate.
- It should be possible to force the cluster out of the "Creating a new replica" phase or adjust the desired replica count.

**Questions:**

- Is there a way to force the cluster out of the "Creating a new replica" phase manually?
- Is my understanding of the issue correct, or is there a recommended approach to handle this scenario?

**Note:**

Please forgive any misunderstandings, and if there is a more appropriate way to resolve this issue or if I've missed any critical information, kindly guide me in the right direction.

### Cluster resource

```shell
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::******:role/******
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"postgresql.cnpg.io/v1","kind":"Cluster","metadata":{"annotations":{"eks.amazonaws.com/role-arn":"arn:aws:iam::******:role/******"},"name":"rsi-db-dk-5","namespace":"wm"},"spec":{"affinity":{"enablePodAntiAffinity":true,"nodeAffinity":{"preferedDuringSchedulingIgnoredDuringExecution":{"nodeSelectorTerms":[{"matchExpressions":[{"key":"karpenter.k8s.aws/instance-cpu","operator":"Lte","values":["18"]}]}]}},"nodeSelector":{"karpenter.sh/capacity-type":"spot","kubernetes.io/arch":"amd64"},"topologyKey":"kubernetes.io/hostname"},"backup":{"barmanObjectStore":{"data":{"compression":"gzip","encryption":"AES256","immediateCheckpoint":false,"jobs":2},"destinationPath":"s3://********/recovery/7","s3Credentials":{"inheritFromIAMRole":true},"wal":{"compression":"gzip","maxParallel":8}},"retentionPolicy":"30d","target":"primary"},"bootstrap":{"recovery":{"database":"dk_1","owner":"*****","secret":{"name":"******"},"source":"rsi-db-dk-5"}},"externalClusters":[{"barmanObjectStore":{"destinationPath":"s3://******/recovery/4","s3Credentials":{"inheritFromIAMRole":true},"wal":{"maxParallel":15}},"name":"rsi-db-dk-5"}],"imageName":"ghcr.io/cloudnative-pg/postgis:15-3.3","inheritedMetadata":{"annotations":{"cluster-autoscaler.kubernetes.io/safe-to-evict":"true"}},"instances":3,"logLevel":"debug","monitoring":{"enablePodMonitor":true},"nodeMaintenanceWindow":{"inProgress":false,"reusePVC":false},"postgresql":{"parameters":{"auto_explain.log_min_duration":"10s","checkpoint_completion_target":"0.9","checkpoint_timeout":"15min","log_checkpoints":"on","maintenance_work_mem":"8GB","max_connections":"500","max_wal_size":"16GB","pg_stat_statements.max":"10000","pg_stat_statements.track":"all","shared_buffers":"20GB","statement_timeout":"1800000","temp_buffers":"2048MB","wal_compression":"on","work_mem":"8GB"},"pg_hba":["host rsiuser all all password"]},"primaryUpdateStrategy":"unsupervised","replicationSlots":{"highAvailability":{"enabled":true}},"resources":{"limits":{"cpu":"6","memory":"64Gi"},"requests":{"cpu":"6","memory":"64Gi"}},"serviceAccountTemplate":{"metadata":{"annotations":{"eks.amazonaws.com/role-arn":"arn:aws:iam::******:role/******"}}},"startDelay":300,"stopDelay":300,"storage":{"size":"3000Gi","storageClass":"ebs-gp3"},"walStorage":{"size":"25Gi","storageClass":"ebs-gp3"}}}
  creationTimestamp: "2023-11-16T08:48:30Z"
  generation: 1
  name: rsi-db-dk-5
  namespace: wm
  resourceVersion: "146790109"
  uid: a7b2e171-e3b3-4deb-b9a8-71301457bd74
spec:
  affinity:
    enablePodAntiAffinity: true
    nodeAffinity: {}
    nodeSelector:
      karpenter.sh/capacity-type: spot
      kubernetes.io/arch: amd64
    podAntiAffinityType: preferred
    topologyKey: kubernetes.io/hostname
  backup:
    barmanObjectStore:
      data:
        compression: gzip
        encryption: AES256
        jobs: 2
      destinationPath: s3://******/recovery/7
      s3Credentials:
        inheritFromIAMRole: true
      wal:
        compression: gzip
        maxParallel: 8
    retentionPolicy: 30d
    target: primary
  bootstrap:
    recovery:
      database: dk_1
      owner: ******
      secret:
        name: ******
      source: rsi-db-dk-5
  enableSuperuserAccess: true
  externalClusters:
  - barmanObjectStore:
      destinationPath: s3://******/recovery/4
      s3Credentials:
        inheritFromIAMRole: true
      wal:
        maxParallel: 15
    name: rsi-db-dk-5
  failoverDelay: 0
  imageName: ghcr.io/cloudnative-pg/postgis:15-3.3
  inheritedMetadata:
    annotations:
      cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
  instances: 3
  logLevel: debug
  maxSyncReplicas: 0
  minSyncReplicas: 0
  monitoring:
    customQueriesConfigMap:
    - key: queries
      name: cnpg-default-monitoring
    disableDefaultQueries: false
    enablePodMonitor: true
  nodeMaintenanceWindow:
    inProgress: false
    reusePVC: false
  postgresGID: 26
  postgresUID: 26
  postgresql:
    parameters:
      archive_mode: "on"
      archive_timeout: 5min
      auto_explain.log_min_duration: 10s
      checkpoint_completion_target: "0.9"
      checkpoint_timeout: 15min
      dynamic_shared_memory_type: posix
      log_checkpoints: "on"
      log_destination: csvlog
      log_directory: /controller/log
      log_filename: postgres
      log_rotation_age: "0"
      log_rotation_size: "0"
      log_truncate_on_rotation: "false"
      logging_collector: "on"
      maintenance_work_mem: 8GB
      max_connections: "500"
      max_parallel_workers: "32"
      max_replication_slots: "32"
      max_wal_size: 16GB
      max_worker_processes: "32"
      pg_stat_statements.max: "10000"
      pg_stat_statements.track: all
      shared_buffers: 20GB
      shared_memory_type: mmap
      shared_preload_libraries: ""
      statement_timeout: "1800000"
      temp_buffers: 2048MB
      wal_compression: "on"
      wal_keep_size: 512MB
      wal_receiver_timeout: 5s
      wal_sender_timeout: 5s
      work_mem: 8GB
    pg_hba:
    - host ***** all all password
    syncReplicaElectionConstraint:
      enabled: false
  primaryUpdateMethod: restart
  primaryUpdateStrategy: unsupervised
  replicationSlots:
    highAvailability:
      enabled: true
      slotPrefix: _cnpg_
    updateInterval: 30
  resources:
    limits:
      cpu: "6"
      memory: 64Gi
    requests:
      cpu: "6"
      memory: 64Gi
  serviceAccountTemplate:
    metadata:
      annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::******:role******
  startDelay: 300
  stopDelay: 300
  storage:
    resizeInUseVolumes: true
    size: 3000Gi
    storageClass: ebs-gp3
  switchoverDelay: 40000000
  walStorage:
    resizeInUseVolumes: true
    size: 25Gi
    storageClass: ebs-gp3
status:
  certificates:
    clientCASecret: rsi-db-dk-5-ca
    expirations:
      rsi-db-dk-5-ca: 2024-02-14 08:43:30 +0000 UTC
      rsi-db-dk-5-replication: 2024-02-14 08:43:30 +0000 UTC
      rsi-db-dk-5-server: 2024-02-14 08:43:30 +0000 UTC
    replicationTLSSecret: rsi-db-dk-5-replication
    serverAltDNSNames:
    - rsi-db-dk-5-rw
    - rsi-db-dk-5-rw.wm
    - rsi-db-dk-5-rw.wm.svc
    - rsi-db-dk-5-r
    - rsi-db-dk-5-r.wm
    - rsi-db-dk-5-r.wm.svc
    - rsi-db-dk-5-ro
    - rsi-db-dk-5-ro.wm
    - rsi-db-dk-5-ro.wm.svc
    serverCASecret: rsi-db-dk-5-ca
    serverTLSSecret: rsi-db-dk-5-server
  cloudNativePGCommitHash: 6f7f10b7
  cloudNativePGOperatorHash: 542550761e4f964894340e0ae107068e23a23eb473e817d13023a45d6cf3d887
  conditions:
  - lastTransitionTime: "2023-11-16T08:48:30Z"
    message: Cluster Is Not Ready
    reason: ClusterIsNotReady
    status: "False"
    type: Ready
  - lastTransitionTime: "2023-11-16T15:11:37Z"
    message: Continuous archiving is working
    reason: ContinuousArchivingSuccess
    status: "True"
    type: ContinuousArchiving
  - lastTransitionTime: "2023-11-17T00:00:00Z"
    message: New Backup starting up
    reason: BackupStarted
    status: "False"
    type: LastBackupSucceeded
  configMapResourceVersion:
    metrics:
      cnpg-default-monitoring: "61610208"
  currentPrimary: rsi-db-dk-5-1
  currentPrimaryTimestamp: "2023-11-16T15:11:09.240417Z"
  healthyPVC:
  - rsi-db-dk-5-1
  - rsi-db-dk-5-1-wal
  - rsi-db-dk-5-2
  - rsi-db-dk-5-2-wal
  instanceNames:
  - rsi-db-dk-5-1
  - rsi-db-dk-5-2
  instances: 2
  instancesReportedState:
    rsi-db-dk-5-1:
      isPrimary: true
      timeLineID: 27
    rsi-db-dk-5-2:
      isPrimary: false
      timeLineID: 27
  instancesStatus:
    healthy:
    - rsi-db-dk-5-1
    - rsi-db-dk-5-2
  jobCount: 3
  latestGeneratedNode: 3
  managedRolesStatus: {}
  phase: Creating a new replica
  phaseReason: Creating replica rsi-db-dk-5-3-join
  poolerIntegrations:
    pgBouncerIntegration: {}
  pvcCount: 4
  readService: rsi-db-dk-5-r
  readyInstances: 2
  secretsResourceVersion:
    applicationSecretVersion: "61138522"
    clientCaSecretVersion: "145481416"
    replicationSecretVersion: "145481420"
    serverCaSecretVersion: "145481416"
    serverSecretVersion: "145481418"
    superuserSecretVersion: "145481421"
  targetPrimary: rsi-db-dk-5-1
  targetPrimaryTimestamp: "2023-11-16T08:48:30.939564Z"
  timelineID: 27
  topology:
    instances:
      rsi-db-dk-5-1: {}
      rsi-db-dk-5-2: {}
    nodesUsed: 2
    successfullyExtracted: true
  writeService: rsi-db-dk-5-rw
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by adampetrovic** [comment]
Just had this happen to my cluster and am seeing exactly the same issue. I think we need a way to manually intervene into the lifecycle of the cluster / replica creation and abort / force the creation of a new replica.

Right now the only foreseeable way to recover from this is to destroy the cluster and recover from a backup.

**Comment by theuggla** [comment]
Yes, that's the road I went down as well. It seems like it should have to be that way, since there is a fully functioning primary replica up and running.

**Comment by gbartolini** [comment]
Please try again with the latest patch version for the minor version you are using.

**Comment by theuggla** [comment]
Thanks for the answer! I have now upgraded to 1.21.1 and are still seeing the same issue.

**Comment by os-sengel** [comment]
We had a similar symptom with our test cluster. The `Creating a new replica` phase never finished, even though the db pods were up and healthy and join pods finished successfully. 
It's unclear how much the following is applicable to this issue. You can see this as another sanity check.

While introducing additional network policies we accidently **blocked** the status requests from the **operator** namespace. Thus, preventing the operator to check the cluster state and signal a finished startup. 
Having the status ports open to the operator namespace is explicitly required, as stated in the networking section of the documentation:
https://cloudnative-pg.io/documentation/1.20/networking/

**Comment by stevec-skyhawk** [comment]
Has there been any update on this issue?
I am experiencing much the same problem on v1.22.1, though for me the join pod fails to schedule due to insufficient resources. Then the cluster stays in 'Creating a new replica' phase. Without modifying the nodes (for whatever restriction) it should be possible to tell CNPG to scale back that replica , 'forget' about the pod, and go back to Running state.

**Comment by jordi-t** [comment]
I have encountered the exact same issue, where the concerning cluster was stuck in the `Creating new replica` phase. I was able to 'trigger' the reconciliation by removing the concerning 'join' job. Just do a `kubectl get jobs`, identify the job and execute `kubectl delete job <clustername>-<number>-join`. Afterwards a new job was created and the replica was successfully provisioned.

**Comment by blodone** [comment]
After cnpg tried to get a new replica ready it failed and now its failing:
Status:              Creating a new replica Creating replica postgres-002-2-join

I deleted the job but no new job is being created
