### ISSUE TITLE
[Bug]: Cannot disable weak TLS 1.2 ciphers

### ISSUE THREAD

**Issue by senyahnoj** [cloudnative-pg/cloudnative-pg#3376]
### Is there an existing issue already for this bug?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [X] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [X] I have read the troubleshooting guide and I think this is a new bug.

### Version

1.21.0

### What version of Kubernetes are you using?

1.28

### What is your Kubernetes environment?

Self-managed: kind (evaluation)

### How did you install the operator?

Helm

### What happened?

It is becoming increasingly common security policy to disable weak ciphers in TLS 1.2 (ref: https://support.securityscorecard.com/hc/en-us/articles/115003260246-TLS-Service-Supports-Weak-Cipher-Suite#:~:text=Ultimately%2C%20it%20is%20recommended%20to,discovered%20that%20render%20it%20insecure.)

The CNPG operator does not allow you to do this. 

We want to restrict TLS to only ECDHE-RSA-AES256-GCM-SHA384 and minimum TLS version to 1.2. Therefore, we added the following to our installation to set the ciphers for postgresql.conf

```yaml
postgresql:
  parameters:
     ssl_ciphers: ECDHE-RSA-AES256-GCM-SHA384
     ssl_min_protocol_version: TLSv1.2
```
Unfortunately, when you try and set these, the helm install fails with a message

`[spec.postgresql.parameters.ssl_ciphers: Invalid value: "ECDHE-RSA-AES256-GCM-SHA384": Can't set fixed configuration parameter, spec.postgresql.parameters.ssl_min_protocol_version: Invalid value: "TLSv1.2": Can't set fixed configuration parameter]`

Despite the operator letting you set spec.postgresql.parameters with key/value configuration options for postgresql.conf, there are some which the operator is intentionally locking down and this includes ones which would be needed for restricting the cipher suites.

https://github.com/cloudnative-pg/cloudnative-pg/blob/main/pkg/postgres/configuration.go#L284

Helm charts/operators for MySQL, MongoDB and Neo4j all allow the cipher lists to be restricted. The PostgreSQL implementation should seriously consider allowing the same.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gbartolini** [comment]
This was actually an intended and conservative behaviour taken at the start of the project. I have submitted a small patch that by default sets TLS to 1.3 and also allows overriding. See #3408
