### ISSUE TITLE
[Bug]: Cluster resource CPU limit expressed as 2000m gets changed to 2 when manifest applied

### ISSUE THREAD

**Issue by acmayberry** [cloudnative-pg/cloudnative-pg#3399]
### Is there an existing issue already for this bug?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [X] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [X] I have read the troubleshooting guide and I think this is a new bug.

### Contact Details

austin@openfla.me

### Version

1.21.0

### What version of Kubernetes are you using?

1.28

### What is your Kubernetes environment?

Self-managed: kind (evaluation)

### How did you install the operator?

Helm

### What happened?

I applied the below manifest, and the resource section gets converted to:

resources:
    limits:
      cpu: 2
      memory: 4Gi
    requests:
      cpu: 250m
      memory: 1Gi
      
 from:
 
 resources:
    limits:
      cpu: 2000m
      memory: 4Gi
    requests:
      cpu: 250m
      memory: 1Gi
      
 When it is applied to K8S.
 
 If I try, to use "cpu: 2" it gets converted to "cpu: '2'"
 
This causes an issue with ArgoCD as it is constantly resyncing trying to convert the value back to the value in the applied manifest.  Is there a rationale for altering the cluster resource to not match the applied manifest?

### Cluster resource

```shell
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: db
  namespace: database
spec:
  affinity:
    podAntiAffinityType: preferred
  backup:
    target: prefer-standby
  bootstrap:
    initdb:
      database: db
      encoding: UTF8
      localeCType: C
      localeCollate: C
      owner: app
      secret:
        name: db
  enableSuperuserAccess: true
  failoverDelay: 0
  imageName: ghcr.io/cloudnative-pg/postgresql:16.1
  instances: 1
  logLevel: info
  maxSyncReplicas: 0
  minSyncReplicas: 0
  monitoring:
    customQueriesConfigMap:
      - key: queries
        name: cnpg-default-monitoring
    disableDefaultQueries: false
    enablePodMonitor: false
  postgresGID: 26
  postgresUID: 26
  postgresql:
    parameters:
      archive_mode: 'on'
      archive_timeout: 5min
      dynamic_shared_memory_type: posix
      log_destination: csvlog
      log_directory: /controller/log
      log_filename: postgres
      log_rotation_age: '0'
      log_rotation_size: '0'
      log_truncate_on_rotation: 'false'
      logging_collector: 'on'
      max_parallel_workers: '32'
      max_replication_slots: '32'
      max_worker_processes: '32'
      shared_memory_type: mmap
      shared_preload_libraries: ''
      wal_keep_size: 512MB
      wal_receiver_timeout: 5s
      wal_sender_timeout: 5s
    syncReplicaElectionConstraint:
      enabled: false
  primaryUpdateMethod: switchover
  primaryUpdateStrategy: unsupervised
  replicationSlots:
    highAvailability:
      enabled: true
      slotPrefix: _cnpg_
    updateInterval: 30
  resources:
    limits:
      cpu: 2000m
      memory: 4Gi
    requests:
      cpu: 250m
      memory: 1Gi
  smartShutdownTimeout: 180
  startDelay: 30
  stopDelay: 30
  storage:
    resizeInUseVolumes: true
    size: 10Gi
  superuserSecret:
    name: db-main-admin
  switchoverDelay: 40000000
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by YanniHu1996** [comment]
Hi @acmayberry  can this issue be fixed by using the string '2' instead of the number 2?

**Comment by acmayberry** [comment]
@YanniHu1996 that does work and likewise if I use 2100m instead of 2000m it works and does not change the value.

But my bigger question is why it changes the value?  Why does it change 2000m to 2?  or 2 to '2'?  But it doesn't change 2100m to 2.1?  

It's very odd and inconsistent behavior that i need to code around now when allocating clusters so as not to wreak havoc on my continuous deployment tools.

I'd expect the YAML applied to be the same as the YAML stored in etcd.  I've not seen another operator change the YAML before committing like this.  ArgoCD in particular really doesn't like it if what ends up being stored is different than what's applied because it will just cycle constantly resyncing trying to get them to match.

Also, when ArgoCD cycles like that it puts an undesirable amount of stress on the apiserver and etcd.  I've observed it really increasing the memory usage of the two.

**Comment by sxd** [comment]
Closing, this was handled in issue #3706
