### ISSUE TITLE
[Bug]: pdb not removed during maintenance mode on clusters with instances > 1

### ISSUE THREAD

**Issue by adrienpeiffer** [cloudnative-pg/cloudnative-pg#3422]
### Is there an existing issue already for this bug?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [X] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [X] I have read the troubleshooting guide and I think this is a new bug.

### Contact Details

adrien.peiffer@acsone.eu

### Version

1.21.1

### What version of Kubernetes are you using?

1.26

### What is your Kubernetes environment?

Cloud: Azure AKS

### How did you install the operator?

YAML manifest

### What happened?

In order to be able to update kubernetes, we need to activate CNPG's maintenance mode to temporarily remove the pdb. This works on a cluster with 1 postgresql instance, but not on a cluster with more than one instance. In this case, activating maintenance mode will not remove the pdb.

### Cluster resource

```shell
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: cust01258
spec:
  affinity:
    enablePodAntiAffinity: true
    podAntiAffinityType: required
    topologyKey: kubernetes.io/hostname
  enableSuperuserAccess: true
  failoverDelay: 0
  imageName: ghcr.io/cloudnative-pg/postgresql:15.3
  instances: 2
  logLevel: info
  maxSyncReplicas: 0
  minSyncReplicas: 0
  monitoring:
    customQueriesConfigMap:
    - key: queries
      name: cnpg-default-monitoring
    disableDefaultQueries: false
    enablePodMonitor: false
  nodeMaintenanceWindow:
    inProgress: true
    reusePVC: true
  postgresGID: 26
  postgresUID: 26
  postgresql:
    parameters:
      archive_mode: "on"
      archive_timeout: 5min
      auto_explain.log_min_duration: 500ms
      dynamic_shared_memory_type: posix
      log_destination: csvlog
      log_directory: /controller/log
      log_filename: postgres
      log_min_duration_statement: 20ms
      log_rotation_age: "0"
      log_rotation_size: "0"
      log_truncate_on_rotation: "false"
      logging_collector: "on"
      max_parallel_workers: "32"
      max_replication_slots: "32"
      max_worker_processes: "32"
      pg_stat_statements.max: "10000"
      pg_stat_statements.track: all
      shared_memory_type: mmap
      shared_preload_libraries: ""
      wal_keep_size: 512MB
      wal_receiver_timeout: 5s
      wal_sender_timeout: 5s
    syncReplicaElectionConstraint:
      enabled: false
  primaryUpdateMethod: restart
  primaryUpdateStrategy: unsupervised
  replicationSlots:
    highAvailability:
      enabled: true
      slotPrefix: _cnpg_
    updateInterval: 30
  resources: {}
  smartShutdownTimeout: 180
  startDelay: 30
  stopDelay: 30
  storage:
    resizeInUseVolumes: true
    size: 10Gi
  switchoverDelay: 60
```

### Relevant log output

```shell
CNPG Operator log
│ 2023-11-28T14:55:26.484450839+01:00 {"level":"info","ts":"2023-11-28T13:55:26Z","logger":"cluster-resource","msg":"default","version":"v1","name":"postgres","namespace":"cust01258"}                                                                                                                 │
│ 2023-11-28T14:55:26.538990449+01:00 {"level":"info","ts":"2023-11-28T13:55:26Z","logger":"cluster-resource","msg":"validate update","version":"v1","name":"postgres","namespace":"cust01258"}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by YanniHu1996** [comment]
Hi @adrienpeiffer, in a cluster with more than one instance, the operator does not delete the `pdb` for the primary. You can promote the replica to be the primary after the node where the replica is running has finished the maintenance process.

**Comment by Christian-Probst-DATEV** [comment]
We have a team doing the maintenance for k8s and our Team is running the database operator. 3 Nodes, 1 Primary, 2 Standbys. Our Team doesn't know when maintenance is taking place and is not involved with it. We need a way to remove, better avoid, all PDB's by declaration. Like it is suggested in https://github.com/cloudnative-pg/cloudnative-pg/issues/2570
