### ISSUE TITLE
[Bug]: usage of letsencrypt certificate via cert-manager as `serverTLSSecret` is not possible

### ISSUE THREAD

**Issue by olwe0002** [cloudnative-pg/cloudnative-pg#3503]
### Is there an existing issue already for this bug?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [X] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [X] I have read the troubleshooting guide and I think this is a new bug.

### Contact Details

info@devops-experts.de

### Version

1.21.1

### What version of Kubernetes are you using?

1.27

### What is your Kubernetes environment?

Cloud: Other

### How did you install the operator?

YAML manifest

### What happened?

The plan is to use an ingress, which forwards the traffic ("ssl-passthrough") to the postgres instance service, which is using a user provided certificate, specified by attribute `serverTLSSecret`: The ingress annotation triggers the cert-manager to request a official certificate by letsencrypt/zerossl, which gets stored in the kubernetes secret `psql-cluster-identifier-tls` with the keys `tls.crt` and `tls.key`, but no `ca.crt`, like its common for such certificates. At this point: is this a supported usecase, to define only a certificate for the server, which can be used by the client to do a `sslmode=verify-full` connection?

After the secret was in place, I tried to apply the cluster ressource only with `serverTLSSecret`. This results in the following error on apply:
```
is invalid: spec.certificates.servercasecret: Invalid value: "": Server CA secret can't be empty when server TLS secret is provided
```
That is [described](https://cloudnative-pg.io/documentation/1.21/cloudnative-pg.v1/#postgresql-cnpg-io-v1-CertificatesConfiguration) differently: `if ServerTLSSecret is provided, this can be omitted`

Manually extracting the root ca from the fullchain in `tls.crt` and storing it as `ca.crt` in a own secret named `psql-cluster-identifier-ca`, using this as `serverCASecret` (see the commented out line in the cluster resource), allows me apply the ressource without any error on apply. But after that, the instances are not created, and the log output of the operator shows:

```
"error":"cannot create Cluster auxiliary objects: generating client CA certificate: missing ca.key secret data","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/contr │
│ oller.(*Controller).reconcileHandler\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:329\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller). │
│ processNextWorkItem\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t │
│ pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:227"
```
I want to point out that the error message is regarding the _client_ CA, not _server_ CA, even that I did not define any client-related parameter, only `serverCASecret` and `serverTLSSecret`. So how is it possible to define only a `ServerTLSSecret` with only the keys `tls.crt` and `tls.key`, and let the operator create all other missing keys on its own?

might this be related? https://github.com/cloudnative-pg/cloudnative-pg/pull/3347

### Cluster resource

```shell
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: psql-cluster-identifier
  namespace: psql-cluster-identifier
spec:
  affinity:
    podAntiAffinityType: preferred
  backup:
    barmanObjectStore:
      destinationPath: s3://psql-cluster-identifier/
      endpointURL: https://endpoint
      s3Credentials:
        accessKeyId:
          key: accessKey
          name: psql-cluster-identifier
        secretAccessKey:
          key: secretKey
          name: psql-cluster-identifier
    target: prefer-standby
  bootstrap:
    initdb:
      database: app
      encoding: UTF8
      localeCType: C
      localeCollate: C
      owner: app_owner
  certificates:
  #   serverCASecret: psql-cluster-identifier-ca
    serverTLSSecret: psql-cluster-identifier-tls
  enableSuperuserAccess: false
  failoverDelay: 0
  imageName: docker-hub-proxy.registry-domain/cloudnative-pg/postgresql:15.4-9
  instances: 2
  logLevel: info
  maxSyncReplicas: 0
  minSyncReplicas: 0
  monitoring:
    customQueriesConfigMap:
    - key: queries
      name: cnpg-default-monitoring
    disableDefaultQueries: false
    enablePodMonitor: false
  postgresGID: 26
  postgresUID: 26
  postgresql:
    parameters:
      archive_mode: "on"
      archive_timeout: 5min
      dynamic_shared_memory_type: posix
      log_destination: csvlog
      log_directory: /controller/log
      log_filename: postgres
      log_rotation_age: "0"
      log_rotation_size: "0"
      log_truncate_on_rotation: "false"
      logging_collector: "on"
      max_parallel_workers: "32"
      max_replication_slots: "32"
      max_worker_processes: "32"
      shared_memory_type: mmap
      shared_preload_libraries: ""
      wal_keep_size: 512MB
      wal_receiver_timeout: 5s
      wal_sender_timeout: 5s
    pg_hba:
    - host all all all md5
    syncReplicaElectionConstraint:
      enabled: false
  primaryUpdateMethod: restart
  primaryUpdateStrategy: unsupervised
  replicationSlots:
    highAvailability:
      enabled: true
      slotPrefix: _cnpg_
    updateInterval: 30
  resources:
    limits:
      memory: 1Gi
    requests:
      cpu: "1"
      memory: 1Gi
  smartShutdownTimeout: 180
  startDelay: 3600
  stopDelay: 1800
  storage:
    resizeInUseVolumes: true
    size: 2Gi
  switchoverDelay: 3600
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by phisco** [comment]
> That is [described](https://cloudnative-pg.io/documentation/1.21/cloudnative-pg.v1/#postgresql-cnpg-io-v1-CertificatesConfiguration) differently: `if ServerTLSSecret is provided, this can be omitted`

This is incorrect, the full sentence is `ca.key: key used to generate Server SSL certs, if ServerTLSSecret is provided, this can be omitted.`, only the `ca.key` key can be omitted, not the whole `servercasecret`. 

Doesn't the `psql-cluster-identifier-tls` secret contain a `ca.crt` key?

**Comment by olwe0002** [comment]
`psql-cluster-identifier-tls` contains all 3 (for test manually created): ca.crt, tls.crt (fullchain), tls.key, and only `ServerTLSSecret` is used to reference to that secret -> 

```
is invalid: spec.certificates.servercasecret: Invalid value: "": Server CA secret can't be empty when server TLS secret is provided`
```

But if I additionally let `serverCASecret` point to the exact same secret, it seems to work. I'll test that and come back to this.....

**Comment by olwe0002** [comment]
I want to point out that they have to be the same secret. so this works fine:

```
all-in-one-secret:
  ca.crt:
  tls.crt:
  tls.key:

serverTLSSecret: all-in-one-secret
serverCASecret: all-in-one-secret
```

but if you split them up, it failes on reconciling missing `ca.key`:

```
cert-manager-secret:
  tls.crt:
  tls.key:

ca-secret:
  ca.crt:
  
serverTLSSecret: cert-manager-secret
serverCASecret: ca-secret
```

**Comment by phisco** [comment]
What error does the second configuration return? 🤔

**Comment by olwe0002** [comment]
split in two different secrets the apply works fine, but later the operator fails with:

```
"error":"cannot create Cluster auxiliary objects: generating client CA certificate: missing ca.key secret data","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/contr │
│ oller.(*Controller).reconcileHandler\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:329\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller). │
│ processNextWorkItem\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t │
│ pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:227"
```

**Comment by olwe0002** [comment]
for everyone else facing this, I can recommend to 
- use the self-signed certificates created by the operator for the cluster-internal traffic encryption. So do not provide any secrets in `spec.certificates` at all
- terminate TLS in the ingress controller, e.g. traefik V3 is able to do that
