### ISSUE TITLE
[Feature]: ZFS on local disks integration

### ISSUE THREAD

**Issue by qdrddr** [cloudnative-pg/cloudnative-pg#3510]
### Is there an existing issue already for this feature request/idea?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new feature request to be evaluated.

### What problem is this feature going to solve? Why should it be added?

According to your [recommendations](https://www.cncf.io/blog/2023/09/29/recommended-architectures-for-postgresql-in-kubernetes/), it is preferred to use dedicated local disks. In your [video](https://kccncna2023.sched.com/event/1R2ml), you also recommend using volume snapshots since they are much faster to back up & restore a DB. 

To combine both ideas, you basically must have snapshots on local disks. Currently, the only way to do that is by utilizing ZFS. The only way I know to do this in k8s is with OpenEBS. To my knowledge, there are no other options.

So, since you are advocating for both of these recommendations, and the only way to get snapshots is ZFS, it makes sense to incorporate and make a tight integration of cloudnative-pg operator to work and manage/integrate with OpenEBS.

### Describe the solution you'd like

More seamless integration with provisioning and managing ZFS on local disks and managing snapshot copies and snapshot replications to other regions to provide a more seamless experience with backups, disaster recovery, data migration, and cloning with cloudnative-pg.

### Describe alternatives you've considered

Enterprise Storage systems (instead of local disks)

### Additional context

Thank you for your consideration,
Best,
D

### Backport?

No

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gbartolini** [comment]
There's also TopoLVM as an option. However, our main focus is Postgres. We delegate the storage layer to the Kubernetes standard.

We welcome everyone, including storage vendors, to help fill the gap, with documentation or blog articles or tutorials. For example, in this case, it could be the OpenEBS project benchmark our operator or showcase how they can integrate with it. There's too many storage classes or CSI drivers out there, and it would be very easy to lose the focus on our primary mission.

**Comment by qdrddr** [comment]
@gbartolini, I agree. To focus on a specific storage vendor is to lose focus. 
But at the same time, in this particular case, if you recommend **_local disks and volume snapshots_**, only one vendor can support ZFS.
