### ISSUE TITLE
[Feature]: Support for Kubernetes 1.29

### ISSUE THREAD

**Issue by gbartolini** [cloudnative-pg/cloudnative-pg#3555]
### Is there an existing issue already for this feature request/idea?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new feature request to be evaluated.

### What problem is this feature going to solve? Why should it be added?

Kubernetes 1.29 has been released on Dec 13, 2023. CloudNativePG is not supporting it.

### Describe the solution you'd like

We should add support for Kubernetes 1.29. Possibly before releasing 1.22, if reasonably possible. Otherwise, wait for version 1.22.1.

### Describe alternatives you've considered

N/A

### Additional context

Backport only if easier to maintain.

### Backport?

No

### Are you willing to actively contribute to this feature?

No

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gbartolini** [comment]
Given that `kind` does not have yet the 1.29 image, I don't think we can manage to add support for Kubernetes 1.29 to CloudNativePG 1.22.0 - and wait for 1.22.1

**Comment by gbartolini** [comment]
Kind for 1.29 has been released.

https://hub.docker.com/layers/kindest/node/v1.29.0/images/sha256-54a50c9354f11ce0aa56a85d2cacb1b950f85eab3fe1caf988826d1f89bf37eb?context=explore

**Comment by sxd** [comment]
Everything required was merged
