### ISSUE TITLE
refactor addBarmanEndpointCAToJob function

### ISSUE THREAD

**Issue by armru** [cloudnative-pg/cloudnative-pg#361]
Right now the function:

https://github.com/cloudnative-pg/cloudnative-pg/blob/1a322fa7a703c232b401b4fa7e50db676c3a1d9f/pkg/specs/jobs.go#L135

Is extremely hard to maintain given to the approach used. Adding new providers would be extremely error prone

We should refactor and make it more maintainable.

**Comment by leonardoce** [comment]
While reviewing this PR I discovered #453.
