### ISSUE TITLE
[Bug]: Deprecation of github.com/mitchellh/go-ps

### ISSUE THREAD

**Issue by sxd** [cloudnative-pg/cloudnative-pg#3612]
### Is there an existing issue already for this bug?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [X] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [X] I have read the troubleshooting guide and I think this is a new bug.

### Version

1.21.1

### What version of Kubernetes are you using?

1.28

### What is your Kubernetes environment?

Self-managed: kind (evaluation)

### How did you install the operator?

YAML manifest

### What happened?

According to the following GIST https://gist.github.com/mitchellh/90029601268e59a29e64e55bab1c5bdc the dependency github.com/mitchelh/go-ps will be archive and no longer maintained starting 2024, we should look for a replacement for it.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mnencia** [comment]
I’m going to abandon this issue. https://github.com/shirou/gopsutil adds too many dependencies, and if we have to reimplement it, it would be better to fork the repository and maintain our copy. For now, we will remain with [http://github.com/mitchellh/go-ps](https://github.com/mitchellh/go-ps).
