### ISSUE TITLE
fix: e2e collect metrics for "cnpg_runonserver_match"

### ISSUE THREAD

**Issue by wadlejitendra** [cloudnative-pg/cloudnative-pg#366]
Need to verify `cnpg_runonserver_match` label in collected metrics. Need to change the assertion.
refer test : https://github.com/cloudnative-pg/cloudnative-pg/blob/main/tests/e2e/metrics_test.go#L79

Solution:
https://github.com/cloudnative-pg/cloudnative-pg/blob/main/tests/e2e/metrics_test.go#L108

Expect(matches, err).To(HaveLen(`8`), "Metric collection issues on %v.\nCollected metrics:\n%v", pod.GetName(), out)
need to replace with : 
Expect(matches, err).To(HaveLen(`9`), "Metric collection issues on %v.\nCollected metrics:\n%v", pod.GetName(), out)

**Comment by danishedb** [comment]
Minor amend. LGTM.
