### ISSUE TITLE
[Feature]: add `pgadmin4` command to `cnpg` plugin

### ISSUE THREAD

**Issue by gbartolini** [cloudnative-pg/cloudnative-pg#3696]
### Is there an existing issue already for this feature request/idea?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new feature request to be evaluated.

### What problem is this feature going to solve? Why should it be added?

At the moment, CloudNativePG doesn't have a good story to show how to connect with an application to a given database via network. The only application we show is `pgbench`. The `psql` command, indeed, runs on the same container where Postgres runs, and is executed as `postgres` user (so it is not exactly suitable for demonstration and evaluation).

### Describe the solution you'd like

We should add the `pgadmin4` command to `cnpg` plugin to provide an easy way to demonstrate and/or evaluate a deployed Postgres cluster using a web interface. The idea is to tie the deployment to a given cluster, and use only the app user and database to connect to the instance.

**IMPORTANT:** given that users can deploy pgAdmin4 in production independently, it is important to state in the documentation that this setup is for evaluation only and that security considerations must be taken before going in production.

### Describe alternatives you've considered

We have considered running `psql` via the network in a separate container, that is tied to the kubectl command existence. But such a behaviour has been deprecated by kubectl (run command).

### Additional context

N/A

### Backport?

Yes

### Are you willing to actively contribute to this feature?

Yes

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by achanda** [comment]
Not convinced this is a good idea. Adding pgadmin as a part of the plugin will make this look like a recommended way to manage the database. This will open up a large attack surface.

I agree that cnpg does not have a good story around apps connecting to clusters, but I think that is better solved by more docs and a demo app not in the plugin.

**Comment by gbartolini** [comment]
We will make sure to explain this is just for evaluation and not for production. Also, the idea is that pgAdmin is tied to the app user and app database, so it can only used to view the database. Let's wait to see the commit first. Happy to seek your input and help on the docs and messaging.

**Comment by gbartolini** [comment]
@achanda do you want to look at what we've come up with?

**Comment by mnencia** [comment]
I'm going to merge the plugin command. I think that @achanda's concerns have been addressed in the patch. It's clearly stated that this is not intended for permanent deployment but only as a tool for a quick visual inspection of the database or demonstration purposes.
