### ISSUE TITLE
[Feature]: require `--server-side` when installing manifests with `kubectl`

### ISSUE THREAD

**Issue by gbartolini** [cloudnative-pg/cloudnative-pg#3697]
### Is there an existing issue already for this feature request/idea?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new feature request to be evaluated.

### What problem is this feature going to solve? Why should it be added?

CloudNativePG CRDs are becoming too large to be stored in the `kubectl` apply annotation. This prevents for example adding support to Kubernetes 1.29 (#3555).

### Describe the solution you'd like

We are proposing to switch from client-side to server-side application of manifests, by requiring to specify the `--server-side` option by default when installing the operator. We have noticed that other projects, more important than ours, like Prometheus have already gone in this direction (https://github.com/prometheus-operator/prometheus-operator/issues/5104 and https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack#upgrading-an-existing-release-to-a-new-major-version).

See https://kubernetes.io/docs/reference/using-api/server-side-apply/ for details.

### Describe alternatives you've considered

1. Split CRD manifest from resource manifests and require that only the CRD manifest is applied with `--server-side`
2. Reduce the size of the apply annotation by removing the schema of some CRD sections (impacting the validation)

Our preference is not to remove the validation of the schema of the resources. As a result, we would like to understand from the community how the proposed solution will be received.

### Additional context

Installation via Helm and OLM is not impacted by this problem.

### Backport?

Yes

### Are you willing to actively contribute to this feature?

Yes

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by chrisalavoinehmm** [comment]
I would be in favour of option 1, using the `--server-side` switch.

**Comment by leonardoce** [comment]
I'm also in favor of `--server-side`.
I implemented #3639 using a schema-less approach, but doing that prevents validating fields like `poolers.spec.template`, and that's a bit... awkward.

**Comment by phisco** [comment]
Sounds good to me 👍

**Comment by armru** [comment]
I vote for the server side solution

**Comment by rdegez** [comment]
`--server-side` seems to be a good workaround for this issue.

**Comment by Andrew1988123123** [comment]
--server-side

**Comment by gbartolini** [comment]
I think we have enough consensus to proceed with changing our default installation method to `--server-side` and then properly inform our users during the upgrade to the next minor release that they need to start using it and that, for the first time, in case of issues, they need to force the conflicts.
