### ISSUE TITLE
[Docs]: Inconsistent documentation on support status for multi-arch clusters

### ISSUE THREAD

**Issue by StopMotionCuber** [cloudnative-pg/cloudnative-pg#3717]
### Is there an existing issue already for your request/idea?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new documentation enhancement to be evaluated.

### What problem in the existing documentation this issue aims to solve?

The documentation on multi-arch Kubernetes clusters is inconsistent on whether multi-arch clusters are supported.

On https://cloudnative-pg.io/documentation/1.22/#container-images there is an info box saying multi-arch clusters are not supported. But then, on https://cloudnative-pg.io/documentation/1.22/installation_upgrade/#in-place-updates-of-the-instance-manager it says that for this feature all pods need to run on the same architecture.

This is inconsistent: I would assume that if multi-arch clusters would not be supported, the rest of the documentation would not need to refer to that.

My assumption is that multi-arch clusters might not have been supported in the past but are with recent releases of the operator.

### Describe what pages need to change in the documentation, if any

If my assuptions are correct, https://cloudnative-pg.io/documentation/1.22/#container-images would need a change.

I think there are 2 good ways to go forward:
1. Remove that box entirely, as multi-arch clusters are supported by the operator
2. Change the text to something in the direction of "multi-arch clusters are supported. Limitations apply"

### Backport?

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by NiccoloFei** [comment]
Related to #3868 . See https://github.com/cloudnative-pg/cloudnative-pg/issues/3868#issuecomment-1964271703

**Comment by gbartolini** [comment]
Please let's include this change in #3868
