### ISSUE TITLE
[Docs]: About incremental and differential block level backup in Volume Snapshots

### ISSUE THREAD

**Issue by kiskk** [cloudnative-pg/cloudnative-pg#3724]
### Is there an existing issue already for your request/idea?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new documentation enhancement to be evaluated.

### What problem in the existing documentation this issue aims to solve?

The CloudNativePG manual ``Backup on volume snapshots'' describes
incremental and differential backups of Snapshots.

https://cloudnative-pg.io/documentation/1.22/backup_volumesnapshot/
> Normally, storage classes that provide volume snapshotting
> support incremental and differential block level backup
> in a transparent way for the application

However, even in the latest k8s (1.29), I don't think the incremental 
and differential backups of snapshot function is implemented yet.

CSI Differential Snapshot for Block Volumes
https://github.com/kubernetes/enhancements/issues/3314

Is the description in the CloudNativePG manual based on the assumption
that incremental/backup functions will be implemented in k8s in the future?

### Describe what additions need to be done to the documentation

If my question is correct, how about adding it to the manual that it is not available at this time?

### Describe what pages need to change in the documentation, if any

https://cloudnative-pg.io/documentation/1.22/backup_volumesnapshot/

### Backport?

No

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by till** [comment]
Related discussion:

https://github.com/cloudnative-pg/cloudnative-pg/discussions/3145

**Comment by leonardoce** [comment]
> However, even in the latest k8s (1.29), I don't think the incremental
> and differential backups of snapshot function is implemented yet.

As far as I can tell, storage class providers can implement incremental and differential backups.

The KEP you mentioned is about exposing the Change Block Tracking information via CSI in a `VolumeSnapshotDelta` resource. And yes, that would be really nice to have!
With that resource, a backup system could discover that information using the CSI APIs and back up only the changed blocks.

This is not related to how the actual Volume Snapshot is stored.

**Comment by leonardoce** [comment]
> Related discussion:
> https://github.com/cloudnative-pg/cloudnative-pg/discussions/3145

In my mind, this is not related to the pgbackrest discussion.
It is more about how volume snapshots are implemented.

Backup systems and volume snapshots have different trade-offs, and they may even be useful both at the same time.

**Comment by kiskk** [comment]
thank you for your reply.

> In my mind, this is not related to the pgbackrest discussion.
> It is more about how volume snapshots are implemented.

yes. I created this issue because I wanted to know about 
differential and incremental backups using volume snapshots.
pgbackrest also has these functions, but they are different
from backups using volume snapshots.

> As far as I can tell, storage class providers can implement incremental and differential backups.

Surely, This is not a CloudNativePG issue, but rather a question of
whether the storage class provides differential and incremental backups.
Are there any storage classes that currently provide
differential and incremental backup?
I'm trying CloudNativePG's volumesnapshot with
csi-driver-nfs (https://github.com/kubernetes-csi/csi-driver-nfs),
but it seems that differential/incremental backup cannot be used.
snapshot just created a simple PGDATA tarball.

**Comment by leonardoce** [comment]
> yes. I created this issue because I wanted to know about
> differential and incremental backups using volume snapshots.
> pgbackrest also has these functions, but they are different
> from backups using volume snapshots.

Yeah, I agree with you. They solve a samilar problem at different levels.
I'm not against pgbackrest per se; every backup tool has pros & cons.

> I'm trying CloudNativePG's volumesnapshot with
> csi-driver-nfs (https://github.com/kubernetes-csi/csi-driver-nfs),
> but it seems that differential/incremental backup cannot be used.
> snapshot just created a simple PGDATA tarball.

I'm not an expert on `csi-driver-nfs` but I think you're going to need a CSI implementation that is working at block-level to support snapshots. Longhorn does that, and many cloud providers do that, too.

**Comment by kiskk** [comment]
Thank you for the useful information! 
I have confirmed that by using Longhorn Snapshot with CloudNativePG Snapshot, I can use Longhorn differential Snapshot.

https://cloudnative-pg.io/documentation/1.21/backup_volumesnapshot/
https://longhorn.io/docs/1.5.3/snapshots-and-backups/csi-snapshot-support/csi-volume-snapshot-associated-with-longhorn-snapshot/

This is supplementary information.
Longhorn volumes and snapshots look like this on the OS.(Save in /var/lib/longhorn on each node by default)
Snapshots have differential information, and these files are sparse files, only the capacity actually used is consumed.

```
## The img file is a sparse file. It reserved 5GB.

# ls -l
total 313988
-rw------- 1 root root       4096 Feb  1 10:16 revision.counter
-rw-r--r-- 1 root root 5368709120 Feb  1 10:16 volume-head-002.img
-rw-r--r-- 1 root root        187 Feb  1 10:15 volume-head-002.img.meta
-rw-r--r-- 1 root root 5368709120 Feb  1 10:15 volume-snap-snapshot-51d01017-a2d6-425b-a43c-e71275928771.img
-rw-r--r-- 1 root root        197 Feb  1 10:15 volume-snap-snapshot-51d01017-a2d6-425b-a43c-e71275928771.img.meta
-rw-r--r-- 1 root root 5368709120 Feb  1 10:13 volume-snap-snapshot-a2668079-ea57-4445-9d2b-a28d5427fd39.img
-rw-r--r-- 1 root root        136 Feb  1 10:13 volume-snap-snapshot-a2668079-ea57-4445-9d2b-a28d5427fd39.img.meta
-rw-r--r-- 1 root root        203 Feb  1 10:15 volume.meta

## check the actual size using the du.
## The actual size used is small and has differential information.

# du -skh *
4.0K    revision.counter
33M     volume-head-002.img
4.0K    volume-head-002.img.meta
50M     volume-snap-snapshot-51d01017-a2d6-425b-a43c-e71275928771.img
4.0K    volume-snap-snapshot-51d01017-a2d6-425b-a43c-e71275928771.img.meta
225M    volume-snap-snapshot-a2668079-ea57-4445-9d2b-a28d5427fd39.img
4.0K    volume-snap-snapshot-a2668079-ea57-4445-9d2b-a28d5427fd39.img.meta
4.0K    volume.meta
```

As you explained in your first reply, if `VolumeSnapshotDelta` is implemented, I think that we can expect to be able to use Differential Snapshot even if the storage class does not support it.

I found that there is already a StorageClass that support differential snapshot, so there is no need to add it to the doc.
This issue has been resolved and will be closed, thank you.
