### ISSUE TITLE
[Feature]: Self-tuning of `archive_mode` and `wal_level` settings

### ISSUE THREAD

**Issue by gbartolini** [cloudnative-pg/cloudnative-pg#3731]
### Is there an existing issue already for this feature request/idea?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new feature request to be evaluated.

### What problem is this feature going to solve? Why should it be added?

Currently, both `archive_mode` and `wal_level` are fixed options for PostgreSQL, namely `on` and `logical`. This heavily impacts performance of Postgres in cases where backup is not yet configured and so replication - typical use case is bulk loading in initial import.

### Describe the solution you'd like

We should be able to automatically control the settings of both options, as follows.

`archive_mode` can be set to `off` if no WAL archive is set, which currently means no `barmanObjectStore` is defined. In the future, it might also mean that no WAL archive plugin for the new CNPG-I is defined (in case CNPG-I progresses).

`wal_level` is set to:

- `logical` when `instances` > 1, otherwise
- `replica` if `archive_mode` is `on`, otherwise
- `minimal`

This heuristic will improve the default behavior and out of the box improve the performance of database imports done on a single instance cluster without WAL archive.

A change in any of the two settings will first require a restart of the instance.

### Describe alternatives you've considered

The alternative is to leave users the possibility to self-configure this option. However, the risks are still bigger than the benefits. We can always revisit this when the adoption keeps increasing along Postgres skills.

### Additional context

N/A

### Backport?

Yes

### Are you willing to actively contribute to this feature?

Yes

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gbartolini** [comment]
I think that during an initdb bootstrap with import, we should temporarily disable archive_mode and set wal_level to minimal, in order to reduce the risk of running out of disk - which is what's happening now given that we do not set the archive_command anyway until the import phase is finished, resulting in these log messages:

```
archive_mode enabled, yet archive_command is not set
```

In this case, WAL files keep accumulating during the import job, potentially leading to these issues:

```
could not write to file \"pg_wal/xlogtemp.XXXXXX\": No space left on device
```

Given that replicas, where present, will be bootstrapped after the job is completed, it is safer to resume WAL archiving when the server starts.

**Comment by gbartolini** [comment]
I would change the heuristic then as follows:

```
`archive_mode` can be set to `off` when:

- no WAL archive is set, which currently means no `barmanObjectStore` is defined - In the future, it might also mean that no WAL archive plugin for the new CNPG-I is defined (in case CNPG-I progresses)
- running an initdb bootstrap with an `import` phase

`wal_level` is set to:

- `minimal` for the duration of an import bootstrap
- `logical` when `instances` > 1, otherwise
- `replica` if `archive_mode` is `on`, otherwise
- `minimal`
```

Any thoughts?

**Comment by gbartolini** [comment]
In terms of `wal_level`, the heuristic should provide the minimum required level by the operator to function. This way, we could enable users to configure their desidered `wal_level` and allow it only if it is higher or equal than then required one. For example, if the heuristic returns `minimal`, a user could decide to set it to `replica`  (because they plan to use replica clusters) or `logical` (because they plan to use it for logical replication publications).

On the other hand, it the required valued is `logical` we should forbid lower settings such as `replica` or `minimal`.

**Comment by fcanovai** [comment]
Enforcing `replica` or `minimal` when `instances` = 1 could break workloads (users with logical replication from a single instance). Additionally, if `archive_mode` is `on`, `replica` should be enough as the minimum, unless the user plans to use logical replication.

We currently have `logical` as the only possible value, and changing this could break existing user workloads. We could keep `logical` as the default and allow lower values.

I cannot see anything wrong in enforcing `minimal` during an import bootstrap.

**Comment by gbartolini** [comment]
I am updating the proposal for `wal_level` configuration.

As per [Postgres documentation](https://www.postgresql.org/docs/current/runtime-config-wal.html), `wal_level` can assume any of these values in ascending order:

- `minimal` (for crash recovery)
- `replica` (for WAL archiving and for replication)
- `logical` (for logical replication - currently the fixed value in CloudNativePG)

Let `.spec.postgresql.parameters.wal_level` be the requested value from the user, by default unset.

Let `minimum_wal_level` be the one automatically determined by the operator through the following heuristic:

- `minimal` for the duration of an import bootstrap
- `replica` when `instances` > 1 or `archive_mode` is `on`, otherwise
- `minimal`

If `.spec.postgresql.parameters.wal_level` is set, we always use that in case it is >= than `minimum_wal_level`, otherwise we block it at validation level with the webhoook).

If `.spec.postgresql.parameters.wal_level`, we should set it to `minimum_wal_level`. This will introduce the breaking change with existing users who might really need `logical` replication, opening two possible ways:

- Make the change now and encourage users to change their configuration in case they need logical replication
- Restore `logical` when `instances > 1` for the currently supported minor versions, and make the change from a future minor version, leaving some time to prepare

Does it resonate WITH YOU @fcanovai ?

**Comment by fcanovai** [comment]
There are a few implications. Activating `archive_mode` or going from a single instance to multiple ones will cause a server restart, if not already set at a level above `minimal`. I don't expect such an instance to be a mission-critical one, but it should be documented.

> * Make the change now and encourage users to change their configuration in case they need logical replication
> * When minimum_wal_level = replica (and instances > 1?), restore logical for the currently supported minor versions, and make the change from a future minor version, leaving some time to prepare

I'd avoid breaking a configuration. This set of rules however is starting to be too complex. E.g.: it is breaking the (unlikely?) case where someone has a single instance without backup (`minimum_wal_level=minimal`) with logical replication, requiring `logical` (which currently requires nothing). I'd keep `logical` by default unless the user decides otherwise, with the exclusion of the import (`minimal`). When the import is over, switch back to `logical`.

**Comment by gbartolini** [comment]
Obviously, we need to document the required restarts.

However, I don't understand your final proposal. IIUC, we should still calculate the minimum required value and use that while checking what the user provides. And by default, if not specified, set wal level to logical. Am I interpreting it right?

**Comment by gbartolini** [comment]
That makes sense to me. Thanks Francesco.

**Comment by gbartolini** [comment]
I have separated the management of the import bootstrap with ticket #3741

**Comment by gbartolini** [comment]
The `wal_level` configuration is now part of another ticket. This ticket should only cover self-tuning of `archive_mode`.

**Comment by gbartolini** [comment]
Given that two downstream tickets have been created (#3774 and #3746), we can close this ticket.
