### ISSUE TITLE
[Feature]: Privide a condition for the resuming cluster from hibernation 

### ISSUE THREAD

**Issue by litaocdl** [cloudnative-pg/cloudnative-pg#3751]
### Is there an existing issue already for this bug?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [X] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [X] I have read the troubleshooting guide and I think this is a new bug.

### Version

1.22.0

### What version of Kubernetes are you using?

1.28

### What is your Kubernetes environment?

Self-managed: kind (evaluation)

### How did you install the operator?

YAML manifest

### What happened?

Cluster in resuming is in healthy phase, and there is no condition to show it is resuming either. the hibernate condition `cnpg.io/hibernation` is removed at the first place when hibernate annotation is removed. this task defer the removing of hibernating condtion, introduce the `HibernationConditionReasonResumingPods` reason for hibernate condition. once all pods are resumed, then remove the hibernate condtion.  

### Cluster resource

```shell
N/A
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mnencia** [comment]
After some discussions with @gabriele-wolfox and @litaocdl, we agreed that the operator should not try to be more specific about the "resuming" state of the Cluster because, from the operator's point of view, it is indistinguishable from its normal operations.
