### ISSUE TITLE
[Docs]: connection pooling authentication is incomplete

### ISSUE THREAD

**Issue by vixns** [cloudnative-pg/cloudnative-pg#3771]
### Is there an existing issue already for your request/idea?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new documentation enhancement to be evaluated.

### What problem in the existing documentation this issue aims to solve?

https://cloudnative-pg.io/documentation/1.22/connection_pooling/#authentication explain how to manually integrate the pooler.

following this documentation on a new database does not work, the pooler can authenticate on the database created by cnpg, not the other.

### Describe what additions need to be done to the documentation

Precise the function `user_search` **must** be owned by the admin user, usually `postgres`
Explain a way to create this function from an admin user session.

I was able to create this function with the right owner by connecting to the master instance using psql from the shell (connecting using the admin user is denied from the network), changing database with `\c databasename`, and then creating the function as explained in the documentation.

### Describe what pages need to change in the documentation, if any

https://cloudnative-pg.io/documentation/1.22/connection_pooling/#authentication

### Backport?

Yes

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gbartolini** [comment]
Thanks, patch provided.

**Comment by ianstanton** [comment]
Thanks for addressing this! @chuckhend, @nhudson and I ran into this yesterday.
