### ISSUE TITLE
[Feature]: `grafana` dashboard available behind a versioned URL for user not using `helm` chart

### ISSUE THREAD

**Issue by davinkevin** [cloudnative-pg/cloudnative-pg#3780]
### Is there an existing issue already for this feature request/idea?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new feature request to be evaluated.

### What problem is this feature going to solve? Why should it be added?

After migration of the [Grafana dashboard to the chart](https://github.com/cloudnative-pg/cloudnative-pg/issues/3765), it's not possible anymore to download the dashboard using `curl` for a specific version

```
$ curl -qsL https://raw.githubusercontent.com/cloudnative-pg/cloudnative-pg/${VERSION}/docs/src/samples/monitoring/grafana-dashboard.json
```

It's something required if you don't base your installation on the chart, [like I do](https://gitlab.com/davinkevin.fr/home-server/blob/349933383010baa0b33da03d6cb9b23e6ca8b0db/cnpg-system/Taskfile.yaml#L10-17).

### Describe the solution you'd like

Because it's now part of the chart, a solution could be to `git tag` the chart with the `cnpg` version associated, so we can use the previous `curl` call, with just a different url. 

If not possible, with a bit of duplication, a `kustomize` module could be provided for the `monitoring` feature and stored/versioned in the `cnpg` repository. This would match exactly the expectation of user of the `cnpg.yaml` file provided. 

See the one I've created fyi: https://gitlab.com/davinkevin.fr/home-server/-/tree/cfc0f4786d719251deff493a02c310f2e28015e2/cnpg-system/base/components/monitoring

### Describe alternatives you've considered

Because the chart repository doesn't have tag based on `cnpg`, I can't say if the dashboard I download is the one for my instance 🤷… and I have no other alternatives. 

### Backport?

N/A

### Are you willing to actively contribute to this feature?

No

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itay-grudev** [comment]
Is there a reason why you would need a specific version of the chart as it is very much backwards compatible.

**Comment by davinkevin** [comment]
"very much backward compatible", is it enough for prod use case?

If you assure it is backward compatible, yeah it's useless. But I know it's very complicated to do so. Having a versioned one could be simpler for you and your users

**Comment by gbartolini** [comment]
The Grafana dashboard so far has been provided as a sample in the documentation, and never officially supported. As the project grows, we're trying to elevate that, possibly with a separate project within the CloudNativePG organization. Would you be interested in helping?

**Comment by davinkevin** [comment]
Helping on this *yes*, but it really depends how much effort. I'm mainly a consumer of the `grafana` dashboard, nothing else. 

The dashboard you just delivered in the Grafana system is, to me, the best solution because it's automatically versionned: https://grafana.com/grafana/dashboards/20417-cloudnativepg/?tab=revisions

**Comment by sxd** [comment]
The dashboard is now being managed here https://github.com/cloudnative-pg/grafana-dashboards please refer to there for anything related to the dashboard
