### ISSUE TITLE
[Docs]: grafana file missing from the docs 

### ISSUE THREAD

**Issue by AllardKrings** [cloudnative-pg/cloudnative-pg#3781]
### Is there an existing issue already for your request/idea?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new documentation enhancement to be evaluated.

### What problem in the existing documentation this issue aims to solve?

in the official cnpg documentation there is a chapter about grafana / prometheus.

in the chapter Quickstart

[](https://cloudnative-pg.io/documentation/1.16/quickstart/#part-4-monitor-clusters-with-prometheus-and-grafana)

 it says 

kubectl apply -f \
  https://raw.githubusercontent.com/cloudnative-pg/cloudnative-pg/main/docs/src/samples/monitoring/cnpg-prometheusrule.yaml

and 

kubectl apply -f \
  https://raw.githubusercontent.com/cloudnative-pg/cloudnative-pg/main/docs/src/samples/monitoring/grafana-configmap.yaml

the mentioned files are missing from github.

### Describe what additions need to be done to the documentation

either adust the documentation or add the files

### Describe what pages need to change in the documentation, if any

see above

### Backport?

Yes

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by phisco** [comment]
Could you provide links to the docs page mentioning those links?

**Comment by AllardKrings** [comment]
https://cloudnative-pg.io/documentation/1.16/quickstart/#part-4-monitor-clusters-with-prometheus-and-grafana

**Comment by AllardKrings** [comment]
i kow its an old version, my mistake!

**Comment by gbartolini** [comment]
Please refer to https://cloudnative-pg.io/documentation/current/quickstart/#grafana-dashboard
