### ISSUE TITLE
[Bug]: e2e-matrix-generator.py fails when running alone

### ISSUE THREAD

**Issue by sxd** [cloudnative-pg/cloudnative-pg#3784]
### Is there an existing issue already for this bug?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [X] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [X] I have read the troubleshooting guide and I think this is a new bug.

### Version

1.22.0

### What version of Kubernetes are you using?

1.28

### What is your Kubernetes environment?

Self-managed: kind (evaluation)

### How did you install the operator?

YAML manifest

### What happened?

When running the e2e-matrix-generator.py we get this:
```
python3 e2e-matrix-generator.py 
Traceback (most recent call last):
  File "/home/zeus/src/cloudnative-pg/.github/e2e-matrix-generator.py", line 86, in <module>
    with open(E2E_TEST_TIMEOUT) as json_file:
         ^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '.github/e2e_test_timeout.json'
```
We should at least fix this error and have a proper output and the timeout shouldn't be required at all

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mnencia** [comment]
Your issue is that you needed to run it from the repo's root. It could be helpful to make it resilient to run from any directory and check that the environment is set correctly at the start instead of throwing a random error during the execution.
