### ISSUE TITLE
[Feature]: Add `shutdownCheckpointToken` in the status after fencing/hibernating

### ISSUE THREAD

**Issue by gbartolini** [cloudnative-pg/cloudnative-pg#3790]
### Is there an existing issue already for this feature request/idea?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new feature request to be evaluated.

### What problem is this feature going to solve? Why should it be added?

When fencing or hibernating a Postgres cluster, it would be handy to add in the status a token containing information about write-ahead logging and checkpoint processing.

### Describe the solution you'd like

We should add a new field in the status called `shutdownCheckpointToken` that is normally empty.

Following a fencing operation (and consequently hibernation too), `shutdownCheckpointToken` is an encoded string containing the following information from `pg_controldata`:

- Database system identifier
- Latest checkpoint's TimeLineID
- Latest checkpoint's REDO location
- Latest checkpoint's REDO WAL file
- Time of latest checkpoint

The above values must be taken when the `Database cluster state` is `shut down`.

### Describe alternatives you've considered

N/A

### Additional context

N/A

### Backport?

Yes

### Are you willing to actively contribute to this feature?

Yes

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mnencia** [comment]
Given that the content of the token is only taken when the state is shut down, we could name it `shutdownToken`.

**Comment by gbartolini** [comment]
Ok with `shutdownToken` or `shutdownCheckpointToken`.

**Comment by mnencia** [comment]
I like the latter. :+1: for `shutdownCheckpointToken`

**Comment by gbartolini** [comment]
We should also make sure that this is set as part of #3796

**Comment by gbartolini** [comment]
Given that all the features related to switchover to a replica cluster are landing at the same time on version 1.24.0, it is IMHO unnecessary to introduce a gradual introduction of the feature that involves both fencing and hibernation. We should just update the status when demotion is requested. Thoughts @leonardoce @armru @fcanovai?

**Comment by leonardoce** [comment]
Yes, I agree. This would lead to a more maintainable implementation.

It will be less confusing to use: there would be just one way to do a DC switchover. And one E2E scenario will be enough to exercise the workflow.

**Comment by gbartolini** [comment]
This ticket has been converted to managing the `demotionToken` and to be triggered only when a primary cluster becomes a replica one.
