### ISSUE TITLE
[Bug]: When using a Google Bucket for WAL storage the spec.backup.retentionPolicy setting has not effect

### ISSUE THREAD

**Issue by chrisalavoinehmm** [cloudnative-pg/cloudnative-pg#3809]
### Is there an existing issue already for this bug?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [X] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [X] I have read the troubleshooting guide and I think this is a new bug.

### Contact Details

chris.alavoine@humanmademachine.com

### Version

1.22.1

### What version of Kubernetes are you using?

1.27

### What is your Kubernetes environment?

Cloud: Google GKE

### How did you install the operator?

YAML manifest

### What happened?

When attempting to use spec.backup.retentionPolicy to limit the amount of days WALs we keep, this setting appears to be ignored by the operator. We are using a standard Google Bucket which works in all other respects for WALs and basebackups.

### Cluster resource

```shell
# dev16s-post.yaml
#
#
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: dev16s
  annotations:
    cnpg.io/coredumpFilter: "0xFF"
spec:
  # Postgres 16 image
  imageName: eu.gcr.io/XXX/postgres:16.1.4
  imagePullPolicy: Always
  enableSuperuserAccess: true
  instances: 3
  primaryUpdateStrategy: unsupervised
  primaryUpdateMethod: restart
  startDelay: 30
  stopDelay: 30

  ephemeralVolumeSource:
    volumeClaimTemplate:
      spec:
        accessModes: ["ReadWriteOnce"]
        # example storageClassName, replace with one existing in your Kubernetes cluster
        storageClassName: "standard-rwo"
        resources:
          requests:
            storage: 200Gi

  affinity:
    tolerations:
    - effect: NoSchedule
      key: dedicated
      operator: Equal
      value: database

  # env variable set to get R working with this image
  env:
  - name: R_HOME
    value: /usr/lib/R
  - name: TMPDIR
    value: /var/lib/postgresql/wal/
  - name: LD_LIBRARY_PATH
    value: "/usr/lib/R/lib:/usr/lib/x86_64-linux-gnu:/usr/lib/jvm/default-java/lib/server:/usr/local/lib"
  - name: R_ENABLE_JIT
    value: "0"

  monitoring:
    enablePodMonitor: true

  postgresql:
    pg_hba:
      - hostssl all all all scram-sha-256
    parameters:
      shared_buffers: "8GB"
      max_connections: "300"
      work_mem: "32MB"
      maintenance_work_mem: "4GB"
      effective_io_concurrency: "400"
      max_parallel_workers_per_gather: "8"
      max_parallel_maintenance_workers: "8"
      effective_cache_size: "32GB"
      max_parallel_workers: "24"
      wal_buffers: "16MB"
      min_wal_size: "512MB"
      max_wal_size: "4GB"
      checkpoint_completion_target: "0.9"
      random_page_cost: "1.1"
      default_statistics_target: "200"
      autovacuum_max_workers: "10"
      autovacuum_naptime: "10"
      timescaledb.max_background_workers: "114"
      cron.max_running_jobs: "64"
      cron.use_background_workers: "on"

      dynamic_shared_memory_type: sysv
      shared_memory_type: sysv

      max_slot_wal_keep_size: "50GB"


    shared_preload_libraries:
      - 'plr'
      - 'citext'
      - 'quantile'
      - 'pg_trgm'

  storage:
    storageClass: premium-rwo
    size: 450Gi
  walStorage:
    storageClass: premium-rwo
    size: 300Gi

  resources:
    requests:
      memory: "32Gi"
      cpu: "4000m"
    limits:
      memory: "32Gi"
      cpu: "4000m"


  managed:
    roles:
      - name: stolon
        ensure: present
        superuser: true
        createdb: true
        login: true
        passwordSecret:
          name: stolon


  backup:
    volumeSnapshot:
      className: gke-vsc-pd
    barmanObjectStore:
      destinationPath: 'gs://XXX/CNPGdev16s'
      googleCredentials:
        gkeEnvironment: true
      wal:
        compression: snappy
        maxParallel: 2

  serviceAccountTemplate:
    metadata:
      annotations:
        iam.gke.io/gcp-service-account: cloudnative-pg@XXX.iam.gserviceaccount.com
```

### Relevant log output

```shell
n/a
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by BaudouinH** [comment]
Hello @chrisalavoinehmm 
This is due to using Volume Snapshot backups, 
As per the documentation:
> [retention policy is] currently only applicable when using the BarmanObjectStore method.
[CloudNativePG API documentation regarding retention policy](https://cloudnative-pg.io/documentation/1.22/cloudnative-pg.v1/#postgresql-cnpg-io-v1-BackupConfiguration)

My team use lifecycle policies on the bucket to remove old WAL instead.


The same issue will arise with the backups themselves: Old volumesnapshot backups are also not garbage-collected despite the retention policy.


You can find more details on a related GitHub issue I opened: https://github.com/cloudnative-pg/cloudnative-pg/issues/3657

**Comment by chrisalavoinehmm** [comment]
I tried to set Lifecycle on my bucket and it completely broke the WAL shipping. How many days did you set your Lifecycle to?

**Comment by BaudouinH** [comment]
> I tried to set Lifecycle on my bucket and it completely broke the WAL shipping. How many days did you set your Lifecycle to?

We set it to the retention policy we want + 1 day (just in case), so it is deleted afterward. 
I do not understand why the WAL shipping would be broken by setting a lifecycle rule on the bucket storing only the WAL

**Comment by chrisalavoinehmm** [comment]
Me neither, but the fact remains that the spec.backup.retentionPolicy does not work as expected when using Google Buckets.

**Comment by BaudouinH** [comment]
> Me neither, but the fact remains that the spec.backup.retentionPolicy does not work as expected when using Google Buckets.

I think it is unrelated to using Google buckets, it is because you are using volume snapshots : my understanding is that in that situation barman will never do backups on the bucket so it will never compute the backups and wal archives that can be garbage collected with regard to the retention policy, and will never delete them.
So the same issue would arise with S3 for example (or a Google bucket using the S3 API) 

The fact that the retention policy does not work with Volume snapshots is however only present in the API's documentation, not the rest of the documentation

**Comment by gbartolini** [comment]
@BaudouinH is right. We can only delete WAL files when we delete a backup, and we delegate the operation to Barman Cloud for that (so there's little that can be done in CloudNativePG - that is why we are working on the CloudNativePG Interface - CNPG-I).

When we delete a backup, we request Barman Cloud to remove the WAL files prior to the first available backup.
