### ISSUE TITLE
[Bug]: Deleting all the pods in sequence may break the cluster

### ISSUE THREAD

**Issue by mnencia** [cloudnative-pg/cloudnative-pg#3810]
### Is there an existing issue already for this bug?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [X] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [X] I have read the troubleshooting guide and I think this is a new bug.

### Version

trunk (main)

### What version of Kubernetes are you using?

1.28

### What is your Kubernetes environment?

Self-managed: kind (evaluation)

### How did you install the operator?

YAML manifest

### What happened?

If you delete all the pods in sequence, the cluster ends up in a state that cannot be recovered automatically.

Steps to reproduce (in the root of the cloudnative-pg repository):

```
kubectl apply -f docs/src/samples/cluster-example.yaml
kubectl wait --for=condition=Ready --timeout 600s cluster/cluster-example 
for instance in $(kubectl get pod -l 'cnpg.io/cluster=cluster-example' -o name); do kubectl delete $instance; done
```

The result is a cluster running only one pod (cluster-example-1) that will never become ready because it's a former primary.

```
$ $ kubectl get cluster cluster-example 
NAME              AGE     INSTANCES   READY   STATUS                                       PRIMARY
cluster-example   3m26s   3                   Waiting for the instances to become active   cluster-example-2

$ kubectl get pod -l 'cnpg.io/cluster=cluster-example' 
NAME                READY   STATUS    RESTARTS   AGE
cluster-example-1   0/1     Running   0          38s
```

The PVC labels are the following:

```
$  kubectl get pvc -Lcnpg.io/instanceRole
NAME                STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE     INSTANCEROLE
cluster-example-1   Bound    pvc-70c2165f-4863-46b4-8a95-0bf8419fe90c   1Gi        RWO            standard       6m22s   primary
cluster-example-2   Bound    pvc-46545430-6114-4f57-83c4-2fcf47f816d6   1Gi        RWO            standard       5m57s   replica
cluster-example-3   Bound    pvc-b3e0d4ab-fba0-4bdd-a9bf-1ae126b37c4a   1Gi        RWO            standard       5m30s   replica

```

This highlights a mismatch between the status written in the cluster (the primary is `cluster-example-2`) and in the PVC labels (the primary is `cluster-example-1`).

Running the reproduced several times, you could also end up in a state where the primary in the cluster is `cluster-example-3` and the PVC labels show two primaries (`cluster-example-1` and `cluster-example-2`)

```
$ kubectl get pvc -Lcnpg.io/instanceRole
NAME                STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE     INSTANCEROLE
cluster-example-1   Bound    pvc-c15a8329-f31f-438e-9408-2c8c1d5e8dba   1Gi        RWO            standard       8m14s   primary
cluster-example-2   Bound    pvc-62a8d836-b94d-4dd2-83ef-2f5e9743dd07   1Gi        RWO            standard       7m49s   primary
cluster-example-3   Bound    pvc-b1db4f55-d651-4cad-b854-066fa40acf47   1Gi        RWO            standard       7m23s   replica
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mnencia** [comment]
I believe this is the root cause of #3091

**Comment by mnencia** [comment]
A workaround to recover this error is to make sure that the `cnpg.io/instanceRole` label is correctly set on every PVCs to match what is set in the cluster's `.status.currentPrimary` field.

**Comment by mnencia** [comment]
This scripts is a workaround for the issue:

``` sh
CLUSTER_NAME=cluster-example

PRIMARY=$(kubectl get cluster "$CLUSTER_NAME" -o jsonpath='{.status.currentPrimary}')
for pvc in $(kubectl get pvc -l"cnpg.io.io/cluster=$CLUSTER_NAME" -o name); do 
  ROLE=$([ "$pvc" = "persistentvolumeclaim/$PRIMARY" ] && echo primary || echo replica)
  kubectl label "$pvc" --overwrite "cnpg.io.io/instanceRole=$ROLE" "role=$ROLE"
done
kubectl delete pod -l "cnpg.io.io/cluster=$CLUSTER_NAME"
```

**Comment by ElanHasson** [comment]
Slight correction to the script above to use correct resource type `clusters.postgresql.cnpg.io`.

```bash
CLUSTER_NAME=cluster-example
NAMESPACE=default

PRIMARY=$(kubectl get clusters.postgresql.cnpg.io  -n "$NAMESPACE" "$CLUSTER_NAME" -o jsonpath='{.status.currentPrimary}')
for pvc in $(kubectl get pvc -n "$NAMESPACE" -l"cnpg.io/cluster=$CLUSTER_NAME" -o name); do 
  ROLE=$([ "$pvc" = "persistentvolumeclaim/$PRIMARY" ] && echo primary || echo replica)
  kubectl label -n "$NAMESPACE" "$pvc" --overwrite "cnpg.io/instanceRole=$ROLE" "role=$ROLE"
done
kubectl delete pod -n "$NAMESPACE" -l "cnpg.io/cluster=$CLUSTER_NAME"
```
