### ISSUE TITLE
[Bug]: version 1.18 of the operator is incompatible with 1.20, 1.21, 1.22

### ISSUE THREAD

**Issue by jsilvela** [cloudnative-pg/cloudnative-pg#3821]
### Is there an existing issue already for this bug?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [X] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [X] I have read the troubleshooting guide and I think this is a new bug.

### Version

older minor (unsupported)

### What version of Kubernetes are you using?

1.28

### What is your Kubernetes environment?

Self-managed: kind (evaluation)

### How did you install the operator?

YAML manifest

### What happened?

Running the operator in release 1.18, a field that is present in the cluster manifest is `smartStopDelay`.
If setting a non-default value for that field, the manifest becomes incompatible with the more advanced
minor releases, which use `smartShutdownTimeout` instead.

### Cluster resource

```shell
kind: Cluster
metadata:
  name: cluster-example
spec:
  instances: 4

  smartStopDelay: 200
  storage:
    size: 1Gi
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gbartolini** [comment]
@jsilvela Why do we want to back-port this to 1.18 (which was last updated 8 months ago)? See https://github.com/cloudnative-pg/cloudnative-pg/tree/release-1.18

**Comment by jsilvela** [comment]
@gbartolini I think this issue should be closed. The incompatibility with 1.18 did not happen in this project. Apologies.

**Comment by jsilvela** [comment]
Just going to make sure the code doesn't get deleted yet.
As soon as that's done I will close the PR and the issue.
