### ISSUE TITLE
[Feature]: Build ARM64 images for variant v8

### ISSUE THREAD

**Issue by sxd** [cloudnative-pg/cloudnative-pg#3825]
### Is there an existing issue already for this feature request/idea?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new feature request to be evaluated.

### What problem is this feature going to solve? Why should it be added?

Build ARM64 images for variant v8

### Describe the solution you'd like

Build ARM64 images for variant v8

### Describe alternatives you've considered

Build ARM64 images for variant v8

### Backport?

Yes

### Are you willing to actively contribute to this feature?

Yes

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by harryzcy** [comment]
Doesn't `linux/arm64` refer to `v8` variant by default? `v8` is the first variant to support 64 bit instructions
