### ISSUE TITLE
Release script isn't updating the documentation with the current branch

### ISSUE THREAD

**Issue by leonardoce** [cloudnative-pg/cloudnative-pg#383]
The `hack/release.sh` script isn't updating the URL of the operator manifest inside the documentation with the branch where the releases is being created.
This will result in a broken manifest URL because it's pointing to the `main` branch instead of to the correct branch.

**Comment by litaocdl** [comment]
replace operator manifest version url word `main` or `release-xxx` to current branch name in release script
