### ISSUE TITLE
[Feature]: Multi-arch in-place update through instance manager injection for multiple architectures

### ISSUE THREAD

**Issue by NiccoloFei** [cloudnative-pg/cloudnative-pg#3868]
### Is there an existing issue already for this feature request/idea?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new feature request to be evaluated.

### What problem is this feature going to solve? Why should it be added?

Currently, the [In-place update of the instance manager](https://cloudnative-pg.io/documentation/1.22/installation_upgrade/#in-place-updates-of-the-instance-manager) requires all pods (operators and operands) to run on the same architecture, meaning that this feature doesn't yet support hybrid/mixed architectures Clusters (e.g running a given Cluster pods on either amd64 or arm64 nodes).

At present, the operator contains a [validation check](https://github.com/cloudnative-pg/cloudnative-pg/blob/d03e164ea33f7b5c7c6414fb3e89e6dc9379636d/controllers/cluster_controller.go#L619) preventing in-place updates in a cluster containing mixed architectures.
 

### Describe the solution you'd like

Starting with [4ee639f](https://github.com/cloudnative-pg/cloudnative-pg/commit/4ee639f0393f17ff8c6f635f3f31970cffd54f45): we've enhanced our multi-arch images to store the binary of each supported architecture in every architecture image.

Following up with [87e6591](https://github.com/cloudnative-pg/cloudnative-pg/commit/87e659136c4234b2ef642cb5cd7e12fb1f045e76): we've added in the operator a catalog of all the available architectures contained in the running operator image, together with a new Cluster status field named `AvailableArchitectures` which lists all the architectures available for a target Cluster (each paired with their unique hash).

This patch aims to start using the matching architecture's binary during in-place updates, enabling the operator to inject the correct binary in any Pod having a supported architecture.
The check preventing in-place updates in a cluster containing mixed architectures will be also relaxed.

### Describe alternatives you've considered

Not provided.

### Backport?

Yes

### Are you willing to actively contribute to this feature?

Yes

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mmeier86** [comment]
One proposal which is related to this, I believe: Can we make the warning that's currently shown in the logs a bit clearer? I've just set up my first cluster on a mixed ARM64/AMD64 k8s cluster and got this warning:

```json
{"level":"info","ts":"2024-02-24T11:09:50Z",
"msg":"Warning: mismatch architecture between controller and instances. This is an unsupported configuration.",
"controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"keycloak-pg-cluster","namespace":"testsetup"},"namespace":"testsetup","name":"keycloak-pg-cluster","reconcileID":"e4cf6ddc-b4a2-435c-8846-65c8a33ae77b","uuid":"3aa05ab2-d305-11ee-b17a-3a3f9a721d3b","controllerArch":"amd64","instanceArch":"arm64","pod":"keycloak-pg-cluster-2"}
```
This made me think that mixed architectures are not supported in general, but if I'm reading this issue correctly, it's only related to in-place updates of the instance manager, and otherwise mixed-arch clusters are fine?

I think it would be good to only show this warning when there is a mix of architectures _and_ in-place updates are actually enabled.

**Comment by NiccoloFei** [comment]
@mmeier86 Absolutely! Btw that warning is generated by the same check I've mentioned earlier, and right now it's only being used to validate if an instance manager online update (e.g in-place) would be possible.
So I agree it probably shouldn't be emitted in case a user didn't enable in-place updates of the instance manager.

>This made me think that mixed architectures are not supported in general, but if I'm reading this issue correctly, it's only related to in-place updates of the instance manager, and otherwise mixed-arch clusters are fine?

That's correct, mixed architectures clusters should be working properly provided that you are using the default rolling update method to upgrade the operator. Given that each pod is terminated and recreated in a rolling update fashion, the new version of the instance manager will be downloaded by the `bootstrap-controller` initContainer of each pod. 
I guess what's missing is that this kind of setup is not currently documented, nor we are explicitly mentioning in the doc if this is a supported scenario. So we should clarify that..

**Comment by giovannicandido** [comment]
> @mmeier86 Absolutely! Btw that warning is generated by the same check I've mentioned earlier, and right now it's only being used to validate if an instance manager online update (e.g in-place) would be possible. So I agree it probably shouldn't be emitted in case a user didn't enable in-place updates of the instance manager.
> 
> > This made me think that mixed architectures are not supported in general, but if I'm reading this issue correctly, it's only related to in-place updates of the instance manager, and otherwise mixed-arch clusters are fine?
> 
> That's correct, mixed architectures clusters should be working properly provided that you are using the default rolling update method to upgrade the operator. Given that each pod is terminated and recreated in a rolling update fashion, the new version of the instance manager will be downloaded by the `bootstrap-controller` initContainer of each pod. I guess what's missing is that this kind of setup is not currently documented, nor it's explicitly being mentioned in the doc if this is a supported scenario. So yeah that should be clarified..

Amazing, I'm mixing x86_64 and ARM for cost reduction in the entire cluster. Is good to know that effort is made to support this. I think this is the only Postgresql operator that does support this scenario. I'm using node affinity to separeae workloads, but I will test remove this restriction in HA postgresql. ❤️
