### ISSUE TITLE
Helm chart link broken

### ISSUE THREAD

**Issue by mysticaltech** [cloudnative-pg/cloudnative-pg#39]
Hey folks, amazing work! The helm chart link here https://cloudnative-pg.io/docs/1.15.0/installation_upgrade/#using-the-helm-chart, which is https://github.com/cloudnative-pg/cloudnative-pg-helm, leads to a 404!

Also, it would be great to have that info in the main readme, IMHO.

**Comment by gbartolini** [comment]
Hello! Thanks for your suggestion. We are actually going to move the Helm chart project from EnterpriseDB to the CloudNativePG organization in the next days/weeks. We have created a new project for that: https://github.com/cloudnative-pg/charts.

Do you think it is OK for you to close this ticket given that the activity will be tracked cloudnative-pg/charts#1?

**Comment by mysticaltech** [comment]
Thanks! :) And don't forget to fix the broken link!
