### ISSUE TITLE
Monolith database import is requiring a TLS connection

### ISSUE THREAD

**Issue by leonardoce** [cloudnative-pg/cloudnative-pg#392]
We're currently requiring a TLS connection between the CNP cluster to be created and the PostgreSQL instance we're downloading data from but just from the **monilith** import approach, but we don't to that for the **microservice** approach.

The reason behind this is that the microservice approach is going to create a connection from the instance manager to the source PostgreSQL instance using **lib/pq** which is by setting `sslmode` to `required` by default.
Unfortunately TLS is not commonly configured for development databases; see [this article](https://errorsingo.com/github.com-lib-pq-err-ssl-not-supported/) for more information.

We should check whether it's best to document this behavior or change our implementation to make the monolith and the microservice approach have the same requirements.

**Comment by gbartolini** [comment]
I think this is more a bug.

**Comment by gbartolini** [comment]
I am removing the commit from the trunk and pushforcing main to remove the above commit from the history given that it was the last commit. We have decided that it makes more sense to work on replacing libpq with pgx and keep the 'prefer' sslmode. In the meantime we just document monolith.
