### ISSUE TITLE
Add DCO action

### ISSUE THREAD

**Issue by gbartolini** [cloudnative-pg/cloudnative-pg#40]
Our [contributing guidelines](../blob/main/contribute/README.md) require contributors to sign their work and provide Developer Certificate of Origin (DCO). Please add a Github action that enforces this with any pull request (example: https://github.com/marketplace/actions/actions-dco)

**Comment by sxd** [comment]
This was handled adding https://github.com/apps/dco app that it's based on protobot to handle the DCO in the entire organization.
