### ISSUE TITLE
[Feature]: Display PDB in `cnpg status`

### ISSUE THREAD

**Issue by gbartolini** [cloudnative-pg/cloudnative-pg#4019]
### Is there an existing issue already for this feature request/idea?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new feature request to be evaluated.

### What problem is this feature going to solve? Why should it be added?

We don't show if PodDisruptionBudgets are present in a cluster.

### Describe the solution you'd like

Following the introduction of configurable pod disruption budgets (#3837), we should easily show in the `cnpg status` command. Ideally, we should check if the cluster has any PDB objects associated to it, instead of relying on the new `enablePDB` option.

### Describe alternatives you've considered

N/A

### Backport?

No

### Are you willing to actively contribute to this feature?

Yes

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by zekiyeaydemir** [comment]
Hi Team, I am working on this
