### ISSUE TITLE
[Bug]: shellquote.Split prevents creating postgresql functions in initdb

### ISSUE THREAD

**Issue by rewemkris** [cloudnative-pg/cloudnative-pg#4042]
### Is there an existing issue already for this bug?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [X] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [X] I have read the troubleshooting guide and I think this is a new bug.

### Contact Details

m.kristo@rewe-group.at

### Version

1.22.1

### What version of Kubernetes are you using?

1.28

### What is your Kubernetes environment?

Cloud: Google GKE

### How did you install the operator?

Helm

### What happened?

I created in postInitTemplateSql a plpgsql function.

`postInitTemplateSQL:
          - |
            CREATE OR REPLACE FUNCTION set_default_privileges() RETURNS event_trigger AS $$
              DECLARE
                  db_owner TEXT;
                  last_schema_name TEXT;
              BEGIN
              ...
              END;
              $$ LANGUAGE plpgsql; (edited) `

 During creation of the Pod it gets into error state, because of an error.

The problem is the operator complains about the $$ in the plpgsql funciton, as the operator uses shellquote.Split function to clean up the postInit stuff.
Function documentation:
`Split splits a string according to /bin/sh's word-splitting rules. It supports backslash-escapes, single-quotes, and double-quotes. Notably it does not support the $" style of quoting.`

### Relevant log output

```shell
`initdb","error":"while configuring new instance: could not execute init Template queries: ERROR: syntax error at or near \"$\" (SQLSTATE 42601)","stacktrace":"[github.com/cloudnative-pg/cloudnative-pg/pkg/management/log.(*logger).Error](http://github.com/cloudnative-pg/cloudnative-pg/pkg/management/log.(*logger).Error)\n\tpkg/management/log/log.go:128\[ngithub.com/cloudnative-pg/cloudnative-pg/pkg/management/log.Error](http://ngithub.com/cloudnative-pg/cloudnative-pg/pkg/management/log.Error)\n\tpkg/management/log/log.go:166\[ngithub.com/cloudnative-pg/cloudnative-pg/internal/cmd/manager/instance/initdb.initSubCommand](http://ngithub.com/cloudnative-pg/cloudnative-pg/internal/cmd/manager/instance/initdb.initSubCommand)\n\tinternal/cmd/manager/instance/initdb/cmd.go:151\[ngithub.com/cloudnative-pg/cloudnative-pg/internal/cmd/manager/instance/initdb.NewCmd.func2](http://ngithub.com/cloudnative-pg/cloudnative-pg/internal/cmd/manager/instance/initdb.NewCmd.func2)\n\tinternal/cmd/manager/instance/initdb/cmd.go:104\[ngithub.com/spf13/cobra.(*Command).execute](http://ngithub.com/spf13/cobra.(*Command).execute)\n\tpkg/mod/github.com/spf13/cobra@v1.8.0/command.go:983\[ngithub.com/spf13/cobra.(*Command).ExecuteC](http://ngithub.com/spf13/cobra.(*Command).ExecuteC)\n\tpkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115\[ngithub.com/spf13/cobra.(*Command).Execute](http://ngithub.com/spf13/cobra.(*Command).Execute)\n\tpkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039\nmain.main\n\tcmd/manager/main.go:64\nruntime.main\n\t/opt/hostedtoolcache/go/1.21.6/x64/src/runtime/proc.go:267"}
Error: while configuring new instance: could not execute init Template queries: ERROR: syntax error at or near "$" (SQLSTATE 42601)`
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sxd** [comment]
hi @rewemkris 

Why not using "postInitApplicationSQLRefs" for this matter?

Regards,
