### ISSUE TITLE
[Feature]: Generate hostname as service.namespace in postgresql uri/jdbc-uri in credentials secret

### ISSUE THREAD

**Issue by jonaszlasut** [cloudnative-pg/cloudnative-pg#4062]
### Is there an existing issue already for this feature request/idea?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new feature request to be evaluated.

### What problem is this feature going to solve? Why should it be added?

Credentials secret [cluster-name]-app generates `uri` and `jdbc-uri` key-value pairs which contain hostname. This hostname consists only of service name and not service name and namespace.
This creates and issue when using schema management tools like Atlas Operator with connection secret, which can't properly resolve DNS names because of that (it can reside in a different namespace than CNPG Cluster). Temporary solution is to generate another secret with mutated `uri` with added namespace however it's suboptimal.

### Describe the solution you'd like

I'd like CNPG operator to generate host in jdbc-uri/uri in credentials secret in form of svc-name.namespace instead of svc-name.

Example:
jdbc:postgresql://demo-database-rw:5432/demo?password=... -> jdbc:postgresql://demo-database-rw.default:5432/demo?password=...

### Describe alternatives you've considered

Temporary/alternative solution is to generate another secret with mutated `uri` with added namespace however it's suboptimal.

### Backport?

Yes

### Are you willing to actively contribute to this feature?

Yes

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bionaut** [comment]
We're dealing with the same issue when using CNPG with Atlas.
We also use Stackgres that generates a secret with FQDN (namespace included) - Atlas works without issues.
