### ISSUE TITLE
[Docs]: Uncomment instructions for `--server-side`

### ISSUE THREAD

**Issue by gbartolini** [cloudnative-pg/cloudnative-pg#4113]
### Is there an existing issue already for your request/idea?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new documentation enhancement to be evaluated.

### What problem in the existing documentation this issue aims to solve?

We do not explain what to do when updating to 1.22.2 and 1.21.4 due to future Kubernetes 1.29 support.

### Describe what additions need to be done to the documentation

We need to add info about server-side apply of manifests and K8s 1.29 supported in 1.22

### Describe what pages need to change in the documentation, if any

- https://cloudnative-pg.io/documentation/current/installation_upgrade/
- https://cloudnative-pg.io/documentation/current/supported_releases/

### Backport?

Yes

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sxd** [comment]
This was already fixed on #4114
