### ISSUE TITLE
use policyv1 for PodDisruptionBudget for Kubernetes 1.25+

### ISSUE THREAD

**Issue by armru** [cloudnative-pg/cloudnative-pg#413]
In Kubernetes 1.25+ `PodDisruptionBudget` beta1 is getting dropped and this is relevant because we currently use it in our codebase.

To solve this issue we can choose between:
- Create betav1policyv1 if kubernetes versions is 1.19 or 1.20. This perhaps will require introducing in our codebase a Kubernetes version getter and parser just like we do for Postgres.
- Drop the support for 1.19 and 1.20 and update to policyv1  

Feel free to suggest any other option available to us

**Comment by mdallaire** [comment]
Is there any news on this? I just upgraded to 1.25 and now my cnpg-operator is crashing :)
