### ISSUE TITLE
[Feature]: Configurable backup and restore temporary directory

### ISSUE THREAD

**Issue by nick-ivanov-edb** [cloudnative-pg/cloudnative-pg#4137]
### Is there an existing issue already for this feature request/idea?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new feature request to be evaluated.

### What problem is this feature going to solve? Why should it be added?

Currently the temporary directory for both cloud backup and restore are hardcoded, pointing to the worker ephemeral storage (mounted in `/controller`):

https://github.com/cloudnative-pg/cloudnative-pg/blob/0fd98f61e9025124d8b7395f0feecc2f50b56344/pkg/postgres/configuration.go#L190

For non-trivial database sizes this can not only fail the backup if its size exceeds the available space on the worker, but also put the whole worker at risk.

Making the backup and restore directory configurable will allow backing up and restoring large databases without these problems. Ideally, the backup and restore should be performed by a separate job, not the manager itself, which would allow mounting a properly-sized PV just for that job.

### Describe the solution you'd like

Short term:

- Add the temporary path property to the Backup CRD, and let manager use that for the temporary directory.

Long term:

- Re-implement the backup and recovery process as a K8s job, allowing more flexible pod configuration, not needing to permanently allocate workers' ephemeral storage for occasional use by Barman.

### Describe alternatives you've considered

Volume snapshots are an option for large databases, however, often the backup is used to move databases between environments (e.g. from prod to QA etc.) where volume snapshots won't work.

### Backport?

No

### Are you willing to actively contribute to this feature?

Yes

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nachi-netskope** [comment]
We're looking to either mount the /backup dir to a PVC so we can ensure to have enough storage to do a full backup operation, or control the path of the barman command via the TMPDIR variable.

**Comment by nick-ivanov-edb** [comment]
In the spirit of the operator's declarative approach to configuration, I think the implementation might be something like this:

- Add extra properties to `spec.backup.barmanObjectStore` (since this feature is only useful for Barman Cloud backups): `scratchStorageClass` and `scratchSize`
- When these properties are present, the operator would create a additional PVC with the `ReadWriteMany` access, associate it with the Postgres pods, and mount the respective volume at `/controller/backup` to override the default. 

This approach won't require any changes to the Barman Cloud backup implementation, as it will transparently use whatever is mounted at `/controller/backup`.

Using the `ReadWriteMany` mode should be safe as the backup only runs on one node at a time. It won't require creating redundant volumes for each Postgres node and will allow backups to run on the primary or standby, as configured.

**Comment by jdambly** [comment]
this is my first try at this, https://github.com/jdambly/cloudnative-pg/pull/1 

I added a property: `backupStorage` and `size`

**Comment by jdambly** [comment]
@nick-ivanov-edb I made some changes to the patch, I was able to build/test and deploy, both on a local k8s clusters as well as our sandbox cluster

```
(⎈ |iad0-sandbox:postgres)➜  ~ k get pods
NAME                READY   STATUS    RESTARTS   AGE
cluster-example-1   1/1     Running   0          3m23s
cluster-example-2   1/1     Running   0          2m24s
cluster-example-3   1/1     Running   0          44s
(⎈ |iad0-sandbox:postgres)➜  ~ k get pvc
NAME                       STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS               AGE
cluster-example-1          Bound    pvc-25b6ea0b-21cf-4f63-aa08-9fc39f372059   1Gi        RWO            ns-rook-ns-rook-ceph-csi   4m6s
cluster-example-1-backup   Bound    pvc-22d9cefa-ec14-489b-888d-a8fa89256ce8   1Gi        RWO            ns-rook-ns-rook-ceph-csi   4m6s
cluster-example-2          Bound    pvc-b5b9a047-1249-42a9-ad20-0c6099d46c80   1Gi        RWO            ns-rook-ns-rook-ceph-csi   3m2s
cluster-example-2-backup   Bound    pvc-19e2259d-672d-48c1-b18e-0aa737cc9859   1Gi        RWO            ns-rook-ns-rook-ceph-csi   3m2s
cluster-example-3          Bound    pvc-d4f794fc-1eb6-4966-883d-61b21d22c09b   1Gi        RWO            ns-rook-ns-rook-ceph-csi   115s
cluster-example-3-backup   Bound    pvc-02c3b118-88ac-4b85-bcfe-acb7a30ef86a   1Gi        RWO            ns-rook-ns-rook-ceph-csi   115s
(⎈ |iad0-sandbox:postgres)➜  ~
```

with this cluster spec

```
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-example
spec:
  instances: 3

  storage:
    size: 1Gi
  backupStorage:
    size: 1Gi
  resources:
    requests:
      cpu: "4"
      memory: "16Gi"
      hugepages-2Mi: "50Mi"
    limits:
      hugepages-2Mi: "50Mi"
      memory: "16Gi"
      cpu: "4"
```

**Comment by nick-ivanov-edb** [comment]
I think `ephemeralVolumeSource` in the cluster spec should solve this problem:

https://github.com/cloudnative-pg/cloudnative-pg/blob/d401af7964ffbf744af4965ee6dd336f41ed92e5/docs/src/cluster_conf.md?plain=1#L52
