### ISSUE TITLE
refine upgrade e2e test case to use function to create minio

### ISSUE THREAD

**Issue by litaocdl** [cloudnative-pg/cloudnative-pg#417]
Make sure we have a unique place to create minio and control the version, reuse minio utils in upgrade test case to create minio

**Comment by litaocdl** [comment]
Done

**Comment by hh24k** [comment]
LGTM ... for the moment, a few minio env setup YML files (**/upgrademinio-secret.yaml, /upgrade/minio-pvc.yaml, /upgrade/minio-deployment.yaml, /upgrade/minio-service.yaml, /upgrade/minio-client.yaml**) are kept for dev's convenience  to quickly set up minio env. @litaocdl will remove them once he gets the minio setup script ready into the repo.
