### ISSUE TITLE
Default username/password for cluster example

### ISSUE THREAD

**Issue by sigezhao** [cloudnative-pg/cloudnative-pg#4190]
### Is there an existing issue already for your request/idea?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new documentation enhancement to be evaluated.

### What problem in the existing documentation this issue aims to solve?

user the example yaml to build a cluster:
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-example
spec:
  instances: 3

  storage:
    size: 1Gi
I can not find username/password. What is it and How I can custom them

### Describe what additions need to be done to the documentation

tell users the default username/password and teach How to custom them

### Backport?

Yes

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gbartolini** [comment]
This is already documented. See:

- https://cloudnative-pg.io/documentation/current/applications/
- https://cloudnative-pg.io/documentation/current/bootstrap/#bootstrap-an-empty-cluster-initdb

Also, you might find useful this blog article that I wrote: https://gabrielebartolini.it/articles/2024/03/cloudnativepg-recipe-2-inspecting-default-resources-in-a-cloudnativepg-cluster/

I hope this helps.
