### ISSUE TITLE
Allow running E2E test from forked repos

### ISSUE THREAD

**Issue by sxd** [cloudnative-pg/cloudnative-pg#426]
Currently, users are getting a "403 Forbidden" error while running E2E test, even if we allow those test to run, this is due external organization user doesn't have write permissions on the packages.

**Comment by leonardoce** [comment]
PR: #429

**Comment by litaocdl** [comment]
The correct behavior finally I understand is
1.   contributor create a pr from fork repository to cnpg repository
2.  maintainer review the pr and approve to run test. 
3.  maintainer issue `/ready-to-test` command in pr comments to trigger the label `ready-to-test` been added to pr, which then 
will trigger the `pull_request_target` event in continuous-delivery workflow file and run the test.

**Comment by litaocdl** [comment]
add a ref in checkout build meta pass https://github.com/cloudnative-pg/cloudnative-pg/runs/7451048607?check_suite_focus=true

**Comment by litaocdl** [comment]
403 happens for the above ci in build and push action with 403 error

**Comment by litaocdl** [comment]
build container step pass for workflow run in repository , now need make e2e-matrix-generator.py support `pull_request_target`
https://github.com/cloudnative-pg/cloudnative-pg/runs/7495742882?check_suite_focus=true

**Comment by litaocdl** [comment]
finally got e2e run with `push_request_target` event on enpg repository 
https://github.com/cloudnative-pg/cloudnative-pg/actions/runs/2731161502

**Comment by litaocdl** [comment]
Some verify result now:

Success trigger an e2e run in folk repository, which is triggered by workflow_dispatch event.
[continuous-delivery · Tao-TL/cloudnative-pg@fff9ffe](https://github.com/Tao-TL/cloudnative-pg/actions/runs/2736746468) 

In fork pull request,  /test is not permited to trigger e2e by contributer
test: remote branch run e2e test  · cloudnative-pg/cloudnative-pg@3d62df7 

In fork pull request , /test is allowed to run e2e test by maintainer
[continuous-delivery · cloudnative-pg/cloudnative-pg@0bcd903](https://github.com/cloudnative-pg/cloudnative-pg/actions/runs/2737384598) 

In fork pull request, add ready to test label can trigger e2e test run, test workflow is triggered by pull_request_target event.
test: remote branch run e2e test  · cloudnative-pg/cloudnative-pg@f1db2dd
