### ISSUE TITLE
[Feature]: metrics and more logs for barman

### ISSUE THREAD

**Issue by quercus-carsten** [cloudnative-pg/cloudnative-pg#4289]
### Is there an existing issue already for this feature request/idea?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new feature request to be evaluated.

### What problem is this feature going to solve? Why should it be added?

There is no metrics for barman, which can be used for alarming.

I found "cnpg_pg_stat_archiver_*"

but from the numbers these seem to be focused on WAL archiving (continuous backup).

I didn't find any barman related metrics like "time_since_last_barman_backup" , where I could base an alarm on.
This would help to find ScheduledBackups which are stuck in "running" state and pile up. Seems like there is no
timeout for ScheduledBackups I guess.

### Describe the solution you'd like

E. g. metrics like:

cnpg_pg_stat_barman_seconds_since_last_archival
and
cnpg_pg_stat_barman_seconds_since_last_failure

### Describe alternatives you've considered

I already have alarming in elastic based on log entries like "backup failed".

But this solution doesn't cover all cases and also has downsides. Take this particular case: When a new backup job finds the same job already running you can find the log entry: "Backup is already running on". But often backup jobs run nightly, and therefore the first time you get notified about this is during on-call duty. It would be beneficial to check on your backups based on a metric which provides the time of the last successful barman backup since I can check on them based on the time frame I expect them to be finished  - and also last failed barman backup would definitely help.

### Additional context

Right now, I have two clusters, which
have multiple ScheduledBackup jobs in "running" state. Logging shows no errors.
Only "Backup is already running on" is logged.

For one cluster I deleted the "running" jobs and started a backup task manually. This
finished successfully. The following ScheduledBackup was also ok.

(Maybe a timeout is also an option. But I don't have details about whats going wrong so... )

### Backport?

Yes

### Are you willing to actively contribute to this feature?

No

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sxd** [comment]
Hi @quercus-carsten 

This information it's already available here you have the documentation https://cloudnative-pg.io/documentation/current/monitoring/#predefined-set-of-metrics
```
timestamps indicating last failed and last available backup, as well as the first point of recoverability for the cluster
```
Closing now, feel free to reopen if needed

Best regards!
