### ISSUE TITLE
[Bug]: kubectl-cnpg status --> Physical backups progress 

### ISSUE THREAD

**Issue by smiyc** [cloudnative-pg/cloudnative-pg#4323]
### Is there an existing issue already for this bug?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [X] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [X] I have read the troubleshooting guide and I think this is a new bug.

### Contact Details

smiyc@pm.me

### Version

1.22.2

### What version of Kubernetes are you using?

1.26

### What is your Kubernetes environment?

Other

### How did you install the operator?

YAML manifest

### What happened?

The progress in the `Physical backups` section of `kubectl-cnpg status` is not correctly calculated

```
Physical backups
Name             Phase                     Started at                   Total  Transferred  Progress  Tablespaces
----             -----                     ----------                   -----  -----------  --------  -----------
keycloak-2-join  streaming database files  2024-04-17T12:59:48.939639Z  46 GB  38 GB        0.84%     0/1
```

according to https://github.com/cloudnative-pg/cloudnative-pg/commit/2d1c4db3909d62cab4861e627deacd0c564cafb2 the progress is calculated BackupStreamed/BackupTotal
```
		progress := ""
		if bb.BackupTotal != 0 {
			progress = fmt.Sprintf("%.2f%%", float64(bb.BackupStreamed)/float64(bb.BackupTotal))
		}
```
imho it should be 100/BackupTotal*BackupStreamed

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sxd** [comment]
This was already fixed on #4131
