### ISSUE TITLE
[Feature]: allow transition to replica cluster while the cluster is hibernated

### ISSUE THREAD

**Issue by leonardoce** [cloudnative-pg/cloudnative-pg#4352]
### Is there an existing issue already for this feature request/idea?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new feature request to be evaluated.

### What problem is this feature going to solve? Why should it be added?

Following #3796, where we allow the primary cluster to be reconfigured as a replica cluster, we should also allow this for hibernated clusters.

### Describe the solution you'd like

In the latter case, we should avoid starting PostgreSQL immediately as a primary after the cluster has been rehydrated.

### Describe alternatives you've considered

Sticking with the transition while the cluster is up and running, and evaluating putting PostgreSQL in a "replication cycle" to stop the Cluster architecture from receiving write transactions. 

### Additional context

See #3796 for a more in-depth overview of the transitions of replica clusters.

### Backport?

No

### Are you willing to actively contribute to this feature?

Yes

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gbartolini** [comment]
Blocking #4678

**Comment by gbartolini** [comment]
@leonardoce @armru @fcanovai is this still relevant at this point?

**Comment by leonardoce** [comment]
In my opinion it's not relevant anymore. Let's wait for Armando and Francesco opinions too.
