### ISSUE TITLE
[Feature]: Expose additional command args for barman-cloud-wal-archive

### ISSUE THREAD

**Issue by pselliotc** [cloudnative-pg/cloudnative-pg#4357]
### Is there an existing issue already for this feature request/idea?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new feature request to be evaluated.

### What problem is this feature going to solve? Why should it be added?

To allow access to barman-cloud-wal-archive arguments that are not already exposed in the WalBackupConfiguration. In my case I need access to the sse-kms-key-id argument. 

### Describe the solution you'd like

Add an "additionalCommandArgs" field to WalBackupConfiguration, the same as what there is for DataBackupConfiguration.

### Describe alternatives you've considered

n/a

### Backport?

No

### Are you willing to actively contribute to this feature?

Yes

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gabriele-wolfox** [comment]
@pselliotc 
Just a side note here, the new Barman release 3.10.1 adds a new option `--no-partial`  to `barman-cloud-wal-restore`, so that partial WAL files are not downloaded.
See release notes here https://github.com/EnterpriseDB/barman/releases/tag/release/3.10.1.
