### ISSUE TITLE
Imports sorting should be deterministic

### ISSUE THREAD

**Issue by phisco** [cloudnative-pg/cloudnative-pg#438]
We have always been implicitly enforcing a specific sorting for imports, but without the linter actually checking it, many files are adopting different standards.
A [pr](https://github.com/golangci/golangci-lint/pull/2892) was merged and got into the latest relese of golangci-lint, reenabling gci autofix. So I suggest enabling gci as a linter and setting any required configuration.

The implicit standard we have been following I think was (standard libraries, everything else, local packages) separated by a line, but feel free to suggest any other standard we should enforce from now on.

**Comment by mnencia** [comment]
I like the idea. We need to merge #437 before implementing this. Otherwise, it will trigger gosec alerts, as explained in #436.

**Comment by mnencia** [comment]
This issue on `gci` would be good to solve before implementing this enhancement https://github.com/daixiang0/gci/issues/65

**Comment by armru** [comment]
we are waiting for a release that contains https://github.com/daixiang0/gci/pull/88

**Comment by mnencia** [comment]
It is released and available in the latest golangci-lint version 1.147.3
