### ISSUE TITLE
[Bug]: stopBackup should handle disconnects

### ISSUE THREAD

**Issue by csdaraujo** [cloudnative-pg/cloudnative-pg#4444]
### Is there an existing issue already for this bug?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [X] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [X] I have read the troubleshooting guide and I think this is a new bug.

### Contact Details

caetano@heroiclabs.com

### Version

older in 1.22.x

### What version of Kubernetes are you using?

1.29

### What is your Kubernetes environment?

Cloud: Amazon EKS

### How did you install the operator?

YAML manifest

### What happened?

Some backups are kept on `started` state blocking newer backups. One of the causes seems to be that connection is closed within the `backupConnection` struct and there is no re-connecting strategy. Sample log:
```
{
  "level": "error",
  "ts": "2024-05-05T10:44:04Z",
  "msg": "while stopping PostgreSQL physical backup",
  "step": "stop",
  "logging_pod": "mycluster-1",
  "error": "sql: connection is already closed",
  "stacktrace": "github.com/cloudnative-pg/cloudnative-pg/pkg/management/log.(*logger).Error\n\tpkg/management/log/log.go:128\ngithub.com/cloudnative-pg/cloudnative-pg/pkg/management/postgres/webserver.(*backupConnection).stopBackup.func2\n\tpkg/management/postgres/webserver/backup_connection.go:214\ngithub.com/cloudnative-pg/cloudnative-pg/pkg/management/postgres/webserver.(*backupConnection).executeWithLock\n\tpkg/management/postgres/webserver/backup_connection.go:94\ngithub.com/cloudnative-pg/cloudnative-pg/pkg/management/postgres/webserver.(*backupConnection).stopBackup\n\tpkg/management/postgres/webserver/backup_connection.go:212"
}
```

https://github.com/cloudnative-pg/cloudnative-pg/blob/ae692bf86f96467f8ef97eee2ec97e0c1cfb4b5c/pkg/management/postgres/webserver/backup_connection.go#L213

Not sure if my reasoning is right but looks like a reconnect could solve the issue we are facing.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by armru** [comment]
Hello @csdaraujo, sadly, reconnecting wouldn't solve the issue.
The instance manager should allow a new backup to be started, and this is something we think we have fixed.

Is it possible for you to try to replicate the bug using the latest operator version?

**Comment by csdaraujo** [comment]
> Hello @csdaraujo, sadly, reconnecting wouldn't solve the issue. The instance manager should allow a new backup to be started, and we think we have fixed this.
> 
> Can you try to replicate the bug using the latest operator version?
> 
> Thank you very much for your time and report.

Hi, @armru. After leaving the new released version for two weeks I can confirm that there are no more pending/blocking backups so far. Only issue that was identified so far seem related to the issue reported:
```
{"level":"error","ts":"2024-07-01T10:45:34Z","msg":"while stopping PostgreSQL physical backup","step":"stop","logging_pod":"xyz","error":"sql: connection is already closed","stacktrace":"github.com/cloudnative-pg/cloudnative-pg/pkg/management/log.(*logger).Error\n\tpkg/management/log/log.go:128\ngithub.com/cloudnative-pg/cloudnative-pg/pkg/management/postgres/webserver.(*backupConnection).stopBackup.func2\n\tpkg/management/postgres/webserver/backup_connection.go:214\ngithub.com/cloudnative-pg/cloudnative-pg/pkg/management/postgres/webserver.(*backupConnection).executeWithLock\n\tpkg/management/postgres/webserver/backup_connection.go:94\ngithub.com/cloudnative-pg/cloudnative-pg/pkg/management/postgres/webserver.(*backupConnection).stopBackup\n\tpkg/management/postgres/webserver/backup_connection.go:212"}
```

Do you think it is worth keeping this open?

Thank for keeping an eye!

**Comment by csdaraujo** [comment]
Sorry. Forgot to leave the error message on the Backup object status field: `can't execute snapshot backup: trying to stop backup with name: , while reconciling backup with name: xyz-backup-20240701104525"`

**Comment by csdaraujo** [comment]
Yeap. All good! 👏
