### ISSUE TITLE
Convert current/target primary timestamps to Kubernetes Time objects

### ISSUE THREAD

**Issue by gbartolini** [cloudnative-pg/cloudnative-pg#446]
In b603233a2dbda824afbe9c276d74691d1987f6b0 we introduced two fields: `CurrentPrimaryTimestamp` and `TargetPrimaryTimestamp`. They are part of the status, in string format.

We should convert them to the Kubernetes `Time` type, and make sure that they are then displayed with the nanosecond precision (RFC3339Nano).

Clean the code by removing the unnecessary methods that we might have created in the meantime and that can be replaced by the Kubernetes library.

**Comment by armru** [comment]
we will not proceed with this issue with the current release, we will make the switch after we have switched to microtime and some time has passed to avoid disruptive changes
