### ISSUE TITLE
[Feature]: Graceful handling of WAL disk space exhaustion

### ISSUE THREAD

**Issue by leonardoce** [cloudnative-pg/cloudnative-pg#4521]
### Is there an existing issue already for this feature request/idea?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new feature request to be evaluated.

### What problem is this feature going to solve? Why should it be added?

PostgreSQL will cleanly shut down when there's no space left for WAL files.
The operator will perceive that condition as a failure of the primary instance, leading to a failover.

Failing over will not help because every other replica will have the same error condition.

### Describe the solution you'd like

Having the operator automatically fence the primary would help because it would prevent any automatic failover from happening and would give the user time to increase the WAL disk space, fixing the root cause of the issue.

### Describe alternatives you've considered

Automatically scaling up the disk space will work, too, but I feel this as a different and broader topic.

### Backport?

No

### Are you willing to actively contribute to this feature?

Yes

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gbartolini** [comment]
Closes #3775

**Comment by NiharDudam** [comment]
Hi team, are we also planning to track disk statistics in cluster CR? 

As a consumer I would want to track the disk usages and warn my customers that disk is filling up at certain threshold and then let cloud native pg operator shutdown the postgres when disk actually fills up
