### ISSUE TITLE
[Bug]: Kubectl cnpg status forbidden for non cluster-admins

### ISSUE THREAD

**Issue by HaveFun83** [cloudnative-pg/cloudnative-pg#4522]
### Is there an existing issue already for this bug?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [X] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [X] I have read the troubleshooting guide and I think this is a new bug.

### Version

older in 1.22.x

### What version of Kubernetes are you using?

1.28

### What is your Kubernetes environment?

Other

### How did you install the operator?

Helm

### What happened?

Kubectl pulgin version:  v1.23.1

When using "kubectl cnpg status" as namespaced admin the following error occured
```
kubectl cnpg status -n db-test db-test  --as-group namespace-admin --as foobar
Error: while extracting PodDisruptionBudgetList: poddisruptionbudgets.policy is forbidden: User "foobar" cannot list resource "poddisruptionbudgets" in API group "policy" at the cluster scope
```
and no status is printed
Maybe a regression of https://github.com/cloudnative-pg/cloudnative-pg/pull/4319

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by smartbit** [comment]
In my environment above issue does **not** occur with plugin `1.22.1` nor `1.22.2` and it does happen with plugin `1.22.3` and `1.23.1`. Seems that is was a change between 1.22.2 and 1.22.3, as @HaveFun83 suggested these are the [changes in `status.go`](https://github.com/cloudnative-pg/cloudnative-pg/compare/v1.22.2...v1.22.3#diff-6a10da9d98890826e17b3c0795a4b9a99f9c63d32dd9d6194e2b3c83d4a14f7d) between those releases.
