### ISSUE TITLE
[Bug]: instance manager quitting without a proper shutdown

### ISSUE THREAD

**Issue by leonardoce** [cloudnative-pg/cloudnative-pg#4669]
### Is there an existing issue already for this bug?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [X] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [X] I have read the troubleshooting guide and I think this is a new bug.

### Contact Details

leonardo.cecchi@enterprisedb.com

### Version

1.23.1

### What version of Kubernetes are you using?

1.30 (unsupported)

### What is your Kubernetes environment?

Self-managed: kind (evaluation)

### How did you install the operator?

YAML manifest

### What happened?

After a PostgreSQL restart, if we can't connect to PostgreSQL after the programmed timeout, we immediately exit from the instance manager with exit status 1.
This prevents the instance manager from having a clean shutdown.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mnencia** [comment]
Closed by #4670
