### ISSUE TITLE
Test PostgreSQL 17 rc, alpha, beta

### ISSUE THREAD

**Issue by gbartolini** [cloudnative-pg/cloudnative-pg#4684]
Start testing PostgreSQL 17 pre-release versions (rc, alpha, betas).

**Comment by gbartolini** [comment]
Blocked by https://github.com/docker-library/postgres/issues/1243

**Comment by gbartolini** [comment]
Beta images are now available. See https://hub.docker.com/_/postgres

**Comment by NiccoloFei** [comment]
Done in https://github.com/cloudnative-pg/cloudnative-pg/commit/518e038b3e3cae15efeafb1922435cdb1f877ea5
