### ISSUE TITLE
PostgreSQL 17 support

### ISSUE THREAD

**Issue by gbartolini** [cloudnative-pg/cloudnative-pg#4685]

**Comment by pschichtel** [comment]
https://www.postgresql.org/about/news/postgresql-17-released-2936/

**Comment by maxpain** [comment]
Doesn't CNPG support PostgreSQL 17 yet? Really?
What are the limitations of the 17 version?

**Comment by gbartolini** [comment]
This ticket is a formality. 1.24.1 already makes 17 the default image and ... FWIW we are already testing PostgreSQL 18 with the `postgres-trunk-containers` project. Normally, we limit PostgreSQL official support to the supported releases at the time of the .0 version of a minor release.
