### ISSUE TITLE
[Bug]: Wrong timezone used in timestamps received from barman-cloud-backup-list

### ISSUE THREAD

**Issue by teran** [cloudnative-pg/cloudnative-pg#4688]
### Is there an existing issue already for this bug?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [X] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [X] I have read the troubleshooting guide and I think this is a new bug.

### Version

1.23.1

### What version of Kubernetes are you using?

1.27

### What is your Kubernetes environment?

Self-managed: k0s

### How did you install the operator?

Helm

### What happened?

In some cases when k8s worker node have non-UTC timezone set timestamps displayed in backup resource could be inconsistent

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mnencia** [comment]
This will be solved when #6252 will be closed
