### ISSUE TITLE
Explicitly set security context for pgbouncer deployment

### ISSUE THREAD

**Issue by rauanmayemir** [cloudnative-pg/cloudnative-pg#479]
Unlike postgres container pod, pgbouncer deployment doesn't explicitly set `securityContext`.

So even though container image itself explicitly specifies `USER pgbouncer`, setting `securityContext` in the kubernetes deployment as well would help mitigate infosec compliance requirements.

**Comment by gbartolini** [comment]
I believe this is very similar to what we did for the Postgres pods in this commit: dac868b70012d2b7c1cf6127e5db4a2d902c05e6
