### ISSUE TITLE
Introduce Snyk in CloudNativePG pipeline

### ISSUE THREAD

**Issue by gbartolini** [cloudnative-pg/cloudnative-pg#48]
Evaluate the introduction of [Snyk](https://snyk.io/) in the pipeline to shorten the feedback for vulnerabilities and third party dependencies.

**Comment by drsm79** [comment]
https://snyk.io/plans/

**Comment by anikoo-nr** [comment]
Have you considered Github Dependebot? It's built-into GitHub and free to use for opensource projects.

**Comment by sxd** [comment]
The project was submitted to the opensource campaign
