### ISSUE TITLE
[Feature]: add support for Barman 3.10.1

### ISSUE THREAD

**Issue by gbartolini** [cloudnative-pg/cloudnative-pg#4850]
### Is there an existing issue already for this feature request/idea?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new feature request to be evaluated.

### What problem is this feature going to solve? Why should it be added?

Barman 3.10.1 has been released (see https://github.com/EnterpriseDB/barman/releases/tag/release%2F3.10.1).

It includes a patch requested by CloudNativePG: `Add --no-partial option to barman-cloud-wal-restore`.

This feature is fundamental for the controlled switchover capability to work without streaming replication.

### Describe the solution you'd like

We should add a new capability to Barman Cloud from 3.10.1, which addresses the "no-partial" option.

When this capability is available, the WAL restore command should always invoke it with `--no-partial`.

The new promotion capability should instead restore the partial WAL file required for the switchover.

### Describe alternatives you've considered

N/A

### Backport?

No

### Are you willing to actively contribute to this feature?

Yes

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gbartolini** [comment]
This is a blocker for #4678

**Comment by mnencia** [comment]
We are abandoning the feature. After testing it, we discovered that having more control over when to download the partial WAL file doesn't improve the overall handling of WAL files. In particular, once you download a partial WAL, Postgres archives it several times until the timeline switch happens or the partial WAL file is completed in another way.
