### ISSUE TITLE
[Feature]: Make pod liveness/readiness probes timeout configurable

### ISSUE THREAD

**Issue by xhejtman** [cloudnative-pg/cloudnative-pg#4852]
### Is there an existing issue already for this feature request/idea?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new feature request to be evaluated.

### What problem is this feature going to solve? Why should it be added?

Current databaze pods have 5 seconds timeout to liveness/readiness probes and this timeout is hardcoded in `pkg/specs/pods.go`. It would be nice, if this could be configurable. In our setup, we need timeout about 20 seconds, it seems that DNS is involved in the probe and if DNS reply is lost, the Pod is restarted. With increased timeout, all is running just fine. I understand, it should not be default, but configurable.

### Describe the solution you'd like

Add new field to cluster spec so that Pod probes timeout can be changed. 

### Describe alternatives you've considered

I do not know about alternative as the timeout is currently hardcoded.

### Backport?

No

### Are you willing to actively contribute to this feature?

Yes

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gbartolini** [comment]
Did you look at this for the liveness one? commit:5f8e86d91b61503775a243caf577212d0696e725

**Comment by xhejtman** [comment]
> Did you look at this for the liveness one? commit [5f8e86d](https://github.com/cloudnative-pg/cloudnative-pg/commit/5f8e86d91b61503775a243caf577212d0696e725)

thanks, does it mean, that these values are futher altered?

https://github.com/cloudnative-pg/cloudnative-pg/blob/631bb20c500a64564773db0f98fc66704c6d0f54/pkg/specs/pods.go#L187

because, in the function here, both timeouts are hardcoded:
https://github.com/cloudnative-pg/cloudnative-pg/blob/631bb20c500a64564773db0f98fc66704c6d0f54/pkg/specs/pods.go#L208
and 
https://github.com/cloudnative-pg/cloudnative-pg/blob/631bb20c500a64564773db0f98fc66704c6d0f54/pkg/specs/pods.go#L219

**Comment by xhejtman** [comment]
and moreover, I think that both probes are executed - liveness and readiness, so the abovemention patch should alter both timeouts.

**Comment by weiyentan** [comment]
@xhejtman  for reference, this commit was for this [issue 4642](https://github.com/cloudnative-pg/cloudnative-pg/issues/4642) raised here

**Comment by cnwaldron** [comment]
Please add the configurations for pod specs! The `livenessProbeTimeout` setting that was recently added does not change the timeout, it only adjusts the `failureThreshold` which is calculated from the timeout setting which is never actually changed. All these settings be configured for both readiness & liveness probes.

**Comment by bentastic27** [comment]
Created a PR for this as I have an instance of this running the [cloudnative-pgvecto.rs](https://github.com/tensorchord/cloudnative-pgvecto.rs) image that _seems_ to getting killed while PG is starting up.

**Comment by gbartolini** [comment]
I think we should look at all the available options and make a solid decision about how we want to expose the fine tuning of probes. See: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#configure-probes
