### ISSUE TITLE
[Bug]: kubectl cnpg plugin shows PDB of all namespaces if cluster name is the same

### ISSUE THREAD

**Issue by Otterpohl** [cloudnative-pg/cloudnative-pg#4853]
### Is there an existing issue already for this bug?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [X] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [X] I have read the troubleshooting guide and I think this is a new bug.

### Version

older in 1.23.x

### What version of Kubernetes are you using?

1.28

### What is your Kubernetes environment?

Self-managed: kind (evaluation)

### How did you install the operator?

YAML manifest

### What happened?

# Problem
When checking the status of my cluster using `kubectl cnpg status gb4-postgresql -n dre-dev-psql-testing-p-g`, I noticed that it was returning PodDisruptionBudgets for clusters with the same name in other namespaces.

# Replicate Problem
Create cluster with name `ClusterA` in `namespaceA` 
Observe status output:
```
Pod Disruption Budgets status
Name               Role     Expected Pods  Current Healthy  Minimum Desired Healthy  Disruptions Allowed
----               ----     -------------  ---------------  -----------------------  -------------------
cluster-a          replica  2              2                1                        1
cluster-a-primary  primary  1              1                1                        0
```

Create cluster with name `ClusterA` in `namespaceB` 
Observe status output:
```
Pod Disruption Budgets status
Name               Role     Expected Pods  Current Healthy  Minimum Desired Healthy  Disruptions Allowed
----               ----     -------------  ---------------  -----------------------  -------------------
cluster-a          replica  2              2                1                        1
cluster-a-primary  primary  1              1                1                        0
cluster-a          replica  2              2                1                        1
cluster-a-primary  primary  1              1                1                        0
```

I suspect whatever is fetching the PDB's is not filtering by namespace.

PodDisruptionBudgets:
```
NAMESPACE↑                 NAME                                          MIN AVAILABLE                MAX UNAVAILABLE                ALLOWED DISRUPTIONS                AGE
namespace-a                cluster-a                                     1                            N/A                            1                                  13m
namespace-a                cluster-a-primary                             1                            N/A                            0                                  13m
namespace-b                cluster-a                                     1                            N/A                            1                                  25m
namespace-b                cluster-a-primary                             1                            N/A                            0                                  25m
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sxd** [comment]
Hi @Otterpohl 

Can you confirm the exact version of the plugin? This should be already fixed here https://github.com/cloudnative-pg/cloudnative-pg/pull/4530 it is possible you test the latest version of the plugin?

Regards,

**Comment by Otterpohl** [comment]
Rookie mistake, i should have checked that i was on the latest version.

I was on version `Build: {Version:1.23.1 Commit:336ddf53 Date:2024-04-30}`

```
kubectl krew update
kubectl krew upgrade cnpg
```

and now it is fixed, thanks!
