### ISSUE TITLE
[Feature]: ignore missing extension `google_vacuum_mgmt`

### ISSUE THREAD

**Issue by dnplkndll** [cloudnative-pg/cloudnative-pg#4877]
### Is there an existing issue already for this feature request/idea?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new feature request to be evaluated.

### What problem is this feature going to solve? Why should it be added?

any loading from google Cloud SQL you have a missing extension `google_vacuum_mgmt` need to skip it as is not configurable. 

I am not 100% this is the cause so if this is not the issue and something else not in the logs can be done I will look more. Not sure if bug or feature depending on how you look at it. 

### Describe the solution you'd like

ability to ignore the issue on the pg_restore or some control of not failing in the pre-data
google_vacuum_mgmt

### Describe alternatives you've considered

- removing the extension from the gcp panel
- dumping to a staging system that could accept the ext drop
- 

### Additional context

{"level":"info","ts":"2024-06-16T21:37:04Z","msg":"Running pg_restore","logging_pod":"db-1-import","cmd":"pg_restore","options":["-U","postgres","--no-owner","--no-privileges","--role=app","-d","app","--section","pre-data","/var/lib/postgresql/data/pgdata/dumps/odoo.dump"]}
{"level":"info","ts":"2024-06-16T21:37:04Z","logger":"postgres","msg":"record","logging_pod":"db-1-import","record":{"log_time":"2024-06-16 21:37:04.351 UTC","user_name":"postgres","database_name":"app","process_id":"47","connection_from":"[local]","session_id":"666f5b00.2f","session_line_num":"1","command_tag":"CREATE EXTENSION","session_start_time":"2024-06-16 21:37:04 UTC","virtual_transaction_id":"3/37","transaction_id":"0","error_severity":"ERROR","sql_state_code":"0A000","message":"extension \"google_vacuum_mgmt\" is not available","detail":"Could not open extension control file \"/usr/share/postgresql/15/extension/google_vacuum_mgmt.control\": No such file or directory.","hint":"The extension must first be installed on the system where PostgreSQL is running.","query":"CREATE EXTENSION IF NOT EXISTS google_vacuum_mgmt WITH SCHEMA google_vacuum_mgmt;\n\n\n","application_name":"pg_restore","backend_type":"client backend","query_id":"-4877003220278606660"}}
{"level":"info","ts":"2024-06-16T21:37:04Z","logger":"pg_restore","msg":"pg_restore: error: could not execute query: ERROR:  extension \"google_vacuum_mgmt\" is not available","pipe":"stderr","logging_pod":"db-1-import"}
{"level":"info","ts":"2024-06-16T21:37:04Z","logger":"pg_restore","msg":"DETAIL:  Could not open extension control file \"/usr/share/postgresql/15/extension/google_vacuum_mgmt.control\": No such file or directory.","pipe":"stderr","logging_pod":"db-1-import"}
{"level":"info","ts":"2024-06-16T21:37:04Z","logger":"pg_restore","msg":"HINT:  The extension must first be installed on the system where PostgreSQL is running.","pipe":"stderr","logging_pod":"db-1-import"}
{"level":"info","ts":"2024-06-16T21:37:04Z","logger":"pg_restore","msg":"Command was: CREATE EXTENSION IF NOT EXISTS google_vacuum_mgmt WITH SCHEMA google_vacuum_mgmt;","pipe":"stderr","logging_pod":"db-1-import"}
{"level":"info","ts":"2024-06-16T21:37:04Z","logger":"pg_restore","msg":"pg_restore: error: could not execute query: ERROR:  extension \"google_vacuum_mgmt\" does not exist","pipe":"stderr","logging_pod":"db-1-import"}
{"level":"info","ts":"2024-06-16T21:37:04Z","logger":"pg_restore","msg":"Command was: COMMENT ON EXTENSION google_vacuum_mgmt IS 'extension for assistive operational tooling';","pipe":"stderr","logging_pod":"db-1-import"}
{"level":"info","ts":"2024-06-16T21:37:04Z","logger":"pg_restore","msg":"pg_restore: warning: errors ignored on restore: 2","pipe":"stderr","logging_pod":"db-1-import"}

### Backport?

N/A

### Are you willing to actively contribute to this feature?

No

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sxd** [comment]
Hello @dnplkndll 

This i something that the operator can't fix since it's PostgreSQL the one that is getting a dump with an extension that doesn't exists, here there's some options:

* Provide the PostgreSQL image with the extension
* Take the backup with that extension disabled
* Modify the SQL file (if is an SQL file) and remove the creation of that extension manually

Sadly, is out of the operator capabilities to modify or pre-process a dump that it's being dumped into PostgreSQL

Closing since this can't be done

Cheers!

**Comment by dnplkndll** [comment]
unfortunate as removal of google_vacuum_mgmt is not possible or install on the an image. 

so no path forward to accept a database from Google Cloud SQL 

use case would be to clone prod db into a review env with operator managed DB

documenting for reference: 
https://www.googlecloudcommunity.com/gc/Databases/Unable-to-migrate-from-CloudSQL-Postgres-to-AlloyDB-due-to-the/m-p/762672
