### ISSUE TITLE
[Bug]: barman not being able to cleanup based on retentionPolicy with Minio S3

### ISSUE THREAD

**Issue by vojtechmares** [cloudnative-pg/cloudnative-pg#4890]
### Is there an existing issue already for this bug?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [X] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [X] I have read the troubleshooting guide and I think this is a new bug.

### Contact Details

iam@vojtechmares.com

### Version

1.23.2

### What version of Kubernetes are you using?

1.27

### What is your Kubernetes environment?

Self-managed: RKE

### How did you install the operator?

Helm

### What happened?

CNPG/Barman is not able to do cleanup on Minio S3, causing the S3 (self-hosted) to grow in size with no clean up policy. See the log bellow. Unfortunately I was unable to pin-point the cause of the issue.

Currently we are using Minio policy to delete the data, which is not safe if database is down for long period of time, because it is not using a retention window. The Minio policy is deleting objects when they expire after given time.

*We are running bare metal Kubernetes cluster with RKE2.

### Cluster resource

```shell
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: converge43db
  namespace: cybroslabs-c43
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:15.4
  instances: 2
  primaryUpdateStrategy: unsupervised
  primaryUpdateMethod: switchover
  superuserSecret:
    name: superuser-credentials
  storage:
    storageClass: longhorn
    size: 20Gi
  resources:
    limits:
      cpu: "1"
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 2Gi
  bootstrap:
    initdb:
      database: converge
      owner: c4core
      secret:
        name: c4core-credentials
      postInitSQL:
        - ALTER ROLE c4core WITH LOGIN;
  ## Postgres configuration ##
  # Enable 'postgres' superuser
  enableSuperuserAccess: true
  # Postgres instance parameters
  postgresql:
    parameters:
      max_connections: "1000"
  # High Availability configuration
  minSyncReplicas: 1
  maxSyncReplicas: 1
  # Enable replication slots for HA in the cluster
  replicationSlots:
    highAvailability:
      enabled: true
  monitoring:
    enablePodMonitor: true
  backup:
    retentionPolicy: "3d"
    barmanObjectStore:
      tags:
        backupRetentionPolicy: "expire"
      historyTags:
        backupRetentionPolicy: "keep"
      destinationPath: "s3://cybroslabs-backups/databases/converge43_v1"
      endpointURL: "http://10.77.0.60:9000"
      # endpointCA:
      #   name: cybroslabs-converge-backup-ca
      #   key: ca.crt
      wal:
        compression: bzip2
      data:
        compression: bzip2
      s3Credentials:
        accessKeyId:
          name: cybroslabs-converge-backup-credentials
          key: s3AccessKey
        secretAccessKey:
          name: cybroslabs-converge-backup-credentials
          key: s3SecretKey
```

### Relevant log output

```shell
{"level":"error","ts":"2024-06-11T01:09:42Z","logger":"barman","msg":"Error invoking barman-cloud-backup-delete","logging_pod":"converge43db-1","options":["--endpoint-url","http://10.77.0.60:9000","--cloud-provider","aws-s3","--retention-policy","RECOVERY WINDOW OF 3 DAYS","s3://cybroslabs-backups/databases/converge43_v1/","converge43db"],"stdout":"","stderr":"2024-06-11 01:09:42,251 [535399] ERROR: Barman cloud backup delete exception: An error occurred (XMinioInvalidObjectName) when calling the ListObjectsV2 operation: Object name contains unsupported characters.\n","error":"exit status 4","stacktrace":"github.com/cloudnative-pg/cloudnative-pg/pkg/management/log.(*logger).Error\n\tpkg/management/log/log.go:125\ngithub.com/cloudnative-pg/cloudnative-pg/pkg/management/barman.DeleteBackupsByPolicy\n\tpkg/management/barman/backupdelete.go:89\ngithub.com/cloudnative-pg/cloudnative-pg/pkg/management/postgres.(*BackupCommand).backupMaintenance\n\tpkg/management/postgres/backup.go:393\ngithub.com/cloudnative-pg/cloudnative-pg/pkg/management/postgres.(*BackupCommand).run\n\tpkg/management/postgres/backup.go:291"}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MichaluxPL** [comment]
It looks like this is not CNPG problem. From the log output it looks like barman-cloud problem or even file name problem.
I'd check WAL file names or WAL folders on S3 for unwanted files (with unsupported characters).
You could also update postgres image to 15.7 to test latest barman version.

**Comment by vojtechmares** [comment]
I kinda thought so, I just wanted to be sure. I will report this to barman then.

Unfortunately I can't downgrade Postgres cluster from 16.x to 15.7 (if I understand it correctly, what are you asking me to do).

**Comment by MichaluxPL** [comment]
Are U sure, You're using PGSQL 16.x ? From the manifest You've presented:
imageName: ghcr.io/cloudnative-pg/postgresql:**15.4**

**Comment by vojtechmares** [comment]
Sorry, you are right. I maintain a couple CNPG clusters and some are on 15.4 and some on 16.2... 

I will upgrade to 15.7 and get back to this issue.

**Comment by vojtechmares** [comment]
I've upgraded the Postgres to `15.7`, no luck, still getting the same error.

Also, I checked with my other databases and I am having the same issue on `16.2`.

I will raise this issue with Barman as well, since this is most likely not CNPG fault.

**Comment by sxd** [comment]
Hello

Closing this sine is more a Barman issue than a CNPG issue

Cheers!

**Comment by vojtechmares** [comment]
Hello, I've manage to fix the issue. I will post it here for future reference.

There is a difference for the destination path... it can't contain a trailing slash, see:

```diff
- destinationPath: "s3://cybroslabs-backups/databases/converge43_v1/"
+ destinationPath: "s3://cybroslabs-backups/databases/converge43_v1"
```

That is a tiny change and used in many examples in CNPG documentation, but with Minio this does not work.

I tested it with multiple Postgres cluster on different versions (15.7 and 16.2). I suggest adding a note to documentation, since this can be quite troublesome, yet examples in documentation use trailing slash.

**Comment by martinmarques** [comment]
@sxd seems it was not a barman issue ;) 

My suggestion is to follow what @vojtechmares mentioned regarding adding a note to the docs, or removing the trailing slash, if that works with other S3 compatible buckets

**Comment by james-callahan** [comment]
This was also an issue for us on S3: `ListBuckets` was failing because the path had 2 `/`s:
`s3://mybucket/mypath/` resulted in:
```
2025-08-15 02:53:23,330 [1911] DEBUG: https://mybucket.s3.amazonaws.com:443 "GET /?list-type=2&prefix=mypath%2F%2Fmy-db%2Fbase%2F&delimiter=&encoding-type=url HTTP/1.1" 403 None
```
