### ISSUE TITLE
[Bug]: CNPG Pod restarts randomly

### ISSUE THREAD

**Issue by ksudarsh00** [cloudnative-pg/cloudnative-pg#4946]
### Is there an existing issue already for this bug?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [X] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [X] I have read the troubleshooting guide and I think this is a new bug.

### Version

older in 1.23.x

### What version of Kubernetes are you using?

1.27

### What is your Kubernetes environment?

Other

### How did you install the operator?

Helm

### What happened?

We have number of cnpg clusters running in production kubernetes clusters.

Recently we started facing issue that all cnpg clusters running on a node restarts at same time for no reason and these restarted are happening randomly. Upon debugging postgres container it was terminated with Exit Code 137.

We couldn't find any error logs in splunk.

What could be the reason for these restarts? 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sxd** [comment]
Hi @ksudarsh00 

This usually it's related to running out of memory, that will explain why all the pods in the node are going out of memory check your cluster resources usage.

Regards!

**Comment by ksudarsh00** [comment]
Hi @sxd

Memory are within limits and if it's due to out of memory the pod restarts and we can see the reason as OOMKilled when we describe the pod.

We also checked our grafana dashboards, memory usage is looking good and within the limits.

**Comment by sxd** [comment]
Hi @ksudarsh00 

This is widely covered on the internet please refer to some places like this https://www.kerno.io/learn/oomkiller or this https://komodor.com/learn/how-to-fix-oomkilled-exit-code-137/ 

Since these is on the Kubernetes side I'm closing this since it's not an operator issue

Regards!

**Comment by prateekpandey14** [comment]
I am seeing the same behaviour  with the version `1.22.2` and `1.23.2` , pod describe says OOMKilled , even i have sufficient resources available on nodes.
