### ISSUE TITLE
[Bug]: cannot specify targetImmediate recovery target

### ISSUE THREAD

**Issue by gpothier** [cloudnative-pg/cloudnative-pg#4971]
### Is there an existing issue already for this bug?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [X] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [X] I have read the troubleshooting guide and I think this is a new bug.

### Contact Details

gpothier@gmail.com

### Version

older in 1.23.x

### What version of Kubernetes are you using?

1.29

### What is your Kubernetes environment?

Other

### How did you install the operator?

Helm

### What happened?

I cannot create a cluster with a `targetImmediate: true` recovery target, the admission controller throws the following error:
```
admission webhook "vcluster.cnpg.io" denied the request: Cluster.postgresql.cnpg.io "hippo-recovery-cluster" is invalid: spec.bootstrap.recovery.recoveryTarget: Required value: BackupID is missing
```

The API reference states that "All the target options except TargetTLI are mutually exclusive." (<https://cloudnative-pg.io/documentation/1.23/cloudnative-pg.v1/#postgresql-cnpg-io-v1-RecoveryTarget>). The PITR secion of the documentation states that "(...) this isn't possible for the remaining targets: targetName, targetXID, and targetImmediate. In such cases, it's important to specify backupID, **unless the last available backup in the catalog is acceptable**." (emphasis mine, <https://cloudnative-pg.io/documentation/1.23/recovery/#recovery-targets>). So according to the docs it should be ok not to specify `backupID`.

What I am trying to achieve is to restore the cluster from the latest full backup in the object store, without applying the WAL logs (I don't care that I don't get the latest data, it is just to set up a development environment). If I don't specify a `recoveryTarget`, the operator correctly selects the latest full backup, without having to specify a `backupID`, as specified in the documentation. But then it applies the WAL logs, which is what I am trying to avoid with `targetImmediate`. 

This is with operator version 1.23.1, as the latest version (1.23.2) is not available in the Helm repository.

### Cluster resource

```shell
---
# Source: cluster/templates/cluster.yaml
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: hippo-recovery-cluster
  labels:
    helm.sh/chart: cluster-0.0.9
    app.kubernetes.io/name: cluster
    app.kubernetes.io/instance: hippo-recovery
    app.kubernetes.io/part-of: cloudnative-pg
    app.kubernetes.io/managed-by: Helm
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:15.2
  imagePullPolicy: IfNotPresent
  postgresUID: 26
  postgresGID: 26
  storage:
    size: 80Gi
    storageClass: rbd-ssd-nobackup
  walStorage:
    size: 1Gi
    storageClass: 
  affinity:
    enablePodAntiAffinity: true
    podAntiAffinityType: required
    topologyKey: kubernetes.io/hostname
  priorityClassName: 

  primaryUpdateMethod: switchover
  primaryUpdateStrategy: unsupervised
  logLevel: info
  enableSuperuserAccess: true
  postgresql:
    shared_preload_libraries:

  managed:
    roles:
      - createdb: true
        login: true
        name: app
    

  monitoring:
    enablePodMonitor: false
  
  bootstrap:
    recovery:
      recoveryTarget:
        targetImmediate: true
      source: objectStoreRecoveryCluster
  
  externalClusters:
    - name: objectStoreRecoveryCluster
      barmanObjectStore:
        serverName: hippo-recovery-cluster
      
        endpointURL: "http://minio-backup.ozone.caligrafix.cl:9000"
        destinationPath: "s3://odoo-v8-caligrafix-master-cnpg-backups/"
        s3Credentials:
          accessKeyId:
            name: odoo-v8-caligrafix-master-cnpg-backups-ro-creds
            key: ACCESS_KEY_ID
          secretAccessKey:
            name: odoo-v8-caligrafix-master-cnpg-backups-ro-creds
            key: ACCESS_SECRET_KEY
```

### Relevant log output

```shell
Error: UPGRADE FAILED: failed to create resource: admission webhook "vcluster.cnpg.io" denied the request: Cluster.postgresql.cnpg.io "hippo-recovery-cluster" is invalid: spec.bootstrap.recovery.recoveryTarget: Required value: BackupID is missing
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gbartolini** [comment]
This is a documentation bug. You need `backupID` in that case.
