### ISSUE TITLE
Single replica breaking OCP upgrade

### ISSUE THREAD

**Issue by aaronmcohen** [cloudnative-pg/cloudnative-pg#498]
_Originally posted by @sxd in https://github.com/cloudnative-pg/cloudnative-pg/issues/486#issuecomment-1197304620_

Hi @aaronmcohen 

A couple of things to notice:
* Please create an issue so we can talk an discuss it there and assign a responsible for this PR
* Fix the linter issue
* Please run the E2E test on this on your repo 

On the other hand, this will basically delete the PDB on every cluster that we create, but we may not want that since this
protects the node from being drained and this needs to be done with during maintenance window and knowing that we
can reuse the PVC, otherwise, this may turn everything into a possible mess, do you have some examples that you can
mention in the issue?

Regards

**Comment by aaronmcohen** [comment]
@sxd I agree a PDB makes sense for an HA deployment. However a single replica is not HA. Adding PDB to a single replica essentially ensures the underlying cluster cannot be upgraded.

**Comment by phisco** [comment]
The PDB is there to prevent unintentional disruption of the Postgres cluster. Moving a single instance could be a risky operation if anything goes wrong with pvcs or anything else could result in the database indefinite unavailability, therefore should not be taken lightly. If possible it's better to always deploy at least 2 instances and if that's not possible we suggest using the maintenance mode.

**Comment by aaronmcohen** [comment]
@phisco I completely agree that if a user wants to prevent unintentional disruption of Postgres they should be running with 2+ instances. I am suggesting that a single replica deployment should not have that expectation and should be used for only POCs. If a Kubernetes/Openshift cluster admin finds a pod preventing a cluster from upgrading they are just going to delete the pod anyway. This of course begs the question what would cause it ti go` wrong with pvcs or anything else could result in the database indefinite unavailability`?

**Comment by phisco** [comment]
There could be valid reasons to deploy single replicas in production, I do agree for POCs it could be good to have the default being not having any pdb, but I think it should be opt-in, leaving the default to be focused toward production use-cases. You can already achieve the same thing by setting both maintenance mode and reuse pvc to true. Maybe we could document it better and make it more clear.
