### ISSUE TITLE
[Feature]: Ability to pause automatic failover promotion if a sync standby is not available

### ISSUE THREAD

**Issue by baran81** [cloudnative-pg/cloudnative-pg#5000]
### Is there an existing issue already for this feature request/idea?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new feature request to be evaluated.

### What problem is this feature going to solve? Why should it be added?

We are a bank that need a ducumented approval from the management to lose data on some application. We can't accept an automatic promote on an istance that is not in sync.

### Describe the solution you'd like

We would like to have a configuration parameter that pause/avoid automatic promotion if a sync standby is not available.

### Describe alternatives you've considered

.

### Backport?

Yes

### Are you willing to actively contribute to this feature?

No

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gbartolini** [comment]
Related to #3969

**Comment by gbartolini** [comment]
Superseded by #5095
