### ISSUE TITLE
[Feature]: Allow upgrading using image catalogs

### ISSUE THREAD

**Issue by CodeReaper** [cloudnative-pg/cloudnative-pg#5014]
### Is there an existing issue already for this feature request/idea?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new feature request to be evaluated.

### What problem is this feature going to solve? Why should it be added?

We are normally able to change the operand image of a cluster to any version. Now we are looking at image catalogs from (#3711) to simplify and centralize version management, but they seems to be locked down when it comes to changing the major version.

### Describe the solution you'd like

Either not enforcing this:
```
// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="Major is immutable"
```
or changing it so there is a way to say "I know what I am doing" and allow changing the major version.

### Describe alternatives you've considered

Setting which image to use explicitly on each cluster:

```
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:15.7
```

### Backport?

No

### Are you willing to actively contribute to this feature?

No

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mnencia** [comment]
Changing the PostgreSQL major version is not as easy as changing the container image. You have several possibilities.

The default way of operating is to use the [database import](https://cloudnative-pg.io/documentation/1.23/database_import/) feature to import data onto a new cluster.

If you need a very low downtime, you can use the logical replication following Gabriele's blog [How to migrate your PostgreSQL database in Kubernetes with ~0 downtime from anywhere](https://www.gabrielebartolini.it/articles/2024/03/cloudnativepg-recipe-5-how-to-migrate-your-postgresql-database-in-kubernetes-with-~0-downtime-from-anywhere/).

**Comment by CodeReaper** [comment]
I had assumed that the container image was "the way" to handle upgrading including major versions (we have not yet changed major versions).

Those resources for upgrading are sure to come in handy when we get there. It would have been an unwelcome surprise otherwise, when we had a failed upgrade.

**Comment by maaft** [comment]
Sorry to hijack this closed issue but when following this blog I get this webhook validation error:

```
one or more objects failed to apply, reason: failed to create typed patch object (vision-ai-hub/cluster2; postgresql.cnpg.io/v1, Kind=Cluster): .spec.bootstrap.initdb.import.schmaOnly: field not declared in schema. Retrying attempt #4 at 8:30AM.
```

Apparently that field does not exist in the schema? I'm using the latest cnpg operator release.

@mnencia  any idea?

**Comment by maaft** [comment]
Hey, sorry to hijack this issue, but I just tried it according to the blog.

Even though I specifically told cnpg to import "hasura" database

```yaml
bootstrap:
    initdb:
      import:
        type: microservice
        schemaOnly: true
        databases:
          - hasura
        source:
          externalCluster: hasura
```

This database does not exist after bootstrapping. Only a database "app" and role "app" was created.

@mnencia Might this be a bug?

**Comment by nusratulhassan** [comment]
> Hey, sorry to hijack this issue, but I just tried to upgrade from 15 to 16 by creating publication and subscriptions according to the blog.
> 
> Even though I specifically told cnpg to import "hasura" database
> 
> bootstrap:
>     initdb:
>       import:
>         type: microservice
>         schemaOnly: true
>         databases:
>           - hasura
>         source:
>           externalCluster: hasura
> This database does not exist after bootstrapping. Only a database "app" and role "app" was created.
> 
> Therefore, I also don't see any progress when issuing:
> 
> SELECT
>   confirmed_flush_lsn, pg_current_wal_lsn(), (pg_current_wal_lsn() - confirmed_flush_lsn) AS lsn_distance
> FROM
>   pg_replication_slots
> WHERE
>   slot_name = 'migration';
>  confirmed_flush_lsn | pg_current_wal_lsn | lsn_distance 
> ---------------------+--------------------+--------------
> (0 rows)
> [@mnencia](https://github.com/mnencia) Might this be a bug?

The same issue with me, the source database is imported into  "app" database.

**Comment by nusratulhassan** [comment]
@maaft you need to create required database in init.
`bootstrap:
    initdb:
      database: hasura
      import:
        type: microservice
        schemaOnly: true
        databases:
          - hasura
        source:
          externalCluster: hasura`
