### ISSUE TITLE
[Bug]: Replica Mode E2E failure

### ISSUE THREAD

**Issue by fcanovai** [cloudnative-pg/cloudnative-pg#5059]
### Is there an existing issue already for this bug?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [X] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [X] I have read the troubleshooting guide and I think this is a new bug.

### Version

trunk (main)

### What version of Kubernetes are you using?

1.27

### What is your Kubernetes environment?

Cloud: Google GKE

### How did you install the operator?

YAML manifest

### What happened?

In https://github.com/EnterpriseDB/cloudnative-pg/actions/runs/9866707508/job/27245992865#step:14:948 we had a test failure in which queries we run on postgresql and postgresql seems to be down.

This seems due to us adding the `app-secret`, and restarting the pod. From the cluster status:

```
        "phase": "Primary instance is being restarted without a switchover",
        "phaseReason": "original and target PodSpec differ in volumes: element app-secret has been added",
        [...]
        "conditions": [
            {
                "type": "Ready",
                "status": "False",
                "lastTransitionTime": "2024-07-10T02:47:55Z",
                "reason": "ClusterIsNotReady",
                "message": "Cluster Is Not Ready"
            },
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by akloss-terion** [comment]
I'm curious about this issue.  This still happens when [changing resources](https://github.com/cloudnative-pg/cloudnative-pg/blob/main/docs/src/rolling_update.md#rolling-updates) on CNPG 1.28.0.
