### ISSUE TITLE
[Bug]: database password not working for bootstrap 

### ISSUE THREAD

**Issue by gcasali01** [cloudnative-pg/cloudnative-pg#5060]
### Is there an existing issue already for this bug?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [X] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [X] I have read the troubleshooting guide and I think this is a new bug.

### Version

1.23.2

### What version of Kubernetes are you using?

1.27

### What is your Kubernetes environment?

Cloud: Other

### How did you install the operator?

YAML manifest

### What happened?

I tried to install the cluster db trying to create a registry database with user and password , but using psql is not possible to login with same credential of the secret reguser,postgres123 (password authentication failure).

### Cluster resource

```shell
db-cluster.yml
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: db-cluster
  namespace : harbor
spec:
  instances: 3

  bootstrap:
    initdb:
      database: registry
      owner: reguser
      secret:
        name: db-secret

  storage:
    size: 1Gi
---
db-secret.yml
apiVersion: v1
data:
  username: cmVndXNlcgo=
  password: cG9zdGdyZXMxMjMK
kind: Secret
metadata:
  name: db-secret
  namespace : harbor
type: kubernetes.io/basic-auth
```

### Relevant log output

```shell
$ kubectl get secret db-secret   -o jsonpath="{.data.password}" | base64 -d
postgres123
$ kubectl get secret db-secret   -o jsonpath="{.data.username}" | base64 -d
reguser

k get svc
NAME            TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
db-cluster-r    ClusterIP   10.254.57.150   <none>        5432/TCP   18m
db-cluster-ro   ClusterIP   10.254.52.182   <none>        5432/TCP   18m
db-cluster-rw   ClusterIP   10.254.55.83    <none>        5432/TCP   18m

trying from a ubuntu pod in the same cluster db namespace :
root@ubuntu:/# psql -h db-cluster-rw.harbor.svc.cluster.local -p 5432 -U reguser -d registry
Password for user reguser:
psql: error: connection to server at "db-cluster-rw.harbor.svc.cluster.local" (10.254.55.83), port 5432 failed: FATAL:  password authentication failed for user "reguser"
connection to server at "db-cluster-rw.harbor.svc.cluster.local" (10.254.55.83), port 5432 failed: FATAL:  password authentication failed for user "reguser"
root@ubuntu:/# psql -h db-cluster-rw.harbor.svc.cluster.local -p 5432 -U reguser
Password for user reguser:
psql: error: connection to server at "db-cluster-rw.harbor.svc.cluster.local" (10.254.55.83), port 5432 failed: FATAL:  password authentication failed for user "reguser"
connection to server at "db-cluster-rw.harbor.svc.cluster.local" (10.254.55.83), port 5432 failed: FATAL:  password authentication failed for user "reguser"
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gbartolini** [comment]
How did you create the secret? Can you share the instructions?

As you can see there's a newline character in the password.

**Comment by gcasali01** [comment]
Hi Gabriele , thanks for helping , I installed this way :
$ k apply -f db-secret.yml
secret/db-secret unchanged

cat db-secret.yml | base64 -w 0; echo
YXBpVmVyc2lvbjogdjEKZGF0YToKICB1c2VybmFtZTogY21WbmRYTmxjZ289CiAgcGFzc3dvcmQ6IGNHOXpkR2R5WlhNeE1qTUsKa2luZDogU2VjcmV0Cm1ldGFkYXRhOgogIG5hbWU6IGRiLXNlY3JldAogIG5hbWVzcGFjZSA6IGhhcmJvcgp0eXBlOiBrdWJlcm5ldGVzLmlvL2Jhc2ljLWF1dGgK

md5sum db-secret.yml
c0effb86b7894724d9b7f0aa37a5422d  db-secret.yml

**Comment by gcasali01** [comment]
thanks for helping I solved with your comment :
gcasale@eonetworkstation4:~/hcinss-vnamespace/harbor3$ echo  'cG9zdGdyZXMxMjM=' | base64 -d | od -c
0000000   p   o   s   t   g   r   e   s   1   2   3
0000013
gcasale@eonetworkstation4:~/hcinss-vnamespace/harbor3$ echo  'cG9zdGdyZXMxMjMK' | base64 -d | od -c
0000000   p   o   s   t   g   r   e   s   1   2   3  \n
0000014

root@ubuntu:/# psql -h db-cluster-rw.harbor.svc.cluster.local -p 5432 -U reguser -d registry
Password for user reguser:
psql (16.3 (Ubuntu 16.3-0ubuntu0.24.04.1))
SSL connection (protocol: TLSv1.3, cipher: TLS_AES_256_GCM_SHA384, compression: off)
Type "help" for help.

registry=>

Only one other question , there is any way to set up postgres password , I tried like this :
```
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: db-cluster
  namespace : harbor
spec:
  instances: 3
  superuserSecret:
    name: superuser-secret
  bootstrap:
    initdb:
      database: registry
      owner: reguser
      secret:
        name: db-secret

  storage:
    size: 1Gi
---
apiVersion: v1
data:
  username: cG9zdGdyZXM=
  password: cG9zdGdyZXMxMjM=
kind: Secret
metadata:
  name: super-secret
  namespace : harbor
type: kubernetes.io/basic-auth
```

Is that correct ?

**Comment by litaocdl** [comment]
@gcasali01 If you want to use super-user secrets, need to enable the superUser access, see `enableSuperuserAccess ` in https://cloudnative-pg.io/documentation/current/cloudnative-pg.v1/#postgresql-cnpg-io-v1-ClusterSpec.

**Comment by sxd** [comment]
I'm guessing this was solved, otherwise you can open a new ticket
Closing
