### ISSUE TITLE
[Bug]: recovery_min_apply_delay rejected by admissions webhook

### ISSUE THREAD

**Issue by rocket357** [cloudnative-pg/cloudnative-pg#5079]
### Is there an existing issue already for your request/idea?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new documentation enhancement to be evaluated.

### What problem in the existing documentation this issue aims to solve?

Found the following issue: https://github.com/cloudnative-pg/cloudnative-pg/issues/4021

This implies that recovery_min_apply_delay is accepted as postgresql parameter, however, when attempting to apply this parameter via clusters yaml, we get an admissions webhook rejection "Invalid value: "1h" Can't set fixed configuration parameter."

The docs also state [the following](https://cloudnative-pg.io/documentation/1.23/postgresql_conf/#fixed-parameters):

```
Some PostgreSQL configuration parameters should be managed exclusively by the operator. The operator prevents the user from setting them using a webhook.

Users are not allowed to set the following configuration parameters in the postgresql section:

<snip>
recovery_min_apply_delay
```

So it seems we're at an impasse, where to implement a delayed replica we need to set a postgresql parameter, but the operator does not allow the postgresql parameter to be set by the user even though the documentation suggests this should be possible.

Is it possible to set recovery_min_apply_delay via another means that I've overlooked?

### Backport?

Yes

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gbartolini** [comment]
This should only be allowed in the case of a replica cluster.

**Comment by gbartolini** [comment]
This is a bug IMHO

**Comment by gbartolini** [comment]
We should:

- add the provided value in the `custom.conf` file
- enforce `recovery_min_apply_delay` to `0` in override.conf unless you are a primary or a designated primary.

**Comment by fcanovai** [comment]
Since the idea is to allow delays only on the dedicated primary of a replica cluster, we could have a specific parameter in the `replica` section. I believe it would make clearer to the users where the parameter applies, without a configuration parameter that behaves differently according to the instance underneath. We could also easily add a CEL rule to prevent a using a `promotionToken` together with a delay, as it would make little sense to try a controlled switchover on something artificially lagging behind.

**Comment by mnencia** [comment]
I like @fcanovai proposal. Putting the parameter in the `replica` section makes its scope self-evident.

**Comment by gbartolini** [comment]
I like this. Yesterday I was chatting with Armando and one possible solution would have been a webhook that prevented a designated primary to be promoted if `recovery_min_apply_delay` was set. But ... I agree, this is more elegant.
