### ISSUE TITLE
[Feature]: allow additionalCommandArgs to be passed to `barman-cloud-wal-restore`

### ISSUE THREAD

**Issue by mnencia** [cloudnative-pg/cloudnative-pg#5096]
### Is there an existing issue already for this feature request/idea?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new feature request to be evaluated.

### What problem is this feature going to solve? Why should it be added?

The operator currently supports `additionalCommandArgs` for `barman-cloud-backup` and `barman-cloud-wal-archive`. To ensure completeness, we should also add support for additional arguments to `barman-cloud-wal-restore`.

### Describe the solution you'd like

Since the `additionalCommandArgs` for archiving has not yet been released, I suggest renaming it to `archiveAdditionalCommandArgs` and introducing `restoreAdditionalCommandArgs`.

The `restoreAdditionalCommandArgs` parameter would affect replicas within the same cluster when specified in the backup stanza. Additionally, it would impact the restore process from remote locations when specified in the externalCluster stanza.

### Describe alternatives you've considered

An alternative could be to leave the field driving the WAL archiving as it is and only add the new parameter, but I wouldn't say I like the solution because it is not symmetrical.

### Backport?

No

### Are you willing to actively contribute to this feature?

Yes

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gbartolini** [comment]
Related to #4357

**Comment by maxpain** [comment]
Please fix the docs. There is `wal.additionalCommandArgs`.

<img width="373" alt="Image" src="https://github.com/user-attachments/assets/a19a74d4-d9a7-436c-b6c1-2415966710de" />

```
Cluster/gameflare/gf-pg dry-run failed: failed to create typed patch object (gameflare/gf-pg; postgresql.cnpg.io/v1, Kind=Cluster): .spec.backup.barmanObjectStore.wal.additionalCommandArgs: field not declared in schema
```
