### ISSUE TITLE
[Bug]: Volume backups kill DB instances

### ISSUE THREAD

**Issue by droslean** [cloudnative-pg/cloudnative-pg#5138]
### Is there an existing issue already for this bug?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [X] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [X] I have read the troubleshooting guide and I think this is a new bug.

### Contact Details

nmoraiti@redhat.com

### Version

1.23.2

### What version of Kubernetes are you using?

1.28

### What is your Kubernetes environment?

Cloud: Other

### How did you install the operator?

YAML manifest

### What happened?

I have a cluster with 2 instances. When the single backup runs it fails because of the rate limit of our cloud provider. That means that the single backup is making multiple calls to the cloud provider for some reason. Either way, the backup is failing because of that. After the failure, the 2nd instance of our cluster goes down with the error:
```console
{"level":"info","ts":"2024-07-23T09:31:59Z","msg":"DB not available, will retry","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"nordes-postgres","namespace":"nordes"},"namespace":"nordes","name":"nordes-postgres","reconcileID":"e1283ee3-2d12-41e8-bb40-c35effff78b1","logging_pod":"nordes-postgres-2","err":"failed to connect to `user=postgres database=postgres`: /controller/run/.s.PGSQL.5432 (/controller/run): server error: FATAL: the database system is starting up (SQLSTATE 57P03)"}

```

As you can see, that instance is trying to access the wrong host and database with the wrong username. The first instance is running and accepts connections.

### Cluster resource

```shell
- apiVersion: postgresql.cnpg.io/v1
  kind: Cluster
  metadata:
    name: nordes-postgres
    namespace: nordes
  spec:
    postgresql:
      parameters:
        max_connections: "500"
    instances: 2
    bootstrap:
      initdb:
        database: nordes
        owner: nordes
    storage:
      size: 20Gi
    backup:
      volumeSnapshot:
        className: do-block-storage-snapshot-postgres-class
        labels:
          app: nordes
        online: true
      target: primary
      retentionPolicy: 10d
    monitoring:
      enablePodMonitor: true

with the scheduled backup
```yaml
- apiVersion: postgresql.cnpg.io/v1
  kind: ScheduledBackup
  metadata:
    name: nordes-online-backup
    namespace: nordes
  spec:
    schedule: "30 0 0 * * *"
    immediate: true
    backupOwnerReference: self
    cluster:
      name: nordes-postgres
    method: volumeSnapshot
    target: primary
    online: true
```
```


### Relevant log output

```shell
{"level":"info","ts":"2024-07-23T09:31:59Z","msg":"DB not available, will retry","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"nordes-postgres","namespace":"nordes"},"namespace":"nordes","name":"nordes-postgres","reconcileID":"e1283ee3-2d12-41e8-bb40-c35effff78b1","logging_pod":"nordes-postgres-2","err":"failed to connect to `user=postgres database=postgres`: /controller/run/.s.PGSQL.5432 (/controller/run): server error: FATAL: the database system is starting up (SQLSTATE 57P03)"}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gbartolini** [comment]
The `postgres` user and the `postgres` database are always present and are used as coordination database by CloudNativePG (see https://cloudnative-pg.io/documentation/current/before_you_start/). So it is all expected.

Regarding issues on the storage, these should be now detected from 1.24 by #4404 . There's indeed little we can do if the storage stops writing operations.
