### ISSUE TITLE
[Bug]: Password authentication failed , bootstrap initdb

### ISSUE THREAD

**Issue by sinaure** [cloudnative-pg/cloudnative-pg#5265]
### Is there an existing issue already for this bug?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [X] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [X] I have read the troubleshooting guide and I think this is a new bug.

### Contact Details

aureliano.buendias@outlook.com

### Version

1.23.2

### What version of Kubernetes are you using?

1.30 (unsupported)

### What is your Kubernetes environment?

Self-managed: kind (evaluation)

### How did you install the operator?

Helm

### What happened?

using 0.21.6 version helm chart

1. created a cluster

cna't psql inside... using the autogenerated secret is working

### Cluster resource

```shell
`
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: test-pg
spec:
  instances: 1
  bootstrap:
    initdb:
      database: testdb
      owner: testdb
      secret:
        name: app-secret
  storage:
    size: 1Gi
`
```

### Relevant log output

```shell
└─(17:16:26 on test_postgres ✖ ✭)──> k exec -it test-pg-1 -n test bash                                                                                       (dev/default)
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
Defaulted container "postgres" out of: postgres, bootstrap-controller (init)
postgres@test-pg-1:/$ psql -u testdb testdb
/usr/lib/postgresql/16/bin/psql: invalid option -- 'u'
psql: hint: Try "psql --help" for more information.
postgres@test-pg-1:/$ psql -U testdb testdb
psql: error: connection to server on socket "/controller/run/.s.PGSQL.5432" failed: FATAL:  Peer authentication failed for user "testdb"
postgres@test-pg-1:/$ psql -h 127.0.0.1 -U testdb testdb
Password for user testdb: 
psql: error: connection to server at "127.0.0.1", port 5432 failed: FATAL:  password authentication failed for user "testdb"
connection to server at "127.0.0.1", port 5432 failed: FATAL:  password authentication failed for user "testdb"
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vongrad** [comment]
@sinaure Make sure that your secret has correct format as well as you correctly base64 encoded your username/password.
It should look approx. like:
```
apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
data:
  username: dGVzdGRi
  password: dGVzdGRi
metadata:
  name: app-secret
```
Note the `dGVzdGRi` is base64 encoded string `testdb`

**Comment by sinaure** [comment]
indeed my secret was not correctly encoded

**Comment by sinaure** [comment]
can close
