### ISSUE TITLE
[Feature]: Extra Annotations/Labels for pods

### ISSUE THREAD

**Issue by mhkarimi1383** [cloudnative-pg/cloudnative-pg#5266]
### Is there an existing issue already for this feature request/idea?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new feature request to be evaluated.

### What problem is this feature going to solve? Why should it be added?

Some times there is a need of adding some extra annotations or labels to database pods

### Describe the solution you'd like

Inherit from Cluster metadata or adding `spec.podLabels` and `spec.podAnnotations` just file `spec.env`

### Describe alternatives you've considered

Nothing

### Backport?

N/A

### Are you willing to actively contribute to this feature?

Yes

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by achanda** [comment]
Does this work for your use case? https://github.com/cloudnative-pg/cloudnative-pg/blob/5ab2763451a6c20bab6b89b234367fe1eacd0355/docs/src/operator_conf.md?plain=1#L38-L39

**Comment by mhkarimi1383** [comment]
@achanda 
Yes, thanks 
I was not able to find them when searching

**Comment by aryklein** [comment]
I was exactly looking for the same config. Thanks!

**Comment by mhkarimi1383** [comment]
@achanda I think document improvement is needed :)
