### ISSUE TITLE
[Feature]: Allow setting `dns_max_ttl` in PgBouncer

### ISSUE THREAD

**Issue by fullykubed** [cloudnative-pg/cloudnative-pg#5276]
### Is there an existing issue already for this feature request/idea?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new feature request to be evaluated.

### What problem is this feature going to solve? Why should it be added?

[This article](https://blog.digitalis.io/using-pgbouncer-with-consul-for-postgresql-high-availability-686049c232fc) outlines the motivation, but in essence this will allow reducing downtime during failover when using the Pooler (PgBouncer).

Even though the article is for Consul-based DNS, I believe the architecture and problem is almost identical for Kubernetes-based DNS.

### Describe the solution you'd like

`dns_max_ttl` is not an allowable option in the Pooler settings for PgBouncer ([docs](https://cloudnative-pg.io/documentation/1.23/connection_pooling/)). However, it does not appear to be set at all in the configuration file that CNPG puts onto the PgBouncer pods. As a result, it seems like this should be an allowable option for user configuration especially as it helps achieve the goal outlined above.

### Describe alternatives you've considered

None

### Additional context

None

### Backport?

No

### Are you willing to actively contribute to this feature?

No

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fullykubed** [comment]
If I am reading the code correctly, this parameter does not appear to be in used anywhere and is definitely not one of the enforced parameters. As a result, I do not think exposing this for user configuration will have any negative impact.

I think the only necessary change is adding it to the list [here](https://github.com/cloudnative-pg/cloudnative-pg/blob/41cc0f5570a5cb88962309275eee633d4a8c5d42/api/v1/pooler_webhook.go#L39) and the docs [here](https://github.com/cloudnative-pg/cloudnative-pg/blob/41cc0f5570a5cb88962309275eee633d4a8c5d42/docs/src/connection_pooling.md?plain=1#L362).

@gbartolini If you approve, happy to open a PR for this.

**Comment by gbartolini** [comment]
I don't remember the criteria we used back then to determine which options to enable and which not to. I think we initially decided to take a conservative approach. A good exercise could be to make an inventory of all the available options in PgBouncer that we do not allow to customise (e.g., put them in a spreadsheet) and have an open discussion. For example, the `cancel_wait_timeout` setting was added after the implementation of our pooler CRD. Thoughts? Are you willing to help?

**Comment by fullykubed** [comment]
Absolutely willing to help. Will do that this week.

**Comment by fullykubed** [comment]
From what I can tell, the only enforced settings are [here](https://github.com/cloudnative-pg/cloudnative-pg/blob/292f688067ff8dd055a9c839776251a9adb3be1d/pkg/management/pgbouncer/config/config.go#L117) and [here](https://github.com/cloudnative-pg/cloudnative-pg/blob/292f688067ff8dd055a9c839776251a9adb3be1d/pkg/management/pgbouncer/config/config.go#L73). I have excluded those from the below list as they are currently in use by CNPG.

Additionally, I have omitted any item in [this list](https://github.com/cloudnative-pg/cloudnative-pg/blob/41cc0f5570a5cb88962309275eee633d4a8c5d42/api/v1/pooler_webhook.go#L39) as they are already allowed.

Additionally, I have omitted any `auth_` settings as they would interfere with the CNPG configuration.

Finally, I have omitted any item that is in a subsection (e.g., `[databases]`) since that isn't compatible with the current API.

| Option | Should Allow | Notes |
| -----|:-------:|-------|
| `logfile`| | No need to log to a file in K8s |
|`pidfile`| | Would impact CNPG's ability to manage PgBouncer |
| `unix_socket_mode` | | Would impact CNPG's ability to manage PgBouncer |
| `unix_socket_group` | | Would impact CNPG's ability to manage PgBouncer |
| `user` | | Would impact CNPG's ability to manage PgBouncer |
| `track_extra_parameters` | X | Seems reasonable one might want the ability to set this; no clear downside | 
| `peer_id` | | Not applicable to the CNPG architecture for PgBouncer |
| `conffile` | | Would impact CNPG's ability to manage PgBouncer |
| `service_name` | | Only used for win32 platforms |
|`job_name` | | Alias for `service_name` |
| `stats_period` | X | Since `log_stats` is allowed, it would make sense to allow this. |
| `admin_users` | ? | I believe this could impact CNPG's ability to manage PgBouncer |
| `stats_users` | ? | I believe this could impact CNPG's ability to manage PgBouncer |
| `dns_max_ttl` | X | See original post |
| `dns_nxdomain_ttl` | X | See original post |
| `dns_zone_check_period` | | Only works with the c-ares backend (not sure if the current image is compiled with that enabled) |
| `resolv_conf` |  | Using the operating system default should be sufficient |
| `client_tls_protocols` | | Default of `secure` should be enforced |
| `client_tls_ciphers` | | Default should be enforced; this setting doesn't apply to newer TLS versions |
| `client_tls_ecdhcurve` | | Default is most secure; no clear reason why you'd want to be less secure |
| `client_tls_dheparams` | | Default is most secure; no clear reason why you'd want to be less secure |
| `server_tls_protocols` | | See above |
| `server_tls_ciphers` | | See above |
| `cancel_wait_timeout` | X | Should be allowed since other timeouts like `query_wait_timeout` are allowed |
| `suspend_timeout`| X | Should be allowed since other timeouts like `query_wait_timeout` are allowed |
| `pkt_buf` | X | Desirable for performance optimizations; limited downside to allowing |
| `max_packet_size` | X | Possibly needed if working with very large result set rows |
| `listen_backlog` | X | Desirable for performance optimizations; limited downside to allowing |
| `sbuf_loopcnt`| X | Desirable for performance optimizations; limited downside to allowing |
| `so_reuseport` | X | Not applicable to CNPG's architecture for PgBouncer |
| `tcp_defer_accept` | X | Other `tcp_` options are allowed |
| `tcp_socket_buffer` | X | Other `tcp_` options are allowed |

**Comment by gbartolini** [comment]
Thanks @fullykubed. Except for the `so_reuseport` (which I would not allow for now), the proposed options look OK to me. Please proceed with a patch. Thanks.

**Comment by gbartolini** [comment]
Hi @fullykubed, have you by any chance prepared a patch for this? Thanks!

**Comment by fullykubed** [comment]
@gbartolini Thanks for the reminder. Just opened a PR at #6216

**Comment by fullykubed** [comment]
@gbartolini Just confirming whether you want this back ported (no pref on my end). I notice the label and associated milestones seem to conflict.

**Comment by gbartolini** [comment]
> [@gbartolini](https://github.com/gbartolini) Just confirming whether you want this back ported (no pref on my end). I notice the label and associated milestones seem to conflict.

We are trying now to stop backporting stuff unless fixes. Thanks for asking.

**Comment by JordanP** [comment]
@fullykubed Since the pooler sends traffic to a K8s ClusterIP service, in case of switchover the clusterIP doesn't change, i.e it resolves to the same IP. I am not sure lowering `dns_max_ttl` would help. What do you think ?

**Comment by fullykubed** [comment]
@JordanP Good question! You are correct.
