### ISSUE TITLE
[Docs]: proposal for standard node labels and taints

### ISSUE THREAD

**Issue by gbartolini** [cloudnative-pg/cloudnative-pg#5305]
### Is there an existing issue already for your request/idea?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new documentation enhancement to be evaluated.

### What problem in the existing documentation this issue aims to solve?

As CloudNativePG, we have not yet taken a position in terms of workload separation of PostgreSQL with other nodes, leaving this decision in the end users' hands. We briefly mention taints and tolerations, but do nothing in terms of promotion of more standard and widely recognised labels/taints.

### Describe what additions need to be done to the documentation

We need to decide on a standard label for nodes and a standard taint. My proposal is to use `node-role.kubernetes.io/postgres`.

If you want more information, I've already conducted research and provided details here: https://www.gabrielebartolini.it/articles/2024/08/cloudnativepg-recipe-10-simulating-production-postgresql-on-kubernetes-with-kind/

We should also work with helm charts in order to extend this recommendation there too.

### Describe what pages need to change in the documentation, if any

- https://cloudnative-pg.io/documentation/current/architecture/
- https://cloudnative-pg.io/documentation/current/scheduling/

### Describe what pages need to be removed from the documentation, if any

N/A

### Additional context

N/A

### Backport?

Yes

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tsndqst** [comment]
I really like this idea but I am apprehensive about the use of the restricted node labels.  As you described in  [Recipe 10](https://www.gabrielebartolini.it/articles/2024/08/cloudnativepg-recipe-10-simulating-production-postgresql-on-kubernetes-with-kind/#understanding-well-known-node-labels-in-kubernetes), the restricted node labels require a workaround to add them.

While using the `node-role.kubernetes.io` is nice from a visual perspective (I like that it sets the ROLE column in kubectl output), I think a different well-known label for workload separation would be better.  I am concerned about the Infrastructure as Code case where it may be difficult to add a restricted label at node creation time.

**Comment by gbartolini** [comment]
> While using the `node-role.kubernetes.io` is nice from a visual perspective (I like that it sets the ROLE column in kubectl output), I think a different well-known label for workload separation would be better. I am concerned about the Infrastructure as Code case where it may be difficult to add a restricted label at node creation time.

I've been doing some research and found that the reason for "reserving" the possibility to add the `node-role.kubernetes.io` label to the control plane only via `kubeadm` is primarily for security reasons. However, this label can be added later with no problem. For example, even Red Hat OpenShift moves in that direction: see ["Creating an infrastructure node"](https://docs.openshift.com/container-platform/4.16/nodes/nodes/nodes-nodes-creating-infrastructure-nodes.html). The same goes for the label (with no problem whatsoever in terms of reservation).

As part of the CloudNativePG community, I believe we should set high goals. We have the responsibility and duty to push the boundaries further, with the goal of making running Postgres databases a common practice in Kubernetes. Ideally, this step is in that direction.

In case the label cannot be used, it's not a big deal; we could suggest an alternate one, like 'postgres.node.kubernetes.io' - which is not reserved.

Today I wrote [CNPG Recipe 11](https://www.gabrielebartolini.it/articles/2024/08/cloudnativepg-recipe-11-isolating-postgresql-workloads-in-kubernetes-with-kind/) to comprehensively address this issue. I am increasingly convinced and confident that this is the right direction. Are you less apprehended now? :)

**Comment by tsndqst** [comment]
I think proceeding with the `node-role.kubernetes.io` would be preferred.  I just wanted to bring up the potential issue when using that label in an Infrastructure as Code setting.  If the standard node-role label works that will be great.

**Comment by mnencia** [comment]
I like recommending `node-role.kubernetes.io/postgres` as a standard label and taint. The fact that OpenShift documentation suggests a similar approach indicates that this is the right direction to follow. The correct role being displayed in the `kubectl get node` output also greatly improves usability.

**Comment by gbartolini** [comment]
I have written a draft, changing both architecture and scheduling pages. See PR #5318. I would like to get this in 1.24. Thanks.
