### ISSUE TITLE
Change location of the webtest project

### ISSUE THREAD

**Issue by sxd** [cloudnative-pg/cloudnative-pg#532]
Now the webtest project is under the CloudNativePG organization, we need to release a version and change the current endpoints in the sourcecode

**Comment by sxd** [comment]
@gbartolini yes we're handling that! =)

**Comment by leonardoce** [comment]
Should this be cherry picked? I think we should. We didn't change the behavior of webtest, we are just uploading the images in the GitHub registry and supporting multiarch.
