### ISSUE TITLE
[Docs]: Document permissions required by the kubectl cnpg plugin

### ISSUE THREAD

**Issue by sxd** [cloudnative-pg/cloudnative-pg#5330]
### Is there an existing issue already for your request/idea?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new documentation enhancement to be evaluated.

### What problem in the existing documentation this issue aims to solve?

Currently we don't have an extensive documentation or which permissions are required and to do what on the plugin

### Backport?

Yes

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gbartolini** [comment]
Given that this is planned for 1.24 and at the moment I have not seen any PR, are you planning to work on this @sxd ? Release is tomorrow.

**Comment by sxd** [comment]
@gbartolini yes move it to 1.24.1 because I've been doing the work but it's a lot will not make it by tomorrow not even close :/
