### ISSUE TITLE
[Bug]: smartShutdownTimeout cannot be set to 0

### ISSUE THREAD

**Issue by fullykubed** [cloudnative-pg/cloudnative-pg#5338]
### Is there an existing issue already for this bug?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [X] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [X] I have read the troubleshooting guide and I think this is a new bug.

### Version

1.23.3

### What version of Kubernetes are you using?

1.29

### What is your Kubernetes environment?

Cloud: Amazon EKS

### How did you install the operator?

Helm

### What happened?

Setting `smartShutdownTimeout` to `0` on the `Cluster` CR manifest results in it being overwritten by the operator to `180`. It seems like `0` should be an allowed value if you do not want smart shutdowns at all.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gbartolini** [comment]
I looked into the code and I don't see why we should not allow a setting of 0, given that there are situations in which we set it (see https://github.com/cloudnative-pg/cloudnative-pg/blob/5d3f5159c853d50d897b422de3963822821a1035/pkg/management/postgres/instance.go#L511)
