### ISSUE TITLE
[Bug]: wal-archive instance manager subcommand should not connect to the kubernetes-api server

### ISSUE THREAD

**Issue by mnencia** [cloudnative-pg/cloudnative-pg#5366]
### Is there an existing issue already for this bug?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [X] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [X] I have read the troubleshooting guide and I think this is a new bug.

### Version

trunk (main)

### What version of Kubernetes are you using?

1.31

### What is your Kubernetes environment?

Self-managed: kind (evaluation)

### How did you install the operator?

YAML manifest

### What happened?

The `wal-archive` instance manager subcommand creates a ControllerRuntimeClient. This is a costly operation, and we should avoid it.

https://github.com/cloudnative-pg/cloudnative-pg/blob/24437b6879d8ef015f97bd856052c30eb5931b80/internal/cmd/manager/walarchive/cmd.go#L81-L85

The client is used later to patch a condition, using the Cluster from the cache as the source state. This should be moved inside the main instance manager code to avoid the cost of opening a client and potential consistency issues.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gbartolini** [comment]
This was introduced before the open source release in commit:dcd0d0ba89a5a6cfc4838a0761730be39c9d78bd
