### ISSUE TITLE
Avoid mounting ServiceAccountToken 

### ISSUE THREAD

**Issue by sxd** [cloudnative-pg/cloudnative-pg#544]
Following the [Trivy](https://github.com/aquasecurity/trivy) results, we should [avoid mounting](https://avd.aquasec.com/misconfig/ksv036) the [ServiceAccountToken](https://kubernetes.io/docs/reference/access-authn-authz/service-accounts-admin/#serviceaccount-admission-controller)

**Comment by phisco** [comment]
But... we need the token 🤔

**Comment by mnencia** [comment]
Without the ServiceAccountToken we cannot communicate with the API server.
AFAIK there is no way to have our Pods work without it.
