### ISSUE TITLE
[Feature]: add possibility to create logical backups (dumps) of databases to s3

### ISSUE THREAD

**Issue by dragoangel** [cloudnative-pg/cloudnative-pg#5440]
### Is there an existing issue already for this feature request/idea?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new feature request to be evaluated.

### What problem is this feature going to solve? Why should it be added?

I would like to have not only physical (base) backups on S3, but also logical (sql dumps) on S3.

### Describe the solution you'd like

Would like to have ability to backup sql dumps to S3, and ideally also ability to import databases from S3 as well.

### Describe alternatives you've considered

n/a

### Backport?

Yes

### Are you willing to actively contribute to this feature?

No

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sxd** [comment]
Hello @dragoangel 

This is not supported by barman-cloud, or it wasn't, they added support for it ?
What's the difference on using a CronJob that runs a container and execute pg_dump and put the file into S3?

Regards,

**Comment by dragoangel** [comment]
> Hello @dragoangel 
> 
> This is not supported by barman-cloud, or it wasn't, they added support for it ?
> What's the difference on using a CronJob that runs a container and execute pg_dump and put the file into S3?
> 
> Regards,

Hi @sxd , you right that barman-cloud do not support logical backups. This FR about creating such backups using not bartman-cloud but something controlled by cloudnative-pg, to track if backup was successful and provide some details about it in custom resource, as well as the option to import (restore) such backups from S3.

**Comment by sxd** [comment]
Hello @dragoangel 

Well, if barman-cloud doesn't supported then the operator will not do it, we will stop having these kind of features in favor of the new plugin interface in development where user will be able to add just plugins to do these kind of specific tasks.

Please wait for that interface and you'll be able to create a plugin or use a plugin that someone else may built.

Regards!
