### ISSUE TITLE
[Bug]: Cluster stuck after destroing pods with volume

### ISSUE THREAD

**Issue by takeda** [cloudnative-pg/cloudnative-pg#5542]
### Is there an existing issue already for this bug?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [X] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [X] I have read the troubleshooting guide and I think this is a new bug.

### Version

1.24.0

### What version of Kubernetes are you using?

1.3

### What is your Kubernetes environment?

Cloud: Amazon EKS

### How did you install the operator?

Helm

### What happened?

So this was triggered trying some extreme operations to see how CNPG reacts to.

I have cluster set up with WAL logging to S3 bucket running 3 instances. I wanted to see what happens if I destroy all 3 instances and get rid of the EBS storage, whether it will be able to resume operation from the S3 bucket data.

So I issued something similar to:

```
./kubectl-cnpg -n ccpm destroy ccpm-db ccpm-db-1
./kubectl-cnpg -n ccpm destroy ccpm-db ccpm-db-2
./kubectl-cnpg -n ccpm destroy ccpm-db ccpm-db-3
```

A job called "ccpm-db-4-snapshot-recovery-8bj7q" was created but it is constantly in pending state. When looking into controller logs this is repeating all the time:

"Failed to watch *v1.PodMonitor: failed to list *v1.PodMonitor: the server could not find the requested resource (get podmonitors.monitoring.coreos.com)"

I did not install prometheus operator there, and `enablePodMonitor` is set to false. I'm guessing the operator relies on prometheus to get status of other nodes, but didn't except someone did not have it installed?

The status of the cluster is as follows:
```
Cluster Summary
Name:                ccpm-db
Namespace:           ccpm
PostgreSQL Image:    ghcr.io/cloudnative-pg/postgresql:16.4
Primary instance:    ccpm-db-2
Primary start time:  2024-09-18 15:19:07 +0000 UTC (uptime 7h4m9s)
Status:              Failing over Failing over from ccpm-db-2 to ccpm-db-3
Instances:           3
Ready instances:     0

Certificates Status
Certificate Name     Expiration Date                Days Left Until Expiration
----------------     ---------------                --------------------------
ccpm-db-ca           2024-12-14 05:10:34 +0000 UTC  86.28
ccpm-db-replication  2024-12-14 05:10:34 +0000 UTC  86.28
ccpm-db-server       2024-12-14 05:10:34 +0000 UTC  86.28

Continuous Backup status
First Point of Recoverability:  2024-09-15T05:19:53Z
No Primary instance found
Physical backups
Primary instance not found

Streaming Replication status
Primary instance not found

Unmanaged Replication Slot Status
No unmanaged replication slots found

Managed roles status
No roles managed

Tablespaces status
No managed tablespaces

Pod Disruption Budgets status
Name             Role     Expected Pods  Current Healthy  Minimum Desired Healthy  Disruptions Allowed
----             ----     -------------  ---------------  -----------------------  -------------------
ccpm-db          replica  0              0                1                        0
ccpm-db-primary  primary  0              0                1                        0

Instances status
Name  Database Size  Current LSN  Replication role  Status  QoS  Manager Version  Node
----  -------------  -----------  ----------------  ------  ---  ---------------  ----
```

### Cluster resource

```shell
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: ccpm-db
spec:
  description: Database for storing CCPM data
  instances: 3
  primaryUpdateStrategy: unsupervised

  serviceAccountTemplate:
    metadata:
      annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::xxxxx:role/kubernetes-test-BucketRole-LS4i8VRPLis8

  monitoring:
    enablePodMonitor: false # Needs prometheus

  bootstrap:
    recovery:
      database: ccpm
      owner: ccpm
      #      source: mainBackup
      backup:
        name: daily-backups-20240915050051
      #    initdb:
      #      database: ccpm
      #      owner: ccpm

  storage:
    size: 1Gi
    storageClass: ebs-sc
  walStorage:
    size: 500Mi
    storageClass: ebs-sc

  externalClusters:
    - name: mainBackup
      barmanObjectStore:
        destinationPath: s3://xxxx
        serverName: ccpm-db # name of the folder/old server
        s3Credentials:
          inheritFromIAMRole: true
        wal:
          maxParallel: 8

  backup:
    volumeSnapshot:
      className: csi-aws-vsc
      labels:
        pg-backup: ccpm
    barmanObjectStore:
      destinationPath: s3://xxxx
      s3Credentials:
        inheritFromIAMRole: true
      wal:
        compression: gzip
        maxParallel: 8
      data:
        compression: gzip
        jobs: 2
    retentionPolicy: "1d"

  enablePDB: true
  affinity:
    enablePodAntiAffinity: true
    topologyKey: topology.kubernetes.io/zone
```
```


### Relevant log output

```shell
Failed to watch *v1.PodMonitor: failed to list *v1.PodMonitor: the server could not find the requested resource (get podmonitors.monitoring.coreos.com)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by takeda** [comment]
After posting it I also noticed that there was another issue, not showing in logs, but looks like CNPG tried to use snapshot to get WAL log, and it was failing to get the volume (or was it snapshot) attached, because I specified that WAL store is 500Mi while the minimum size is 1Gi so the size was not matching.

Anyway I repeated this again and saw a different errors for example this one: https://github.com/cloudnative-pg/cloudnative-pg/issues/3819

The thing is that every time I do this operation:

```
./kubectl-cnpg -n ccpm destroy ccpm-db ccpm-db-1
./kubectl-cnpg -n ccpm destroy ccpm-db ccpm-db-2
./kubectl-cnpg -n ccpm destroy ccpm-db ccpm-db-3
```

I get cluster in a stuck state every single time, and the only way I managed to get out of it was to removing the cluster and restoring it from the backup.

**Comment by gbartolini** [comment]
At the moment there's no other way to resume from this. Think about it. If this happens, it means that there's a much bigger problem in the infrastructure (I hope you are not using the same storage and node for different replicas).

Given the consequences of data loss, you need a business/manual decision in this extraordinary scenario.

Closing this ticket. Thanks for posting.
