### ISSUE TITLE
Improving test starting from a bug

### ISSUE THREAD

**Issue by sxd** [cloudnative-pg/cloudnative-pg#564]
### Discussed in https://github.com/cloudnative-pg/cloudnative-pg/discussions/525

<div type='discussions-op-text'>

<sup>Originally posted by **sxd** August  4, 2022</sup>
Currently, since we implemented the `/ready-to-test` line which use `pull_request_target` instead of `pull_request` to run the test, we're expecting the label `ready to test :elephant:` and we cannot see this when running the test on `pull_request` or even when running the `/test` command.

The proposal is:
- Only run on `pull_request_target` when label is equal to `ready to test :elephant:` and not on any other situation, even when labels are removed.
- The `/test` or `/ready-to-test` command should be used to run all the E2E test, unit test can stay for now to run on every situation.
- Even if members of the project create a PR this will not run until `/test` or `/ready-to-test` command are trigger.

The idea with this approach is to:
* Do not run test every time we create a PR or we push
* Avoid the excessive consumption of runners, since we don't have so much runners
* Run test in PR from forked repo

What do you think about this @phisco @leonardoce @gbartolini ?</div>

**Comment by gbartolini** [comment]
I would like to raise the priority of this ticket with the goal to reduce the number of runners we use for every commit. We should rationalise them by reducing the combinations of distros/pg versions at an early stage, and remove some automatisation too (like you are proposing here). I suggest we talk about this in the next dev meeting.

**Comment by litaocdl** [comment]
The code looks good, as I lack of token in my fork, I can only test the `pull_request_target` feature when this pr is merged, I am going to merge it and do the test again.

**Comment by litaocdl** [comment]
If add label (like `test`) to the pr and the pr contains label `ready to test`, the e2e test will still be triggered. but it seems github does not provide way to check the current label/unlabel content. 
will merge once correct the comments.
