### ISSUE TITLE
[split from `#4679`]: enhance validation - e.g. the DB name must be valid in PG

### ISSUE THREAD

**Issue by jsilvela** [cloudnative-pg/cloudnative-pg#5649]
Should we even validate? If we use an invalid name the reconciler will reject it.
Check if the message is clear enough.

Look at the definition. Seems to be arbitrary and 64 chars max.

**Comment by jsilvela** [comment]
Ref
https://dba.stackexchange.com/questions/217533/what-is-the-data-type-name-in-postgresql

**Comment by mnencia** [comment]
I don't think we should validate this. Let Postgres handle the validation.
