### ISSUE TITLE
[split from `#4679`] clarify behavior of Database in replica clusters

### ISSUE THREAD

**Issue by jsilvela** [cloudnative-pg/cloudnative-pg#5692]
In the initial implementation of the Declarative Database feature, a Database object
defined against a replica cluster will be marked as failed, with an error message saying
`"waiting for the cluster to become primary"`, and then it will be requeued, with the
retry period of 30 seconds.

Let's make sure we document this clearly, and give coherent info to the user.

- in the controller, move the bits about checking for replica cluster above the bits checking the Database object
- revise the documentation
- make sure we don't have insistent logging, since the object will be requeued many times until cluster promotion

**Comment by jsilvela** [comment]
@gbartolini , @leonardoce we would like your input on this design discussion.

**Comment by gbartolini** [comment]
I don't think it's worth checking anything beyond the existence of the database in this phase.

I would not go over the "Principle of least surprise" section. The main use case here is a distributed topology with users that rely on GitOps and have the same Database objects defined in each Kubernetes cluster. When the replica cluster is promoted, the Database objects will start being reconciled.

**Comment by jsilvela** [comment]
TODO:
- in the controller, move the bits about checking for replica cluster above the bits checking the Database object

**Comment by jsilvela** [comment]
I think this was all my confusion about the feedback you left in the document ticket @gbartolini . Will rewrite that bit of the documentation.
I think the existing approach is what you expected. We will keep it like that.
