### ISSUE TITLE
[Docs]: provide clearer instructions for professional support page

### ISSUE THREAD

**Issue by gbartolini** [cloudnative-pg/cloudnative-pg#5706]
### Is there an existing issue already for your request/idea?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new documentation enhancement to be evaluated.

### What problem in the existing documentation this issue aims to solve?

The [Professional Support](https://cloudnative-pg.io/support/) page on the website hosts companies that claim offering support on CloudNativePG. So far we have assumed that [CNCF guidelines](https://github.com/cncf/foundation/blob/main/website-guidelines.md) would be known (see items 3 and 4). From [Cybertec's submission](https://github.com/cloudnative-pg/cloudnative-pg.github.io/pull/229) it is clear that this is not enough.

### Describe what additions need to be done to the documentation

Clearly state that the description should be limited to professional services and that:

* Companies must be listed on that page in alphabetical order, or the order can be changed randomly on each page load. It’s OK to have different categories of support offered. Simple vetting by the project is needed to ensure that all companies listed really can provide the support promised. Projects are welcome to outsource this vetting to CNCF staff if it becomes a burden.

* Links to companies offering support are expected to go a page that at least mentions support of the project. This can either be the company homepage or a project-specific landing page.

### Describe what pages need to change in the documentation, if any

https://cloudnative-pg.io/documentation/current/commercial_support/
https://cloudnative-pg.io/support/

### Describe what pages need to be removed from the documentation, if any

We should probably remove the "Commercial support" page from the docs.
We should provide instructions in a separate page in the CloudNativePG Github project and leave the "Support" page on the website to list the companies and link that page.

### Backport?

Yes

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by df7cb** [comment]
> Links to companies offering support are expected to go a page that at least mentions support of the project. This can either be the company homepage or a project-specific landing page.

Fwiw, the existing EDB link does not pass this test.

**Comment by gbartolini** [comment]
You are right. It used to be on the home page when it was added. I have asked EDB folks to suggest changes. In any case, we will make a decision with maintainers and come up with a clear guideline that takes inspiration from the one linked above (not necessarily that).
