### ISSUE TITLE
[Docs]: Clarify use cases for `pg_basebackup`

### ISSUE THREAD

**Issue by gbartolini** [cloudnative-pg/cloudnative-pg#5719]
### Is there an existing issue already for your request/idea?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new documentation enhancement to be evaluated.

### What problem in the existing documentation this issue aims to solve?

The ["Bootstrap from a live cluster"](https://cloudnative-pg.io/documentation/current/bootstrap/#bootstrap-from-another-cluster) section can be misleading, particularly in the statement:

> The primary use case for this method is represented by migrations to CloudNativePG, either from outside Kubernetes or within Kubernetes (e.g., from another operator).

This claim is, in my opinion, overstated. In practice, the "Requirements" section is often overlooked, misunderstood, or not followed, which can lead to challenges. While theoretically possible, successfully importing a database from outside Kubernetes or from another operator via physical replication is quite *rare*. The process requires many complex factors to align perfectly.

It's worth noting that this section was written when CloudNativePG, at the time a closed-source product within EDB, lacked the import functionality and logical replication was not yet feasible.

### Describe what additions need to be done to the documentation

We should rephrase that sentence and clearly scope down the feature.

### Describe what pages need to change in the documentation, if any

https://cloudnative-pg.io/documentation/current/bootstrap/#bootstrap-from-another-cluster

### Backport?

Yes

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxpain** [comment]
> While theoretically possible, successfully importing a database from outside Kubernetes or from another operator via physical replication is quite _rare_. The process requires many complex factors to align perfectly.

@gbartolini 
Where can I find the requirements to prepare my existing non-cnpg database to migrate using physical replication?
