### ISSUE TITLE
 SSL-related issue during migration from Zalando Postgres to CloudNativePG

### ISSUE THREAD

**Issue by anaskhandevops** [cloudnative-pg/cloudnative-pg#5736]
### Is there an existing issue already for this bug?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [X] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [X] I have read the troubleshooting guide and I think this is a new bug.

### Contact Details

anaskhandevops@gmail.com

### Version

1.24.0

### What version of Kubernetes are you using?

1.31

### What is your Kubernetes environment?

Other

### How did you install the operator?

Helm

### What happened?

Hi, We are currently running a Zalando PostgreSQL cluster in production and have decided to migrate to CloudNativePG, which has been quite promising for us so far. 

### Cluster resource

```shell
logLevel: info
globalConfig:
  configurationProfile: "dev"
  containerRegistryBase: null
modulesConfig:
  certPlatformEnabled: "true"
  monitoringPlatformEnabled: "false"
  vaultPlatformEnabled: "false"

  cnpgPostgresPlatformEnabled: "true"
  cnpgPostgresPlatform:
    cloudnative-pg:
      monitoring:
        podMonitorEnabled: false
        podMonitorAdditionalLabels:
          release: "monitoring-platform"
        grafanaDashboard:
          create: false
          labels:
            grafana_dashboard: '1'
          annotations:
            k8s-sidecar-target-directory: /tmp/dashboards/Postgres

    clusters:
      qvt-postgredb:
         enabled: false
      qvt-cnpg63:
        enabled: true
        vaultConfiguration: false
        spec:
          affinity:
            topologyKey: topology.kubernetes.io/zone
          enableSuperuserAccess: true
          instances: 2
          monitoring:
            enablePodMonitor: true
          imageName: cnpg-timescale:13.6-1_8_master_343530d04
          postgresql:
            parameters:
              pg_stat_statements.max: "100"
              pg_stat_statements.track: all
              ssl: "off"
              # ssl_ca_file: '/controller/certificates/client-ca.crt'
              # ssl_cert_file: '/controller/certificates/server.crt'
              # ssl_key_file: '/controller/certificates/server.key'
              max_connections: "100"
              sslmode: "disable"
              random_page_cost: "1"
              wal_level: "logical"
              max_replication_slots: "15"
              max_wal_senders: "20"
            shared_preload_libraries:
              - timescaledb
              - pg_stat_statements
              - pg_stat_kcache
              - set_user
              - bg_mon
              - pgextwlist
              - pg_auth_mon
            pg_hba:
              - host    all             all             0.0.0.0/0               md5
              - host    all             replication      0.0.0.0/0               md5
              
          bootstrap:
            pg_basebackup:
              source: xyz-cluster
          replica:
            enabled: true
            source: xyz-cluster

          externalClusters:
          - name: xyz-cluster
            connectionParameters:
              host: 10.42.3.6
              user: replication
              dbname: db1
#            sslmode: disable
            password:
                name: zalando-superuser
                key: password
            sslKey:
             name: cnpg63-replication
             key: tls.key
            sslCert:
             name: cnpg63-replication
             key: tls.crt
            sslRootCert:
              name: cnpg63-ca
              key: ca.crt
        
          resources:
            requests:
              memory: 1Gi
              cpu: "0.1"
          storage:
            size: 2Gi
 ```

We have reviewed the CloudNativePG documentation and observed that SSL is enabled by default and cannot be turned off, as indicated here: https://github.com/cloudnative-pg/cloudnative-pg/blob/5d4195ca16a62bf24f989bda58a15a5f525adab7/docs/src/postgresql_conf.md#the-postgresql-section

<img width="654" alt="cnpg" src="https://github.com/user-attachments/assets/ca5804f7-f305-4c3a-b48d-4f2910b59345">
```


### Relevant log output
We are encountering an issue when bootstrapping the cluster using pg_basebackup from our backup. The process fails to initialize the cluster in CloudNativePG and throws the following error related to SSL connections:

Logs(platform/qvt-cnpg60-1-pgbasebackup-qsmtc:pgbasebackup):

```shell
 error (FATAL: no pg_hba.conf entry for replication connection from host \"10.42.3.10\", user \"replication\", SSL on (SQLSTATE 28000))"}  
```

We are testing on dev environment and everything is running on same namspace. Is there any workaround or method to disable SSL for replication connections, or any alternative solution to handle this scenario? Any guidance would be greatly appreciated.

**Comment by gbartolini** [comment]
Unfortunately no. SSL is required.

You should not use physical replication to migrate from Zalando. Please check this article I wrote: https://www.gabrielebartolini.it/articles/2024/03/cloudnativepg-recipe-5-how-to-migrate-your-postgresql-database-in-kubernetes-with-~0-downtime-from-anywhere/

**Comment by bhanotjyoti** [comment]
@anaskhandevops : How did you solve? I am facing the same issue?

**Comment by anaskhandevops** [comment]
@bhanotjyoti i wasn't able to fix ssl related issue. but i was able to setup migration. https://wiki.technonies.com/en/Databases/PostgreSQL/cloudnative-pg/Migrating-Zalando-to-Postgres-and-Establishing-Cloud-Native-Logical-Replication

**Comment by bhanotjyoti** [comment]
@anaskhandevops : Can we connect to discuss more? Also, I tried using the micro service approach of migration, but need some help with that

**Comment by bhanotjyoti** [comment]
@anaskhandevops : I followed this document and it executed the pg_dump and pg_restore https://cloudnative-pg.io/documentation/1.16/database_import/

But when I try to map it using the helm chart, I get issues. Can you help me
