### ISSUE TITLE
[Feature]: Support zstd as compression algorithm for data and wal backup

### ISSUE THREAD

**Issue by VoVAllen** [cloudnative-pg/cloudnative-pg#5758]
### Is there an existing issue already for this feature request/idea?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new feature request to be evaluated.

### What problem is this feature going to solve? Why should it be added?

Better compression ratio and backup/recovery time 

### Describe the solution you'd like

It's already supported in Barman, would be better to port to cnpg
Ref: https://github.com/EnterpriseDB/barman/pull/898

### Describe alternatives you've considered

NA

### Backport?

No

### Are you willing to actively contribute to this feature?

Yes

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sxd** [comment]
Hello @VoVAllen 

Sadly this is supported on Barman but not in Barman cloud, please refer here for the documentation https://docs.pgbarman.org/release/3.11.1/barman-cloud-backup.1.html

Closing since it's not possible

**Comment by maxpain** [comment]
@sxd could you please look into this?

**Comment by sxd** [comment]
@maxpain https://github.com/cloudnative-pg/plugin-barman-cloud/issues/127

**Comment by vladimirfx** [comment]
As I can see in the documentation, ZSTD is supported for WALs only. Is this intentional, or is it a mistake?

**Comment by maxpain** [comment]
> [@maxpain](https://github.com/maxpain) [cloudnative-pg/plugin-barman-cloud#127](https://github.com/cloudnative-pg/plugin-barman-cloud/issues/127)

This is the new experimental CNPG-I plugin.
How to use the `zstd` compression algorithm in the current version of CNPG with the old-style plugin?
