### ISSUE TITLE
[Feature]: flexible data durability enforcement in synchronous replication

### ISSUE THREAD

**Issue by gbartolini** [cloudnative-pg/cloudnative-pg#5793]
### Is there an existing issue already for this feature request/idea?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new feature request to be evaluated.

### What problem is this feature going to solve? Why should it be added?

With the introduction of the new synchronous replication interface in CloudNativePG version 1.24 (see #5095), the system now prioritizes **data durability**, as typically expected by PostgreSQL DBAs. However, this approach contrasts with the previously established (now deprecated) method of managing synchronous replication using `minSyncReplicas` and `maxSyncReplicas`, which places an emphasis on **self-healing** and system availability over strict data durability.

This creates a potential conflict for users who rely on the older method's flexibility and ability to maintain availability in the face of replica failure, especially in cloud-native environments where resilience and self-healing are often prioritized. The current behavior in version 1.24 may lead to scenarios where availability is sacrificed in favor of ensuring synchronous data replication, which could be unexpected for users accustomed to the previous balance of these two factors.

### Describe the solution you'd like

To provide more flexibility in managing data durability, we propose adding a method to relax the strict enforcement of data durability in the new synchronous replication interface.

In particular, the proposal is to introduce a new option in the `.spec.postgresql.synchronous` section, called `dataDurability`, with two configurable values:

1. `required` (default):  
   - Synchronous replication will strictly enforce data durability.
   - If there are no healthy replicas, write operations with synchronous commit set to `on`, `remote_write`, or `remote_apply` will hang until a replica becomes available.
   - This option ensures data consistency at all times, as expected by traditional DBAs, and it is the default

2. `preferred`:  
   - Data durability will be enforced whenever healthy replicas are available.
   - If not enough replicas are available, the system will disable synchronous replication, allowing write operations to continue. This prioritizes system availability and self-healing over strict durability.
   - This method is designed for cloud-native environments where availability and resilience are key concerns, and restores the default pre-1.24 behavior.

The `preferred` method can only be applied if both `preStandbyNames` and `postStandbyNames` are empty, ensuring that it does not interfere with replica preferences that may be set.

### Describe alternatives you've considered

N/A

### Additional context

This feature request was raised by Damien Glisse in the [Developer's meeting (Oct 2, 2024 - 48)](https://docs.google.com/document/d/1Bmf2AZG5WLKAyESJbYk7MbsfiuD3jgdIDQrDkNuKT9w/edit#heading=h.wevss7y071v6).

### Backport?

No

### Are you willing to actively contribute to this feature?

Yes

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ardentperf** [comment]
I realize this feature has already shipped and it's too late to change it now... but I wanted to leave a comment for posterity, that Postgres and CNPG absolutely do still guarantee durability when this is set to `preferred` - just that durability is only guaranteed for the local pod. (For proof, look at how the postgres community responded to the fsync debacle a couple years ago.) With network attached block storage that itself is mirrored (including many cloud provider storage options), this is generally considered acceptable. However if a local [unmirrored] NVMe disk is being used then it may not be acceptable. I think that the common position is that data should be persisted to a minimum of two physical storage devices. Whether to increase replication to three or four underlying physical devices is generally seen as a tradeoff between cost and stronger durability.
