### ISSUE TITLE
[Feature]: additional options for `pg_dump` and `pg_restore` in import

### ISSUE THREAD

**Issue by gbartolini** [cloudnative-pg/cloudnative-pg#5832]
### Is there an existing issue already for this feature request/idea?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new feature request to be evaluated.

### What problem is this feature going to solve? Why should it be added?

The import database process doesn't provide a way to pass additional options to `pg_dump` and `pg_restore`.

### Describe the solution you'd like

Introduce two new options in the `.spec.initdb.import` stanza that allow users to pass additional options to `pg_dump` and `pg_restore`.

### Describe alternatives you've considered

N/A

### Backport?

No

### Are you willing to actively contribute to this feature?

No

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxpain** [comment]
In my case, I want to speed up the process of bootstrapping the CNPG cluster using our 1TB production non-CNPG database. By default, `pg_dump` does everything in a single thread; I want to add a `-j 16` flag.

**Comment by audunsol** [comment]
If I understand this feature correctly, this will enable us to do:

```yaml
        pgDumpExtraOptions:
          - '--exclude-table-data=big_log_table_not_needed'
          - '--exclude-table-data=big_calculation_results_table_not_needed'
```

If so, for us, this would add the one final missing piece allowing us to move to cnpg databases in-cluster for our dynamic review-environments (per Pull Request/Merge Request) where we clone our main/test/staging database (managed in AKS - for now) into short-lived ephemeral databases for reviewing/testing features 🤩 

The `pg_dump -Fc $SOURCE_DB | pg_restore $DEST_DB` simply would take too long in our CI/CD flow without this, so we are running with a home grown (but not very stable) solution for this now.

(The `-j` flag mentioned by @maxpain might come in handy as well here for us, thanks!)

In turn, this may be the gateway drug for us to move PROD DBs into the cluster with CNPG as well 💊 

Highly appreciated!

**Comment by shajia-deshaw** [comment]
+ 1 to what @audunsol said. We have a similar workflow where we'd love to leverage this feature. Looking forward to get this merged soon! 🚀

**Comment by gbartolini** [comment]
I have successfully imported a database with the following bootstrap section:

```yaml
  # <snip>
  bootstrap:
    initdb:
      import:
	type: microservice
	databases:
	  - app
	source:
	  externalCluster: cluster-example
	pgDumpExtraOptions:
	- '--jobs=2'
	pgRestoreExtraOptions:
	- '--jobs=2'
 ```
