### ISSUE TITLE
[Bug]: PG running but cluster broken after restore with velero

### ISSUE THREAD

**Issue by 4censord** [cloudnative-pg/cloudnative-pg#5912]
### Is there an existing issue already for this bug?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [X] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [X] I have read the troubleshooting guide and I think this is a new bug.

### Contact Details

i didn't realize this was posted publicly. you can contact me via github.

### Version

1.23.4

### What version of Kubernetes are you using?

1.29

### What is your Kubernetes environment?

Other

### How did you install the operator?

Helm

### What happened?

A some time (weeks) ago i did a restore of a full namespace using velero.
this namespace included a postgres cluster.

After restore, the all postgres pods came backup and started working.
But, i seems like these pods where never readopted into cloudnative-pg.
So today i tried to upgrade postgres, and was told that there are no pods.
this also broke replication, so my replicas where weeks out of date by this point.

I'm not sure what the right path for cloudnative-pg is, but other operators seem to just addopt their resources after a restore

### Cluster resource

```shell
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-sharkey
  namespace: daniel-sharkey
spec:
  instances: 2
  storage:
    size: 1Gi
    storageClass: ceph-rwo
  monitoring:
    enablePodMonitor: true
```

### Relevant log output

```shell
[this is spammed continuously]
{"level":"info","ts":"2024-10-20T14:19:59Z","msg":"refusing to create the primary instance while the latest generated serial is not zero","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"pg-sharkey","namespace":"daniel-sharkey"},"namespace":"daniel-sharkey","name":"pg-sharkey","reconcileID":"37eb3893-d9e4-4548-be8a-7feb1bd65b46","latestGeneratedNode":2}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 4censord** [comment]
So i've tried over the last few hours to build a repro env for this, but
for now have failed as velero does not work on minikube.

But the basic step are:
* create a cnpg cluster
* backup that cluster using velero
* delete the cluster
* restore the cluster using velero

This brings back the pods in running state, but leaves them unmanged by cnpg.

I've not yet found any way to re-addopt the cluster yet, currently the
only option seem to be to create a new cluster and import the data.

**Comment by armru** [comment]
Hello, thanks for opening an issue.
Currently, velero is not supported by CNPG.
