### ISSUE TITLE
[Bug]: "cnpg psql" doesn't detect a cluster that doesn't exist

### ISSUE THREAD

**Issue by gbartolini** [cloudnative-pg/cloudnative-pg#5913]
### Is there an existing issue already for this bug?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [X] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [X] I have read the troubleshooting guide and I think this is a new bug.

### Version

1.24.0

### What version of Kubernetes are you using?

1.31

### What is your Kubernetes environment?

Self-managed: kind (evaluation)

### How did you install the operator?

YAML manifest

### What happened?

When running:

```bash
kubectl cnpg psql --replica cluster-example -- -c 'SHOW primary_conninfo'
```

I got this:

```console
Error: cannot find Pod with role "replica"
```

It took me a while to figure out that I had removed the cluster-example cluster.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by zekiyeaydemir** [comment]
I'd like take this one
