### ISSUE TITLE
[Bug]: Databse size is no longer shown by "kubectl cnpg status"

### ISSUE THREAD

**Issue by NiklasMayerhauserGH** [cloudnative-pg/cloudnative-pg#5952]
### Is there an existing issue already for this bug?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [X] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [X] I have read the troubleshooting guide and I think this is a new bug.

### Version

1.24.0

### What version of Kubernetes are you using?

1.28

### What is your Kubernetes environment?

Self-managed: k3s

### How did you install the operator?

Helm

### What happened?

With the new version of the cloudnative-pg the database size is no longer shown. 
I saw that you updated the type of getting the db size, maybe there is a bug? 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sxd** [comment]
Hello @NiklasMayerhauserGH 

Can you shows what's your output? also have you read the release notes? there's some changes in the plugin :D 

Regards

**Comment by NiklasMayerhauserGH** [comment]
Yes I read about the change. This is my output: 

![image](https://github.com/user-attachments/assets/69fca630-abb2-4ed3-bcea-e88a98847e2d)
