### ISSUE TITLE
[Bug]: .spec.postgresql.synchronous and .spec.instances = 1 --> SyncRep

### ISSUE THREAD

**Issue by smiyc** [cloudnative-pg/cloudnative-pg#5964]
### Is there an existing issue already for this bug?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [X] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [X] I have read the troubleshooting guide and I think this is a new bug.

### Version

1.24.0

### What version of Kubernetes are you using?

1.28

### What is your Kubernetes environment?

Other

### How did you install the operator?

YAML manifest

### What happened?

when scaling .spec.instances down to 1 without removing .spec.postgresql.synchronous
the single instance cluster has synchronous_standby_names set to
` FIRST 1 ("xxx-1")`
pointing to itself and leafing the commit hanging on "syncrep" wait

imho it would be best to not apply the yaml when instances = 1 an  .spec.postgresql.synchronous in place or ignore the sync parameters

### Cluster resource

```shell
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: xxx
  namespace: cnpg-system
  annotations:  
  labels:
    release: prometheus-operator  
spec:
  logLevel: info
  monitoring:
    enablePodMonitor: true
  imagePullSecrets:
    - name: docker-registry-repo-xxx-auth    
  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ClusterImageCatalog
    name: postgresql
    major: 17
  imagePullPolicy: Always
  instances: 1

...

  postgresql:
    synchronous:
      method: first
      number: 1
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by armru** [comment]
Hello @smiyc , would #5985 help with the issue?

**Comment by smiyc** [comment]
Hi @armru 
Jep, looks good
