### ISSUE TITLE
[Bug]: missing logs in e2e if decoding fails

### ISSUE THREAD

**Issue by fcanovai** [cloudnative-pg/cloudnative-pg#5987]
### Is there an existing issue already for this bug?

- [x] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [x] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [x] I have read the troubleshooting guide and I think this is a new bug.

### Version

trunk (main)

### What version of Kubernetes are you using?

1.31

### What is your Kubernetes environment?

Self-managed: kind (evaluation)

### How did you install the operator?

YAML manifest

### What happened?

Running the e2e, in case some log gets emitted which is not in json format (which shouldn't happen, but it may) the log collector stops writing them on file without giving any info. We should get details about the failure and see if it is possible to keep writing logs.

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by sxd** [comment]
@fcanovai I wasn't able to reproduce this issue, I've created a non json line in the logs that it's being pushed all the time and stern was able to put it into the files, meaning I can't reproduce this :s

**Comment by sxd** [comment]
There's no easy way to make sure we always capture the logs and we don't miss a line, discarding for now
