### ISSUE TITLE
[Bug]: FATAL: password authentication failed for user "testdb". I have tried so many things but i cant connect to my postgres (using pgadmin4)

### ISSUE THREAD

**Issue by ember11498** [cloudnative-pg/cloudnative-pg#6002]
### Is there an existing issue already for this bug?

- [x] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [x] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [x] I have read the troubleshooting guide and I think this is a new bug.

### Contact Details

dborges.miguel@gmail.com

### Version

1.24.0

### What version of Kubernetes are you using?

1.31

### What is your Kubernetes environment?

Self-managed: kind (evaluation)

### How did you install the operator?

YAML manifest

### What happened?

I cannot login into my postgres using pgadmin4. Here is my yaml file:

    apiVersion: v1
    kind: Secret
    type: kubernetes.io/basic-auth
    data:
      username: dGVzdGRi
      password: dGVzdGRi
    metadata:
      name: app-secret

    ---
    apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
      name: pg-block-storage
      namespace: db
    provisioner: dobs.csi.digitalocean.com
    parameters:
      fsType: ext4
    reclaimPolicy: Retain
    volumeBindingMode: Immediate
    allowVolumeExpansion: true

    ---
    apiVersion: postgresql.cnpg.io/v1
    kind: Cluster
    metadata:
      name: pg
      namespace: db
    spec:
      instances: 3
      imageName: ghcr.io/cloudnative-pg/postgis:14

      bootstrap:
        initdb:
          database: mydb
          owner: testdb
          secret:
            name: app-secret
          postInitTemplateSQL:
            - CREATE EXTENSION postgis;
            - CREATE EXTENSION postgis_topology;
            - CREATE EXTENSION fuzzystrmatch;
            - CREATE EXTENSION postgis_tiger_geocoder;

      storage:
        size: 1Gi
      walStorage:
        size: 1Gi
      postgresql:
        parameters:
          shared_buffers: 256MB
          work_mem: 64MB
          max_connections: "200"
        pg_hba:
          - hostssl all all 0.0.0.0/0 scram-sha-256

      startDelay: 30 # Delay before starting the database instance
      stopDelay: 100 # Delay before stopping the database instance
      primaryUpdateStrategy: unsupervised # Strategy for handling primary updates

      backup:
        retentionPolicy: "30d" # Backup retention policy
        barmanObjectStore:
          destinationPath: "s3://plot-bucket/backup/" # Backup destination in S3
          endpointURL: "https://plot-bucket.ams3.digitaloceanspaces.com" # S3 endpoint URL
          s3Credentials: # Credentials for accessing S3
            accessKeyId:
              name: s3-creds # Secret name containing access key
              key: ACCESS_KEY_ID # Key for access key ID
            secretAccessKey:
              name: s3-creds # Secret name containing secret key
              key: ACCESS_SECRET_KEY # Key for secret access key

      monitoring:
        enablePodMonitor: true # Enable the PodMonitor for Prometheus
        tls:
          enabled: false # Set to true if TLS is enabled for metrics

    ---
    apiVersion: postgresql.cnpg.io/v1
    kind: Pooler
    metadata:
      name: pgbouncer-rw
      namespace: db
    spec:
      cluster:
        name: pg
      instances: 3
      type: rw
      pgbouncer:
        poolMode: session
        parameters:
          max_client_conn: "1000"
          default_pool_size: "50"

    ---
    apiVersion: postgresql.cnpg.io/v1
    kind: Pooler
    metadata:
      name: pgbouncer-ro
      namespace: db
    spec:
      cluster:
        name: pg
      instances: 5
      type: ro
      pgbouncer:
        poolMode: session
        parameters:
          max_client_conn: "1000"
          default_pool_size: "50"

Then, in order to connect in pgadmin4 to my postgres primary database i create a service like this in order to open a nodeport:

    apiVersion: v1
    kind: Service
    metadata:
      name: pg-rw-nodeport
      namespace: db
    spec:
      type: NodePort
      selector:
        role: primary
      ports:
        - name: pgadmin4
          port: 5432
          targetPort: 5432
          nodePort: 30001

Then get the node ip using "kubectl get nodes -o wide". i use port 30001 and testdb for everything else like shown in the image below.

![Image](https://github.com/user-attachments/assets/dc8a83f0-d9b8-424e-bc17-bec30622a30b)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by ember11498** [comment]
after spending almost a day over this i found out i did not mention the namespace in the secret.. ! i added the namespace: db and now it works.

anyways, if someone could explain this part:

    pg_hba:
      - hostssl all all 0.0.0.0/0 scram-sha-256

i dont quiet understand what i should put here

**Comment by quercus-carsten** [comment]
You can find details about pg_hba.conf in the [pg documentation](https://www.postgresql.org/docs/current/auth-pg-hba-conf.html). It's basically host-based authentication you can configure there. You probably don't have to change the default, so you could remove the given part from your config.
But in any case, if you don't have special requirements a swift look into the default config may be good to know what is set.

**Comment by jmealo** [comment]
@ember11498 If this is resolved could you please close the issue?
