### ISSUE TITLE
[Bug]: better error message for `kubectl-cnpg status` when permissions are missing

### ISSUE THREAD

**Issue by ari-becker** [cloudnative-pg/cloudnative-pg#6057]
### Is there an existing issue already for this bug?

- [x] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [x] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [x] I have read the troubleshooting guide and I think this is a new bug.

### Version

1.24.0

### What version of Kubernetes are you using?

1.30

### What is your Kubernetes environment?

Cloud: Google GKE

### How did you install the operator?

YAML manifest

### What happened?

During evaluation of CNPG, at one point I had the `kubectl-cnpg status` working 100% and at some point I started to get the same errors as in the following bugs:

https://github.com/cloudnative-pg/cloudnative-pg/issues/5510
https://github.com/cloudnative-pg/cloudnative-pg/issues/6025

This was a real head-scratcher until I managed to find, in the GKE audit logs, that the call relied on the `container.pods.proxy` permission, which is apparently a separate permission from port-forwarding (so my debugging using `kubectl port-forward pod/postgresql-16-1 8000` and `curl -k https://localhost:8000/pg/status` succeeding were REALLY confusing), and our security folks confirmed that they had recently removed the permission.

The bug I'm trying to report is that the error message is very vague and was difficult to pin down. It would have been really helpful to at least have an error message like "you lack the `container.pods.proxy` permission", and for these permission requirements to be in the documentation.

### Cluster resource

```shell
N/A
```

### Relevant log output

```shell
Error(s) extracting status
-----------------------------------
unknown (get pods https:postgresql-16-1:8000)
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by sxd** [comment]
hi @ari-becker 

This error comes from Kubernetes API, it's not an error that we add, so it could be anything, probably it could be improved, PRs are welcome! :D 

Regards!

**Comment by ari-becker** [comment]
@sxd sure, I opened the following PR: https://github.com/cloudnative-pg/cloudnative-pg/pull/6092
