### ISSUE TITLE
[Feature]: allow configuring servicetemplate metadata for default Services

### ISSUE THREAD

**Issue by rewemkris** [cloudnative-pg/cloudnative-pg#6089]
### Is there an existing issue already for this feature request/idea?

- [x] I have searched for an existing issue, and could not find anything. I believe this is a new feature request to be evaluated.

### What problem is this feature going to solve? Why should it be added?

The problem is we have several K8s Clusters residing in multiple different GCP Projects, the VPCs are peered with each other and pod to pod communication is estabilished. 
Pods can resolve dns entries in their own project and with peered dns zones.
Currently there is no possibility to annotate the default cnpg services so that external-dns can create records in dns zones.

### Describe the solution you'd like

We would need a possibility to annotate the cnpg default services to trigger external-dns write new records into the dns zone. In this way pods from other kubernetes clusters can resolve the name correctly and access our pods via dns.

### Describe alternatives you've considered

Yes there is possibility to create an additional ClusterIP Service with selectortype rw, but the question is if this would not be a kind of wasting IPs.

### Backport?

N/A

### Are you willing to actively contribute to this feature?

No

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by sxd** [comment]
Hi @rewemkris 

This isn't possible with service template that will modified the service? it should be possible to set that annotation in the servicetemplate and that will be passed to the service.

Regards,

**Comment by rewemkris** [comment]
Hi @sxd,

Thanks for the quick response.
Yes it is currently possible but only under managed.additional.serviceTemplate which will create a new Service.
I wonder if this is really needed just for one annotation to have it integrated with external-dns.

Can't we overwrite the existing default rw Service maybe under Cluster.Spec.ServiceTemplate (currently does not exist) ?
