### ISSUE TITLE
Create the Helm release for 1.16.1

### ISSUE THREAD

**Issue by leonardoce** [cloudnative-pg/cloudnative-pg#612]
We need to update Helm too!

**Comment by hh24k** [comment]
The README.md needs to be updated too ... see to https://artifacthub.io/packages/helm/cloudnative-pg/cloudnative-pg, the version and some other info is not in sync.

File a PR for it: https://github.com/cloudnative-pg/charts/pull/29/files

**Comment by hh24k** [comment]
And the PR for updating installation instructions for cloudnative-pg in gh-pages branch
[charts: chore: update instructions for cloudnative-pg installationOPEN](https://github.com/cloudnative-pg/charts/pull/30)
