### ISSUE TITLE
[Bug]: no matches for kind "Database" in version "postgresql.cnpg.io/v1"

### ISSUE THREAD

**Issue by david-curran-90** [cloudnative-pg/cloudnative-pg#6270]
### Is there an existing issue already for this bug?

- [x] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [x] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [x] I have read the troubleshooting guide and I think this is a new bug.

### Version

1.24.0

### What version of Kubernetes are you using?

1.30

### What is your Kubernetes environment?

Cloud: Amazon EKS

### How did you install the operator?

Helm

### What happened?

I have installed the operator via helm and a cluster using a manfiest applied with `kubectl apply` I am now following the [Declarative Database Management](https://github.com/cloudnative-pg/cloudnative-pg/blob/main/docs/src/declarative_database_management.md) document but when I apply the manifest I get errors that the `Database` resource does not exist in my cluster

```
$ k apply -f pgdatabases.yaml
resource mapping not found for name: "cluster-example-one" namespace: "" from "pgdatabases.yaml": no matches for kind "Database" in version "postgresql.cnpg.io/v1"
ensure CRDs are installed first
resource mapping not found for name: "cluster-example-testing" namespace: "" from "pgdatabases.yaml": no matches for kind "Database" in version "postgresql.cnpg.io/v1"
ensure CRDs are installed first
```

I see that other CRDs have installed OK but not the `databases` one

```
k api-resources | grep -i post
backups                                                      postgresql.cnpg.io/v1                     true         Backup
clusterimagecatalogs                                         postgresql.cnpg.io/v1                     false        ClusterImageCatalog
clusters                                                     postgresql.cnpg.io/v1                     true         Cluster
imagecatalogs                                                postgresql.cnpg.io/v1                     true         ImageCatalog
poolers                                                      postgresql.cnpg.io/v1                     true         Pooler
scheduledbackups                                             postgresql.cnpg.io/v1                     true         ScheduledBackup
```

I have confirmed that crds are set to create

```
$ helm get values -a cnpg | yq '.crds'
create: true
```

Is there some other step I need to complete to use the declarative database management?

### Cluster resource

```shell

```

### Relevant log output

```shell

```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by gbartolini** [comment]
Declarative databases will be released in v1.25.0
