### ISSUE TITLE
[Feature]: Need database based restore

### ISSUE THREAD

**Issue by esakarya** [cloudnative-pg/cloudnative-pg#6272]
### Is there an existing issue already for this feature request/idea?

- [x] I have searched for an existing issue, and could not find anything. I believe this is a new feature request to be evaluated.

### What problem is this feature going to solve? Why should it be added?

In my cluster running almost 30 multiple database.
I read documents all backup restore solutions is cluster based.
for eg: I need only restore one database for time based. another 29 database must not restore.
How can i do that ?

### Describe the solution you'd like

during restore select database  will be powerfull.

### Describe alternatives you've considered

I want to restore database by database restore.
pgbackrest can do this

### Backport?

Yes

### Are you willing to actively contribute to this feature?

No

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by gbartolini** [comment]
We don't have any plans to include database level backup in core. Our stance is still to recommend a single database per cluster, and the reasons are detailed in the FAQ.

However, we have received the feedback on extending backup/recovery to other solutions. Our response is the new CNPG-I plugin interface, which will enable third parties to write plugins for any kind of backup tool.
