### ISSUE TITLE
[Bug]: Existing database's owner changed when using new Database CRD.

### ISSUE THREAD

**Issue by pchovelon** [cloudnative-pg/cloudnative-pg#6305]
### Is there an existing issue already for this bug?

- [x] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [x] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [x] I have read the troubleshooting guide and I think this is a new bug.

### Version

trunk (main)

### What version of Kubernetes are you using?

1.31

### What is your Kubernetes environment?

Cloud: Other

### How did you install the operator?

YAML manifest

### What happened?

Testing the new Database CRD. I managed to change database owner of an existing database (manually created).
I expected that the Database CRD won't be applied. So I qualified it as a bug.

First create a database manually : 

```sql
postgres=# create database db1;
CREATE DATABASE

postgres=# \l
                                                List of databases
   Name    |  Owner   | Encoding | Locale Provider | Collate | Ctype | Locale | ICU Rules |   Access privileges   
-----------+----------+----------+-----------------+---------+-------+--------+-----------+-----------------------
 app       | app      | UTF8     | libc            | C       | C     |        |           | 
 db1       | postgres | UTF8     | libc            | C       | C     |        |           |

[...]
```

Applying this file : 

```yaml
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: cluster-demo-db1
spec:
  name: db1
  owner: app
  cluster:
    name: cluster-demo
```

db1 database's owner is now app.

```sql
                                                List of databases
   Name    |  Owner   | Encoding | Locale Provider | Collate | Ctype | Locale | ICU Rules |   Access privileges   
-----------+----------+----------+-----------------+---------+-------+--------+-----------+-----------------------
 app       | app      | UTF8     | libc            | C       | C     |        |           | 
 db1       | app      | UTF8     | libc            | C       | C     |        |       
```

In my point of view, a check need to be made before altering / creating the database.

Regards

### Cluster resource

```shell

```

### Relevant log output

```shell

```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by pchovelon** [comment]
One more example, it could lead to dangerous situation where an existing database can be deleted without any warning : 

db1 is created : 
```sql
postgres=# create database db1;
CREATE DATABASE

postgres=# \l
                                                List of databases
   Name    |  Owner   | Encoding | Locale Provider | Collate | Ctype | Locale | ICU Rules |   Access privileges   
-----------+----------+----------+-----------------+---------+-------+--------+-----------+-----------------------
 app       | app      | UTF8     | libc            | C       | C     |        |           | 
 db1       | postgres | UTF8     | libc            | C       | C     |        |           | 
 postgres  | postgres | UTF8     | libc            | C       | C     |        |           | 
 template0 | postgres | UTF8     | libc            | C       | C     |        |           | =c/postgres          +
           |          |          |                 |         |       |        |           | postgres=CTc/postgres
 template1 | postgres | UTF8     | libc            | C       | C     |        |           | =c/postgres          +
           |          |          |                 |         |       |        |           | postgres=CTc/postgres
(5 rows)
```

When applying this CRD with `ensure: absent` the database will be dropped ... without warning 😢 

```yaml
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: cluster-dalidemo-db1
spec:
  name: db1
  owner: app
  ensure: absent
  cluster:
    name: cluster-dalidemo
```

**Comment by mnencia** [comment]
The operator's primary role is to execute the instructions provided in the manifests. When you explicitly request an action—such as deleting a resource or changing the owner—it assumes this is intentional and executes the operation as instructed. Introducing warnings for every potentially destructive action could lead to noise and might undermine the declarative nature of Kubernetes operations.

Could you clarify what kind of warning or safeguard you believe would be appropriate?

**Comment by pchovelon** [comment]
> Introducing warnings for every potentially destructive action could lead to noise and might undermine the declarative nature of Kubernetes operations.

Yes, I agree, it's not necessary to have too many messages. 

> Could you clarify what kind of warning or safeguard you believe would be appropriate?

What I tried to point out, is that a database that wasn't originally created by CNPG can be changed / destroyed without any warning.
I think it's dangerous. In a "perfect world", everything must be done through the operator, but will it be the case ? :) Not sure ^^
The safeguard can be to check if the database is created/managed by CNPG.

**Comment by mnencia** [comment]
One of the primary reasons for introducing the `ensure: absent` behavior is precisely to allow the deletion of a database that was not initially created through a Database resource. 

Additionally, users might modify the database directly from SQL, causing a divergence from what’s defined in the Database resource. If such a divergence occurs, updating the resource becomes a complex scenario: How do we decide what changes to apply or preserve? Should we prioritize the state defined in the resource or the state within the database?

These challenges highlight the importance of keeping this feature as simple as possible, avoiding introducing logic that is difficult to understand and predict.

**Comment by pchovelon** [comment]
So as it looks like that it will not be considered as a bug, I close this issue and will open a discussion. :)
