### ISSUE TITLE
[Bug]: Backup now working at all

### ISSUE THREAD

**Issue by Adrelien** [cloudnative-pg/cloudnative-pg#6319]
### Is there an existing issue already for this bug?

- [x] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [x] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [x] I have read the troubleshooting guide and I think this is a new bug.

### Version

1.24.0

### What version of Kubernetes are you using?

1.31

### What is your Kubernetes environment?

Self-managed: kind (evaluation)

### How did you install the operator?

YAML manifest

### What happened?

Just setup the most basic cluster with backup using s3 from hetzner 

### Cluster resource

```shell
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: timescaledb-prod-cluster
  namespace: telemetry-harbor-prod-db
spec:
  description: "Production-ready TimescaleDB Cluster with Longhorn Storage"
  imageName: ghcr.io/clevyr/cloudnativepg-timescale:16
  instances: 3
  storage:
    storageClass: longhorn-postgres-replica-storage
    size: 10Gi

  nodeMaintenanceWindow:
    reusePVC: false # rebuild from other replica instead

  postgresql:
    shared_preload_libraries:
      - timescaledb
    parameters:
      shared_buffers: 2GB
      work_mem: "128MB"
      maintenance_work_mem: "256MB"
      effective_cache_size: "6GB"
      max_worker_processes: "8"
      max_parallel_workers_per_gather: "4"
      max_parallel_workers: "8"
      random_page_cost: "1.1" # Optimized for SSD
      effective_io_concurrency: "200" # Optimized for SSD
      timescaledb.max_background_workers: "16"
      timescaledb.max_parallel_workers: "8"
      timescaledb.last_tune_version: "3.0.2"
    pg_hba:
      - host all all 0.0.0.0/0 md5

  enableSuperuserAccess: true
  superuserSecret:
    name: timescaledb-superuser

  bootstrap:
    initdb:
      postInitTemplateSQL:
        - CREATE EXTENSION IF NOT EXISTS timescaledb;
      database: harbor
      owner: ship
      secret:
        name: timescaledb-app-user

  backup:
    barmanObjectStore:
      destinationPath: s3://timescaledb-backup/
      endpointURL: https://telemetryharbor1.hel1.your-objectstorage.com
      s3Credentials:
        accessKeyId:
          name: backup-creds
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: backup-creds
          key: ACCESS_SECRET_KEY
      wal:
        compression: gzip
      data:
        compression: gzip
        immediateCheckpoint: true
        jobs: 4 # Increased for better performance
    retentionPolicy: "30d"
```

### Relevant log output

```shell
{"level":"info","ts":"2024-12-12T15:39:50.526713962Z","msg":"WAL archiving is working","logging_pod":"timescaledb-prod-cluster-2"}
{"level":"info","ts":"2024-12-12T15:39:50.55687239Z","msg":"Starting barman-cloud-backup","backupName":"timescaledb-prod-cluster","backupNamespace":"telemetry-harbor-prod-db","logging_pod":"timescaledb-prod-cluster-2","options":["--user","postgres","--name","backup-20241212153950","--endpoint-url","https://telemetryharbor1.hel1.your-objectstorage.com","--cloud-provider","aws-s3","s3://timescaledb-backup/","timescaledb-prod-cluster"]}
{"level":"info","ts":"2024-12-12T15:39:56.432437112Z","msg":"Backup completed","backupName":"timescaledb-prod-cluster","backupNamespace":"timescaledb-prod-cluster","logging_pod":"timescaledb-prod-cluster-2"}
{"level":"error","ts":"2024-12-12T15:39:57.359607147Z","logger":"barman","msg":"Can't extract backup id","backupName":"timescaledb-prod-cluster","backupNamespace":"telemetry-harbor-prod-db","logging_pod":"timescaledb-prod-cluster-2","command":"barman-cloud-backup-show","options":["--format","json","--endpoint-url","https://telemetryharbor1.hel1.your-objectstorage.com","--cloud-provider","aws-s3","s3://timescaledb-backup/","timescaledb-prod-cluster","backup-20241212153950"],"stdout":"","stderr":"2024-12-12 15:39:57,223 [16113] ERROR: Barman cloud backup show exception: Unknown backup 'backup-20241212153950' for server 'timescaledb-prod-cluster'\n","error":"exit status 4","stacktrace":"github.com/cloudnative-pg/machinery/pkg/log.(*logger).Error\n\tpkg/mod/github.com/cloudnative-pg/machinery@v0.0.0-20241014090714-c27747f9974b/pkg/log/log.go:125\ngithub.com/cloudnative-pg/barman-cloud/pkg/command.executeQueryCommand\n\tpkg/mod/github.com/cloudnative-pg/barman-cloud@v0.0.0-20240924124724-92831d48562a/pkg/command/backuplist.go:88\ngithub.com/cloudnative-pg/barman-cloud/pkg/command.GetBackupByName\n\tpkg/mod/github.com/cloudnative-pg/barman-cloud@v0.0.0-20240924124724-92831d48562a/pkg/command/backuplist.go:141\ngithub.com/cloudnative-pg/barman-cloud/pkg/backup.(*Command).GetExecutedBackupInfo\n\tpkg/mod/github.com/cloudnative-pg/barman-cloud@v0.0.0-20240924124724-92831d48562a/pkg/backup/backup.go:153\ngithub.com/cloudnative-pg/cloudnative-pg/pkg/management/postgres.(*BackupCommand).takeBackup\n\tpkg/management/postgres/backup.go:244\ngithub.com/cloudnative-pg/cloudnative-pg/pkg/management/postgres.(*BackupCommand).run\n\tpkg/management/postgres/backup.go:173"}
{"level":"error","ts":"2024-12-12T15:39:57.359748503Z","msg":"Backup failed","backupName":"timescaledb-prod-cluster","backupNamespace":"timescaledb-prod-cluster","logging_pod":"timescaledb-prod-cluster-2","error":"exit status 4","stacktrace":"github.com/cloudnative-pg/machinery/pkg/log.(*logger).Error\n\tpkg/mod/github.com/cloudnative-pg/machinery@v0.0.0-20241014090714-c27747f9974b/pkg/log/log.go:125\ngithub.com/cloudnative-pg/cloudnative-pg/pkg/management/postgres.(*BackupCommand).run\n\tpkg/management/postgres/backup.go:177"}
{"level":"info","ts":"2024-12-12T15:39:57.402395221Z","msg":"Applying backup retention policy","backupName":"timescaledb-prod-cluster","backupNamespace":"timescaledb-prod-cluster","logging_pod":"timescaledb-prod-cluster-2","retentionPolicy":"30d"}
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by mnencia** [comment]
Let's format the logs for easier understanding

```json
{
  "level": "info",
  "ts": "2024-12-12T15:39:50.55687239Z",
  "msg": "Starting barman-cloud-backup",
  "backupName": "timescaledb-prod-cluster",
  "backupNamespace": "telemetry-harbor-prod-db",
  "logging_pod": "timescaledb-prod-cluster-2",
  "options": [
    "--user",
    "postgres",
    "--name",
    "backup-20241212153950",
    "--endpoint-url",
    "https://telemetryharbor1.hel1.your-objectstorage.com",
    "--cloud-provider",
    "aws-s3",
    "s3://timescaledb-backup/",
    "timescaledb-prod-cluster"
  ]
}
{
  "level": "info",
  "ts": "2024-12-12T15:39:56.432437112Z",
  "msg": "Backup completed",
  "backupName": "timescaledb-prod-cluster",
  "backupNamespace": "timescaledb-prod-cluster",
  "logging_pod": "timescaledb-prod-cluster-2"
}
{
  "level": "error",
  "ts": "2024-12-12T15:39:57.359607147Z",
  "logger": "barman",
  "msg": "Can't extract backup id",
  "backupName": "timescaledb-prod-cluster",
  "backupNamespace": "telemetry-harbor-prod-db",
  "logging_pod": "timescaledb-prod-cluster-2",
  "command": "barman-cloud-backup-show",
  "options": [
    "--format",
    "json",
    "--endpoint-url",
    "https://telemetryharbor1.hel1.your-objectstorage.com",
    "--cloud-provider",
    "aws-s3",
    "s3://timescaledb-backup/",
    "timescaledb-prod-cluster",
    "backup-20241212153950"
  ],
  "stdout": "",
  "stderr": "2024-12-12 15:39:57,223 [16113] ERROR: Barman cloud backup show exception: Unknown backup 'backup-20241212153950' for server 'timescaledb-prod-cluster'\n",
  "error": "exit status 4",
  "stacktrace": "github.com/cloudnative-pg/machinery/pkg/log.(*logger).Error\n\tpkg/mod/github.com/cloudnative-pg/machinery@v0.0.0-20241014090714-c27747f9974b/pkg/log/log.go:125\ngithub.com/cloudnative-pg/barman-cloud/pkg/command.executeQueryCommand\n\tpkg/mod/github.com/cloudnative-pg/barman-cloud@v0.0.0-20240924124724-92831d48562a/pkg/command/backuplist.go:88\ngithub.com/cloudnative-pg/barman-cloud/pkg/command.GetBackupByName\n\tpkg/mod/github.com/cloudnative-pg/barman-cloud@v0.0.0-20240924124724-92831d48562a/pkg/command/backuplist.go:141\ngithub.com/cloudnative-pg/barman-cloud/pkg/backup.(*Command).GetExecutedBackupInfo\n\tpkg/mod/github.com/cloudnative-pg/barman-cloud@v0.0.0-20240924124724-92831d48562a/pkg/backup/backup.go:153\ngithub.com/cloudnative-pg/cloudnative-pg/pkg/management/postgres.(*BackupCommand).takeBackup\n\tpkg/management/postgres/backup.go:244\ngithub.com/cloudnative-pg/cloudnative-pg/pkg/management/postgres.(*BackupCommand).run\n\tpkg/management/postgres/backup.go:173"
}
```

From these logs, it looks like the just-completed backup is not present in the S3-compatible storage provided by Hetzner. My first guess is that something in the Hetzner implementation doesn't match the backup system expectations. Can you try to execute a backup using a different cloud service provider? To be on the safe side, I suggest testing with AWS S3.

**Comment by Adrelien** [comment]
> Let's format the logs for easier understanding
> 
> {
>   "level": "info",
>   "ts": "2024-12-12T15:39:50.55687239Z",
>   "msg": "Starting barman-cloud-backup",
>   "backupName": "timescaledb-prod-cluster",
>   "backupNamespace": "telemetry-harbor-prod-db",
>   "logging_pod": "timescaledb-prod-cluster-2",
>   "options": [
>     "--user",
>     "postgres",
>     "--name",
>     "backup-20241212153950",
>     "--endpoint-url",
>     "https://telemetryharbor1.hel1.your-objectstorage.com",
>     "--cloud-provider",
>     "aws-s3",
>     "s3://timescaledb-backup/",
>     "timescaledb-prod-cluster"
>   ]
> }
> {
>   "level": "info",
>   "ts": "2024-12-12T15:39:56.432437112Z",
>   "msg": "Backup completed",
>   "backupName": "timescaledb-prod-cluster",
>   "backupNamespace": "timescaledb-prod-cluster",
>   "logging_pod": "timescaledb-prod-cluster-2"
> }
> {
>   "level": "error",
>   "ts": "2024-12-12T15:39:57.359607147Z",
>   "logger": "barman",
>   "msg": "Can't extract backup id",
>   "backupName": "timescaledb-prod-cluster",
>   "backupNamespace": "telemetry-harbor-prod-db",
>   "logging_pod": "timescaledb-prod-cluster-2",
>   "command": "barman-cloud-backup-show",
>   "options": [
>     "--format",
>     "json",
>     "--endpoint-url",
>     "https://telemetryharbor1.hel1.your-objectstorage.com",
>     "--cloud-provider",
>     "aws-s3",
>     "s3://timescaledb-backup/",
>     "timescaledb-prod-cluster",
>     "backup-20241212153950"
>   ],
>   "stdout": "",
>   "stderr": "2024-12-12 15:39:57,223 [16113] ERROR: Barman cloud backup show exception: Unknown backup 'backup-20241212153950' for server 'timescaledb-prod-cluster'\n",
>   "error": "exit status 4",
>   "stacktrace": "github.com/cloudnative-pg/machinery/pkg/log.(*logger).Error\n\tpkg/mod/github.com/cloudnative-pg/machinery@v0.0.0-20241014090714-c27747f9974b/pkg/log/log.go:125\ngithub.com/cloudnative-pg/barman-cloud/pkg/command.executeQueryCommand\n\tpkg/mod/github.com/cloudnative-pg/barman-cloud@v0.0.0-20240924124724-92831d48562a/pkg/command/backuplist.go:88\ngithub.com/cloudnative-pg/barman-cloud/pkg/command.GetBackupByName\n\tpkg/mod/github.com/cloudnative-pg/barman-cloud@v0.0.0-20240924124724-92831d48562a/pkg/command/backuplist.go:141\ngithub.com/cloudnative-pg/barman-cloud/pkg/backup.(*Command).GetExecutedBackupInfo\n\tpkg/mod/github.com/cloudnative-pg/barman-cloud@v0.0.0-20240924124724-92831d48562a/pkg/backup/backup.go:153\ngithub.com/cloudnative-pg/cloudnative-pg/pkg/management/postgres.(*BackupCommand).takeBackup\n\tpkg/management/postgres/backup.go:244\ngithub.com/cloudnative-pg/cloudnative-pg/pkg/management/postgres.(*BackupCommand).run\n\tpkg/management/postgres/backup.go:173"
> }
> From these logs, it looks like the just-completed backup is not present in the S3-compatible storage provided by Hetzner. My first guess is that something in the Hetzner implementation doesn't match the backup system expectations. Can you try to execute a backup using a different cloud service provider? To be on the safe side, I suggest testing with AWS S3.

This my guess, I have been working on this for two days. Tried EVERYTHING. I will test aws now.

**Comment by dbackeus** [comment]
We're backing up to Hetzner Object Storage and it works just fine.

You need to correct your endpoint configuration though, the correct manifest should be:

```yaml
  backup:
    barmanObjectStore:
      destinationPath: s3://telemetryharbor1/timescaledb-backup/
      endpointURL: https://hel1.your-objectstorage.com
```

That is, you don't include your bucket name in the endpoint URL but put it in the destination instead.

**Comment by Adrelien** [comment]
> We're backing up to Hetzner Object Storage and it works just fine.
> 
> You need to correct your endpoint configuration though, the correct manifest should be:
> 
>   backup:
>     barmanObjectStore:
>       destinationPath: s3://telemetryharbor1/timescaledb-backup/
>       endpointURL: https://hel1.your-objectstorage.com
> That is, you don't include your bucket name in the endpoint URL but put it in the destination instead.

OMG, it worked! it was the endpoint that was making me problems. I wish it was mentioned somewhere. I spent days trying to figure it out. All I saw either error 4 which us related to perms or back up complete but not found. Thank you so much man!

**Comment by psavva** [comment]
> We're backing up to Hetzner Object Storage and it works just fine.
> 
> You need to correct your endpoint configuration though, the correct manifest should be:
> 
>   backup:
>     barmanObjectStore:
>       destinationPath: s3://telemetryharbor1/timescaledb-backup/
>       endpointURL: https://hel1.your-objectstorage.com
> That is, you don't include your bucket name in the endpoint URL but put it in the destination instead.

Kudos to you.  Thanks for pointing this out :)

I think it would be a nice idea to include the Hetzner object storage in the documentation.
@gbartolini  What you think?
