### ISSUE TITLE
[Bug]: MutatingWebhook on pod image => broken cluster

### ISSUE THREAD

**Issue by awoimbee** [cloudnative-pg/cloudnative-pg#6344]
### Is there an existing issue already for this feature request/idea?

- [x] I have searched for an existing issue, and could not find anything. I believe this is a new feature request to be evaluated.

### What problem is this feature going to solve? Why should it be added?

I can't create a cluster because pods get continuously restarted, because I have a mutating webhook that points every image to my internal registry:

```json
{
    "level": "info",
    "ts": "2024-12-17T23:59:34.467296869Z",
    "msg": "Recreating instance pod",
    "controller": "cluster",
    "controllerGroup": "postgresql.cnpg.io",
    "controllerKind": "Cluster",
    "Cluster": {
        "name": "postgresql-1",
        "namespace": "postgresql"
    },
    "namespace": "postgresql",
    "name": "postgresql-1",
    "reconcileID": "65f675c5-1cfa-41cc-bbf9-63f497677324",
    "pod": "postgresql-1-3",
    "to": "myregistry.example.com/f/ghcr/cloudnative-pg/postgresql:17.2",
    "reason": "Restarting instance postgresql-1-3, because: the instance is using an old init container image: myregistry.example.com/f/ghcr/cloudnative-pg/cloudnative-pg:1.24.1 -> ghcr.io/cloudnative-pg/cloudnative-pg:1.24.1"
}
```

https://github.com/Trow-Registry/trow

### Describe the solution you'd like

Either make the init container image configurable
Or use another method to check if the image is outdated

### Describe alternatives you've considered

Disabling image caching for cloudnative_pg

### Backport?

No

### Are you willing to actively contribute to this feature?

No

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by armru** [comment]
Closing the issue due to inactivity, feel free to reopen if needed
