### ISSUE TITLE
Configured shared_preload_libraries are not loaded when bootstrap initialization queries execute

### ISSUE THREAD

**Issue by redbaron** [cloudnative-pg/cloudnative-pg#649]
Libraries listed in `spec.postgresql.shared_preload_libraries` are not yet available when bootstrap init queries are executed, but they should be. One of the use case of init queries is `CREATE EXTENSION` which can access functions provided by shared lib and if lib not loaded, `CREATE EXTENSION` fails.

Found with postInitTemplateSQL, but looks like all `postInit*SQL` queries are affected.

**Comment by leonardoce** [comment]
I rebased this on `release-1.16` but I didn't rebase it on `release-1.15` because we are not getting the cluster resource in the initialization phase in that version.
