### ISSUE TITLE
WAL archive stops when control plane is not reachable

### ISSUE THREAD

**Issue by redbaron** [cloudnative-pg/cloudnative-pg#661]
I didn't reproduce it myself, but just reading code it looks to me that if `/controller/manager wal-archive` can't fetch Cluster CRD it fails archiving process. This can happen during control plane outage and can negatively affect RPO.

Given that archive configuration is likely static it should be cached locally in a file, so that WAL archiving can continue regardless of control plane availability.

**Comment by mnencia** [comment]
The instance manager caches it. If you look at https://github.com/cloudnative-pg/cloudnative-pg/blob/main/internal/cmd/manager/walarchive/cmd.go#L103, we get the client from the instance manager cache.

We build a client, but we use it only to update the conditions in case of failures.

**Comment by redbaron** [comment]
I see, cacheclient talks not to kubernetes cluster, but to the local instance manager, which serves latest version of cluster resource instance manager knows about. neat!
