### ISSUE TITLE
Display "Failures by test" summary table in e2e summary page

### ISSUE THREAD

**Issue by litaocdl** [cloudnative-pg/cloudnative-pg#662]
"Failures by test" summary table  is not displayed in e2e summary page, the code is already there and just need a display.

**Comment by litaocdl** [comment]
Create a failure test case on purpose and show the summary table as below


![Image](https://user-images.githubusercontent.com/42050086/187358979-9413f9f5-16e1-4412-a0cc-10abbb0c2464.png)


https://github.com/cloudnative-pg/cloudnative-pg/actions/runs/2953659075

I will rollback the failed case and move this ticket forward

**Comment by jsilvela** [comment]
Another run, after reordering the columns for better readability.
https://github.com/cloudnative-pg/cloudnative-pg/actions/runs/2958095943
