### ISSUE TITLE
Replace libpq with pgx

### ISSUE THREAD

**Issue by armru** [cloudnative-pg/cloudnative-pg#667]
Following https://github.com/cloudnative-pg/cloudnative-pg/pull/569 limitations,  we should replace libpq with pgx as it is better maintained.

**Comment by gbartolini** [comment]
@armru 

As part of this patch, let's also remove this from the `docs/src/database_import.md` file in the docs:

> You need to specify `sslmode: disable` in the `connectionParameters` section
