### ISSUE TITLE
Creation of a new volume for WAL files (pg_wal) on an existing cluster

### ISSUE THREAD

**Issue by gbartolini** [cloudnative-pg/cloudnative-pg#675]
Following #10, we need to allow users to add a new `walStorage` section to their existing clusters.

Current limitation: removal of `walStorage` once added is not possible.

Underneath, we need to check that the old location and the new location of the WALs exist, then - when the instance is down - we move the content of the old directory in the new one, remove the old folder, and set the `pg_wal` symlink accordingly.

**Comment by dhilipkumars** [comment]
Awesome news, thanks @jlong49 and @gbartolini .  
![Awesome](https://gifdb.com/images/high/cheering-minions-awesome-l5g6suhj1b4h47p8.webp)
