### ISSUE TITLE
Verify coherence of `min_wal_size` and `max_wal_size` with the size of `walStorage`

### ISSUE THREAD

**Issue by gbartolini** [cloudnative-pg/cloudnative-pg#677]

**Comment by gbartolini** [comment]
If the user has specified a separate volume for `walStorage`, verify the settings for `min_wal_size` and `max_wal_size` are coherent. See https://www.postgresql.org/docs/current/runtime-config-wal.html

**Comment by Sonali-Rajput** [comment]
Can you please further explain where the changes should be made?
