### ISSUE TITLE
The plugin command: `cnp report operator` fails if the operator was deployed with more than one replica 

### ISSUE THREAD

**Issue by armru** [cloudnative-pg/cloudnative-pg#69]
If we deploy the operator with more than one replica and run the command

`kubectl cnp report operator`

We receive the following error:

`Error: could not get operator pod: number of running operator pods greater than 1: 2 pods running`

This is caused by the following code block:

https://github.com/cloudnative-pg/cloudnative-pg/blob/27404c93ad728ef1654c2c439b0555df56dee666/internal/cmd/plugin/report/deployments/deployments.go#L60-L62

We should make the function `GetOperatorPod` more robust by allowing it to handle multiple replica operator deployments

**Comment by jsilvela** [comment]
Code looks good. Also, compiled the plugin and tested that it works with 2 operator Pods.
Nice job @armru
