### ISSUE TITLE
E2E: on operator restart, capture previous operator logs

### ISSUE THREAD

**Issue by litaocdl** [cloudnative-pg/cloudnative-pg#705]

**Comment by jsilvela** [comment]
Green run in the open source repo: https://github.com/cloudnative-pg/cloudnative-pg/actions/runs/3037641528
Run with displayed operator log lines via Ginkgo, plus download file
https://github.com/EnterpriseDB/cloud-native-postgres/actions/runs/3040633862/jobs/4897091719#step:11:2080
(this is in the closed source copy).
Look for line 2114 in the display.
