### ISSUE TITLE
ensure that clusters created by the 1.15 version contains conditions that are compatible with the successive releases

### ISSUE THREAD

**Issue by armru** [cloudnative-pg/cloudnative-pg#719]
In version 1.15 of the operator, we use conditions that are not compatible with the metav1.Conditions structs.
Given that we started to use metav1.Conditions struct in 1.16 we should be sure that in the 1.15 version we have conditions that can be converted to the new struct

**Comment by mnencia** [comment]
Closed by bb2c39a8d8d5e752b0fdc558644e720e92e54389 on `release-1.15` branch
