### ISSUE TITLE
Enable customization of log field names

### ISSUE THREAD

**Issue by gbartolini** [cloudnative-pg/cloudnative-pg#750]
CloudNativePG currently has this fixed set of fields that are automatically logged to the standard output channel of each running container, in JSON format.

The are the fields:

- level
- ts
- logger
- msg
- record
- logging_podName

See https://cloudnative-pg.io/documentation/current/logging/

This implementation constraints the range of deployments of both the operator and the Postgres clusters with external tools and platforms for log management, such as GKE Stackdriver. This request came from Mo Firouz in the Sept 7, 2022 developer meeting. See the recording: https://youtu.be/mWXXRzslOXg?t=50

Specifically, their use case is to rename "level" into "severity".

We should provide a way to define a mapping at the operator configuration level that sets the above field names through an existing configmap/secret, and propagate that for instances. See https://cloudnative-pg.io/documentation/current/operator_conf/

**Comment by gbartolini** [comment]
We could think of an environment variable at the operator level like the following (default):

`LOG_FIELDS=level,ts,logger,msg,record,logging_podName`

You can remove some of these fields:

`LOG_FIELDS=level,ts,logger,msg,record`

You can rename fields:

`LOG_FIELDS=level:severity,ts:timestamp,logger,msg,record,logging_podName`

We now need to pass this info to the instance managers.

Any ideas?

**Comment by phisco** [comment]
TBH I don't think it's in scope for the operator, I expect a good log ingestion system to be able to do that later, e.g. as you would do if you had fluentd parsing logs before shipping them. Sounds more like a missing feature in GKE stackdriver, than in our operator.

**Comment by gbartolini** [comment]
> TBH I don't think it's in scope for the operator, I expect a good log ingestion system to be able to do that later, e.g. as you would do if you had fluentd parsing logs before shipping them. Sounds more like a missing feature in GKE stackdriver, than in our operator.

I get your point of view for a more generic and customizable approach. However, unless you believe this will create issues at runtime and complicate maintenance, I believe this would be a nice thing to have.
