### ISSUE TITLE
EKS IRSA role setup for s3 backups

### ISSUE THREAD

**Issue by tbondarchuk** [cloudnative-pg/cloudnative-pg#756]
Current documentation shows only example of putting AWS access key to k8s secret, so in order to use irsa role on eks I had to do a bit of docs digging and guessing :)

So, is the following setup ok or there are some other/easier ways to do this that I've missed?

* create s3 bucket and irsa role allowed to use it, with namespace/service account of db Cluster (sa name == Cluster name)
* enable eks role annotation in controller config `INHERITED_ANNOTATIONS: eks.amazonaws.com/role-arn`
* restart controller to pickup new config
* add annotation with irsa role arn to Cluster.
* manually add annotation to Cluster's service account since annotations are not updating after cluster creation
* restart Cluster's pods to pickup updated sa token
* add backup config to Cluster with `barmanObjectStore. s3Credentials.inheritFromIAMRole: true` 
* create backup

If this is a proper way of using irsa role on EKS, would be nice to have it mentioned in documentation, same as the fact that service account is created for Cluster.

P.S. CNPG is just awesome, love it! Thanks a lot for sharing it!

**Comment by phisco** [comment]
Hi @aliusmiles, thanks for using cnpg and for the docs digging and guessing!
There is another option as mentioned [here](https://github.com/cloudnative-pg/cloudnative-pg/discussions/442#discussioncomment-3200424), you could avoid setting `INHERITED_ANNOTATIONS` in the operator's config and use the provided `spec.inheritedMetadata.annotations` field in the Cluster object. This way for a new cluster the procedure would be the following:
- create s3 bucket and irsa role allowed to use it, with namespace/service account of db Cluster (sa name == Cluster name)
- add backup config to Cluster with `barmanObjectStore.s3Credentials.inheritFromIAMRole: true` and `spec.inheritedMetadata.annotations: eks.amazonaws.com/role-arn: arn...`
- then create a backup/scheduledbackup
But, we could definitely add this to the docs! PRs are welcome :wink:

**Comment by Smana** [comment]
I opened this [PR](https://github.com/cloudnative-pg/cloudnative-pg/pull/836) to update the documentation accordingly however I think this is worth opening a new issue because with this solution we can't add the service account after the cluster has been created and the annotations are propagated to all the resources. Ideally, we should be able to define them for the service account only

**Comment by valeriodelsarto** [comment]
As I wrote in a comment [there](https://github.com/cloudnative-pg/cloudnative-pg/pull/836#discussion_r1004132678) (Thanks for the PR!) the second option would be to pre-create the `ServiceAccount` with the annotation that IRSA requires, then CloudNativePG will use it and that annotation will be kept. I would prefer this approach to the usage of `spec.inheritedMetadata.annotations` for this purpose...

**Comment by gbartolini** [comment]
Chatting with @valeriodelsarto, @leonardoce and @gabriele-wolfox, they came with the idea of enabling the cluster to define some annotations and labels for the service account. We've created #1083 for that reason. This should make setup of backup object stores authentication and authorization much easier and safer.
