### ISSUE TITLE
Multi database cluster?

### ISSUE THREAD

**Issue by bennylut** [cloudnative-pg/cloudnative-pg#773]
Hi,
First I want to thank you for this great project!

Is there an option to have multiple databases on the same cluster? 

Thanks!

**Comment by phisco** [comment]
Hi, we do not allow that by design, as we want to push for a one-to-one mapping between databases and clusters, see this discussion for more details: https://github.com/cloudnative-pg/cloudnative-pg/discussions/497. 
Closing this issue, feel free to contribute to the discussion directly.
