### ISSUE TITLE
Add https://cloudnative-pg.io/documentation/latest to allow for long term link referencing

### ISSUE THREAD

**Issue by cloudflight-cweiss** [cloudnative-pg/cloudnative-pg#788]
Official documentation website https://cloudnative-pg.io/documentation/1.17/ uses `major.minor` version in its URL.
Since the release cycle of the operator is quite fast, referencing documentation via URL is only reachable for about 6 months.
Even though specific documentation sections will change, referencing for example the page about [Supported Releases](https://cloudnative-pg.io/documentation/1.17/supported_releases/) should not "expire" after half a year.

An extra reverse proxy subpath like `documentation/latest` pointing to the latest version or something similar would help with the ability to reference official documentation in company internal Guides, Evaluations etc.

**Comment by sxd** [comment]
It's a valid request but this it's not the proper place for this, can you re-open the issue in the website project? https://github.com/cloudnative-pg/cloudnative-pg.github.io

**Comment by cloudflight-cweiss** [comment]
I actually found that you can use the `current` keyword for exactly that and I also just now found the corresponding documentation change in the repo you suggested https://github.com/cloudnative-pg/cloudnative-pg.github.io/pull/96

JFYI for anybody who comes here with the same question :)
