### ISSUE TITLE
Adopt PostgreSQL 15 native jsonlog capability

### ISSUE THREAD

**Issue by gbartolini** [cloudnative-pg/cloudnative-pg#792]
With [this patch by Michael Paquier](https://git.postgresql.org/gitweb/?p=postgresql.git;a=commitdiff;h=dc686681e0799b12c40f44f85fc5bfd7fed4e57f), PostgreSQL 15 introduces direct support for JSON log.

CloudNativePG should set the default behaviour to match the capability introduced in version 15 and directly use in the configuration:

```ini
log_destination = jsonlog
```

For older versions, fall back to the current implementation which makes usage of CSV and parses the content.

This should be transparent for the end user.

**Comment by phisco** [comment]
We agreed this doesn't add anything w.r.t. the operator's current behavior, parsing JSON instead of CSV would only worsen the log pipeline performances without any pros.

**Comment by gbartolini** [comment]
See https://youtu.be/jhnNFZEksXs?t=177
