### ISSUE TITLE
Replication slots for HA

### ISSUE THREAD

**Issue by gbartolini** [cloudnative-pg/cloudnative-pg#8]
Cloud Native Postgres currently relies only on the archive log to synchronize those standby servers that have fallen out of sync. However, for some high workload scenarios, this can be inefficient. We need to introduce a smart way for the operator to manage replication slots on the primary and designated primary instances, so that the operator itself regularly moves forward the WAL location based on the most delayed standby. The operator must also remove the replication slot from the former primary and add it to the new one following a failover or switchover.

**Comment by gbartolini** [comment]
Hi @francoispqt,

thanks for your reply. I know that @sxd and @mnencia were working on a prototype implementation - I am pretty sure that @sxd wrote some code while on the plane from South America to KubeCon but I don't see a branch for that.

The idea was to have the operator regularly advance the replication slot based on the position in the standbys, so yes, similar to what you were describing.

@sxd can you please share the code?

Cheers,
Gabriele

**Comment by gbartolini** [comment]
Thanks @sxd! @francoispqt please reach out in the slack channel if you need help.

**Comment by francoispqt** [comment]
Thanks @gbartolini @sxd, I'll continue the conversation on the slack channel.

**Comment by ns-gzhang** [comment]
This seems to be the right issue for me to watch on for Debezium CDC support for PG HA with cnpg operator. Until it's available, we really cannot use the cnpg operator.
