### ISSUE TITLE
Better support for sidecar containers in batch jobs (aka Istio support)

### ISSUE THREAD

**Issue by gbartolini** [cloudnative-pg/cloudnative-pg#801]
CloudNativePG uses Kubernetes jobs to initialize the PGDATA content on the persistent volumes.

However, when used in conjunction with Istio, Kubernetes jobs do not terminate, as the injected sidecar running the Envoy based `pilot-agent` runs indefinitely. For details: https://medium.com/redbox-techblog/handling-istio-sidecars-in-kubernetes-jobs-c392661c4af7

Although there are a few options, including [annotations](https://istio.io/latest/docs/reference/config/annotations/), the most reasonable way forward is to introduce support for the `/quitquitquit` endpoint of the [Envoy server](https://www.envoyproxy.io/docs/envoy/latest/operations/admin).

Such support was introduced in [Istio 1.3](https://istio.io/latest/news/releases/1.3.x/announcing-1.3/change-notes/) - see https://github.com/istio/istio/issues/15041 for details.

This is also the recommended approach in this discussion: https://discuss.istio.io/t/best-practices-for-jobs/4968

**Comment by slickwilli** [comment]
@gbartolini I can take a crack at implementing this.

**Comment by gbartolini** [comment]
Looking forward to your pull request!

**Comment by hh24k** [comment]
Hi @slickwilli ... although I raised a Pull request for it https://github.com/cloudnative-pg/cloudnative-pg/pull/967, it's more a kind of an experiment. So feel free to raise yours.
