### ISSUE TITLE
Cnpg kubectl plugin subcommand to run pgbench

### ISSUE THREAD

**Issue by phisco** [cloudnative-pg/cloudnative-pg#820]
We forgot to move https://github.com/EnterpriseDB/cnp-bench to https://github.com/cloudnative-pg/charts, when cnpg was open-sourced, but instead of just moving the helm chart now, we could take the chance to introduce a new command in the kubectl cnpg plugin which will directly run a benchmark.

We agreed to start by addressing only pgbench for now and leave fio for another time.

A user should be able to run a benchmark using pgbench simply running `kubectl cnpg pgbench CLUSTER_NAME ...`, the subcommand should by default apply the job and output the command to see the results, but should also have a flag to output only the manifests, so that any customization can be directly done on the generated manifest, which can then be applied simply using `kubectl apply`.

The deletion of the completed job should also be addressed, therefore either we print the cleanup command together with the command to read the results or we add a flag to delete instead of creating the jobs, obviously in case the pure manifests were used it will be the users' duty to delete whatever he created by hand.

Previously the chart was also deploying a cluster to target, the subcommand should instead focus on benchmarking existing clusters directly.

**Comment by gbartolini** [comment]
I completely forgot we had this ticket. I have created another one #847 with more details on the task.
