### ISSUE TITLE
Expose conditions to provide a simple and reliable way to wait for a CNPO Cluster to be ready

### ISSUE THREAD

**Issue by wadlejitendra** [cloudnative-pg/cloudnative-pg#84]
Currently (re)deployment of a CNPO cluster seems to be a bit tricky to wait for completion of in a kubectl-friendly way.
For pods, you might

`1. kubectl wait --for=status=Ready -n the-cnp-cluster-namespace pods `

but this is very race-prone. It tends to report premature success if the pods aren't created yet, or if the old pods haven't started termination. Or it can hang indefinitely if some of the old pods still exist but are terminating, because kubectl wait will wait forever for a pod that went away. And it might return premature success if only some of the pods are created yet, but others haven't started creation.
CNPO deletes and creates pods after a new or updated `Cluster` resource is applied to the k8s config. So the new configured `Cluster` resource is visible but the pods haven't been terminated or launched yet. That's fine and normal for an operator, but poses issues if you want to wait for readiness.
AFAICS there is no `Condition` exposed by the `Cluster` CRD, so something like this will not work:

`1. kubectl wait -n app-db --for=condition=Ready clusters/app-db`

and `kubectl` doesn't know how to wait for arbitrary fields like `State=Cluster in healthy state`. It doesn’t support waiting for `Phase` which is considered deprecated, nor for generic wait conditions ([kubectl wait on arbitrary jsonpath · Issue #83094 · kubernetes/kubernetes](https://github.com/kubernetes/kubernetes/issues/83094) ) .
`kubectl`'s `--field-selector` doesn't seem to help either as it's a pretty limited feature that doesn't seem to work well if at all with CRDs.
I'd like to be able to wait for a `Condition` that becomes true when `readyInstances == pvcCount` i.e. `phase: Cluster in healthy state`
In the mean time all I can see to do is to poll until `Cluster in healthy state`, as shown in the `Status` or `phase` fields. But is that i18n-safe? Is that a stable key I can rely on not changing?

**Comment by NiharDudam** [comment]
Ideally, every custom resource status should have proper conditions so that an adopter can wait on that condition to be true. 

Currently, we are waiting on `Cluster in healthy state` and `ReadyInstances` to match with what we expect. Is that a good way to wait until proper conditions are delivered?

**Comment by wadlejitendra** [comment]
> Ideally, every custom resource status should have proper conditions so that an adopter can wait on that condition to be true.
> 
> Currently, we are waiting on `Cluster in healthy state` and `ReadyInstances` to match with what we expect. Is that a good way to wait until proper conditions are delivered?

Thank you for shared your thoughts on this feature. 
Yes, If custom resource have proper conditions in status field then we can use `kubectl wait` command to get current status for custom resources.
In our case, for CR `cluster`if we want like this 
kubectl wait -n <namespace_name> --for=condition=Ready cluster/<cluster_name>

So here:
Condition Type is `Ready` 
Status could be `true/false`
It will be wait until the cluster condition `Ready` has been `true`.

**Comment by wadlejitendra** [comment]
Waiting for "https://github.com/cloudnative-pg/cloudnative-pg/issues/208" once it will be merged then will move forward this.

**Comment by gbartolini** [comment]
@wadlejitendra I have temporarily shifted this to 1.17.0 as we are late for 1.16 and we already have lots of enhancements to release. Let me know what you think. If you feel we are close enough to complete the task, let's move it back 1.16. Thanks.

**Comment by wadlejitendra** [comment]
@gbartolini This feature is not fully implemented yet, need some time to complete this task I think it would be part of v1.17.0 release.

**Comment by wadle** [comment]
@mnencia @leonardoce 
While looking into the cluster conditions these came into my mind. 

**First** : 
Type : `PrimaryIsReady`
Status : `True/False`

**Second** : 
Type: `ClusterIsHealthy`
Status: `True/False`

After implementation above two conditions will look like this: 

"`conditions`": [
      {
        "type": “`PrimaryReady`”,
        "status": "False",
        "lastTransitionTime": "2022-07-14T09:59:43Z"
        "reason": "`PrimaryIsNotReady`",
        "message": “Primary instance is not ready : <msg> (msg: with current status of primary)
      },
      {
        "type": “`ClusterIsHealthy`”,
        "status": "False",
        "lastTransitionTime": "2022-07-14T09:59:41Z",
        "reason": “`ClusterIsNotHealthy`”,
        "message": “Cluster is not healthy: primary is not ready"
      },
    ],

Once primary and cluster is healthy conditions look like this : 

"`conditions`": [
      {
        "type": “`PrimaryReady`”,
        "status": "True",
        "lastTransitionTime": "2022-07-14T09:59:43Z"
        "reason": "`PrimaryIsReady`",
        "message": “Primary is ready"
      },
      {
        "type": “`ClusterIsHealthy`”,
        "status": "True",
        "lastTransitionTime": "2022-07-14T09:59:41Z",
        "reason": “`ClusterIsHealthy`”,
        "message": “Cluster is healthy"
      },
    ],

**Comment by NiharDudam** [comment]
Is there a way we can also track replication status? for example, if replication between primary and replica is not happening, we could add a condition `ReplicationIsWorking` ?

**Comment by wadlejitendra** [comment]
@NiharDudam Thank you for sharing your thoughts on this feature. Will discuss with team and accordingly update to you.

**Comment by leonardoce** [comment]
Yes, good advice. The problem is that the operator won't be notified when the replication stop working, and it's really difficult to find a criteria defining a working replica.

I.e. a replica may be ready but not connected to the primary. Is this replica working?
a replica may be connected to the primary and replicating data but have a big lag because of a performance issue. Is this replica working?

I believe this is important when it comes to monitoring the PostgreSQL cluster, and I'm not sure we should report that to the API server or not.

**Comment by ringerc** [comment]
Best not to expand the scope on this more than necessary. If it's practical to report primary readiness then start with that.

I can definitely see value to other conditions, but the critical one is primary readiness - when it's up and accepting connections.
