### ISSUE TITLE
Improve `cnpg status` when cluster is fenced

### ISSUE THREAD

**Issue by gbartolini** [cloudnative-pg/cloudnative-pg#841]
I just fenced a cluster with:

```
kubectl cnpg fencing on kubecon-eu-central-1 "*"
```

and then when running `kubectl cnpg status kubecon-eu-central-1` I cannot clearly understand that a fence is on:

```console
Cluster Summary
Name:               kubecon-eu-central-1
Namespace:          default
System ID:
PostgreSQL Image:   ghcr.io/cloudnative-pg/postgresql:15
Primary instance:   kubecon-eu-central-1-1
Status:             Cluster in healthy state
Instances:          3
Ready instances:    0
Current Write LSN:   (Timeline: 0 - WAL File: )

Certificates Status
Certificate Name                  Expiration Date                Days Left Until Expiration
----------------                  ---------------                --------------------------
kubecon-eu-central-1-ca           2023-01-09 09:47:31 +0000 UTC  89.80
kubecon-eu-central-1-replication  2023-01-09 09:47:31 +0000 UTC  89.80
kubecon-eu-central-1-server       2023-01-09 09:47:31 +0000 UTC  89.80

Continuous Backup status
First Point of Recoverability:  2022-10-11T09:53:39Z
Working WAL archiving:          Starting Up
WALs waiting to be archived:    0
Last Archived WAL:              -
Last Failed WAL:                -

Streaming Replication status
Not available yet

Instances status
Name                    Database Size  Current LSN  Replication role       Status  QoS         Manager Version  Node
----                    -------------  -----------  ----------------       ------  ---         ---------------  ----
kubecon-eu-central-1-1                              Primary                OK      Guaranteed  1.17.1           ip-192-168-89-157.eu-central-1.compute.internal
kubecon-eu-central-1-2                              Standby (starting up)  OK      Guaranteed  1.17.1           ip-192-168-5-161.eu-central-1.compute.internal
kubecon-eu-central-1-3                              Standby (starting up)  OK      Guaranteed  1.17.1           ip-192-168-40-242.eu-central-1.compute.internal
```

**Comment by hh24k** [comment]
The `Ready instances:    0` might give a hint about the fencing, but it does not necessarily indicate all the instances have been fenced. Also, I tested fencing a specific instance, the situation is similar:

` 
❯ kubectl cnpg fencing on cluster-example cluster-example-1
cluster-example-1 fenced

❯ kubectl cnpg status cluster-example
Cluster Summary
Name:               cluster-example
Namespace:          default
System ID:          
PostgreSQL Image:   ghcr.io/cloudnative-pg/postgresql:14
Primary instance:   cluster-example-1
Status:             Cluster in healthy state 
Instances:          2
Ready instances:    1
Current Write LSN:   (Timeline: 0 - WAL File: )

Certificates Status
Certificate Name             Expiration Date                Days Left Until Expiration
----------------             ---------------                --------------------------
cluster-example-ca           2023-01-15 07:01:02 +0000 UTC  89.90
cluster-example-replication  2023-01-15 07:01:02 +0000 UTC  89.90
cluster-example-server       2023-01-15 07:01:02 +0000 UTC  89.90

Continuous Backup status
Not configured

Streaming Replication status
Not available yet

Instances status
Name               Database Size  Current LSN  Replication role      Status  QoS         Manager Version  Node
----               -------------  -----------  ----------------      ------  ---         ---------------  ----
cluster-example-2  33 MB          0/90000A0    Standby (file based)  OK      BestEffort  1.17.1           pg-operator-e2e-v1-24-2-cnpg-worker2
cluster-example-1                              Primary               OK      BestEffort  1.17.1           pg-operator-e2e-v1-24-2-cnpg-worker
`
