### ISSUE TITLE
Error with permissions for WAL archiving takes long to recover

### ISSUE THREAD

**Issue by jsilvela** [cloudnative-pg/cloudnative-pg#85]
From a Support incident: reported errored WAL archiving after adding backup info to an existing cluster.

**Repro steps:**

1. create a cluster with no backup section, wait for it to become healthy
2. add a backup section to the cluster
3. wait, or write some info to the db to trigger WAL writing
4. With cnpg plugin verify the WAL archiving is not working, see complaints in pod logs about WAL archiving errors 

**Root cause:**

1. We amend the cluster to include backup, this triggers creation of Secrets for backup credentials
2. The role takes a bit to create with the permissions for the backup credentials
3. meanwhile the instance manager tries to cache the backup info but role permissions fail — and the error is ignored
4. the wal-archive process doesn't find the credentials in the cache and keeps trying and failing
5. the error will recover only after the next reconciliation is triggered, which could take more than 30 minutes - 45 in my testing.
6. An alleviation is to make a trivial modification to the cluster, so a new reconciliation loop is triggered immediately.

**Comment by jsilvela** [comment]
E2E branches seem to be green, moving this forward.

**Comment by litaocdl** [comment]
It is a great reproduce steps. 
without patch, I can easily reproduced the issue. after add `backup` section to the cluster and triggered the war archieving, the cnpg status report WAL archieving failed, in minio, there is no directory created for the cluster name. 

with the patch, use the same steps, right after I run bgbench against the cluster, I can see the cluster directory is created in minio, and cnpg status reports `OK` for the WAL archieving.
