### ISSUE TITLE
[Bug] test-connection: failed to create containerd task: failed to create shim task

### ISSUE THREAD

**Issue by Ornias1993** [cloudnative-pg/cloudnative-pg#860]
When running as a helm dependency, similair to the sandbox chart, on k3d-k3s, version 1.24, installation/run tests fail with the following error:
```
Error: failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "curl": executable file not found in $PATH: unknown
```

This is a shame, as I was planning to use cloudnative-PG as our primarily project-wide postgresql operator.

See:
![image](https://user-images.githubusercontent.com/7613738/195389124-3af38741-fdf7-4208-b257-a82e4dbc10ab.png)

Complete example run available here:
https://github.com/truecharts/charts/actions/runs/3235926958/jobs/5301157871

**Comment by phisco** [comment]
You are right, the test is using the operator's image which we moved to distroless recently and doesn't have curl anymore. The test is not adding anything useful with respect to just having the pod getting ready, so we might even remove that altogether.

**Comment by phisco** [comment]
So, if that's an option for you I'd suggest just not running the test, otherwise you'll have to wait for the next release of the helm chart.
