### ISSUE TITLE
Improve `STATUS` of cnpg when cluster, especially when primary instance is fenced

### ISSUE THREAD

**Issue by hh24k** [cloudnative-pg/cloudnative-pg#882]
Quite related to issue #841: when an instance of the cluster, especially when the primary is fenced, the cluster actually is down, but when querying the status of the cluster, you still get it as `Cluster in healthy state`:

```
❯ kubectl get clusters.postgresql.cnpg.io cluster-example

NAME              AGE   INSTANCES   READY   STATUS                     PRIMARY
cluster-example   47h   2
```

We might need to adjust the `status` in this case, but be careful with the potential side effects of breaking the API

**Comment by sxd** [comment]
This was abandoned
