### ISSUE TITLE
Status plugin: implement JSON output

### ISSUE THREAD

**Issue by jsilvela** [cloudnative-pg/cloudnative-pg#892]
The `cnpg status` kubernetes plugin offers two options for the `output` flag:

- text (default)
- json

If the json option is chosen, only the most basic information is printed. The replication
and instance status information is discarded.
See

``` go
	err = plugin.Print(status, format, os.Stdout)
	if err != nil {
		return err
	}

	if format != plugin.OutputFormatText {
		return nil
	}
	...
```

in `internal/cmd/plugin/status/status.go`

If the json option is chosen, we should display all the information that would be available
with `text` selected in the output option and the `verbose` option activated.

**Comment by sonali-rajput** [comment]
can you please help me out with how I can implement this? Do I need to get the same output as text format so this ` if format != plugin.OutputFormatText {
		return nil
	} ` should be removed?

**Comment by litaocdl** [comment]
Hello @sonali-rajput 
   
     Thanks for looking into this ticket, basically what we want is to make `kubectl-cnpg status <cluster> -o json ` display the same content with  `kubectl-cnpg status <cluster> -o text -v` but in json format. For the implemention, yes, we should remove that line `if format != plugin.OutputFormatText { return nil }` and rewrite `Status` function https://github.com/cloudnative-pg/cloudnative-pg/blob/main/internal/cmd/plugin/status/status.go#L87 to print same content with different format in a swtich case

```
            switch format {
			case plugin.OutputFormatJSON, plugin.OutputFormatYAML:
				//print in json or yaml
			case plugin.OutputFormatText:
				// print in text as before
			default:
				//error
			}
```

**Comment by jsilvela** [comment]
To add to what @litaocdl mentioned: this will involve a refactoring of the existing `status` plugin code.
We probably should define `struct` types to hold the special information gathered in the plugin,
then have a text serializer, as well as a JSON serializer.
Not a small task.

**Comment by sonali-rajput** [comment]
Alright! Thanks for informing me, I'll try to work on this.

**Comment by abhioncbr** [comment]
Question, above mentioned changes, help us to get the status which I have asked in the following [issue]([1700 Failed Cluster deployment without Status.](https://github.com/cloudnative-pg/cloudnative-pg/issues/1700))?

**Comment by sxd** [comment]
Closing since this was already done
