### ISSUE TITLE
Offline data import and major upgrades for Postgres

### ISSUE THREAD

**Issue by gbartolini** [cloudnative-pg/cloudnative-pg#9]
We need to provide a declarative way to import existing Postgres databases in CloudNativePG, starting from offline migrations - which also cover major upgrades of Postgres databases. 

**IMPORTANT:** Offline means that with this method applications must stop their write operations to the source until the database is migrated to the new cluster. Offline migrations are in contrast to online migrations with 0 cutover time - which are implemented using native logical replication (see “Logical replica clusters” for online migrations).

Offline migrations extend the “initdb” bootstrap method of CloudNativePG to enable users to create a new PostgreSQL cluster using a snapshot of the data available in another PostgreSQL database - which can be accessed via the network through a superuser connection.

Import is from any supported version of Postgres.

The logical import relies on pg_dump and pg_restore executed from the primary of the new cluster, for all the databases that are part of the operation and, if requested, for the roles.

There are two types to import a database:

- microservice: select the single database to import in the new cluster as the main application database
- monolith: select one or more databases to import (including “*” wildcard), as well as roles (superuser privileges are removed)

The microservice approach is the preferred method to import databases in CloudNativePG, while the monolith approach is more aligned with a shared PostgreSQL instance having multiple databases that DBAs are familiar with.

**Comment by sxd** [comment]
Currently, this is working but the E2E is not actually working properly I just asked @danishedb a bit of help on this
