### ISSUE TITLE
How can I connect to my Cluster?

### ISSUE THREAD

**Issue by zozidalom** [cloudnative-pg/cloudnative-pg#917]
I've set up a CloudNativePG cluster, how can I connect to it from another pod in the same namespace?

**Comment by leonardoce** [comment]
Hi!

You can have a look at the [Connecting from an application](https://cloudnative-pg.io/documentation/1.17/applications/) documentation page.

The documentation contains an [example on how to use certificates for mutual TLS authentication](https://cloudnative-pg.io/documentation/1.17/ssl_connections/#testing-the-connection-via-a-tls-certificate) too.

In the [cnp-bench](https://github.com/EnterpriseDB/cnp-bench/tree/main/pgbench-benchmark) repo you can find an example of a pgbench connecting to a CloudNativePG powered cluster using a Job.

**Comment by zozidalom** [comment]
Connection refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.

**Comment by phisco** [comment]
Hi, if the content of the `postgresql-secret` secret you are providing contains both the `username` and `password` fields, you should be able to connect through the `postgresql-rw` or `postgresql-ro` using the configured username and password, if that's not the case, please provide more context, e.g. operator and cluster pods' logs.
However, a few notes on your manifest:
- you are not using an official image, I suggest you remove the `postgres:14-alpine` reference and either rely on the default one chosen by the operator or pick one of the official ones you can find [here](https://github.com/cloudnative-pg/postgres-containers/pkgs/container/postgresql)
- you are not setting a storage size, which will end up in no pod being spawned up at all, you should add `.spec.storage.size: <desired size>` as you can see [here](https://github.com/cloudnative-pg/cloudnative-pg/blob/main/docs/src/samples/cluster-example-secret.yaml#L19)

**Comment by phisco** [comment]
The Size validation was already added in #904, so with the next release of the operator, trying to apply a manifest not specifying a proper storage size will result in an error:
```
The Cluster "postgresql" is invalid: spec.Storage.size: Invalid value: "": Size not configured. Please add it, or a storage request in the pvcTemplate.
```

**Comment by till** [comment]
> The Size validation was already added in #904, so with the next release of the operator, trying to apply a manifest not specifying a proper storage size will result in an error:
> 
> ```
> 
> The Cluster "postgresql" is invalid: spec.Storage.size: Invalid value: "": Size not configured. Please add it, or a storage request in the pvcTemplate.
> 
> ```

My ticket was about duplicate size configuration though. Has this been changed again?

**Comment by phisco** [comment]
@till, we fixed that issue and took the chance to improve the validation too 😉

**Comment by zozidalom** [comment]
@phisco Thank you for the response.

After adding
```
storage:
    size: 1Gi
```
now the instances are up and running and now I get  _password authentication failed for user postgres_

```
---
apiVersion: v1
data:
  password: mypassword
  username: postgres
kind: Secret
metadata:
  namespace: dev
  name: postgresql-secret
type: kubernetes.io/basic-auth
```

This is what my secret looks like.
I removed the imageName as well to use the default one for now.
This is what my connection string looks like (Rust): 

`postgresql://postgres:mypassword@postgresql-rw:5432/mydatabase`

The same connection string works for a single postgresql:14-alpine pod but not for the cluster of CloudNativePG at the moment.

**Comment by phisco** [comment]
This is working for me:
```bash
kubectl apply -f - <<EOF
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql
spec:
  instances: 3
  primaryUpdateStrategy: unsupervised
  postgresql:
    parameters:
      shared_buffers: 256MB
      pg_stat_statements.max: '10000'
      pg_stat_statements.track: all
      auto_explain.log_min_duration: '10s'
  bootstrap:
    initdb:
      database: mydatabase
      owner: postgres
      secret:
        name: postgresql-secret
  storage:
    size: '1Gi'
---
apiVersion: v1
stringData:
  password: mypassword
  username: postgres
kind: Secret
metadata:
  name: postgresql-secret
type: kubernetes.io/basic-auth
EOF
```
and I can connect successfully by running:
```sh
$ kubectl run -i -t --rm --image ghcr.io/cloudnative-pg/postgresql:14 test --restart Never --command psql postgresql://postgres:mypassword@postgresql-rw:5432/mydatabase                                                                                                                                                          
If you don't see a command prompt, try pressing enter.
mydatabase=>
```

I think you are setting a `\n` somewhere in the username or password. However I suggest you not to use the `postgres` user, as it's a special admin user in the database, we use the `app` user by default for the application database.

**Comment by till** [comment]
I would also let the operator set a password and rely on the defaults before you customize it. Creating a k8s _secret_ is icky with base64 encoding and `\n` as @phisco mentioned.

By default the secret is in the same namespace as the cluster and it's called: `$cluster-app`.

In your example (`namespace=dev`, `cluster=postgresql`): 

```golang
	secret, err := clientset.CoreV1().Secrets("dev").Get(context.TODO(), "postgresql-app", metav1.GetOptions{})
	if err != nil {
		return nil, err
	}
```
You can extract it from Kubernetes with the above go code. :)

**Comment by zozidalom** [comment]
It works after deleting (`kubectl delete -f cluster.yml`) the cluster and recreating it (`kubectl apply -f cluster.yml`) completely.
