### ISSUE TITLE
Publish kubectl-cnpg plugin on Krew

### ISSUE THREAD

**Issue by mnencia** [cloudnative-pg/cloudnative-pg#92]
Currently, users need to manually download our plugin using the command line that we have in the README of the kubectl-cnpg project, but this doesn’t work well on Windows and makes it hard for users to find our plugin.

The idea is to use Krew as the official plugin distribution of Kubernetes, which seems to be the best idea.

A couple of tasks need to be done:

Write the Krew plugin manifest following [this documentation](https://krew.sigs.k8s.io/docs/developer-guide/plugin-manifest/), one good example is [here](https://github.com/kubernetes-sigs/krew-index/blob/master/plugins/tree.yaml)

Test the install process [locally](https://krew.sigs.k8s.io/docs/developer-guide/testing-locally/)

Manually submit the plugin to the krew-index following [this documentation](https://krew.sigs.k8s.io/docs/developer-guide/release/new-plugin/)

Create the automated process [recommended by the Kew community](https://krew.sigs.k8s.io/docs/developer-guide/release/automating-updates/)

After doing these tasks, there’s an interesting link that you can follow to get [some stats](https://krew.sigs.k8s.io/docs/developer-guide/plugin-stats/) of the plugin: [stats.krew.dev](https://datastudio.google.com/c/reporting/f74370a0-adcf-4cec-b7bd-a58c638948f5/page/Ufl7)

_This issue was originally submitted in the EnterpriseDB ticketing system by @sxd._

**Comment by sxd** [comment]
No we're waiting for the PR to publish the first version on Krew which is required to publish any new version.

Here's the PR https://github.com/kubernetes-sigs/krew-index/pull/2241

**Comment by sxd** [comment]
The PR was merged, but currently we will not be listed with the GitHub stars icon because we don't have the GitHub URL in the homePage field but https://cloudnative-pg.io site, probably we should add the GitHub page? this will point the users directly to the GitHub instead of the webpage and then jumping into the GitHub repo... Something to think about it, what do you think @gbartolini ?

**Comment by sxd** [comment]
@leonardoce We already discussed that with @gbartolini and @mnencia in Slack around here https://cloudnativepg.slack.com/archives/C03D68KGG65/p1652348675498369 we agree on use GitHub url as the homepage since this is the plugin =)
